### ISSUE TITLE
TypeError: createCanvas is not a function

### ISSUE THREAD

**Issue by mathiaslsn** [Automattic/node-canvas#1011]
getting this error using the main example file

const canvas = createCanvas(200, 200)
               ^

TypeError: createCanvas is not a function
    at Object.<anonymous> (C:\Users\.........\Documents\bottest\test.js:2:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3

**Comment by albertyou2** [comment]
+1

**Comment by LinusU** [comment]
> -----
> 
> ## This is the documentation for the unreleased version 2.0
> 
> **For the current version 1.x documentation, see [the v1.x branch](https://github.com/Automattic/node-canvas/tree/v1.x)**
> 
> -----

You either want to install the alpha of 2.0 by using `npm install canvas@next`; or read the documentation for version 1.x here: https://github.com/Automattic/node-canvas/tree/v1.x

**Comment by Izhaki** [comment]
@LinusU 

That's just confusing. 

There is the v2 clause on top saying using `canvas@next`, yet the install instruction below uses:

    $ npm install canvas

So if the docs are for v2, shouldn't the install section also show `canvas@next`?
