### ISSUE TITLE
Registerfont not working..

### ISSUE THREAD

**Issue by Chiyoku** [Automattic/node-canvas#1018]
```
registerFont("./utils/commands/Raleway-Black.ttf",{
    family:"Raleway"
})
```

error

```
  return Canvas._registerFont(fs.realpathSync(src), fontFace)
                ^

Error: Could not parse font file
    at registerFont (C:\Users\Chiyoku\Desktop\Programação\BotPram\node_modules\canvas\index.js:48:17)
    at Object.<anonymous> (C:\Users\Chiyoku\Desktop\Programação\BotPram\utils\commands\profile.js:7:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Client.<anonymous> (C:\Users\Chiyoku\Desktop\Programação\BotPram\utils\bot.js:54:46)
    at emitOne (events.js:120:20)
    at Client.emit (events.js:210:7)
    at MessageCreateHandler.handle (C:\Users\Chiyoku\Desktop\Programação\BotPram\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Chiyoku\Desktop\Programação\BotPram\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Chiyoku\Desktop\Programação\BotPram\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:330:35)
 ```

**Comment by LinusU** [comment]
Could you post the font-file as well?

**Comment by Chiyoku** [comment]
[https://github.com/hydrabolt/discord.js/issues/2034#issuecomment-336936461](url)

**Comment by Chiyoku** [comment]
[Raleway-Black.zip](https://github.com/Automattic/node-canvas/files/1388477/Raleway-Black.zip)

**Comment by Chiyoku** [comment]
@LinusU

**Comment by Chiyoku** [comment]
Sorry i'm noob with github

**Comment by LinusU** [comment]
Hmm, it seems to work for me. On latest master though, which version of canvas are you using?

**Comment by Chiyoku** [comment]
I think that is @2.0 Alpha 0.5

**Comment by Chiyoku** [comment]
I'm using Windows 10 64 bits . And i installed the dependencies using Chocolatey

**Comment by Chiyoku** [comment]
Sorry . idk if it resolve my question but. How can i use Pango in Node-Canvas ( i read issues and people changed the Cairo to Pango )

Sorry my bad english >@<

**Comment by zbjornson** [comment]
It's working for me on 2.0.0-alpha.5 on Windows 10 x64. I think Chocolatey installs dependencies to a different location than the build script expects them to be in (and the wiki page doesn't say this). Do you have a a `C:\GTK\bin` directory containing `libpango-1.0-0.dll`, `libcairo-2.dll`, etc?

**Comment by Chiyoku** [comment]
Yes... i have

**Comment by tybenz** [comment]
Y'all are talking about the alpha version, but most people install with "npm install canvas", which gives you version 1.6.9, which is a zip that excludes registerFont altogether (index.js just exports lib/canvas).

The docs for 1.6.9 usage should be fixed. 1.6.9 does NOT have registerFont available. You have to install via git SHA to get this functionality.

**Comment by tybenz** [comment]
My bad. I thought I was browsing the 1.6.9 branch when I saw a reference to "registerFont". I don't see it now. Obviously, I made a mistake. So sorry about that.

**Comment by LinusU** [comment]
@tybenz no problem at all, sorry if I sounded harsh, it was not my intention at all ☺️

**Comment by zbjornson** [comment]
Sounds like this is fixed...

**Comment by Fedeeriico** [comment]
a
