### ISSUE TITLE
Installation instructions don't work

### ISSUE THREAD

**Issue by megamindbrian** [Automattic/node-canvas#1024]
This comment doesn't help, this is a bad design.

```
<!----------------------------------- STOP! ----------------------------------->
<!---
Having trouble installing node-canvas? Please make sure you have read
the installation instructions located here before asking for help:
https://github.com/Automattic/node-canvas#installation
Still having problems, found a bug or want a feature? Fill out the form below.
-->
```

Followed your instructions and all I get are errors:
```
C:\Users\brian.cullinan\Documents\jupytangular2>choco install -y python2 gtk-runtime microsoft-build-tools libjpeg-turbo
Chocolatey v0.10.8
Chocolatey detected you are not running from an elevated command shell
 (cmd/powershell).

 You may experience errors - many functions/packages
 require admin rights. Only advanced users should run choco w/out an
 elevated shell. When you open the command shell, you should ensure
 that you do so with "Run as Administrator" selected. If you are
 attempting to use Chocolatey in a non-administrator setting, you
 must select a different location other than the default install
 location. See
 https://chocolatey.org/install#non-administrative-install for details.

For the question below, you have 20 seconds to make a selection.

 Do you want to continue?([Y]es/[N]o): Y

Installing the following packages:
python2;gtk-runtime;microsoft-build-tools;libjpeg-turbo
By installing you accept licenses for the packages.
python2 v2.7.14 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
gtk-runtime v2.24.10.20121010 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
microsoft-build-tools v15.0.26320.2 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
libjpeg-turbo v1.2.1.201304081 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

Chocolatey installed 0/4 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Warnings:
 - gtk-runtime - gtk-runtime v2.24.10.20121010 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
 - microsoft-build-tools - microsoft-build-tools v15.0.26320.2 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
 - libjpeg-turbo - libjpeg-turbo v1.2.1.201304081 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
 - python2 - python2 v2.7.14 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

C:\Users\brian.cullinan\Documents\jupytangular2>npm install canvas

> canvas@1.6.7 install C:\Users\brian.cullinan\Documents\jupytangular2\node_modules\canvas
> node-gyp rebuild


C:\Users\brian.cullinan\Documents\jupytangular2\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Users\brian.cullinan\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libfreetype-6.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  color.cc
  Image.cc
  ImageData.cc
  init.cc
  win_delay_load_hook.cc
c:\users\brian.cullinan\documents\jupytangular2\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Canvas.cc) [C:\Users\brian.cullinan\
Documents\jupytangular2\node_modules\canvas\build\canvas.vcxproj]
c:\users\brian.cullinan\documents\jupytangular2\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\CanvasGradient.cc) [C:\Users\brian.c
ullinan\Documents\jupytangular2\node_modules\canvas\build\canvas.vcxproj]
c:\users\brian.cullinan\documents\jupytangular2\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\ImageData.cc) [C:\Users\brian.cullin
an\Documents\jupytangular2\node_modules\canvas\build\canvas.vcxproj]
c:\users\brian.cullinan\documents\jupytangular2\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\init.cc) [C:\Users\brian.cullinan\Do
cuments\jupytangular2\node_modules\canvas\build\canvas.vcxproj]
c:\users\brian.cullinan\documents\jupytangular2\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\CanvasPattern.cc) [C:\Users\brian.cu
llinan\Documents\jupytangular2\node_modules\canvas\build\canvas.vcxproj]
c:\users\brian.cullinan\documents\jupytangular2\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\CanvasRenderingContext2d.cc) [C:\Use
rs\brian.cullinan\Documents\jupytangular2\node_modules\canvas\build\canvas.vcxproj]
c:\users\brian.cullinan\documents\jupytangular2\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Image.cc) [C:\Users\brian.cullinan\D
ocuments\jupytangular2\node_modules\canvas\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\brian.cullinan\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\brian.cullinan\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\brian.cullinan\Documents\jupytangular2\node_modules\canvas
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN extract-text-webpack-plugin@3.0.0 requires a peer of webpack@^3.1.0 but none was installed.
npm WARN html-webpack-plugin@2.30.1 requires a peer of webpack@1 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3 but none was installed.
npm WARN less-loader@4.0.5 requires a peer of webpack@^2.0.0 || ^3.0.0 but none was installed.
npm WARN sass-loader@6.0.6 requires a peer of webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0 but none was installed.
npm WARN uglifyjs-webpack-plugin@0.4.6 requires a peer of webpack@^1.9 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3.0.0 but none was installed.
npm WARN webpack-dev-middleware@1.12.0 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 but none was installed.
npm WARN webpack-dev-server@2.7.1 requires a peer of webpack@^2.2.0 || ^3.0.0 but none was installed.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\brian.cullinan\AppData\Roaming\npm-cache\_logs\2017-10-27T17_55_11_525Z-debug.log
```

**Comment by megamindbrian** [comment]
Requires node 8 in the instructions?

https://github.com/Automattic/node-canvas/issues/619

**Comment by zbjornson** [comment]
The chocolatey instructions don't quite work. There's now a warning on the wiki page about that until someone gets around to fixing them. Please try the manual windows instructions, or use canvas-prebuilt instead.
