### ISSUE TITLE
Can't install node-canvas

### ISSUE THREAD

**Issue by nebakki** [Automattic/node-canvas#1072]
## Your Environment
* Windows 7 32bit
* GTK+ v2.24.10
* Node v8.1.3
* NPM v5.0.3
* libjpeg-turbo (1.5.3-vcc)
* Python 2.7.14
* Visual Studio 2015 community

## Your issue
I tried both, manual and Chocolatey, method to install node-canvas but it's been giving me the same error from the very start. I even followed the method listed in [#619](https://github.com/Automattic/node-canvas/issues/619)
I'd appreciate some help.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'canvas' ]
2 info using npm@5.0.3
3 info using node@v8.1.3
4 verbose npm-session d9b42bfe83832c6c
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/canvas 1435ms (from cache)
8 silly pacote tag manifest for canvas@latest fetched in 2793ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule canvas@1.6.9 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/nan 296ms (from cache)
15 silly pacote range manifest for nan@^2.4.0 fetched in 359ms
16 silly resolveWithNewModule nan@2.8.0 checking installable status
17 silly currentTree Enjuu
17 silly currentTree +-- async-limiter@1.0.0
17 silly currentTree +-- discord.js@11.2.1
17 silly currentTree +-- long@3.2.0
17 silly currentTree +-- prism-media@0.0.1
17 silly currentTree +-- safe-buffer@5.1.1
17 silly currentTree +-- snekfetch@3.5.8
17 silly currentTree +-- tweetnacl@1.0.0
17 silly currentTree +-- ultron@1.1.1
17 silly currentTree `-- ws@3.3.2
18 silly idealTree Enjuu
18 silly idealTree +-- async-limiter@1.0.0
18 silly idealTree +-- canvas@1.6.9
18 silly idealTree +-- discord.js@11.2.1
18 silly idealTree +-- long@3.2.0
18 silly idealTree +-- nan@2.8.0
18 silly idealTree +-- prism-media@0.0.1
18 silly idealTree +-- safe-buffer@5.1.1
18 silly idealTree +-- snekfetch@3.5.8
18 silly idealTree +-- tweetnacl@1.0.0
18 silly idealTree +-- ultron@1.1.1
18 silly idealTree `-- ws@3.3.2
19 silly install generateActionsToTake
20 silly diffTrees action count 2
21 silly diffTrees add nan@2.8.0
22 silly diffTrees add canvas@1.6.9
23 silly decomposeActions action count 16
24 silly decomposeActions fetch nan@2.8.0
25 silly decomposeActions extract nan@2.8.0
26 silly decomposeActions preinstall nan@2.8.0
27 silly decomposeActions build nan@2.8.0
28 silly decomposeActions install nan@2.8.0
29 silly decomposeActions postinstall nan@2.8.0
30 silly decomposeActions finalize nan@2.8.0
31 silly decomposeActions refresh-package-json nan@2.8.0
32 silly decomposeActions fetch canvas@1.6.9
33 silly decomposeActions extract canvas@1.6.9
34 silly decomposeActions preinstall canvas@1.6.9
35 silly decomposeActions build canvas@1.6.9
36 silly decomposeActions install canvas@1.6.9
37 silly decomposeActions postinstall canvas@1.6.9
38 silly decomposeActions finalize canvas@1.6.9
39 silly decomposeActions refresh-package-json canvas@1.6.9
40 silly install executeActions
41 silly doSerial global-install 16
42 verbose correctMkdir C:\Users\Lucius\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
43 verbose lock using C:\Users\Lucius\AppData\Roaming\npm-cache\_locks\staging-2c27a4911c469b68.lock for C:\Users\Lucius\Desktop\Enjuu\node_modules\.staging
44 silly doParallel extract 16
45 silly extract nan@2.8.0
46 silly pacote trying nan@https://registry.npmjs.org/nan/-/nan-2.8.0.tgz by hash: sha1-7XFfP+neArV6XmJS2QqWZ14fCFo=
47 silly extract canvas@1.6.9
48 silly pacote trying canvas@https://registry.npmjs.org/canvas/-/canvas-1.6.9.tgz by hash: sha1-4/lc7HsWvy1vP8clwC2UDTJY9ps=
49 silly pacote canvas@https://registry.npmjs.org/canvas/-/canvas-1.6.9.tgz extracted to C:\Users\Lucius\Desktop\Enjuu\node_modules\.staging\canvas-7d8306da by content address 374ms
50 silly pacote nan@https://registry.npmjs.org/nan/-/nan-2.8.0.tgz extracted to C:\Users\Lucius\Desktop\Enjuu\node_modules\.staging\nan-92d30de2 by content address 421ms
51 silly doReverseSerial remove 16
52 silly doSerial move 16
53 silly doSerial finalize 16
54 silly finalize C:\Users\Lucius\Desktop\Enjuu\node_modules\canvas
55 silly finalize C:\Users\Lucius\Desktop\Enjuu\node_modules\nan
56 silly doParallel refresh-package-json 16
57 silly refresh-package-json C:\Users\Lucius\Desktop\Enjuu\node_modules\canvas
58 silly refresh-package-json C:\Users\Lucius\Desktop\Enjuu\node_modules\nan
59 silly doParallel preinstall 16
60 silly preinstall canvas@1.6.9
61 info lifecycle canvas@1.6.9~preinstall: canvas@1.6.9
62 silly preinstall nan@2.8.0
63 info lifecycle nan@2.8.0~preinstall: nan@2.8.0
64 silly lifecycle canvas@1.6.9~preinstall: no script for preinstall, continuing
65 silly lifecycle nan@2.8.0~preinstall: no script for preinstall, continuing
66 silly doSerial build 16
67 silly build canvas@1.6.9
68 info linkStuff canvas@1.6.9
69 silly linkStuff canvas@1.6.9 has C:\Users\Lucius\Desktop\Enjuu\node_modules as its parent node_modules
70 verbose linkBins canvas@1.6.9
71 verbose linkMans canvas@1.6.9
72 silly build nan@2.8.0
73 info linkStuff nan@2.8.0
74 silly linkStuff nan@2.8.0 has C:\Users\Lucius\Desktop\Enjuu\node_modules as its parent node_modules
75 verbose linkBins nan@2.8.0
76 verbose linkMans nan@2.8.0
77 silly doSerial global-link 16
78 silly doParallel update-linked 16
79 silly doSerial install 16
80 silly install canvas@1.6.9
81 info lifecycle canvas@1.6.9~install: canvas@1.6.9
82 verbose lifecycle canvas@1.6.9~install: unsafe-perm in lifecycle true
83 verbose lifecycle canvas@1.6.9~install: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Lucius\Desktop\Enjuu\node_modules\canvas\node_modules\.bin;C:\Users\Lucius\Desktop\Enjuu\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\platform-tools\;C:\cygwin\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\GTK2-Runtime\bin;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Users\Lucius\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Lucius\AppData\Local\Programs\Python\Python36-32\;C:\Users\Lucius\Desktop\Stiletto\node_modules\ffmpeg\bin;C:\Program Files\Microsoft VS Code\bin
84 verbose lifecycle canvas@1.6.9~install: CWD: C:\Users\Lucius\Desktop\Enjuu\node_modules\canvas
85 silly lifecycle canvas@1.6.9~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
86 silly lifecycle canvas@1.6.9~install: Returned: code: 1  signal: null
87 info lifecycle canvas@1.6.9~install: Failed to exec install script
88 verbose unlock done using C:\Users\Lucius\AppData\Roaming\npm-cache\_locks\staging-2c27a4911c469b68.lock for C:\Users\Lucius\Desktop\Enjuu\node_modules\.staging
89 warn enoent ENOENT: no such file or directory, open 'C:\Users\\Lucius\Desktop\Enjuu\package.json'
90 verbose enoent This is related to npm not being able to find a file.
91 warn discord.js@11.2.1 requires a peer of bufferutil@^3.0.2 but none was installed.
92 warn discord.js@11.2.1 requires a peer of erlpack@hammerandchisel/erlpack but none was installed.
93 warn discord.js@11.2.1 requires a peer of node-opus@^0.2.6 but none was installed.
94 warn discord.js@11.2.1 requires a peer of opusscript@^0.0.3 but none was installed.
95 warn discord.js@11.2.1 requires a peer of sodium@^2.0.1 but none was installed.
96 warn discord.js@11.2.1 requires a peer of libsodium-wrappers@^0.5.4 but none was installed.
97 warn discord.js@11.2.1 requires a peer of uws@^0.14.5 but none was installed.
98 warn Enjuu No description
99 warn Enjuu No repository field.
100 warn Enjuu No README data
101 warn Enjuu No license field.
102 verbose stack Error: canvas@1.6.9 install: `node-gyp rebuild`
102 verbose stack Exit status 1
102 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16)
102 verbose stack     at emitTwo (events.js:125:13)
102 verbose stack     at EventEmitter.emit (events.js:213:7)
102 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
102 verbose stack     at emitTwo (events.js:125:13)
102 verbose stack     at ChildProcess.emit (events.js:213:7)
102 verbose stack     at maybeClose (internal/child_process.js:897:16)
102 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
103 verbose pkgid canvas@1.6.9
104 verbose cwd C:\Users\Lucius\Desktop\Enjuu
105 verbose Windows_NT 6.1.7601
106 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "canvas"
107 verbose node v8.1.3
108 verbose npm  v5.0.3
109 error code ELIFECYCLE
110 error errno 1
111 error canvas@1.6.9 install: `node-gyp rebuild`
111 error Exit status 1
112 error Failed at the canvas@1.6.9 install script.
112 error This is probably not a problem with npm. There is likely additional logging output above.
113 verbose exit [ 1, true ]
```

**Comment by zbjornson** [comment]
Thanks for posting the log -- unfortunately it omits some useful info though. Can you try cloning this repository (vs. installing canvas as a dependency -- can't tell if you were doing that already) and running `npm install nan` and then `node-gyp rebuild` directly?

Blindly guessing: you mentioned 32-bit Windows -- make sure node, cairo and libjpeg are all the 32-bit versions.

Also, prebuilt canvas is available via `npm install canvas-prebuilt` if you want to avoid this process.

**Comment by nebakki** [comment]
@zbjornson Everything is in 32-bit and what do you mean by running node-gyp directly? Also, Isn't Canvas-prebuilt lacks features compared to node-canvas?

**Comment by nebakki** [comment]
@zbjornson Nvm, I found my problem. I was lacking some .dll files and vs c++ compiler, I was having some trouble downloading it so I asked for help here. You can close this issue now. 

Anyone having the same trouble, read the errors in your terminal and make sure you've got those files downloaded.

**Comment by zbjornson** [comment]
Glad you figured it out.

>  Isn't Canvas-prebuilt lacking in features compared to node-canvas?

Nope, `canvas-prebuilt` is  drop-in, fully featured replacement.
