### ISSUE TITLE
SVG load error 

### ISSUE THREAD

**Issue by eqfox** [Automattic/node-canvas#1079]
SVG load error 

Image given has not completed loading

**Comment by LinusU** [comment]
Did you wait for the `onload` event to fire? Or use the new `loadImage`-function?

Please share some of your code so we can help you further...

**Comment by ducva** [comment]
I used loadImage function,

`
loadImage(path.join(__dirname, 'star.svg'))
  .then(image => {
    // image.width = 30
    // image.height = 30
    context.drawImage(image, 300, 120)
    canvas.createPNGStream().pipe(fs.createWriteStream('out.png'))
  })
  .catch(e => debug(e))

`

Then got error:

`
  c:* Error: error while reading from input stream
  c:*     at Image.src (/node_modules/canvas/lib/image.js:30:17)
  c:*     at Promise (/node_modules/canvas/index.js:34:15)
  c:*     at new Promise (<anonymous>)
  c:*     at loadImage (node_modules/canvas/index.js:23:10)

**Comment by pixelass** [comment]
Same issue here

```js
loadImage("icons/github.svg")
    .then(image => {
        console.log(image);
    })
    .catch(err => {
        console.error(err);
    });
```

```
Error: error while reading from input stream
    at Image.src (/Users/greada/Workspace/Pixelass/macos-folder-icons/node_modules/canvas-prebuilt/canvas/lib/image.js:30:17)
    at Promise (/Users/greada/Workspace/Pixelass/macos-folder-icons/node_modules/canvas-prebuilt/canvas/index.js:34:15)
    at new Promise (<anonymous>)
    at loadImage (/Users/greada/Workspace/Pixelass/macos-folder-icons/node_modules/canvas-prebuilt/canvas/index.js:23:10)
    at Promise (/Users/greada/Workspace/Pixelass/macos-folder-icons/index.js:23:5)
    at new Promise (<anonymous>)
    at drawLayer (/Users/greada/Workspace/Pixelass/macos-folder-icons/index.js:22:3)
    at drawBase.then (/Users/greada/Workspace/Pixelass/macos-folder-icons/index.js:47:3)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
✨  Done in 0.64s.
```

**Comment by marcsyp** [comment]
@pixelass did you solve this issue?  I am having this problem with PNG files, and I'm using all the up-to-date code with v2.0.0-alpha.11, Win 10 with Node 9.7.1.

**Comment by pixelass** [comment]
@marcsyp I am using puppeteer now.

**Comment by masataka-kurihara** [comment]
I got same error, loadImage(SVG) at v2.0.0-alpha12, Mac10.13.4 with Node 9.11.1. SVG came from jsdom or file.
I did
- loadImage(svg.outerHTML);
- loadImage(new Buffer(svg.outerHTML));
- loadImage('data:image/svg+xml;charset-utf-8,' + encodeURIComponent(svg.outerHTML));
- loadImage(path.resolve(__dirname, 'source.svg'));
All fail.
