### ISSUE TITLE
loadImage not working with any image source -- error while reading from input stream

### ISSUE THREAD

**Issue by marcsyp** [Automattic/node-canvas#1154]
## Issue or Feature
I am unable to load any PNG images at all, either local or by url

## Steps to Reproduce
Image below was taken from another code sample, I have verified that it exists.

```

// SET UP NODE-CANVAS + BUNDLED FONT
const { registerFont, createCanvas, loadImage } = require('canvas');
var path = require('path');

function fontFile (name) {
    return path.join(__dirname, '../fonts/spartanMB/', name)
}

function testImage() {

    loadImage('http://placehold.it/256x256/0000ff/ffffff&text=node-canvas').then((image) => {
                console.log('test', image);
                ctx.drawImage(image, 250, 0, 70, 70)
    }).catch(e => console.log('testError', e));
}
```
testError Error: error while reading from input stream
    at Image.src (C:\Users\marcs\Documents\Bitbucket\hashgear-server\node_modules\canvas\lib\image.js:30:17)
    at Promise (C:\Users\marcs\Documents\Bitbucket\hashgear-server\node_modules\canvas\index.js:34:15)
    at new Promise (<anonymous>)
    at loadImage (C:\Users\marcs\Documents\Bitbucket\hashgear-server\node_modules\canvas\index.js:23:10)
    at testImage (C:\Users\marcs\Documents\Bitbucket\hashgear-server\modules\utils.js:18:5)
    at Object.<anonymous> (C:\Users\marcs\Documents\Bitbucket\hashgear-server\modules\utils.js:25:1)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)

## Thoughts
The stacktrace goes back to "tryModuleLoad" -- does this mean the Image module is not loading properly (sorry, i'm a n00b)

## Your Environment
* Version of node-canvas (e.g. 1.4.0): 2.0.0-alpha.11 (also tried 12)
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Node 9.7.1 on Windows 10 x64

**Comment by zbjornson** [comment]
node-canvas doesn't let you pass a URL yet (#945) (it should because browsers do).

What does your attempt to load a local image look like?

**Comment by marcsyp** [comment]
I had the same problem with a local file.  But I will try again later.

**Comment by zbjornson** [comment]
@marcsyp if you're still having problems, leave a comment and I'll reopen the issue.
