### ISSUE TITLE
v2.0.0-alpha crashed but v1.6.10 worked fine.

### ISSUE THREAD

**Issue by zjuwjf** [Automattic/node-canvas#1161]
node-canvas 1.6.10 works fine. 
But when I update it to v2.0.0-alpha (using npm install canvas@next), it always crashed.

For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
internal/modules/cjs/loader.js:707
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: dlopen(/Users/zjuwjf/idlefish-git/dsl/node_modules/_canvas@2.0.0-alpha.12@canvas/build/Release/canvas.node, 1): Library not loaded: @loader_path/libintl.8.dylib
  Referenced from: /Users/zjuwjf/idlefish-git/dsl/node_modules/_canvas@2.0.0-alpha.12@canvas/build/Release/canvas.node
  Reason: image not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:707:18)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/zjuwjf/idlefish-git/dsl/node_modules/_canvas@2.0.0-alpha.12@canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/zjuwjf/idlefish-git/dsl/node_modules/_babel-register@6.26.0@babel-register/lib/node.js:152:7)

## My Environment
* Version of node-canvas (e.g. 1.4.0):
* Environment (node v10.1.0 on Mac OS X 10.12.6):

**Comment by chearon** [comment]
Is there anything non-standard about the way you're installing it? It works on macOS. I don't recognize your path to `canvas.node` (why is the folder called `_canvas@2.0.0-alpha.12@canvas`?) so that could be part of it.
