### ISSUE TITLE
C:\Samp\node_modules\canvas\build\Release\canvas.node cannot be found

### ISSUE THREAD

**Issue by Midnightsto** [Automattic/node-canvas#1192]
So i just installed canvas and whenever i want to run the file it gives me the following error:
`module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Samp\node_modules\canvas\build\Release\canvas.node
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Samp\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Samp\node_modules\canvas\lib\canvas.js:13:14)
    at Module._compile (module.js:652:30)
`

## Your Environment
* Version of node-canvas (e.g. 1.4.0):1.6.11
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):latest version windows node js

**Comment by ypenghui6** [comment]
I have this problem too. How is it solved? I use the 64-bit GTK,  the node_modules\canvas\build\Release has libfreetype-6.dll.

**Comment by jafar-rezaei** [comment]
As `canvas-prebuilt` deprecated , how we should solve this issue?

**Comment by LinusU** [comment]
@jafar-rezaei canvas-prebuilt has been merged into this project, you can just use the latest version of canvas and it will include prebuilt binaries :)
