### ISSUE TITLE
Error while building (pangocairo)

### ISSUE THREAD

**Issue by Doges** [Automattic/node-canvas#1263]
## Issue or Feature
Issue

Build fails for canvas on travis/heroku (looks like a error while trying to find pangocairo)
## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');
// etc.
```
Build it on travis or another CLI

## Your Environment
* Version of node-canvas (e.g. 1.4.0):
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):
canvas@2.0.0-alpha.17
Ubuntu 18.04

**Comment by zbjornson** [comment]
Have you looked at the installation info for Heroku: https://github.com/Automattic/node-canvas/wiki/Installation:-Heroku, or our .travis.yml file: https://github.com/Automattic/node-canvas/blob/master/.travis.yml?

**Comment by Doges** [comment]
Yea, it never errored before, thats not the first time that i use canvas.

**Comment by Doges** [comment]
Heres the log from travis:
```> canvas@2.0.0-alpha.17 install /home/travis/build/package/package/node_modules/canvas
> node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.0.0-alpha.17/canvas-prebuilt-v2.0.0-alpha.17-node-v64-linux-glibc-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.0.0-alpha.17 and node@10.11.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
Package pangocairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `pangocairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pangocairo' found
gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp```

**Comment by danielstaleiny** [comment]
I can also confirm that I could install node-canvas before, but now I am hitting the same wall regarding node-gyp

```
error /code/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /code/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@8.11.2 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/code/node_modules/canvas/build/Release/canvas-prebuilt.node" (not found)
node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.0.0-alpha.17/canvas-prebuilt-v2.0.0-alpha.17-node-v57-linux-glibc-x64.tar.gz
node-pre-gyp http 404 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.0.0-alpha.17/canvas-prebuilt-v2.0.0-alpha.17-node-v57-linux-glibc-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.0.0-alpha.17/canvas-prebuilt-v2.0.0-alpha.17-node-v57-linux-glibc-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.0.0-alpha.17 and node@8.11.2 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.0.0-alpha.17/canvas-prebuilt-v2.0.0-alpha.17-node-v57-linux-glibc-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.2 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.2 | linux | x64
gyp http GET https://nodejs.org/download/release/v8.11.2/node-v8.11.2-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.11.2/node-v8.11.2-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v8.11.2/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.11.2/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/code/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/8.11.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.11.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.11.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/code/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.18.9-arch1-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/code/node_modules/canvas/build/Release/canvas-prebuilt.node" "--module_name=canvas-prebuilt" "--module_path=/code/node_modules/canvas/build/Release" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd /code/node_modules/canvas
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/code/node_modules/canvas/build/Release/canvas-prebuilt.node --module_name=canvas-prebuilt --module_path=/code/node_modules/canvas/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/code/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.18.9-arch1-1-ARCH
node-pre-gyp ERR! command "/usr/bin/node" "/code/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /code/node_modules/canvas
node-pre-gyp ERR! node -v v8.11.2
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/code/node_modules/canvas/build/Release/canvas-prebuilt.node --module_name=canvas-prebuilt --module_path=/code/node_modules/canvas/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)

```

**Comment by Doges** [comment]
like, i use npm :thinking:

**Comment by chearon** [comment]
> Yea, it never errored before, thats not the first time that i use canvas.

I wonder if people initially install from the prebuilds, and then are surprised when a new release doesn't have them. @LinusU maybe we should start coordinating releases. You can tag the new version here, then release the binaries on GitHub so they're ready for the `npm publish`.

That said, this should happen to people pretty rarely, since I don't think if you specify `"canvas": "^2.0.0-alpha.17"` that yarn/npm will install `2.0.0-alpha.18` when it's released.

**Comment by danielstaleiny** [comment]
Update, I found out that the issue was primarily with Nodejs version 8.x, by downgrading my environment to 6.x. I fixed the issue for now.

**Comment by shaoxp** [comment]
i met the same problem today without changes on packages, it worked yesterday. .
the same error show when building my docker image, which has dependency to canvas. 

the docker build is using following version. i am still trying the solution.

gyp ERR! node -v v8.15.1                                                                                                                                                                                                                                                        gyp ERR! node-gyp -v v3.8.0
--

**Comment by EliasSeccom** [comment]
@shaoxp We have the same problem since yesterday too...

**Comment by michaelscheurer** [comment]
Same here

**Comment by zbjornson** [comment]
Prebuilds are served from GitHub, and yesterday at least they were having server issues. https://www.githubstatus.com/incidents/fdl6khghfsp3

There is no prebuild for Node.js v13 yet. Until then you'll have to compile it yourself (see top of the readme: https://github.com/Automattic/node-canvas#compiling - or the wiki: https://github.com/Automattic/node-canvas/wiki).

**Comment by shaoxp** [comment]
thanks very much for the information. it works with prebuilds.
