### ISSUE TITLE
Can't run npm run serve, need help

### ISSUE THREAD

**Issue by CW53** [Automattic/node-canvas#1269]
## Issue or Feature

uest3 (master *) wittr
$ npm run serve

> wittr@1.0.0 serve /Users/Guest3/wittr
> gulp serve

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'lodash/object/assign'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/Guest3/wittr/gulpfile.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wittr@1.0.0 serve: `gulp serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wittr@1.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Guest3/.npm/_logs/2018-10-04T19_43_54_828Z-debug.log
## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');
// etc.
```

## Your Environment
* Version of node-canvas (e.g. 1.4.0):
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):

**Comment by zbjornson** [comment]
Unless I'm missing something ... this doesn't look at all related to canvas.
