### ISSUE TITLE
Cannot `yarn add canvas-prebuilt` on MacOS - node-pre-gyp http 404

### ISSUE THREAD

**Issue by lk-jeffpeck** [Automattic/node-canvas#1338]
Cannot `yarn add canvas-prebuilt` on MacOS

## Issue
```
$ yarn add -D canvas-prebuilt
```

```
error ~/dev/rc-oculus/node_modules/canvas-prebuilt: Command failed.
Exit code: 1
Command: node-pre-gyp install
Arguments:
Directory: ~/dev/rc-oculus/node_modules/canvas-prebuilt
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.3
node-pre-gyp info using node@11.3.0 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "~/dev/rc-oculus/node_modules/canvas-prebuilt/canvas/build/Release/canvas-prebuilt.node" (not found)
node-pre-gyp http GET https://github.com/chearon/node-canvas-prebuilt/releases/download/v2.0.0-alpha.14/canvas-prebuilt-v2.0.0-alpha.14-node-v67-darwin-unknown-x64.tar.gz
node-pre-gyp http 404 https://github.com/chearon/node-canvas-prebuilt/releases/download/v2.0.0-alpha.14/canvas-prebuilt-v2.0.0-alpha.14-node-v67-darwin-unknown-x64.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v2.0.0-alpha.14/canvas-prebuilt-v2.0.0-alpha.14-node-v67-darwin-unknown-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (~/dev/rc-oculus/node_modules/node-pre-gyp/lib/install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:187:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (~/dev/rc-oculus/node_modules/request/request.js:1066:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:182:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:562:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:449:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:182:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:287:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:268:11)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "~/.brew/Cellar/node/11.3.0_1/bin/node" "~/dev/rc-oculus/node_modules/canvas-prebuilt/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd ~/dev/rc-oculus/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v11.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
```

## Steps to Reproduce
Try to install canvas-prebuilt on MacOS
```
$ yarn add -D canvas-prebuilt
```

## Your Environment
MacOS 10.14.12

**Comment by zbjornson** [comment]
@chearon is it worth deprecating `canvas-prebuilt` with a message pointing people to `canvas` instead? This has come up a few times.

**Comment by chearon** [comment]
Well we put a message up on the readme... I was resisting deprecating the NPM package because that can be so annoying in deep dependencies, but I guess I should since that's what it's for

**Comment by lk-jeffpeck** [comment]
`yarn add canvas` also fails.

Note, I tried adding canvas-prebuilt as suggested here:
https://github.com/pixijs/pixi.js/issues/4769

If I can get `canvas` working, will that solve this issue?

**Comment by lk-jeffpeck** [comment]
erm, forget last message. It installs fine, but still the same issue.

According to that thread (pixijs/pixi.js#4769), I need `canvas-prebuilt@1`.

**Comment by lk-jeffpeck** [comment]
I was able to use this:
https://www.npmjs.com/package/jest-canvas-mock

So, all set, thanks.
