### ISSUE TITLE
Unable to use Canvas on windows server 2008 R2 with node 10.15

### ISSUE THREAD

**Issue by VittorioAccomazzi** [Automattic/node-canvas#1351]
Hi All,

I'm new to node, and I'm trying to use canvas (not to compile, just to use it) and I'm not able to. I'm clearly doing something wrong, and I appreciate some help.

## Issue or Feature

Unable to install canvas properly with 
```
npm i canvas
```

## Steps to Reproduce

1. Installed on a blank windows 2008 R2 **node 10.15.0**

1. installed canvas with the command ```npm i canvas```
1. in the same folder where canvas is installed, created the file test.js containing the 'Quick Example' in the [npm page](https://www.npmjs.com/package/canvas).
1. ran the example using 
```
node test.js
```
and got the following error :

```js
C:\Users\Administrator>node test.js
internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\Administrator\node_modules\canvas\build\Release\canvas.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Administrator\node_modules\canvas\lib\bindin
gs.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): **2.3.0**
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 10.15.0 running on windows 2008 R2

**Comment by k3rn31p4nic** [comment]
As far as I can tell, pre-built binaries aren't available for Node.js 10+ as I can see in [here](https://github.com/node-gfx/node-canvas-prebuilt#binaries).

Try to build canvas binaries for your version of Node and see if it fixes your issue:
```bash
npm i --build-from-source canvas
```

If this is the case, I would like to suggest to the maintainers to add pre-built binaries for v10 as it is now a LTS version.

**Comment by VittorioAccomazzi** [comment]
Thank you k3rn31p4nic, however if I use the command you suggested I still get a number of error :
`
C:\Users\Administrator>npm i --build-from-source canvas

> canvas@2.3.0 install C:\Users\Administrator\node_modules\canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_mod
ules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\grac
eful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--f
allback-to-build" "--module=C:\\Users\\Administrator\\node_modules\\canvas\\buil
d\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\Admini
strator\\node_modules\\canvas\\build\\Release" "--napi_version=3" "--node_abi_na
pi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd C:\Users\Administrator\node_modules\canvas
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.e
xe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.j
s configure --fallback-to-build --module=C:\Users\Administrator\node_modules\can
vas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\Admini
strator\node_modules\canvas\build\Release --napi_version=3 --node_abi_napi=napi
--napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Administrator\
node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admi
nistrator\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-
to-build"
node-pre-gyp ERR! cwd C:\Users\Administrator\node_modules\canvas
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node
_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build
 --module=C:\Users\Administrator\node_modules\canvas\build\Release\canvas.node -
`
So If I read correctly the table you linked I should be able to use canvas@1.6.x with node 8.x, am I correct ? I think that will work for me. I'll give it a try !

**Comment by VittorioAccomazzi** [comment]
This is the second try using **node.j 8.15** and **Canvas 1.6.2**

```
C:\Users\Administrator\Desktop>node -v
v8.15.0

C:\Users\Administrator\Desktop>npm i canvas@1.6.12
```
apparently this requires Python because I get the following error :
```
C:\Users\Administrator\Desktop\node_modules\canvas>if not defined npm_config_nod
e_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle
\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (nod
e "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.j
s" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_mod
ules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\grac
eful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\Desktop\node_modules\canvas
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Administrator\
Desktop\package.json'
npm WARN Desktop No description
npm WARN Desktop No repository field.
npm WARN Desktop No README data
npm WARN Desktop No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
```

Therefore I installed **Python 2.7.15** and re-run the installation :

```
C:\Users\Administrator\Desktop>npm i canvas@1.6.12

> canvas@1.6.12 install C:\Users\Administrator\Desktop\node_modules\canvas
> node-gyp rebuild


C:\Users\Administrator\Desktop\node_modules\canvas>if not defined npm_config_nod
e_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle
\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (nod
e "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.j
s" rebuild )
Warning: Missing input files:
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libfreetype-6.dll
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  Canvas.cc
c:\users\administrator\desktop\node_modules\canvas\src\Canvas.h(19): fatal erro
r C1083: Cannot open include file: 'cairo.h': No such file or directory [C:\Use
rs\Administrator\Desktop\node_modules\canvas\build\canvas.vcxproj]
  CanvasGradient.cc
c:\users\administrator\desktop\node_modules\canvas\src\Canvas.h(19): fatal erro
r C1083: Cannot open include file: 'cairo.h': No such file or directory [C:\Use
rs\Administrator\Desktop\node_modules\canvas\build\canvas.vcxproj]
  CanvasPattern.cc
c:\users\administrator\desktop\node_modules\canvas\src\Canvas.h(19): fatal erro
r C1083: Cannot open include file: 'cairo.h': No such file or directory [C:\Use
rs\Administrator\Desktop\node_modules\canvas\build\canvas.vcxproj]
  CanvasRenderingContext2d.cc
c:\users\administrator\desktop\node_modules\canvas\src\Canvas.h(19): fatal erro
r C1083: Cannot open include file: 'cairo.h': No such file or directory [C:\Use
rs\Administrator\Desktop\node_modules\canvas\build\canvas.vcxproj]
  color.cc
  Image.cc
c:\users\administrator\desktop\node_modules\canvas\src\Canvas.h(19): fatal erro
r C1083: Cannot open include file: 'cairo.h': No such file or directory [C:\Use
rs\Administrator\Desktop\node_modules\canvas\build\canvas.vcxproj]
  ImageData.cc
c:\users\administrator\desktop\node_modules\canvas\src\Canvas.h(19): fatal erro
r C1083: Cannot open include file: 'cairo.h': No such file or directory [C:\Use
rs\Administrator\Desktop\node_modules\canvas\build\canvas.vcxproj]
  init.cc
c:\users\administrator\desktop\node_modules\canvas\src\Canvas.h(19): fatal erro
```

... so at this point I'm not sure what to do next, any suggestion is welcome !

**Comment by graphitemaster** [comment]
This is problematic, 10.15 is long-term-support and what most up to date production installations of Node are running. How difficult would it be to escalate this to high priority for builds?

**Comment by zbjornson** [comment]
@k3rn31p4nic that readme doesn't have an up-to-date list of prebuilds. The authoritative list is here: https://github.com/node-gfx/node-canvas-prebuilt/releases (the one for win and node 10 is canvas-v2.3.0-node-v64-win32-unknown-x64.tar.gz).

That aside, there is a problem with that build. @chearon all the DLLs are missing from the tar ball.

Until that's fixed, v2.2.0's prebuild is working.

**Comment by LinusU** [comment]
> The build continued through an error that it should have aborted on, which I've fixed.

@chearon I've pushed a 2.3.1 tag with #1352 in it, so we should be able to take that opportunity to publish new working builds? ☺️

**Comment by chearon** [comment]
The MSYS2 installation on AppVeyor seems to be completely screwed up so Windows builds are a no-go for now 😞 . I'll go ahead and run the builds for 2.3.1 but the Windows ones will probably not post.

One thing that would help situations like this is if we somehow kept the library updates separate (like put them in their own NPM module or something). That way most node-canvas updates would just link to the latest library build. We could maybe even make one big statically linked binary blob of Cairo+Pango+JPEG+etc, but that might be difficult

**Comment by LinusU** [comment]
> One thing that would help situations like this is if we somehow kept the library updates separate (like put them in their own NPM module or something).

**Comment by zbjornson** [comment]
It could look sort of like nan, in that we'd make our binding.gyp have `"<!(node -e \"require('canvas-deps')\")"` to add the include directory. It just needs the headers and object files (dll/so/o).

**Comment by chearon** [comment]
> It could look sort of like nan, in that we'd make our binding.gyp have "<!(node -e \"require('canvas-deps')\")"

I like where that's going, I can see that working to aid node-canvas-prebuilt or other people building locally. It would have to use node-pre-gyp given the size of all of the dependencies.

The other way I was thinking of doing it is:  `canvas-deps` has a version that we bump every time we change or update dependencies and it's a regular NPM dependency. Installing `canvas` installs a prebuilt `canvas.node` (again probably node-pre-gyp) that somehow (?) can link to `canvas-deps` when loaded. If any of that fails (it's checked at install time) we fall back to build.

Since 90% of the time we aren't changing the C dependencies it would mean the deploy of prebuilds would be greatly simplified. Also means much quicker download time when people upgrade their node-canvas version.

Wonder if there are any other NPM modules that have such a huge C dependency burden...

Also @LinusU the v2.3.1 builds are up! I'm going to try running the prebuilds on a local Windows and just upload them manually today or tomorrow. Hopefully the issue isn't with MSYS2's package repos.

**Comment by zbjornson** [comment]
👍 doing that might even mean that we could distribute `canvas.node` for all versions of node and all platforms in the NPM tarball itself and drop node-pre-gyp. `canvas.node` is ~460 kB; I think the bulk of the prebuilt tarball size (7 to 27 MB) is the deps, which are the same for all versions of node.

> somehow (?) can link to canvas-deps when loaded

Maybe a simple post-install script to move the files where they're expected to be.

**Comment by lf1991** [comment]
The problem that has troubled me for a long time has finally been solved,thanks for your answer.
