### ISSUE TITLE
await is only valid in async function

### ISSUE THREAD

**Issue by Millie290** [Automattic/node-canvas#1355]
Hey i've got a error and idk why so if u can help it will be nice thx

## Fedora 29 Linux x64
* Version of node-canvas (2.0.1):
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):

code:
```js
var Discord = require ("discord.js");
const Client = require('discord.js').Client;
const YoutubeStream = require('ytdl-core')
const Canvas = require('canvas');
const snekfetch = require('snekfetch');

const client = new Discord.Client();

client.once('ready', () => {
	console.log('Ready!');
});

const applyText = (canvas, text) => {
	const ctx = canvas.getContext('2d');
	let fontSize = 70;

	do {
		ctx.font = `${fontSize -= 10}px sans-serif`;
	} while (ctx.measureText(text).width > canvas.width - 300);

	return ctx.font;
};

client.on('guildMemberAdd', async member => {
	const channel = member.guild.channels.find(ch => ch.name === 'member-log');
	if (!channel) return;

	const canvas = Canvas.createCanvas(700, 250);
	const ctx = canvas.getContext('2d');

	const background = await Canvas.loadImage('./wallpaper.jpg');
	ctx.drawImage(background, 0, 0, canvas.width, canvas.height);

	ctx.strokeStyle = '#74037b';
	ctx.strokeRect(0, 0, canvas.width, canvas.height);

	ctx.font = '28px sans-serif';
	ctx.fillStyle = '#ffffff';
	ctx.fillText('Welcome to the server,', canvas.width / 2.5, canvas.height / 3.5);

	ctx.font = applyText(canvas, `${member.displayName}!`);
	ctx.fillStyle = '#ffffff';
	ctx.fillText(`${member.displayName}!`, canvas.width / 2.5, canvas.height / 1.8);

	ctx.beginPath();
	ctx.arc(125, 125, 100, 0, Math.PI * 2, true);
	ctx.closePath();
	ctx.clip();

	const { body: buffer } = await snekfetch.get(member.user.displayAvatarURL);
	const avatar = await Canvas.loadImage(buffer);
	ctx.drawImage(avatar, 25, 25, 200, 200);

	const attachment = new Discord.Attachment(canvas.toBuffer(), 'welcome-image.png');

	channel.send(`Welcome to the server, ${member}!`, attachment);
});

client.on('message', async message => {
	if (message.content === '!join') {
		client.emit('guildMemberAdd', message.member || await message.guild.fetchMember(message.author));
	}
});

client.login('blabla');
```

the error:
```text
/home/mimillie/Documents/discord-bot (WaPer)/bot.js:136
	const { body: buffer } = await snekfetch.get(member.user.displayAvatarURL);
	                         ^^^^^

SyntaxError: await is only valid in async function
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by LinusU** [comment]
I'm not getting that error, and the script is parsed properly. Are you sure that the code posted is the exact code that you are trying to run?

**Comment by zbjornson** [comment]
Closing without more info. This is also likely not an issue in Canvas since Canvas doesn't use async/await anywhere.
