### ISSUE TITLE
npm install canvas --save fails (chmod, chown, & brew done)

### ISSUE THREAD

**Issue by hashoshi** [Automattic/node-canvas#1378]
Thanks in advance! Cheers

## Issue or Feature
Trying to install node-canvas in my nodejs project with the aforementioned command. Kept getting errors so I tried brew install following the steps in the instructions. Then I tried npm install again. No dice.

## precondition
I have run the brew install command for mac osx successfully, which should have installed the key componenets like cairo and pango. I did this because npm was not doing the trick. However, it does not recognize the install. I need to figure out how to add this into my node project using npm anyway.

## Steps to Reproduce
1. Verify node and npm version (8.10 and 6.4.1 respectively)
2. run npm install canvas --save in project directory
3. error displays

Package pangocairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `pangocairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pangocairo' found
gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users//me/master/main/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/me/master/main/node_modules/canvas/build/Release" "--napi_version=1" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd /Users/me/master/main/node_modules/canvas
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

## Your Environment
* Version of node-canvas that I am trying to install is the latest one
* Environment: OSX 10.14.3, Node 8.10.0, NPM 6.4.1

**Comment by LinusU** [comment]
> Package pangocairo was not found in the pkg-config search path.

Have you installed pango & cairo?

from the readme:

```sh
brew install pkg-config cairo pango libpng jpeg giflib librsvg
```

**Comment by hashoshi** [comment]
Yes sir, I have run that brew install command.

**Comment by LinusU** [comment]
Can you run `echo $PKG_CONFIG_PATH ` and paste the output?

**Comment by hashoshi** [comment]
1. blank path
2. no directory
3. no directory

Which clearly shows it was not installed even thought the brew install finished successfully with no errors. Baffling

**Comment by LinusU** [comment]
Hmm, what does `brew info cairo` show? Maybe it didn't link it, could potentially be fixed by running `brew link cairo`, `brew link pango`...

**Comment by zbjornson** [comment]
Closing due to inactivity, but happy to reopen if needed.
