### ISSUE TITLE
Out of Memory error on image load

### ISSUE THREAD

**Issue by peterbraden** [Automattic/node-canvas#140]
Here's the unit tests failing:

~/Desktop/repos/node-canvas:master$ make test

   canvas: 0.8.3
   cairo: 1.10.0

   canvas.test.js test Canvas#toBuffer(): Error: out of memory
    at Test.fn (/Users/peterbraden/Desktop/repos/node-canvas/test/canvas.test.js:306:35)
    at Test.runParallel (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:959:10)
    at Test.run (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:924:18)
    at next (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:867:22)
    at Test.run (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:925:13)
    at next (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:867:22)
    at Test.run (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:925:13)
    at next (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:867:22)
    at Test.run (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:925:13)
    at next (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:867:22)

   image.test.js test Image#onload: AssertionError: false === true
    at /Users/peterbraden/Desktop/repos/node-canvas/test/image.test.js:32:14
    at Test.<anonymous> (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:961:13)
    at Test.emit (events.js:61:17)
    at EventEmitter.<anonymous> (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:892:18)
    at EventEmitter.<anonymous> (events.js:81:20)
    at EventEmitter.emit (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:1053:10)
    at report (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:992:13)
    at EventEmitter.emit (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:1050:9)

   image.test.js test Image#{width,height}: AssertionError: 0 == 1
    at /Users/peterbraden/Desktop/repos/node-canvas/test/image.test.js:83:14
    at Test.<anonymous> (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:961:13)
    at Test.emit (events.js:61:17)
    at EventEmitter.<anonymous> (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:892:18)
    at EventEmitter.<anonymous> (events.js:81:20)
    at EventEmitter.emit (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:1053:10)
    at report (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:992:13)
    at EventEmitter.emit (/Users/peterbraden/Desktop/repos/node-canvas/node_modules/expresso/bin/expresso:1050:9)

   Failures: 3

make: **\* [test] Error 3

**Comment by peterbraden** [comment]
For reference: 

node v1.2.0
```
   canvas: 1.2.9
   cairo: 1.14.2


  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  30 passing (280ms)
  6 failing

  1)  test Canvas#toBuffer():
     TypeError: Cannot read property 'slice' of undefined
      at Context.module.exports.test Canvas#toBuffer() (test/canvas.test.js:366:28)

  2)  test Canvas#toBuffer() async:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at test/canvas.test.js:371:14

  3)  test Canvas#toDataURL():
     TypeError: Cannot read property 'toString' of undefined
      at Canvas.toDataURL (lib/canvas.js:212:36)
      at Context.module.exports.test Canvas#toDataURL() (test/canvas.test.js:385:27)

  4)  test Canvas#toDataURL() async:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at test/canvas.test.js:399:14
      at lib/canvas.js:207:23

  5)  test Canvas#toDataURL() async with type:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at test/canvas.test.js:407:14
      at lib/canvas.js:207:23

  6)  test Canvas#createSyncPNGStream():
     Error: out of memory
      at Error (native)
      at lib/pngstream.js:42:19


```

**Comment by peterbraden** [comment]
(and for anyone with this issue - I fixed it by using the macports version of cairo, rather than homebrew. woohoo and <3 )

**Comment by LinusU** [comment]
Closing this since it's very old, feel free to reopen if there is any new information :)
