### ISSUE TITLE
Can't install canvas on CentOS 7

### ISSUE THREAD

**Issue by haodalong** [Automattic/node-canvas#1428]
I have read wiki and followed the instructions. (https://github.com/Automattic/node-canvas/wiki/Installation%3A-Fedora-and-other-RPM-based-distributions)
But I Still Got problems. Please Help me, Thanks.

Can't install canvas on CentOS 7

## Log below
```js
[root@VM_0_5_centos ukidOA]# npm install canvas

> canvas@2.5.0 install /root/app/ukidOA/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.5.0 and node@10.15.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/root/app/ukidOA/node_modules/canvas/build' 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/app/ukidOA/node_modules/canvas/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/root/app/ukidOA/node_modules/canvas/.node-gyp'
gyp ERR! System Linux 3.10.0-514.26.2.el7.x86_64
gyp ERR! command "/root/env/node-v10.15.3-linux-x64/bin/node" "/root/env/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/root/app/ukidOA/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/root/app/ukidOA/node_modules/canvas/build/Release" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /root/app/ukidOA/node_modules/canvas
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/root/env/node-v10.15.3-linux-x64/bin/node /root/env/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/app/ukidOA/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/root/app/ukidOA/node_modules/canvas/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/app/ukidOA/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 3.10.0-514.26.2.el7.x86_64
node-pre-gyp ERR! command "/root/env/node-v10.15.3-linux-x64/bin/node" "/root/app/ukidOA/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/app/ukidOA/node_modules/canvas
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/root/env/node-v10.15.3-linux-x64/bin/node /root/env/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/app/ukidOA/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/root/app/ukidOA/node_modules/canvas/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ukidOA@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.5.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-21T07_59_06_915Z-debug.log
[root@VM_0_5_centos ukidOA]# sudo /root/app/ukidOA/node_modules/canvas/build
sudo：/root/app/ukidOA/node_modules/canvas/build：找不到命令
[root@VM_0_5_centos ukidOA]# sudo mkdir /root/app/ukidOA/node_modules/canvas/build
mkdir: 无法创建目录"/root/app/ukidOA/node_modules/canvas/build": 没有那个文件或目录
[root@VM_0_5_centos ukidOA]# sudo mkdir /root/app/ukidOA/node_modules/canvas/.node-gyp
mkdir: 无法创建目录"/root/app/ukidOA/node_modules/canvas/.node-gyp": 没有那个文件或目录
```

## Your Environment
node -v v10.15.3
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):canvas@2.5.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):Linux 3.10.0-514.26.2.el7.x86_64

**Comment by enaukkarinen** [comment]
Having the same issue on Centos 7.4.1708 and Node 8.12.

`
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.2.0 install: 'node-pre-gyp install --fallback-to-build'
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by haodalong** [comment]
Please anyone who can help us? Thanks!

**Comment by Apoorva-GA** [comment]
Facing the same error with node `v12.3.1` on mac `10.14.4`.

NOTE: 
Updating the [canvas](https://github.com/Automattic/node-canvas) dependency to [latest](https://github.com/Automattic/node-canvas/releases/tag/v2.5.0) should fix this. 
Happy to raise a PR for the same.

**Comment by kaushalmodi** [comment]
I am on RHEL 6.8 (glibc 2.12) and I am trying to use `wavedrom-cli` (which relies on this project). I cannot use it because of glibc 2.14 dependency (See https://github.com/wavedrom/cli/issues/11).

**Comment by chuyik** [comment]
There's no problem on CentOS 7, you should check your error message first, there's a line said: user "root" does not have permission to access the dev dir.
