### ISSUE TITLE
BMP's with palettes are unsupported

### ISSUE THREAD

**Issue by NightYoshi370** [Automattic/node-canvas#1433]
## Issue or Feature
Whenever I try to use BMPs made for DS Homebrew in my application, it returns the following error: `Error while processing DIB header - unsupported non-empty color palette`

## Steps to Reproduce

```js
const { createCanvas, loadImage } = require('canvas');
const data = await loadImage('https://github.com/RocketRobz/RocketVideoPlayer/raw/master/icon.bmp');
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): canvas 2.5.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Node 10 on Glitch

**Comment by Javier107** [comment]
Im not sure but prob is bc the BMPs that the DSi reads must not include color information so probably node-canvas can't parse BMPs that don't include color information. (This was suggested by Flame on Discord)

**Comment by NightYoshi370** [comment]
Here is the full error:

```
Error: Error while processing DIB header - unsupported non-empty color palette
    at setSource (/rbd/pnpm-volume/6959811c-1d7b-489f-b1f0-281ae0d8936c/node_modules/.registry.npmjs.org/canvas/2.5.0/node_modules/canvas/lib/image.js:91:13)
    at get.concat (/rbd/pnpm-volume/6959811c-1d7b-489f-b1f0-281ae0d8936c/node_modules/.registry.npmjs.org/canvas/2.5.0/node_modules/canvas/lib/image.js:59:11)
    at concat (/rbd/pnpm-volume/6959811c-1d7b-489f-b1f0-281ae0d8936c/node_modules/.registry.npmjs.org/simple-get/3.0.3/node_modules/simple-get/index.js:89:7)
    at IncomingMessage.<anonymous> (/rbd/pnpm-volume/6959811c-1d7b-489f-b1f0-281ae0d8936c/node_modules/.registry.npmjs.org/simple-concat/1.0.0/node_modules/simple-concat/index.js:7:13)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by zbjornson** [comment]
https://github.com/Automattic/node-canvas/blob/dd0c7c20ab92ae8bcf1f2de1fd3b89cec3bd1faa/src/bmp/BMPParser.cc#L159-L161

BMPs with palettes aren't supported yet. @Hakerh400 might have an idea of how easy/hard it would be to support.
