### ISSUE TITLE
DIB header processing error - doesn't work on V3INFO and V5 Bitmap headers

### ISSUE THREAD

**Issue by NightYoshi370** [Automattic/node-canvas#1436]
## Issue
node-canvas does not support BMPs with either the `BITMAPV3INFOHEADER` or `BITMAPV5HEADER` header

### BITMAPV3INFOHEADER examples

- https://raw.githubusercontent.com/FlameKat53/Relaunch/master/menu/nitrofiles/bg.bmp
- https://github.com/DS-Homebrew/twlmenu-extras/raw/e95a0c15505ebf3c69b58dafb1f6fe7f79b7c077/_nds/TWiLightMenu/akmenu/themes/DSFWTWL/btn2.bmp

### BITMAPV5HEADER example

- https://github.com/DS-Homebrew/twlmenu-extras/blob/e95a0c15505ebf3c69b58dafb1f6fe7f79b7c077/_nds/TWiLightMenu/r4menu/themes/Gameboy%20Mario/bckgrd_1.bmp?raw=true

## Steps to Reproduce

```js
const { createCanvas, loadImage } = require('canvas');
const data = await loadImage('https://raw.githubusercontent.com/FlameKat53/Relaunch/master/menu/nitrofiles/bg.bmp');
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): canvas 2.5.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Node 10 on Glitch

**Comment by NightYoshi370** [comment]
Here's the full error:

```js
Error: Error while processing DIB header - unsupported DIB header "BITMAPV3INFOHEADER"
    at setSource (/rbd/pnpm-volume/6959811c-1d7b-489f-b1f0-281ae0d8936c/node_modules/.github.com/Hakerh400/node-canvas/1c2a47b5c23b2cf122a09d0c17daa4ff3adcad3c/node_modules/canvas/lib/image.js:91:13)
    at get.concat (/rbd/pnpm-volume/6959811c-1d7b-489f-b1f0-281ae0d8936c/node_modules/.github.com/Hakerh400/node-canvas/1c2a47b5c23b2cf122a09d0c17daa4ff3adcad3c/node_modules/canvas/lib/image.js:59:11)
    at concat (/rbd/pnpm-volume/6959811c-1d7b-489f-b1f0-281ae0d8936c/node_modules/.registry.npmjs.org/simple-get/3.0.3/node_modules/simple-get/index.js:89:7)
    at IncomingMessage.<anonymous> (/rbd/pnpm-volume/6959811c-1d7b-489f-b1f0-281ae0d8936c/node_modules/.registry.npmjs.org/simple-concat/1.0.0/node_modules/simple-concat/index.js:7:13)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)```
