### ISSUE TITLE
createCanvas is not defined after successful installation of 2.5.0 with Node 10.16

### ISSUE THREAD

**Issue by simsid66** [Automattic/node-canvas#1458]
## Issue:
Did a fresh install with npm install canvas, then did node main.js, and was met with this error:
   ```js /home/sid/sEngine_node/src/init.js:5
    let canvas = createCanvas(w, h);
                 ^

ReferenceError: createCanvas is not defined
    at init (/home/sid/sEngine_node/src/init.js:5:18)
    at Object.<anonymous> (/home/sid/sEngine_node/src/main.js:28:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

## Steps to Reproduce

```js

//init.js
function init(window) {
w = window.width;
h = window.height;
const { createCanvas, loadImage } = require('canvas');
let canvas =
createCanvas(w, h);
var ctx = canvas.getContext('2d');
}

// main.js
init();

function draw() {
...
```

## Environment
* Version of node-canvas: canvas@2.5.0
* Environment: node v10.16.0 on Ubuntu 18.04.2

**Comment by mk-pmb** [comment]
As suggested in #node.js on IRC:

> as a general strategy for this kind of error message, dump the object from which you try to get the property that turns out undefined. in this case: introduce a temporary variable for the result of require(), and console.debug() it.
> I guess it's a case of outdated readme [and] I'd love to check for myself, but npm is especially unhelpful today.

**Comment by k1tzu** [comment]
```javascript
import * as Canvas from 'canvas';

Canvas.default.createCanvas();
Canvas.default.createImageData();
...etc
```
worked for me.

**Comment by zbjornson** [comment]
If the above comments didn't solve the problem, let us know.

**Comment by sohaieb** [comment]
> ```js
> import * as Canvas from 'canvas';
> 
> Canvas.default.createCanvas();
> Canvas.default.createImageData();
> ...etc
> ```
> 
> worked for me.

Thank you a lot , i spent many hours to find a solution but you helped me !
