### ISSUE TITLE
failed when executing electron-rebuild

### ISSUE THREAD

**Issue by leadream** [Automattic/node-canvas#1477]
## Issue or Feature

I just executed `electron-rebuild` after `yarn install`, then got errors below. Tried to find a solution but none worked.

```
✖ Rebuild Failed
An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.4
gyp info using node@11.0.0 | darwin | x64
gyp info find Python using Python version 2.7.10 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/leadream/Projects/baojiang/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/leadream/Projects/baojiang/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/leadream/Projects/baojiang/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/leadream/.electron-gyp/6.0.11/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/leadream/.electron-gyp/6.0.11',
gyp info spawn args   '-Dnode_gyp_dir=/Users/leadream/Projects/baojiang/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/leadream/.electron-gyp/6.0.11/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/leadream/Projects/baojiang/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/leadream/Projects/baojiang/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/leadream/Projects/baojiang/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=6.0.11" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source" "--module_name=canvas" "--module_path=/Users/leadream/Projects/baojiang/node_modules/canvas/build/Release" "--host=https://github.com/node-gfx/node-canvas-prebuilt/releases/download/" "--remote_path=v2.6.0" "--package_name=canvas-v2.6.0-electron-v6.0-darwin-unknown-x64.tar.gz"
gyp ERR! cwd /Users/leadream/Projects/baojiang/node_modules/canvas
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v5.0.4
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.4
gyp info using node@11.0.0 | darwin | x64
gyp info find Python using Python version 2.7.10 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/leadream/Projects/baojiang/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/leadream/Projects/baojiang/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/leadream/Projects/baojiang/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/leadream/.electron-gyp/6.0.11/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/leadream/.electron-gyp/6.0.11',
gyp info spawn args   '-Dnode_gyp_dir=/Users/leadream/Projects/baojiang/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/leadream/.electron-gyp/6.0.11/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/leadream/Projects/baojiang/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/leadream/Projects/baojiang/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/leadream/Projects/baojiang/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=6.0.11" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source" "--module_name=canvas" "--module_path=/Users/leadream/Projects/baojiang/node_modules/canvas/build/Release" "--host=https://github.com/node-gfx/node-canvas-prebuilt/releases/download/" "--remote_path=v2.6.0" "--package_name=canvas-v2.6.0-electron-v6.0-darwin-unknown-x64.tar.gz"
gyp ERR! cwd /Users/leadream/Projects/baojiang/node_modules/canvas
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v5.0.4
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/Users/leadream/Projects/baojiang/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/Users/leadream/Projects/baojiang/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/Users/leadream/Projects/baojiang/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/Users/leadream/Projects/baojiang/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/Users/leadream/Projects/baojiang/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/Users/leadream/Projects/baojiang/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/Users/leadream/Projects/baojiang/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/Users/leadream/Projects/baojiang/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/Users/leadream/Projects/baojiang/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/leadream/Projects/baojiang/node_modules/rxjs/internal/Subscriber.js:143:22)
error Command failed with exit code 255.
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):

- canvas: 2.6.0
- electron: 6.0.10
- electron-rebuild: 1.8.6
- node v11.0.0
- yarn 1.3.2
- npm 6.11.3

**Comment by LinusU** [comment]
> /bin/sh: pkg-config: command not found
> gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp

To build from source you need to have pkg-config and some other libs installed:

```sh
brew install pkg-config cairo pango libpng jpeg giflib librsvg
```

**Comment by leadream** [comment]
@LinusU Thanks! solved it.
I installed `pkg-config` but found another error:
```
...
Package freetype2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `freetype2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'freetype2' found
...
```
I run `brew info freetype` and found freetype2.pc was in `/usr/local/Cellar/freetype/2.10.1/lib/pkgconfig`. Just add it to `PKG_CONFIG_PATH` by running the shell below:
```
export PKG_CONFIG_PATH=/usr/local/Cellar/freetype/2.10.1/lib/pkgconfig
```
It worked. Record it for others who may meet the same issue.
