### ISSUE TITLE
canvas installation error on Ubuntu14.04

### ISSUE THREAD

**Issue by niceduang** [Automattic/node-canvas#1496]
## Issue or Feature

```
> canvas@2.6.0 install /home/card-spider/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.6.0 and node@10.17.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error read ECONNRESET
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.6.0 and node@10.17.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error zlib: unexpected end of file
make: Entering directory '/home/card-spider/node_modules/canvas/build'
make: Entering directory '/home/card-spider/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/backend/Backend.o
  CXX(target) Release/obj.target/canvas/src/backend/Backend.o
rm: cannot remove './Release/.deps/Release/obj.target/canvas/src/backend/Backend.o.d.raw': No such file or directory
canvas.target.mk:142: recipe for target 'Release/obj.target/canvas/src/backend/Backend.o' failed
make: *** [Release/obj.target/canvas/src/backend/Backend.o] Error 1
make: Leaving directory '/home/card-spider/node_modules/canvas/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v10.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:193:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.4.0-142-generic
gyp ERR! command "/root/.nvm/versions/node/v10.17.0/bin/node" "/root/.nvm/versions/node/v10.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/card-spider/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/card-spider/node_modules/canvas/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /home/card-spider/node_modules/canvas
gyp  CXX(target) Release/obj.target/canvas/src/backend/ImageBackend.o
 ERR! node -v v10.17.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/root/.nvm/versions/node/v10.17.0/bin/node /root/.nvm/versions/node/v10.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/card-spider/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/card-spider/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/card-spider/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.4.0-142-generic
node-pre-gyp ERR! command "/root/.nvm/versions/node/v10.17.0/bin/node" "/home/card-spider/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/card-spider/node_modules/canvas
node-pre-gyp ERR! node -v v10.17.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/root/.nvm/versions/node/v10.17.0/bin/node /root/.nvm/versions/node/v10.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build
--module=/home/card-spider/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/card-spider/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
In file included from ../src/backend/Backend.h:6:0,
                 from ../src/backend/ImageBackend.h:3,
                 from ../src/backend/ImageBackend.cc:1:
../../nan/nan.h:174:53: fatal error: nan_callbacks.h: No such file or directory
compilation terminated.
canvas.target.mk:142: recipe for target 'Release/obj.target/canvas/src/backend/ImageBackend.o' failed
make: *** [Release/obj.target/canvas/src/backend/ImageBackend.o] Error 1
make: Leaving directory '/home/card-spider/node_modules/canvas/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v10.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:193:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-05T04_05_37_067Z-debug.log
gyp ERR! System Linux 4.4.0-142-generic
gyp ERR! command "/root/.nvm/versions/node/v10.17.0/bin/node" "/root/.nvm/versions/node/v10.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/card-spider/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/card-spider/node_modules/canvas/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /home/card-spider/node_modules/canvas
gyp ERR! node -v v10.17.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
```

## Steps to Reproduce

```bash
sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

sudo npm install canvas@2.6.0
```

## Your Environment
- node v10.17.0
- Ubuntu14.04

**Comment by Kreyren** [comment]
The issue still seems to be present, see https://github.com/gitpod-io/gitpod/issues/1520

Environment with the issue is: https://gitpod.io/#https://github.com/Kreyren/gitpod-1520/tree/c405ec22c1cc7236d2ca8a8dc10c46bb6c5de8da

**Comment by Kreyren** [comment]
Seems that this is caused by a wrong package on ubuntu-based system where documentation provides `libjpeg-dev`, but tests are using `libjpeg8-dev`.
