### ISSUE TITLE
Error running canvas on node.js v10.17

### ISSUE THREAD

**Issue by ham02** [Automattic/node-canvas#1498]
When trying to run canvas on node.js v10.17 I get this error:

(node:22368) UnhandledPromiseRejectionWarning: Error: The module '\\?\C:\Users\hamma\node_modules\canvas\build\Release\canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\hamma\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
(node:22368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22368) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Is Node.js v10.17 not supported?

node-canvas v2.6.0
npm version 6.13.0
node.js version 10.17.0

**Comment by zbjornson** [comment]
> was compiled against a different Node.js version using NODE_MODULE_VERSION 72. This version of Node.js requires NODE_MODULE_VERSION 64.

This means you changed Node.js versions since you installed canvas. Try re-running `npm install` or `yarn`.

**Comment by sunshaobin** [comment]
> > was compiled against a different Node.js version using NODE_MODULE_VERSION 72. This version of Node.js requires NODE_MODULE_VERSION 64.
> 
> This means you changed Node.js versions since you installed canvas. Try re-running `npm install` or `yarn`.

same issule, but try to npm install or yarn can't solve this problem

**Comment by crow1796** [comment]
I'm also getting the same error, I'm trying to use it inside a google cloud function:

```sh
Error: The module '/d/project/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1023:18)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/d/Files/Programming/Printree-cf2/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:957:30)
    at Module._compile (pkg/prelude/bootstrap.js:1222:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
⚠  We were unable to load your functions code. (see above)```

* Version of node-canvas: 2.6.1
* Environment: node 10.18.0 on Windows 10 (WSL)
* npm 6.13.4

**Comment by zbjornson** [comment]
@crow1796 that doesn't look like it came from GCF (GCF uses Debian and Ubuntu, and your stack trace is from WSL). If you're running the GCF emulator, try rerunning `yarn` or `npm`?

**Comment by crow1796** [comment]
I've already tried re-running npm many times, I also tried removing the node_modules and reinstall everything, I tried running npm rebuild, and I also tried changing node versions but still same

**Comment by naivedeveloper95** [comment]
I am also getting the same issue in my local. Here is the snapshot of it.

![image](https://user-images.githubusercontent.com/15083393/75220974-b92b8680-57c6-11ea-80b8-c8e480b6f0c5.png)

**Here are the logs**

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.13.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Madrobot@0.0.1~prestart: Madrobot@0.0.1
6 info lifecycle Madrobot@0.0.1~start: Madrobot@0.0.1
7 verbose lifecycle Madrobot@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle Madrobot@0.0.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Dev\Phable\phable.api.backend.satyam.js\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\satyam\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\HashiCorp\Vagrant\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs;C:\Users\satyam\.windows-build-tools\python27;C:\Users\satyam\AppData\Local\Programs\Python\Python38-32\Scripts;C:\Users\satyam\AppData\Local\Programs\Python\Python38-32;C:\Users\satyam\AppData\Local\Microsoft\WindowsApps;C:\Users\satyam\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\MongoDB\Server\4.2\bin;C:\MinGW\bin;C:\Program Files (x86)\Java\jre1.8.0_231\bin;C:\Octave\Octave-5.1.0.0\usr\bin;C:\libjpeg-turbo64\bin;C:\Users\satyam\AppData\Roaming\npm
9 verbose lifecycle Madrobot@0.0.1~start: CWD: D:\Dev\Phable\phable.api.backend.satyam.js
10 silly lifecycle Madrobot@0.0.1~start: Args: [ '/d /s /c', 'node app' ]
11 silly lifecycle Madrobot@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle Madrobot@0.0.1~start: Failed to exec start script
13 verbose stack Error: Madrobot@0.0.1 start: `node app`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid Madrobot@0.0.1
15 verbose cwd D:\Dev\Phable\phable.api.backend.satyam.js
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.19.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error Madrobot@0.0.1 start: `node app`
22 error Exit status 1
23 error Failed at the Madrobot@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**OS: WINDOWS 10
Nodejs: 10.19.0
"canvas-prebuilt": "^2.0.0-alpha.14"**

**Comment by camelmasa** [comment]
@crow1796 I encountered same issue. Could you fix the issue ?

**Comment by dalexhd** [comment]
Same issue here...

**Comment by axle07** [comment]
Delete `node_modules` before you run `npm i`

**Comment by ndtreviv** [comment]
Done. And also tried rebuilding the module using `npm rebuild`. Nothing seems to work:

```
Platform node has already been set. Overwriting the platform with [object Object].
[1] cpu backend was already registered. Reusing existing backend factory.
[1] node-pre-gyp info This Node instance does not support builds for N-API version 5
[1] node-pre-gyp info This Node instance does not support builds for N-API version 6
[1] node-pre-gyp info This Node instance does not support builds for N-API version 5
node-pre-gyp info This Node instance does not support builds for N-API version 6
[1] 2020-10-14 19:03:51.716983: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[1] 2020-10-14 19:03:51.805422: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f844bca1350 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
[1] 2020-10-14 19:03:51.805459: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[1] App threw an error during load
[1] Error: The module '/Users/me/app/node_modules/canvas/build/Release/canvas.node'
[1] was compiled against a different Node.js version using
[1] NODE_MODULE_VERSION 72. This version of Node.js requires
[1] NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
[1] the module (for instance, using `npm rebuild` or `npm install`).
[1]     at process.func (electron/js2c/asar.js:138:31)
[1]     at process.func [as dlopen] (electron/js2c/asar.js:138:31)
[1]     at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
[1]     at Object.func (electron/js2c/asar.js:138:31)
[1]     at Object.func [as .node] (electron/js2c/asar.js:138:31)
[1]     at Module.load (internal/modules/cjs/loader.js:645:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:560:12)
[1]     at Module.require (internal/modules/cjs/loader.js:685:19)
[1]     at require (internal/modules/cjs/helpers.js:16:16)
[1]     at Object.<anonymous> (/Users/me/app/node_modules/canvas/lib/bindings.js:3:18)
```

**Comment by hardikpatel043** [comment]
getting same error. Any reason why this issue is closed?

**Comment by hanvyj** [comment]
> getting same error. Any reason why this issue is closed?

Delete your `node_modules` and then run an `npm install` and it should properly build and install a version with your current version of node.

**Comment by obihill** [comment]
I had this issue after upgrading Node.js from 10 to 12. I had initially built `canvas` from source so I went through the following steps:

1. Remove/delete `node_modules` directory
2. Re-install: `npm install`
3. Rebuild canvas `npm rebuild --build-from-source canvas`

This fixed the issue.

**Comment by dhilt** [comment]
Got the same problem. Of course, the `rm -rf node_modules && npm i`-like recommendations are very nice, but obviously we've all tried this before coming here, and, I suppose, each case might have some specificity... 

In my case the problem was on the VScode end. I was able to run my scripts associated with "canvas.node" in common terminal, but couldn't do the same via VScode. It was pre-commit scripts chain. Terminal had node v14 (through nvm), VScode had node v16. Not sure, how this happened, but what I did is that I made nvm make v14 the default: `nvm alias default 14`. This provided node version consistence in my dev environment.

**Comment by saadkhan011** [comment]
1. delete the node module folder
2. run "npm install"
3. run "npm install canvas"
It will solve your problem

**Comment by RicardoSantos-99** [comment]
try this `npm rebuild canvas --update-binary`

solved for me

**Comment by equityestates** [comment]
> 

This worked for me after: 

`brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman
`
Thanks!

**Comment by yogithesymbian** [comment]
I think **removing** the `node_modules` is more efficient because when running `npm run start/dev`, it shows errors for other `node modules`, not just `canvas`.
