### ISSUE TITLE
Error: Cannot find module '../build/Release/canvas.node'

### ISSUE THREAD

**Issue by IbrH** [Automattic/node-canvas#1499]
## Issue or Feature
Error: Build folder and the mentioned file don't exist. Install method: `npm install canvas`. Also tried
`npm install canvs --build-from-source`
(Verbose output is at the end of this post)
```
$ node index.js
internal/modules/cjs/loader.js:964
    throw err;
    ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- /home/h/Dokumente/Phaser/node_modules/canvas/lib/bindings.js
- /home/h/Dokumente/Phaser/node_modules/canvas/lib/canvas.js
- /home/h/Dokumente/Phaser/node_modules/canvas/index.js
- /home/h/Dokumente/Phaser/node_modules/jsdom/lib/jsdom/utils.js
- /home/h/Dokumente/Phaser/node_modules/jsdom/lib/jsdom/browser/Window.js
- /home/h/Dokumente/Phaser/node_modules/jsdom/lib/api.js
- /home/h/Dokumente/Phaser/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:961:17)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/h/Dokumente/Phaser/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/h/Dokumente/Phaser/node_modules/canvas/lib/bindings.js',
    '/home/h/Dokumente/Phaser/node_modules/canvas/lib/canvas.js',
    '/home/h/Dokumente/Phaser/node_modules/canvas/index.js',
    '/home/h/Dokumente/Phaser/node_modules/jsdom/lib/jsdom/utils.js',
    '/home/h/Dokumente/Phaser/node_modules/jsdom/lib/jsdom/browser/Window.js',
    '/home/h/Dokumente/Phaser/node_modules/jsdom/lib/api.js',
    '/home/h/Dokumente/Phaser/index.js'
  ]
}
```

## Steps to Reproduce

index.js:
```js
const jsdom = require('jsdom');
```
Console:
$ node index.js

## Your Environment

npm list --depth=0
/home/h/Dokumente/Phaser
├── canvas@2.6.0
└── jsdom@15.2.1

npm ERR! extraneous: minimist@1.2.0 /home/h/Dokumente/Phaser/node_modules/rc/node_modules/minimist
npm ERR! extraneous: acorn@6.4.0 /home/h/Dokumente/Phaser/node_modules/acorn-globals/node_modules/acorn
npm ERR! extraneous: cssom@0.3.8 /home/h/Dokumente/Phaser/node_modules/cssstyle/node_modules/cssom
npm ERR! extraneous: tough-cookie@2.4.3 /home/h/Dokumente/Phaser/node_modules/request/node_modules/tough-cookie
npm ERR! extraneous: tough-cookie@2.5.0 /home/h/Dokumente/Phaser/node_modules/request-promise-native/node_modules/tough-cookie

$ node -v
v13.3.0

OS:
Ubuntu 19.04

$ npm install canvas --verbose
```
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/home/h/.nvm/versions/node/v13.3.0/bin/node',
npm verb cli   '/home/h/.nvm/versions/node/v13.3.0/bin/npm',
npm verb cli   'install',
npm verb cli   'canvas',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.13.1
npm info using node@v13.3.0
npm verb npm-session 003e0920c9883fac
npm http fetch GET 304 https://registry.npmjs.org/canvas 112ms (from cache)
npm timing stage:loadCurrentTree Completed in 1153ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 10ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 612ms
npm http fetch GET 304 https://registry.npmjs.org/nan 35ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 62ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-pre-gyp 65ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 30ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 31ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 24ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 1087ms
npm timing stage:loadIdealTree Completed in 1936ms
npm timing stage:generateActionsToTake Completed in 65ms
npm verb correctMkdir /home/h/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/h/.npm/_locks/staging-eb44e244cc61d316.lock for /home/h/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/.staging
npm timing action:extract Completed in 178ms
npm info lifecycle canvas@2.6.0~preuninstall: canvas@2.6.0
npm info lifecycle canvas@2.6.0~uninstall: canvas@2.6.0
npm verb unbuild rmStuff canvas@2.6.0 from /home/h/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules
npm info lifecycle canvas@2.6.0~postuninstall: canvas@2.6.0
npm timing action:unbuild Completed in 2ms
npm timing action:remove Completed in 10ms
npm timing action:finalize Completed in 35ms
npm timing action:refresh-package-json Completed in 90ms
npm info lifecycle canvas@2.6.0~preinstall: canvas@2.6.0
npm timing action:preinstall Completed in 1ms
npm info linkStuff canvas@2.6.0
npm timing action:build Completed in 2ms
npm info lifecycle canvas@2.6.0~install: canvas@2.6.0
npm info lifecycle canvas@2.6.0~install: ignored because ignore-scripts is set to true canvas@2.6.0
npm timing action:install Completed in 5ms
npm info lifecycle canvas@2.6.0~postinstall: canvas@2.6.0
npm timing action:postinstall Completed in 1ms
npm verb unlock done using /home/h/.npm/_locks/staging-eb44e244cc61d316.lock for /home/h/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/.staging
npm timing stage:executeActions Completed in 347ms
npm timing stage:rollbackFailedOptional Completed in 46ms
npm timing stage:runTopLevelLifecycles Completed in 3769ms
npm verb saving [ { name: 'canvas', spec: '^2.6.0', save: 'dependencies' } ]
npm timing audit submit Completed in 702ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 702ms
npm timing audit body Completed in 1ms
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN phaser3-multiplayer-example-with-geckos.io@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
```

~/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/canvas$ node-gyp rebuild
```
gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.1
gyp info using node@13.3.0 | linux | x64
gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/h/.nvm/versions/node/v13.3.0/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/h/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/h/.nvm/versions/node/v13.3.0/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/h/.cache/node-gyp/13.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/h/.cache/node-gyp/13.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/h/.nvm/versions/node/v13.3.0/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/h/.cache/node-gyp/13.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/h/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/h/.nvm/versions/node/v13.3.0/lib/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:219:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! System Linux 5.0.0-37-generic
gyp ERR! command "/home/h/.nvm/versions/node/v13.3.0/bin/node" "/home/h/.nvm/versions/node/v13.3.0/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/h/Dokumente/Phaser Projects/phaser3-multiplayer-game/node_modules/canvas
gyp ERR! node -v v13.3.0
gyp ERR! node-gyp -v v6.0.1
```

**Comment by zbjornson** [comment]
> `npm info lifecycle canvas@2.6.0~install: canvas@2.6.0`
> `npm info lifecycle canvas@2.6.0~install: ignored because ignore-scripts is set to true canvas@2.6.0`

It looks like you set NPM to ignore scripts, which prevents node-pre-gyp from downloading prebuilt binaries. I can't tell from your post; did you manually run `node-gyp rebuild` in `node_modules/canvas` after the install failed?

> Package pixman-1 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `pixman-1.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'pixman-1' found

If you're not allowing scripts, you'll need to follow the build instructions here: https://github.com/Automattic/node-canvas#compiling

**Comment by Crisl07** [comment]
I had a similar problem but I used canvas-prebuilt which is a drop-in replacement for canvas and I fixed it for doing this:
-npm install -g node-gyp
-node-gyp rebuild

**Comment by ajp2020** [comment]
Hi @Crisl07, is this in windows?

**Comment by Crisl07** [comment]
> 
> 
> Hi @Crisl07, is this in windows?
It's in Mac OS

**Comment by Crisl07** [comment]
> 
> 
> Hi @Crisl07, is this in windows?

it's in Mac OS

**Comment by msjbrave** [comment]
change node engine version **10.x to 8.x or rebuild**

**Comment by Ekhwatenge** [comment]
> I had a similar problem but I used canvas-prebuilt which is a drop-in replacement for canvas and I fixed it for doing this:
> -npm install -g node-gyp
> -node-gyp rebuild

**Comment by Ekhwatenge** [comment]
Please ensure to check whether you are in the right directory, this was why I was getting the error so run pwd, then ls just to make sure

**Comment by eightyfive** [comment]
> did you manually run node-gyp rebuild in node_modules/canvas after the install failed?

Thanks @zbjornson

**Comment by perymerdeka** [comment]
I try in Macbook Air M1 return Similar Error like 
```
Error: Cannot find module '../build/Release/canvas.node'
```
how to fix it

**Comment by Destiner** [comment]
Fix:
```bash
cd node_modules/canvas
npx node-gyp rebuild
```

**Comment by Restuta** [comment]
That fix didn't work for me

**Comment by vtereshyn** [comment]
Same here. Issue closed, but error is there
