### ISSUE TITLE
Installation problem with Node.js v13.x

### ISSUE THREAD

**Issue by hijiangtao** [Automattic/node-canvas#1512]
## Issue or Feature

I couldn't install this package in my computer with Node.js v13.x, however I fixed it by downgrading Node.js to v10.18.0, but I still don't know why I couldn't use Node.js v13.x to compile (install) it.

First, I met **node-gyp rebuild errror** and **gyp ERR! stack Error: `make` failed with exit code: 2**:

```
> contextify@0.1.15 install /Users/hijiangtao/Documents/git/work/tutor-cheer-web/node_modules/contextify
> node-gyp rebuild

  CXX(target) Release/obj.target/contextify/src/contextify.o
In file included from ../src/contextify.cc:3:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1: error: no viable conversion from 'Local<v8::Context>' to 'v8::Isolate *'
X(Boolean)
^~~~~~~~~~

...

fatal error: too many errors emitted, stopping now [-ferror-limit=]
3 warnings and 20 errors generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/hijiangtao/.nvm/versions/node/v13.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:305:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/Users/hijiangtao/.nvm/versions/node/v13.5.0/bin/node" "/Users/hijiangtao/.nvm/versions/node/v13.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/hijiangtao/Documents/git/work/tutor-cheer-web/node_modules/fabric/node_modules/canvas
gyp ERR! node -v v13.5.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
```

As said in https://github.com/Automattic/node-canvas/issues/854 and https://stackoverflow.com/questions/32898887/boost-no-longer-works-with-homebrew-on-mac-el-capitan/32929012#32929012 , I thought it may be a problem belongs to Mac OS X v10.11+, so I tried `npm install node-gyp -g` and `xcode-select --install`, but it didn't work.

I also tried many solutions which contains some similar errors output, such as https://github.com/Automattic/node-canvas/issues/788#issuecomment-234702763 , https://github.com/Automattic/node-canvas/issues/788#issuecomment-234702763 , https://github.com/nodejs/node-gyp/issues/1694#issuecomment-499784965 , https://github.com/Automattic/node-canvas/issues/854#issuecomment-272637456 , etc. One of them looks like this:

```
xcode-select --install # I thought this was dumb, but was key to one of my issues 
npm install node-gyp -g
brew install giflib cairo libjpeg giflib pixman
export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig
OTHER_CFLAGS=-I/usr/local/include npm install canvas
```

However, it didn't work. :-(

## Steps to Reproduce

```js
// with nvm installed before
nvm install v10.18.0
npm install canvas
```

## Your Environment
* Version of node-canvas: 1.6.13
* Environment: macOS 10.15.1 (19B88)

Thanks.

**Comment by zbjornson** [comment]
Canvas 1.x isn't supported anymore. Node.js v6+ requires Canvas 2.x.

**Comment by hijiangtao** [comment]
The truth is I also met the problem when installed node-canvas v2.x with `npm i canvas@latest --save`. However, I didn't verify that if I can handle it with downgrade my Node.js' version, I would implement details about it after I tried this way.

**Comment by sjcobb** [comment]
Downgrading Node.js version does not help, I'm also getting the same errors

**Comment by hijiangtao** [comment]
@sjcobb Have you tried specific version such as v10.18.0, I solved it by downgrading it to that, though I didn't figure out why higher Node.js won't work yet.

**Comment by zbjornson** [comment]
> `> contextify@0.1.15 install`

The errors in the OP are actually from the contextify package (which has been defunct since node 0.12).

**Comment by meteorpublish** [comment]
I get similar errors with Node v13.12.0:

```
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/backend/Backend.o
  CXX(target) Release/obj.target/canvas/src/backend/ImageBackend.o
In file included from ../src/backend/ImageBackend.cc:1:0:
../src/backend/ImageBackend.h:27:32: error: ‘v8::Handle’ has not been declared
     static void Initialize(v8::Handle<v8::Object> target);
                                ^~~~~~
../src/backend/ImageBackend.h:27:38: error: expected ‘,’ or ‘...’ before ‘<’ token
     static void Initialize(v8::Handle<v8::Object> target);
                                      ^
../src/backend/ImageBackend.cc:71:31: error: variable or field ‘Initialize’ declared void
 void ImageBackend::Initialize(Handle<Object> target)
                               ^~~~~~
../src/backend/ImageBackend.cc:71:31: error: ‘Handle’ was not declared in this scope
../src/backend/ImageBackend.cc:71:31: note: suggested alternative: ‘rand_r’
 void ImageBackend::Initialize(Handle<Object> target)
                               ^~~~~~
                               rand_r
../src/backend/ImageBackend.cc:71:44: error: expected primary-expression before ‘>’ token
 void ImageBackend::Initialize(Handle<Object> target)
                                            ^
../src/backend/ImageBackend.cc:71:46: error: ‘target’ was not declared in this scope
 void ImageBackend::Initialize(Handle<Object> target)
                                              ^~~~~~
../src/backend/ImageBackend.cc:71:46: note: suggested alternative: ‘tzset’
 void ImageBackend::Initialize(Handle<Object> target)
                                              ^~~~~~
                                              tzset
../src/backend/ImageBackend.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ImageBackend::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/backend/ImageBackend.cc:86:57: error: no matching function for call to ‘v8::Value::Uint32Value()’
  if (info[0]->IsNumber()) width  = info[0]->Uint32Value();
                                                         ^
```

**Comment by zbjornson** [comment]
@meteorpublish that was fixed in v2.4.1. Are you on an older version?

**Comment by IamRifki** [comment]
Doesn't work on my end either, on latest version too.

**Comment by Frazer** [comment]
Why was this closed?  I don't see a resolution to the problem.

**Comment by IamRifki** [comment]
@Frazer Use Version 13.12.0 for now, they've fixed the bug, but it doesn't have a release for that, yet.
