### ISSUE TITLE
Error installing canvas

### ISSUE THREAD

**Issue by Lilwiggy** [Automattic/node-canvas#1547]
## Issue or Feature
When I go to install canvas it always fails at installing lzma-native@3.0.8. Even when --build-from-source is used.
I have been trying to fix this for a few days with no clue how to fix. 

```
node-pre-gyp ERR! Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.8-node-v79-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for lzma-native@3.0.8 and node@13.11.0 (node-v79 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.8-node-v79-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for lzma-native@3.0.8 and node@13.11.0 (node-v79 ABI, glibc) (falling back to source compile with node-gyp)
gyp: Call to 'sh liblzma-config.sh "/root/Penny/node_modules/lzma-native/build" "/root/Penny/node_modules/lzma-native/deps/xz-5.2.3.tar.bz2"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.0-8-amd64
gyp ERR! command "/root/.nvm/versions/node/v13.11.0/bin/node" "/root/.nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/root/Penny/node_modules/lzma-native/binding-v3.0.8-node-v79-linux-x64/lzma_native.node" "--module_name=lzma_native" "--module_path=/root/Penny/node_modules/lzma-native/binding-v3.0.8-node-v79-linux-x64"
gyp ERR! cwd /root/Penny/node_modules/lzma-native
gyp ERR! node -v v13.11.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/root/.nvm/versions/node/v13.11.0/bin/node /root/.nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/Penny/node_modules/lzma-native/binding-v3.0.8-node-v79-linux-x64/lzma_native.node --module_name=lzma_native --module_path=/root/Penny/node_modules/lzma-native/binding-v3.0.8-node-v79-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/Penny/node_modules/lzma-native/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.19.0-8-amd64
node-pre-gyp ERR! command "/root/.nvm/versions/node/v13.11.0/bin/node" "/root/Penny/node_modules/lzma-native/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/Penny/node_modules/lzma-native
node-pre-gyp ERR! node -v v13.11.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/root/.nvm/versions/node/v13.11.0/bin/node /root/.nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/Penny/node_modules/lzma-native/binding-v3.0.8-node-v79-linux-x64/lzma_native.node --module_name=lzma_native --module_path=/root/Penny/node_modules/lzma-native/binding-v3.0.8-node-v79-linux-x64' (1)

[...]

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lzma-native@3.0.8 install: `node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lzma-native@3.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
gyp: Call to 'sh liblzma-config.sh "/root/Penny/node_modules/lzma-native/build" "/root/Penny/node_modules/lzma-native/deps/xz-5.2.3.tar.bz2"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.0-8-amd64
gyp ERR! command "/root/.nvm/versions/node/v13.11.0/bin/node" "/root/.nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/root/Penny/node_modules/lzma-native/binding-v3.0.8-node-v79-linux-x64/lzma_native.node" "--module_name=lzma_native" "--module_path=/root/Penny/node_modules/lzma-native/binding-v3.0.8-node-v79-linux-x64"
gyp ERR! cwd /root/Penny/node_modules/lzma-native
gyp ERR! node -v v13.11.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-25T19_04_41_298Z-debug.log
```

## Steps to Reproduce
npm i canvas
npm i canvas@latest
npm i canvas --build-from-source

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):
Shows 1.6.13 but I have tried installing latest and 2.6.1 with same errors.
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):
node v13.11.0 on Debian 10.3

**Comment by Lilwiggy** [comment]
I seemed to have fixed the issue by downloading the source and running `node-gyp rebuild` inside of node_modules/canvas. Seems weird that it wouldn't work with npm but idk. If anyone else has this issue then I hope I helped.

**Comment by miguelmota** [comment]
@Lilwiggy that worked great, thanks
