### ISSUE TITLE
Installation without request library fails on Node 14

### ISSUE THREAD

**Issue by Filipoliko** [Automattic/node-canvas#1586]
Hi,
there seems to be a problem with installation on Node 14.2.0 on MacOS and Linux when `node-pre-gyp` uses `needle` http agent for `canvas` download. The problem occurs only when dependency `request` is not installed and so the `node-pre-gyp` library uses `needle` library for downloads, which is unable to find remote files and it falls to build from source, which is missing dependencies in my case and fails. But i don't want to build from source, since I can add `request` library to solve the issue, but why cannot the `needle` agent find the remote files? Im not sure, if this is `canvas` issue, but i did not receive any error, when I installed just `node-gyp`, this error occurs only when installing `canvas`.

## Issue or Feature
I receive following error when trying to install `canvas`.
```
> canvas@2.6.1 install /Users/filip.satek/git/node-pre-gyp-test/without-request/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.6.1 and node@14.2.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Remote end closed socket abruptly. 
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/filip.satek/.nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/filip.satek/.nvm/versions/node/v14.2.0/bin/node" "/Users/filip.satek/.nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/filip.satek/git/node-pre-gyp-test/without-request/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/filip.satek/git/node-pre-gyp-test/without-request/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /Users/filip.satek/git/node-pre-gyp-test/without-request/node_modules/canvas
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/filip.satek/.nvm/versions/node/v14.2.0/bin/node /Users/filip.satek/.nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/filip.satek/git/node-pre-gyp-test/without-request/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/filip.satek/git/node-pre-gyp-test/without-request/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/filip.satek/git/node-pre-gyp-test/without-request/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/Users/filip.satek/.nvm/versions/node/v14.2.0/bin/node" "/Users/filip.satek/git/node-pre-gyp-test/without-request/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/filip.satek/git/node-pre-gyp-test/without-request/node_modules/canvas
node-pre-gyp ERR! node -v v14.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/Users/filip.satek/.nvm/versions/node/v14.2.0/bin/node /Users/filip.satek/.nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/filip.satek/git/node-pre-gyp-test/without-request/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/filip.satek/git/node-pre-gyp-test/without-request/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN pre-gyp-test@1.0.0 No description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/filip.satek/.npm/_logs/2020-05-20T10_45_14_354Z-debug.log
```

But when I add `request` dependency, I get the following.
```
> canvas@2.6.1 install /Users/filip.satek/git/node-pre-gyp-test/with-request/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[canvas] Success: "/Users/filip.satek/git/node-pre-gyp-test/with-request/node_modules/canvas/build/Release/canvas.node" is installed via remote
```

## Steps to Reproduce
I created a simple repository, where you can reproduce the issue with `node:14` docker images.

https://github.com/Filipoliko/node-pre-gyp-test

The output from the repository:
```
$ ./test.sh 
Running build with request module installed will pass.

Sending build context to Docker daemon  3.149kB
Step 1/4 : FROM node:14
 ---> e00884c768d7
Step 2/4 : WORKDIR /home
 ---> Running in acc2297b4592
Removing intermediate container acc2297b4592
 ---> 8e370ca3cb67
Step 3/4 : COPY package.json package.json
 ---> 7124517bd4a9
Step 4/4 : RUN npm install
 ---> Running in 9bd1282fe563
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> canvas@2.6.1 install /home/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[canvas] Success: "/home/node_modules/canvas/build/Release/canvas.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN pre-gyp-test@1.0.0 No description

added 116 packages from 90 contributors and audited 116 packages in 11.088s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Removing intermediate container 9bd1282fe563
 ---> ab9379ed09d8
Successfully built ab9379ed09d8

Running build without request module installed will fail.

Sending build context to Docker daemon  3.119kB
Step 1/4 : FROM node:14
 ---> e00884c768d7
Step 2/4 : WORKDIR /home
 ---> Using cache
 ---> 8e370ca3cb67
Step 3/4 : COPY package.json package.json
 ---> 28f6172b64f1
Step 4/4 : RUN npm install
 ---> Running in 609fc8e6a547

> canvas@2.6.1 install /home/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.6.1 and node@14.2.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Remote end closed socket abruptly. 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.6.1 and node@14.2.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error ENOENT: Cannot cd into '/home/node_modules/canvas/build/Release' 
Package pangocairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `pangocairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pangocairo' found
gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.19.76-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/node_modules/canvas
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 4.19.76-linuxkit
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/node_modules/canvas
node-pre-gyp ERR! node -v v14.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 511, in gyp_main
    'cwd': os.getcwd(),
OSError: [Errno 2] No such file or directory
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.19.76-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/node_modules/canvas
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN pre-gyp-test@1.0.0 No description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-20T10_35_19_380Z-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): 2.6.1
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Node 14.2.0 on Mac OS Mojave 10.14.6

**Comment by Filipoliko** [comment]
The issue seems to be caused by needle library, sorry for the spam https://github.com/tomas/needle/issues/312
