### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by zaphier99** [Automattic/node-canvas#1631]
## Issue
Hello! I'm new to Nodejs and I want to try using node-canvas for my project but I'm having issues using it. I tried following the installation guide and I run a sample code from the Quick Sample just to see if it works. This error shows up:

```cmd
internal/modules/cjs/loader.js:1208
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Bots\SampleBot\node_modules\canvas\build\Release\canvas.node
←[90m    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1208:18)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1002:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:901:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1044:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:77:18)←[39m
    at Object.<anonymous> (C:\Bots\SampleBot\node_modules\←[4mcanvas←[24m\lib\bindings.js:3:18)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1158:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1002:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:901:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1044:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:77:18)←[39m
    at Object.<anonymous> (C:\Bots\SampleBot\node_modules\←[4mcanvas←[24m\lib\canvas.js:9:18)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1158:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1002:32)←[39m
```
This is the Installation Log of the package:

```cmd
C:\Bots\SampleBot>npm i --build-from-source canvas
> canvas@2.6.1 install C:\Bots\SampleBot\node_modules\canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying C:/libjpeg-turbo/bin/jpeg62.dll to C:\Bots\SampleBot\node_modules\canvas\build\Release\\jpeg62.dll
          1 file(s) copied.
  Backend.cc
  ImageBackend.cc
  PdfBackend.cc
  SvgBackend.cc
  BMPParser.cc
  Backends.cc
  Canvas.cc
  CanvasGradient.cc
c:\bots\samplebot\node_modules\canvas\src\bmp\bmpparser.cc(189): warning C4018: '>': signed/unsigned mismatch [C:\Bots\SampleBot\node_modules\canva
s\build\canvas.vcxproj]
c:\bots\samplebot\node_modules\canvas\src\bmp\bmpparser.cc(204): warning C4018: '>': signed/unsigned mismatch [C:\Bots\SampleBot\node_modules\canva
s\build\canvas.vcxproj]
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  closure.cc
  color.cc
  Image.cc
  ImageData.cc
  init.cc
  register_font.cc
  win_delay_load_hook.cc
     Creating library C:\Bots\SampleBot\node_modules\canvas\build\Release\canvas.lib and object C:\Bots\SampleBot\node_modules\canvas\build\Release
  \canvas.exp
  canvas.vcxproj -> C:\Bots\SampleBot\node_modules\canvas\build\Release\\canvas.node
  Copying C:/GTK/bin/libpangoft2-1.0-0.dll to C:\Bots\SampleBot\node_modules\canvas\build\Release\\libpangoft2-1.0-0.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libgthread-2.0-0.dll to C:\Bots\SampleBot\node_modules\canvas\build\Release\\libgthread-2.0-0.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libpangowin32-1.0-0.dll to C:\Bots\SampleBot\node_modules\canvas\build\Release\\libpangowin32-1.0-0.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libglib-2.0-0.dll to C:\Bots\SampleBot\node_modules\canvas\build\Release\\libglib-2.0-0.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libcairo-2.dll to C:\Bots\SampleBot\node_modules\canvas\build\Release\\libcairo-2.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libpango-1.0-0.dll to C:\Bots\SampleBot\node_modules\canvas\build\Release\\libpango-1.0-0.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libfontconfig-1.dll to C:\Bots\SampleBot\node_modules\canvas\build\Release\\libfontconfig-1.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libintl-8.dll to C:\Bots\SampleBot\node_modules\canvas\build\Release\\libintl-8.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libfreetype-6.dll to C:\Bots\SampleBot\node_modules\canvas\build\Release\\libfreetype-6.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libgmodule-2.0-0.dll to C:\Bots\SampleBot\node_modules\canvas\build\Release\\libgmodule-2.0-0.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libpangocairo-1.0-0.dll to C:\Bots\SampleBot\node_modules\canvas\build\Release\\libpangocairo-1.0-0.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libgobject-2.0-0.dll to C:\Bots\SampleBot\node_modules\canvas\build\Release\\libgobject-2.0-0.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libpng14-14.dll to C:\Bots\SampleBot\node_modules\canvas\build\Release\\libpng14-14.dll
          1 file(s) copied.
  Copying C:/GTK/bin/zlib1.dll to C:\Bots\SampleBot\node_modules\canvas\build\Release\\zlib1.dll
          1 file(s) copied.
  Copying C:/GTK/bin/libexpat-1.dll to C:\Bots\SampleBot\node_modules\canvas\build\Release\\libexpat-1.dll
          1 file(s) copied.
  win_delay_load_hook.cc
  canvas-postbuild.vcxproj -> C:\Bots\SampleBot\node_modules\canvas\build\Release\\canvas-postbuild.node
```

## Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): canvas@2.6.1
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node v12.16.1 on Windows 7 Ultimate

**Comment by zbjornson** [comment]
That error message can be caused by a variety of things, but I'm guessing in this case it's because you're on Windows 7. Node.js only supports Windows 10 or 8.1 (experimental), see https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list. If I remember correctly, native modules don't load properly on earlier versions, even if Node.js itself can run.

**Comment by steelx** [comment]
happens on max as well
