### ISSUE TITLE
Windows 10 x64 installation failure : "no such file or directory, open [...] config.gypi"

### ISSUE THREAD

**Issue by Catatomik** [Automattic/node-canvas#1632]
## Issue
I'm experiencing an unexcepted error  while installing canvas.
If I'm right, it should've use [a prebuilt binary](https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v72-win32-unknown-x64.tar.gz) from `node-canvas-prebuilt` ?
I'm getting this error (complete output from CMD) : 
```
D:\session\Desktop\Bureau - Discord\Dev\Tests>npm i canvas

> canvas@2.6.1 install D:\session\Desktop\Bureau - Discord\Dev\Tests\node_modules\canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.6.1 and node@12.17.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Remote end closed socket abruptly.
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.6.1 and node@12.17.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error ENOENT: Cannot cd into 'D:\session\Desktop\Bureau - Discord\Dev\Tests\node_modules\canvas\build\Release'
gyp ERR! configure error
gyp ERR! stack Error: ENOENT: no such file or directory, open 'D:\session\Desktop\Bureau - Discord\Dev\Tests\node_modules\canvas\build\config.gypi'
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\session\\Desktop\\Bureau - Discord\\Dev\\Tests\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=D:\\session\\Desktop\\Bureau - Discord\\Dev\\Tests\\node_modules\\canvas\\build\\Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72" "--python=C:/Users/session/.windows-build-tools/python27/python.exe" "--msvs_version=2017"
gyp ERR! cwd D:\session\Desktop\Bureau - Discord\Dev\Tests\node_modules\canvas
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\session\Desktop\Bureau - Discord\Dev\Tests\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=D:\session\Desktop\Bureau - Discord\Dev\Tests\node_modules\canvas\build\Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72 --python=C:/Users/session/.windows-build-tools/python27/python.exe --msvs_version=2017' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\session\Desktop\Bureau - Discord\Dev\Tests\node_modules\canvas\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.19041
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\session\\Desktop\\Bureau - Discord\\Dev\\Tests\\node_modules\\canvas\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\session\Desktop\Bureau - Discord\Dev\Tests\node_modules\canvas
node-pre-gyp ERR! node -v v12.17.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\session\Desktop\Bureau - Discord\Dev\Tests\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=D:\session\Desktop\Bureau - Discord\Dev\Tests\node_modules\canvas\build\Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72 --python=C:/Users/session/.windows-build-tools/python27/python.exe --msvs_version=2017' (1)
npm WARN tests@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\session\AppData\Roaming\npm-cache\_logs\2020-07-27T21_56_55_616Z-debug.log
```

## What did I try
Firstly, classical install with `npm install canvas`, failed.
Secondly, checked the docs for Windows installation : need to build, so I installed all dependencies (**node-gyp** already installed, but uninstalled globally then reinstalled globally, **GTK2** from the given link, then **libjpeg-turbo64**).
Then, re-try to intall canvas.
Note that after reinstalling node-gyp and a reboot, it went further but got another error when starting compiling : 
```
error MSB3491: Unable to write lines in the file "Release\obj\canvas\canvas.tlog\canvas.lastbuildstate". The process can't access the file 'D:- Desktop - Discord\Dev\Tests\node_modules\canvas\build\Release\obj\canvas.tlog\canvas.lastbuildstate'.
```

## Steps to reproduce
Just try to `npm install canvas`.
Note that I tried canvas@2.6.1, @2.6.0 & @2.5.0, same error.

## Your environment
* node v12.17.0
* npm v6.14.4
* Windows 10 x64

`npm config list`
* msvs_version = "2017", manually installed with Visual Studio Installer
* python = "C:/Users/session/.windows-build-tools/python27/python.exe", installed from `npm install --global --production windows-build-tools`

**Comment by Catatomik** [comment]
## Solved, update for those who may experience the same issue
I didn't even try to install it on another folder, but it worked on every others.
After testing what was going wrong in this one, it's due to an old `package-lock.json` and the dependencies inside, I don't know which one.
I drop this here if someone want to find which dep is canceling download of a prebuilt version of canvas [package-lock.txt](https://github.com/Automattic/node-canvas/files/4987544/FAIL.FILE.package-lock.txt).
**So deleting this file was the solution.**
