### ISSUE TITLE
Error: Cannot find module '../build/Release/canvas.node'

### ISSUE THREAD

**Issue by MX199** [Automattic/node-canvas#1641]
C:\Users\GAMER\Desktop\Run Script\discord run script bot\BOT\Raven Store bot>node server.js
internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module '../build/Release/canvas.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\GAMER\Desktop\Run Script\discord run script bot\BOT\Raven Store bot\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)

C:\Users\GAMER\Desktop\Run Script\discord run script bot\BOT\Raven Store bot>pause
Press any key to continue . . .

**Comment by ajmeese7** [comment]
@MX199 how did you fix this?
