### ISSUE TITLE
Unable to execute app in CI due to canvas' unsigned build artifacts 

### ISSUE THREAD

**Issue by Pitt-Pauly** [Automattic/node-canvas#1644]
## Issue or Feature

We have a project that uses canvas as a dependency as well as Cypress with the applitools/eyes-cypress plugin. 
When running the test suite with Cypress, we get the following error: 
```
**Message:** The plugins file is missing or invalid.

Your `pluginsFile` is set to `/Users/pitt/project/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.

**Details:** Error: dlopen(/Users/pitt/project/node_modules/canvas/build/Release/canvas.node, 1): no suitable image found.  Did find:
	/Users/pitt/project/node_modules/canvas/build/Release/canvas.node: code signature in (/Users/pitt/project/node_modules/canvas/build/Release/canvas.node) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/pitt/project/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)

**Stack trace:**
Error: The plugins file is missing or invalid.

Your `pluginsFile` is set to `/Users/pitt/project/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.
    at Object.get (/Users/pitt/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:946:15)
    at EventEmitter.<anonymous> (/Users/pitt/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:121:21)
    at EventEmitter.emit (events.js:210:5)
    at ChildProcess.<anonymous> (/Users/pitt/Library/Caches/Cypress/4.11.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:210:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

```
I've talked to the developers at Applitools, to see if it was related to their plugin, but so far we could find anything.
It looks like the build artifacts of canvas are not signed, and somehow the combination Cypress + applitools plugin refuses to run the app. The app works fine without Cypress and with Cypress without the plugin. 
Here is a Github Issue I had sent to the applitools team: https://github.com/applitools/eyes.sdk.javascript1/issues/225 

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): canvas@2.6.1
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Mac OS Mojave 10.14.6

**Comment by Adam-Burke** [comment]
Same here.

```
Error: The plugins file is missing or invalid.

Your `pluginsFile` is set to `/Users/adam/ligr-v2/packages/dashboard/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.
    at Object.get (/Users/adam/Library/Caches/Cypress/4.12.1/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:946:15)
    at EventEmitter.<anonymous> (/Users/adam/Library/Caches/Cypress/4.12.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:123:21)
    at EventEmitter.emit (events.js:210:5)
    at ChildProcess.<anonymous> (/Users/adam/Library/Caches/Cypress/4.12.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:210:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

```

**Comment by Adam-Burke** [comment]
Same issue

Error: dlopen(/Users/adam/ligr-v2/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node, 1): no suitable image found.  Did find:
	/Users/adam/ligr-v2/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node: code signature in (/Users/adam/ligr-v2/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/adam/ligr-v2/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/adam/ligr-v2/packages/api/src/util/authorization.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/adam/ligr-v2/packages/api/src/gql/services/UserService.ts:10:1)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)

**Comment by zbjornson** [comment]
I might be missing some context here, but Cypress most likely shouldn't be trying to load the canvas binaries in the first place. I'm not sure how to configure applitools to achieve this, but hopefully that points you in the right direction.
