### ISSUE TITLE
Error: libjpeg.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by stijnb1234** [Automattic/node-canvas#1658]
## Issue
I'm always getting this error after installation.
```
internal/modules/cjs/loader.js:1187
return process.dlopen(module, path.toNamespacedPath(filename));
Error: libjpeg.so.8: cannot open shared object file: No such file or directory
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1187:18)
at Module.load (internal/modules/cjs/loader.js:985:32)
at Function.Module._load (internal/modules/cjs/loader.js:878:14)
at Module.require (internal/modules/cjs/loader.js:1025:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/home/container/node_modules/canvas/lib/bindings.js:3:18)
at Module._compile (internal/modules/cjs/loader.js:1137:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
at Module.load (internal/modules/cjs/loader.js:985:32)
at Function.Module._load (internal/modules/cjs/loader.js:878:14)
```

## Steps to Reproduce
1. Install dependencies and canvas with npm i canvas
2. Get this error after trying to start the module (node index.js)

## What I've tried
- Rebuilding with electron
- Rebuilding with node-gyp

It will always return the same error

## Your Environment
* Version of node-canvas: 2.6.1
* Environment: Node v12 in Docker v19.03.8 (Running debian)

**Comment by OKNoah** [comment]
I have a similar issue with `libpng12.so.0: cannot open shared object file: No such file or directory`. This just started today. I'm using a Heroku buildpack in Dokku (Docker-based). I wonder if it's related to some of these libraries being removed from Ubuntu because I think build packs download things directly. So a little lost.

**Comment by OKNoah** [comment]
I created a new app and deployed the same thing there, fixed it ¯\_(ツ)_/¯

**Comment by 0xD8C4A475** [comment]
same here. aarch64 (arm).

Error: libjpeg.so.8: cannot open shared object file: No such file or directory

```
# apt-file find libjpeg.so.8
<empty :/ >
```

**Comment by 0xD8C4A475** [comment]
worked for me
```
https://snapshot.debian.org/archive/debian-ports/20141009T073751Z/pool-arm64/main/libj/libjpeg8/libjpeg8_8d1-2_arm64.deb
https://snapshot.debian.org/archive/debian/20190501T215844Z/pool/main/g/glibc/multiarch-support_2.28-10_arm64.deb
```
