### ISSUE TITLE
Failed to install Error: Unsupported target version: v4.4.2

### ISSUE THREAD

**Issue by legsak1mbo** [Automattic/node-canvas#1661]
## Issue or Feature
When attempting to install on CentOS 7 I receive the following:-

```
npm install -g canvas

> canvas@2.6.1 install /usr/lib/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: v4.4.2
node-pre-gyp ERR! stack     at get_runtime_abi (/usr/lib/node_modules/canvas/node_modules/node-pre-gyp/lib/util/versioning.js:173:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/usr/lib/node_modules/canvas/node_modules/node-pre-gyp/lib/util/versioning.js:295:19)
node-pre-gyp ERR! stack     at install (/usr/lib/node_modules/canvas/node_modules/node-pre-gyp/lib/install.js:206:31)
node-pre-gyp ERR! stack     at Object.self.commands.<computed> [as install] (/usr/lib/node_modules/canvas/node_modules/node-pre-gyp/lib/node-pre-gyp.js:52:37)
node-pre-gyp ERR! stack     at run (/usr/lib/node_modules/canvas/node_modules/node-pre-gyp/bin/node-pre-gyp:82:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/usr/lib/node_modules/canvas/node_modules/node-pre-gyp/bin/node-pre-gyp:134:1)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:1137:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
node-pre-gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:985:32)
node-pre-gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
node-pre-gyp ERR! System Linux 3.10.0-1127.el7.x86_64
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/canvas
node-pre-gyp ERR! node -v v12.18.3
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Unsupported target version: v4.4.2
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

## Your Environment
* Environment (node 12.18.3 on CentOS 7):

**Comment by zbjornson** [comment]
I think that means you're trying to use Node.js v4.4.2. node-canvas requires v10.x or later.

The last line or your post says 12.18.3 though. If you're using a node version manager, maybe check that the expected version is being loaded?
