### ISSUE TITLE
Unable to use / install canvas on windows.

### ISSUE THREAD

**Issue by ridays2001** [Automattic/node-canvas#1686]
I had installed canvas, but I was getting this error which seems to mean that it wasn't built properly.
<details>
<summary>Error: Cannot find module '../build/Release/canvas.node'</summary>

```js
Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- D:\Codes\misc\Luna\node_modules\canvas\lib\bindings.js
- D:\Codes\misc\Luna\node_modules\canvas\lib\canvas.js
- D:\Codes\misc\Luna\node_modules\canvas\index.js
- D:\Codes\misc\Luna\dist\commands\levels\rank.js
- D:\Codes\misc\Luna\node_modules\discord-akairo\src\struct\AkairoHandler.js
- D:\Codes\misc\Luna\node_modules\discord-akairo\src\index.js
- D:\Codes\misc\Luna\dist\client.js
- D:\Codes\misc\Luna\dist\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:900:15)
    at Function.Module._load (node:internal/modules/cjs/loader:745:27)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (D:\Codes\misc\Luna\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Codes\\misc\\Luna\\node_modules\\canvas\\lib\\bindings.js',
    'D:\\Codes\\misc\\Luna\\node_modules\\canvas\\lib\\canvas.js',
    'D:\\Codes\\misc\\Luna\\node_modules\\canvas\\index.js',
    'D:\\Codes\\misc\\Luna\\dist\\commands\\levels\\rank.js',
    'D:\\Codes\\misc\\Luna\\node_modules\\discord-akairo\\src\\struct\\AkairoHandler.js',
    'D:\\Codes\\misc\\Luna\\node_modules\\discord-akairo\\src\\index.js',
    'D:\\Codes\\misc\\Luna\\dist\\client.js',
    'D:\\Codes\\misc\\Luna\\dist\\index.js'
  ]
} Promise {
  <rejected> Error: Cannot find module '../build/Release/canvas.node'
  Require stack:
  - D:\Codes\misc\Luna\node_modules\canvas\lib\bindings.js
  - D:\Codes\misc\Luna\node_modules\canvas\lib\canvas.js
  - D:\Codes\misc\Luna\node_modules\canvas\index.js
  - D:\Codes\misc\Luna\dist\commands\levels\rank.js
  - D:\Codes\misc\Luna\node_modules\discord-akairo\src\struct\AkairoHandler.js
  - D:\Codes\misc\Luna\node_modules\discord-akairo\src\index.js
  - D:\Codes\misc\Luna\dist\client.js
  - D:\Codes\misc\Luna\dist\index.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:900:15)
      at Function.Module._load (node:internal/modules/cjs/loader:745:27)
      at Module.require (node:internal/modules/cjs/loader:972:19)
      at require (node:internal/modules/cjs/helpers:88:18)
      at Object.<anonymous> (D:\Codes\misc\Luna\node_modules\canvas\lib\bindings.js:3:18)
      at Module._compile (node:internal/modules/cjs/loader:1083:30)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
      at Module.load (node:internal/modules/cjs/loader:948:32)
      at Function.Module._load (node:internal/modules/cjs/loader:789:14)
      at Module.require (node:internal/modules/cjs/loader:972:19) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      'D:\\Codes\\misc\\Luna\\node_modules\\canvas\\lib\\bindings.js',
      'D:\\Codes\\misc\\Luna\\node_modules\\canvas\\lib\\canvas.js',
      'D:\\Codes\\misc\\Luna\\node_modules\\canvas\\index.js',
      'D:\\Codes\\misc\\Luna\\dist\\commands\\levels\\rank.js',
      'D:\\Codes\\misc\\Luna\\node_modules\\discord-akairo\\src\\struct\\AkairoHandler.js',
      'D:\\Codes\\misc\\Luna\\node_modules\\discord-akairo\\src\\index.js',
      'D:\\Codes\\misc\\Luna\\dist\\client.js',
      'D:\\Codes\\misc\\Luna\\dist\\index.js'
    ]
  }
}
```

</details>

I tried to rebuild it by `cd node_modules/canvas && node-gyp rebuild --versbose` here's the error I got:
<details>
<summary>gyp ERR! not ok</summary>

```js
❯ node-gyp rebuild --versbose
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.0.1 | win32 | x64
gyp info find Python using Python version 2.7.18 found at "C:\Python27\python.exe"
gyp info find VS using VS2019 (16.7.30611.23) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Riday\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Codes\\misc\\Luna\\node_modules\\canvas\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Riday\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Riday\\AppData\\Local\\node-gyp\\Cache\\15.0.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Riday\\AppData\\Local\\node-gyp\\Cache\\15.0.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Riday\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Riday\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\15.0.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Codes\\misc\\Luna\\node_modules\\canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Codes\\misc\\Luna\\node_modules\\canvas\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  Backend.cc
D:\Codes\misc\Luna\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Cannot open include file: 'cairo
.h': No such file or directory [D:\Codes\misc\Luna\node_modules\canvas\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Riday\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Riday\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--versbose"
gyp ERR! cwd D:\Codes\misc\Luna\node_modules\canvas
gyp ERR! node -v v15.0.1
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
```

</details>

I tried to remove and reinstall the canvas module. I am unable to do it. `npm rm canvas && npm i canvas`

<details>
<summary>npm ERR! D:\Codes\misc\Luna\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory [D:\Codes\misc\Luna\node_modules\canvas\build\canvas.vcxproj]</summary>

```js
❯ npm i canvas
npm ERR! code 1
npm ERR! path D:\Codes\misc\Luna\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "node-pre-gyp install --fallback-to-build"
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
npm ERR!   Backend.cc
npm ERR! D:\Codes\misc\Luna\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory [D:\Codes\misc\Luna\node_modules\canvas\build\canvas.vcxproj]
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\Codes\misc\Luna\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=D:\Codes\misc\Luna\node_modules\canvas\build\Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@15.0.1 | win32 | x64
npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download
npm ERR! node-pre-gyp info check checked for "D:\Codes\misc\Luna\node_modules\canvas\build\Release\canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp http 404 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@15.0.1 (node-v88 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-win32-unknown-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.0.1 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.0.1 | win32 | x64
npm ERR! gyp info find Python using Python version 2.7.18 found at "C:\Python27\python.exe"
npm ERR! gyp info find VS using VS2019 (16.7.30611.23) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Python27\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\Codes\\misc\\Luna\\node_modules\\canvas\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Riday\\AppData\\Local\\node-gyp\\Cache\\15.0.1\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Riday\\AppData\\Local\\node-gyp\\Cache\\15.0.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Riday\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\15.0.1\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=D:\\Codes\\misc\\Luna\\node_modules\\canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'D:\\Codes\\misc\\Luna\\node_modules\\canvas\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.0.1 | win32 | x64
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19041
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\Codes\\misc\\Luna\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=D:\\Codes\\misc\\Luna\\node_modules\\canvas\\build\\Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v88"
npm ERR! gyp ERR! cwd D:\Codes\misc\Luna\node_modules\canvas
npm ERR! gyp ERR! node -v v15.0.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\Codes\misc\Luna\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=D:\Codes\misc\Luna\node_modules\canvas\build\Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Codes\misc\Luna\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1048:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19041
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Codes\\misc\\Luna\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd D:\Codes\misc\Luna\node_modules\canvas
npm ERR! node-pre-gyp ERR! node -v v15.0.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Riday\AppData\Local\npm-cache\_logs\2020-10-26T05_17_17_775Z-debug.log
```

</details>

Can someone please help me?

## Your Environment
* Version of node-canvas: Trying to install v2.6.1
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):
```
❯ node -v
v15.0.1

❯ npm -v
7.0.3

❯ node-gyp -v
v7.1.2
```
Windows 10 - Version 2004 (OS Build 19041.572).
I have installed Visual Studio build tools 2019 and 2017. I also have Py v2.7.

**Comment by ridays2001** [comment]
I have downloaded the GTK zip and extracted it to `C:/GTK` as instructed in instructions.

**Comment by 17621001359** [comment]
You may need to switch your Node version to version 8

**Comment by ridays2001** [comment]
That's so dumb. Why would I need to downgrade the node version of the entire project just to make this one work? And that too to version 8? I mean, 14 is still understandable because it's LTS. But, why 8?

**Comment by ridays2001** [comment]
Okie. I am closing this issue and watching #1688 . Because if #1688 will be solved, mine would probably be solved too.
