### ISSUE TITLE
Error: Unsupported image type

### ISSUE THREAD

**Issue by kibibyte7** [Automattic/node-canvas#1709]
## Issue
 Error: Unsupported image type
            at setSource (C:\Users\Usr\Desktop\Xenova-rewrite-master\node_modules\canvas\lib\image.js:91:13)
            at C:\Users\Usr\Desktop\Xenova-rewrite-master\node_modules\canvas\lib\image.js:59:11
            at C:\Users\Usr\Desktop\Xenova-rewrite-master\node_modules\simple-get\index.js:89:7
            at IncomingMessage.<anonymous> (C:\Users\Usr\Desktop\Xenova-rewrite-master\node_modules\simple-concat\index.js:8:13)
            at Object.onceWrapper (events.js:421:28)
            at IncomingMessage.emit (events.js:327:22)
            at endReadableNT (_stream_readable.js:1327:12)
            at processTicksAndRejections (internal/process/task_queues.js:80:21) 

## Steps to Reproduce
```js
const canvas = Canvas.createCanvas(900, 500);

            const ctx = canvas.getContext('2d');

            Canvas.registerFont('Font/visitor1.ttf', { family: "visitor" });

            const background = await Canvas.loadImage("Images/joinleave1.jpg");

            ctx.drawImage(background, 0, 0, canvas.width, canvas.height);

            ctx.strokeStyle = '#74037b';

            ctx.strokeRect(0, 0, canvas.width, canvas.height);

            ctx.font = '25px visitor';
            ctx.fillStyle = '#ffffff';
            ctx.fillText(`Level ${r[0].level}`, canvas.width / 3, canvas.height / 3.7);

            ctx.beginPath();

            ctx.arc(125, 125, 100, 0, Math.PI * 2, true);

            ctx.closePath();

            ctx.clip();

            const avatar = await Canvas.loadImage(message.author.displayAvatarURL());

            ctx.drawImage(avatar, 25, 0, 200, canvas.height);

            const attachment = new Attachment(canvas.toBuffer(), "level.jpg")

            message.channel.send(attachment);
```

## Your Environment
Canvas 2.6.0
Windows 10 (x64)
Node 14.14.0

**Comment by Snowflake107** [comment]
replace `message.author.displayAvatarURL()` by `message.author.displayAvatarURL({ format: "jpg" })`

**Comment by pafad** [comment]
It works !

**Comment by pafad** [comment]
Wait wait i have another problem, when i use the commad that i make. i have this error 
``Pango-CRITICAL **: pango_win32_font_map_get_font_cache: assertion `font_map != NULL' failed``

**Comment by DrFalcon13** [comment]
where can i find steps to reproduce?
writes of your

**Comment by josephrexme** [comment]
Hi, I was having this problem and was able to create a codesandbox here https://codesandbox.io/s/eager-snowflake-1yjccp to replicate my issue as I'm not able to use a data-uri with `img.src` using the `Image` object

**Comment by josephrexme** [comment]
I actually think this might be worth its own issue.

**Comment by Miniontoby** [comment]
I get this error also whilst every thing is now on jpg

```js
		const canvas = Canvas.createCanvas(700, 250);
		const ctx = canvas.getContext('2d');
		const image = ;
		const background = await Canvas.loadImage('./pictures/wallpaper.jpg');
		ctx.drawImage(background, 0, 0, canvas.width, canvas.height);
		ctx.strokeStyle = '#74037b';
		ctx.strokeRect(0, 0, canvas.width, canvas.height);
		ctx.font = '28px sans-serif';
		ctx.fillStyle = '#ffffff';
		ctx.fillText('Welcome to the server,', canvas.width / 2.5, canvas.height / 3.5);
		ctx.font = applyText(canvas, `${member.displayName}!`);
		ctx.fillStyle = '#ffffff';
		ctx.fillText(`${member.displayName}!`, canvas.width / 2.5, canvas.height / 1.8);
		ctx.font = '20px sans-serif';
		ctx.fillStyle = '#ffffff';
		ctx.fillText(`Member #${member.guild.memberCount}`, canvas.width / 2.5, canvas.height / 1.2);
		ctx.beginPath();
		ctx.arc(125, 125, 100, 0, Math.PI * 2, true);
		ctx.closePath();
		ctx.clip();
		const avatar = await Canvas.loadImage(member.user.displayAvatarURL({ format: "jpg" }));
		ctx.drawImage(avatar, 25, 25, 200, 200);
		const attachment = new MessageAttachment(canvas.toBuffer(), 'welcome-image.jpg');
		channel.send({ content: `Welcome to ${member.guild}, ${member}!`, files: [attachment] });
```

**Comment by Miniontoby** [comment]
> ```
> Error: Unsupported image type
>     at setSource (/home/pi/moderybotstage/node_modules/canvas/lib/image.js:94:13)
>     at /home/pi/moderybotstage/node_modules/canvas/lib/image.js:62:11
>     at /home/pi/moderybotstage/node_modules/simple-get/index.js:97:7
>     at IncomingMessage.<anonymous> (/home/pi/moderybotstage/node_modules/simple-concat/index.js:8:13)
>     at Object.onceWrapper (node:events:639:28)
>     at IncomingMessage.emit (node:events:532:35)
>     at endReadableNT (node:internal/streams/readable:1343:12)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21)
> ```
> 
> I get this error also whilst every thing is now on jpg
> 
> ```js
> 		const canvas = Canvas.createCanvas(700, 250);
> 		const ctx = canvas.getContext('2d');
> 		const image = ;
> 		const background = await Canvas.loadImage('./pictures/wallpaper.jpg');
> 		ctx.drawImage(background, 0, 0, canvas.width, canvas.height);
> 		ctx.strokeStyle = '#74037b';
> 		ctx.strokeRect(0, 0, canvas.width, canvas.height);
> 		ctx.font = '28px sans-serif';
> 		ctx.fillStyle = '#ffffff';
> 		ctx.fillText('Welcome to the server,', canvas.width / 2.5, canvas.height / 3.5);
> 		ctx.font = applyText(canvas, `${member.displayName}!`);
> 		ctx.fillStyle = '#ffffff';
> 		ctx.fillText(`${member.displayName}!`, canvas.width / 2.5, canvas.height / 1.8);
> 		ctx.font = '20px sans-serif';
> 		ctx.fillStyle = '#ffffff';
> 		ctx.fillText(`Member #${member.guild.memberCount}`, canvas.width / 2.5, canvas.height / 1.2);
> 		ctx.beginPath();
> 		ctx.arc(125, 125, 100, 0, Math.PI * 2, true);
> 		ctx.closePath();
> 		ctx.clip();
> 		const avatar = await Canvas.loadImage(member.user.displayAvatarURL({ format: "jpg" }));
> 		ctx.drawImage(avatar, 25, 25, 200, 200);
> 		const attachment = new MessageAttachment(canvas.toBuffer(), 'welcome-image.jpg');
> 		channel.send({ content: `Welcome to ${member.guild}, ${member}!`, files: [attachment] });
> ```

I found out what was wrong:
I was using `displayAvatarURL({ format: "jpg" })` instead of `displayAvatarURL({ extension: "jpg" })`! Don't know when they changed that, but yeah. It works for me again

**Comment by Stiven988** [comment]
`vetomo.on("guildMemberAdd", async (member) => {
    const canvas = createCanvas(1000, 500);
    const ctx = canvas.getContext("2d");

    const bg = await loadImage("./src/Assets/images/welcome-card.png");

    ctx.drawImage(bg, 0, 0, 1000, 500);

    // Avatar
    ctx.translate(0, 88);
    const avatar = await loadImage(member.user.displayAvatarURL({ format: "png" }));
    ctx.drawImage(avatar, 104, 0, 144, 146);

    // Member name
    ctx.translate(0, 197);

    ctx.fillStyle = "white";
    ctx.shadowColor = "#33DAFF";
    ctx.shadowBlur = 1;
    ctx.shadowOffsetX = 3;
    ctx.shadowOffsetY = 3;

    const name = member.displayName.normalize("NFKC");
    const fontSize = 62;
    ctx.font = `${fontSize}px Futura-Normal`;
    ctx.fillText(name, 360, 0);

    // Current member number
    ctx.translate(0, 130);
    ctx.shadowColor = "#E34FB6";
    ctx.font = "42px Futura-Normal";
    ctx.textAlign = "end";
    ctx.shadowOffsetX = 3;
    ctx.shadowOffsetY = 3;
    ctx.fillText(`Miembro #${member.guild.memberCount}`, 925, 0);

    const attachment = new AttachmentBuilder(canvas.toBuffer(), "welcome.png");

    const noteworthyChannels  = [
        {
            emoji: "📚",
            title: "Reglas & Anuncios",
            text: "Asegurate de haber leido las reglas de nuestro servidor antes de entrar en cualquier cosa. Tambien puedes consultar los anuncios relacionados con la banda y el servidor."
        },
        {
            emoji: "🤖",
            title: "Bots",
            text: "Utilizar nuestros bots personalizados en los <#865036166004342789>"
        },
        {
            emoji: "🎶",
            title: "Canales de Voz & Música",
            text: "Puedes hacer amistades mucho mas estrechas mediante los chats de voz o tambien si no tienes amigos :( puedes escuchar m?sica mediante el obispo Andre"
        },
        {
            emoji: "🏬",
            title: "Tienda",
            text: "Echa un vistazo a nuestros articulos actualmente en venta los cuales pueden traer beneficios a largo o corto plazo."
        },
        {
            emoji: "📰",
            title: "Actualizaciones",
            text: "Mantente al día con las publicaciones de la banda en <#865036165403770883>, y recibe notificaciones si dmaorg.info se actualiza en <#865036165403770884>. Puedes inscribirte para recibir notificaciones utilizando el comando `/roles notificaciones` en el canal de <#865036166004342789>."
        }
    ]

    const embed = new EmbedBuilder()
    .setTitle("Bienvenido al servidor de Discord Glowing Skeleton!")
    .setAuthor({ name: member.displayName, iconURL: message.author.displayAvatarURL({ format: "jpg" }) })
    .setDescription(
        "Tienes curiosidad por explorar el servidor? A continuación te mostramos algunos de los canales más populares para que los veas."
    )
    .setImage("attachment://welcome.png");

    embed.addFields({ name: "\u200b", value: "\u200b" });
    for (const { emoji, title, text } of noteworthyChannels) {
        embed.addFields({ name: `${emoji} ${title}`, value: text });
    }

    member.guild.channels.cache.find(c => c.id === channelsIDs.bienvenida).send({ content: `<@${member.id}>`, embeds: [embed], files: [attachment] });

    member.roles.add(rolesIDs.bandito);
    member.roles.add(rolesIDs.nuevo);

    console.log(`Miembro #${member.guild.memberCount} se ha unido`);

})`

_**Console**_

¡Listo! Conectado como Vetomo#1384
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: Unsupported image type
    at setSource (C:\Users\taki0\Documents\Listo-and-the-Bots\node_modules\canvas\lib\image.js:94:13)
    at C:\Users\taki0\Documents\Listo-and-the-Bots\node_modules\canvas\lib\image.js:62:11
    at C:\Users\taki0\Documents\Listo-and-the-Bots\node_modules\simple-get\index.js:97:7
    at IncomingMessage.<anonymous> (C:\Users\taki0\Documents\Listo-and-the-Bots\node_modules\simple-concat\index.js:8:13)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:394:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)

Node.js v18.13.0

**Comment by Leavoh** [comment]
for people stumbling on this because of the `discplayAvatarURL`, the parameter has been renamed. It is now `Player?.displayAvatarURL({ extension: "png" })`

**Comment by soyDaddy** [comment]
Error: Unsupported image type
0|SILVERCITY_OmenBot  |     at setSource (C:\Users\Administrador\Desktop\SilverBot\Webs\BotMaster\bots\Bot\node_modules\canvas\lib\image.js:94:13)
0|SILVERCITY_OmenBot  |     at C:\Users\Administrador\Desktop\SilverBot\Webs\BotMaster\bots\Bot\node_modules\canvas\lib\image.js:62:11
0|SILVERCITY_OmenBot  |     at C:\Users\Administrador\Desktop\SilverBot\Webs\BotMaster\bots\Bot\node_modules\simple-get\index.js:97:7
0|SILVERCITY_OmenBot  |     at IncomingMessage.<anonymous> (C:\Users\Administrador\Desktop\SilverBot\Webs\BotMaster\bots\Bot\node_modules\simple-concat\index.js:8:13)
0|SILVERCITY_OmenBot  |     at Object.onceWrapper (node:events:628:28)
0|SILVERCITY_OmenBot  |     at IncomingMessage.emit (node:events:526:35)
0|SILVERCITY_OmenBot  |     at endReadableNT (node:internal/streams/readable:1359:12)
0|SILVERCITY_OmenBot  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)


`js
 Canvas.registerFont(require("@canvas-fonts/arial-bold-italic"), { family: "Arial Bold Italic" });

        // Create Canvas
        const canvas = Canvas.createCanvas(1024, 450);
        const ctx = canvas.getContext("2d");

        // Draw background
        ctx.fillStyle = '#9b9b9b';
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        let background = await Canvas.loadImage('https://c4.wallpaperflare.com/wallpaper/465/1015/587/anime-darling-in-the-franxx-zero-two-darling-in-the-franxx-hd-wallpaper-preview.jpg');
        ctx.drawImage(background, 0, 0, canvas.width, canvas.height);

        // img 
        let b = await Canvas.loadImage('https://cdn.discordapp.com/attachments/1109913006294442085/1149020654646067292/image.png');
        ctx.drawImage(b, 0, 0, canvas.width, canvas.height);

        // Draw username
        ctx.globalAlpha = 1;
        ctx.font = "45px Arial Bold Italic";
        ctx.textAlign = 'center';
        ctx.fillStyle = '#ffffff';
        ctx.fillText('soyDaddy', canvas.width - 890, canvas.height - 60);
        
        // Draw guild name
        ctx.globalAlpha = 1;
        ctx.font = "45px Arial Bold Italic";
        ctx.textAlign = 'center';
        ctx.fillStyle = '#ffffff';
        ctx.fillText('Test Guild', canvas.width - 225, canvas.height - 44);

        // Draw membercount
        ctx.fillStyle = '#ffffff';
        ctx.font = "22px Arial Bold Italic";
        ctx.fillText('17', 90, canvas.height - 15);

        // Draw guild circle
        ctx.save()
        ctx.beginPath();
        ctx.lineWidth = 10;
        ctx.strokeStyle = '#23272a';
        ctx.arc(canvas.width - 150, canvas.height - 200, 80, 0, Math.PI * 2, true);
        ctx.stroke();
        ctx.closePath();
        ctx.clip();
        const guildIco = await Canvas.loadImage('https://wallpapercave.com/wp/wp7282546.jpg');
        ctx.drawImage(guildIco, canvas.width - 230, canvas.height - 280, 160, 160);
        ctx.restore();

        // Draw avatar circle
        ctx.save();
        ctx.beginPath();
        ctx.lineWidth = 10;
        ctx.strokeStyle = '#23272a';
        ctx.arc(180, 160, 110, 0, Math.PI * 2, true);
        ctx.stroke();
        ctx.closePath();
        ctx.clip();
        const avatar = await Canvas.loadImage(interaction.user.displayAvatarURL({ format: "jpg" }));
        ctx.drawImage(avatar, 45, 40, 270, 270);
        ctx.restore();`

**Comment by AFDavi06** [comment]
`const Discord =  require("discord.js")
const client = new Discord.Client({ intents: Object.values(Discord.IntentsBitField.Flags)})

client.once("ready", () => {
  console.log(`Logged in as ${client.user.tag}!`);
  console.log(client.user.tag)
});
client.login("MTE5MDAwODQ4MjU0ODY4Mjg1Mg.GfMBia.6hPbEiLrkkb1Ex3TVqviRCUlYfkDua7czGv7t4")

const { createCanvas, loadImage, MessageAttachment } = require('canvas');

client.on('guildMemberAdd', async (member) => {
  const welcomeChannel = client.channels.cache.get('1188962541842485353');
  const rulesChannel = client.channels.cache.get('1192109584777760868');
  const verifyChannel = client.channels.cache.get('1193611427450200078');
  const infoChannel = client.channels.cache.get('1192102711718596688');

  if (welcomeChannel && rulesChannel && verifyChannel && infoChannel) {
    console.log("Sto per inviare il messaggio di benvenuto a:", member.user.tag);

    const canvas = createCanvas(1024, 500);
    const ctx = canvas.getContext('2d');

    const background = await loadImage("/static(1).png").catch(error => {
      console.error("Errore nel caricamento dell'immagine:", error);
    });
    
    

    if (background) {
      ctx.drawImage(background, 0, 0, canvas.width, canvas.height);

      ctx.font = '72px sans-serif';
      ctx.fillStyle = '#ffffff';
      ctx.fillText('Welcome', 360, 360);

      ctx.beginPath();
      ctx.arc(512, 166, 128, 0, Math.PI * 2, true);
      ctx.stroke();
      ctx.fill();

      ctx.font = '42px sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText(member.user.tag.toUpperCase(), 512, 410);
      ctx.font = '32px sans-serif';
      ctx.fillText(`You are the ${member.guild.memberCount}th`, 512, 455);

      ctx.beginPath();
      ctx.arc(512, 166, 119, 0, Math.PI * 2, true);
      ctx.closePath();
      ctx.clip();

      const avatar = await loadImage(member.user.displayAvatarURL({ format: 'png', size: 1024 }));
      ctx.drawImage(avatar, 393, 47, 238, 238);

      const attachment = new MessageAttachment(canvas.toBuffer(), `welcome-${member.id}.png`);
      
      try {
        welcomeChannel.send(`:wave: Hello ${member}, welcome to ${member.guild.name}!`, { files: [attachment] });
        welcomeChannel.send(`Don't forget to read the rules in ${rulesChannel} and verify yourself in ${verifyChannel}. For more information, check out ${infoChannel}.`);
        
      
        console.log("Messaggio di benvenuto inviato con successo a:", member.user.tag);
      } catch (error) {
        console.error("Errore nell'invio del messaggio di benvenuto", error);
      }
    }
  }
});`

node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: Unsupported image type
    at setSource (C:\Users\Utente\Desktop\DS\node_modules\canvas\lib\image.js:94:13)
    at C:\Users\Utente\Desktop\DS\node_modules\canvas\lib\image.js:62:11
    at C:\Users\Utente\Desktop\DS\node_modules\simple-get\index.js:97:7
    at IncomingMessage.<anonymous> (C:\Users\Utente\Desktop\DS\node_modules\simple-concat\index.js:8:13)
    at Object.onceWrapper (node:events:633:28)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:402:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)

Node.js v21.5.0
