### ISSUE TITLE
Cannot assign to read only property 'toString' of object '#<DOMMatrix>'

### ISSUE THREAD

**Issue by 1mgr007** [Automattic/node-canvas#1711]
why when I change vps occur this error?
whereas in my old vps there was no error.

## Error : 
```
Unhandled promise exception: TypeError: Cannot assign to read only property 'toString' of object '#<DOMMatrix>'
    at Object.<anonymous> (/root/BotDiscord/Awkarin/node_modules/canvas/lib/DOMMatrix.js:163:30)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/BotDiscord/Awkarin/node_modules/canvas/lib/context2d.js:11:23)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

```

## Your Environment
canvas@2.6.1
NodeJS v14.15.1
Ubuntu 20.04.1 LTS

**Comment by zbjornson** [comment]
Can you provide code to reproduce the issue please?
