### ISSUE TITLE
Cannot install canvas using npm on Debian

### ISSUE THREAD

**Issue by Mzato0001** [Automattic/node-canvas#1721]
Error:

```> canvas@2.6.1 install /home/mzato/actions-runner/_work/Solo-Leveling-Simulator/Solo-Leveling-Simulator/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v89-linux-glibc-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@16.0.0-pre (node-v89 ABI, glibc) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:55:16)
gyp ERR! stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:441:10)
gyp ERR! stack     at Object.self.commands.<computed> [as install] (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:41:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:63:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:30:7
gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:75:11)
gyp ERR! System Linux 4.19.0-13-cloud-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/mzato/actions-runner/_work/Solo-Leveling-Simulator/Solo-Leveling-Simulator/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/mzato/actions-runner/_work/Solo-Leveling-Simulator/Solo-Leveling-Simulator/node_modules/canvas/build/Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v89"
gyp ERR! cwd /home/mzato/actions-runner/_work/Solo-Leveling-Simulator/Solo-Leveling-Simulator/node_modules/canvas
gyp ERR! node -v v16.0.0-pre
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/mzato/actions-runner/_work/Solo-Leveling-Simulator/Solo-Leveling-Simulator/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/mzato/actions-runner/_work/Solo-Leveling-Simulator/Solo-Leveling-Simulator/node_modules/canvas/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v89' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/mzato/actions-runner/_work/Solo-Leveling-Simulator/Solo-Leveling-Simulator/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1063:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
node-pre-gyp ERR! System Linux 4.19.0-13-cloud-amd64
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/mzato/actions-runner/_work/Solo-Leveling-Simulator/Solo-Leveling-Simulator/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/mzato/actions-runner/_work/Solo-Leveling-Simulator/Solo-Leveling-Simulator/node_modules/canvas
node-pre-gyp ERR! node -v v16.0.0-pre
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/mzato/actions-runner/_work/Solo-Leveling-Simulator/Solo-Leveling-Simulator/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/mzato/actions-runner/_work/Solo-Leveling-Simulator/Solo-Leveling-Simulator/node_modules/canvas/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v89' (1)
npm WARN solo-leveling-simulator@2.0.0 No repository field.
npm WARN You are using a pre-release version of node and things may not work as expected
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I have done all of [this](https://github.com/Automattic/node-canvas/wiki/Installation%3A-Ubuntu-and-other-Debian-based-systems) but it didn't work 😢

**Comment by Mzato0001** [comment]
I installed it but somehow when I pulled the code from GitHub through Actions its error again 😢

**Comment by TotallyInformation** [comment]
I have the same issue when installing vega and it leaves npm in a mess. Every time I try to install another module I constantly get the same errors. I have to remove vega so that I can see actual issues with other modules.

**Comment by TotallyInformation** [comment]
Seriously? Closed without comment?!

Canvas causes issues when installing on Debian, one of the most widely used versions of Linux. But you choose to ignore it?

**Comment by Mzato0001** [comment]
@TotallyInformation Sorry :/ Cause ive just realised that i have removed the feature using Canvas so...
