### ISSUE TITLE
Unable to install via npm

### ISSUE THREAD

**Issue by Kingsy** [Automattic/node-canvas#1731]
Hi, I am trying to install canvas on my openbsd VM however it does not install.

kingsy# node -v
v12.16.1
kingsy# npm -v
6.14.11

Command to reproduce 

env CXX=/usr/bin/clang++ npm install canvas --build-from-source

Output

> canvas@2.6.1 install /var/www/sites/kingsy.co.uk/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
/bin/sh: grep: not found
gyp: Call to 'node ./util/has_lib.js jpeg' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System OpenBSD 6.8
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/var/www/sites/kingsy.co.uk/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/var/www/sites/kingsy.co.uk/node_modules/canvas/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /var/www/sites/kingsy.co.uk/node_modules/canvas
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/var/www/sites/kingsy.co.uk/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/var/www/sites/kingsy.co.uk/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/www/sites/kingsy.co.uk/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System OpenBSD 6.8
node-pre-gyp ERR! command "node" "/var/www/sites/kingsy.co.uk/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/www/sites/kingsy.co.uk/node_modules/canvas
node-pre-gyp ERR! node -v v12.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/var/www/sites/kingsy.co.uk/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/var/www/sites/kingsy.co.uk/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN babel-loader@8.1.0 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN redux-persist@6.0.0 requires a peer of redux@>4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN with-redux@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"openbsd","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/next/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"openbsd","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules/webpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"openbsd","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-14T00_41_41_375Z-debug.log

From the output it seems I am missing libjpeg however I have executed

doas pkg_add cairo pango png jpeg giflib

And can confirm they are installed, I can also see the libs via

kingsy# ls -la /usr/local/lib/ | grep jpeg
-rw-r--r--    1 root  bin     2946954 Sep 30 20:46 libjpeg.a
-rw-r--r--    1 root  bin      613568 Sep 30 20:46 libjpeg.so.70.0
-rw-r--r--    1 root  bin     3580424 Sep 30 20:46 libturbojpeg.a
-rw-r--r--    1 root  bin      708328 Sep 30 20:46 libturbojpeg.so.0.0

I have also tried to flush the npm cache via npm cache clean --force just to ensure that it is not caching anything funny.

Any advice welcome, I am a bit stuck here.

Thanks

**Comment by morgant** [comment]
It looks like the path is being clobbered in `has_lib.js` `hasLdconfig()` by being set to an ellipsis, see [line 61](https://github.com/Automattic/node-canvas/blob/e4766560e52891674a2fc37ed1fe9ff0aa53b6f4/util/has_lib.js#L61). This causes `grep` to not be found on [line 31](https://github.com/Automattic/node-canvas/blob/e4766560e52891674a2fc37ed1fe9ff0aa53b6f4/util/has_lib.js#L31) and the script to fail. If I comment out line 61, `node ./util/has_lib.js jpeg` correctly returns true.

(Note: `-p` is not a valid `lfconfig` option under OpenBSD, but that's okay as it'll proceed to check `SYSTEM_PATHS` when that fails.)

**Comment by Kingsy** [comment]
Yes! I thought that was really strange. Why would we ever want to set the path to "..." ? I don't understand that at all.

I guess my next question is, how can I cause npm install to grab a version of canvas without this strange assignment? I suppose understanding more about why "..." is useful will determine if we can issue a PR to change this line to make it openbsd compatible.

**Comment by morgant** [comment]
@Kingsy I don't personally do much `npm` development, but I believe you would want to clone the node-canvas project locally and use [`npm link`](https://docs.npmjs.com/cli/v6/commands/npm-link) to link the local module to your project.

Does anyone else have any input as to why `has_lib.js`'s `hasLdconfig()` is setting the `PATH` in this way and what it does under Linux? I can't find any documentation of the ellipsis being a special supported path in `node` or `sh` under Linux. It doesn't seem to have been changed in 4 years since [`has_lib.sh` was ported to JS](https://github.com/Automattic/node-canvas/commit/5702c4745a72956a34d635344937384a1b3bcd2e).

**Comment by zbjornson** [comment]
@morgant is correct about using `npm link` as the easiest way to do local dev of a dependency.

I don't remember why I wrote `process.env.PATH = '...'`. That's not meaningful in any shell that I know of either. It's possible that was an unfinished TODO, as an alternative to invoking `export` in a separate call. (Still better would be something like `    childProcess.execSync('hash ldconfig 2>/dev/null', {env: {...process.env, PATH: process.env.PATH + ":/sbin"}})`.) Happy to take a PR to fix it! Appreciate the troubleshooting you've done.

**Comment by morgant** [comment]
The following diff, which is what @zbjornson suggested above, does seem to work for me on OpenBSD 6.8-stable:

```
index 1ede900..b73a124 100644
--- a/util/has_lib.js
+++ b/util/has_lib.js
@@ -57,10 +57,8 @@ function hasLdconfig () {
   try {
     // Add /sbin to path as ldconfig is located there on some systems -- e.g.
     // Debian (and it can still be used by unprivileged users):
-    childProcess.execSync('export PATH="$PATH:/sbin"')
-    process.env.PATH = '...'
     // execSync throws on nonzero exit
-    childProcess.execSync('hash ldconfig 2>/dev/null')
+    childProcess.execSync('hash ldconfig 2>/dev/null', {env: {...process.env, PATH: process.env.PATH + ":/sbin"}})
     return true
   } catch (err) {
     return false
```

I don't have any projects using `node-canvas` and I get a bus error part way through `npm test`, but it at least installs for me. @Kingsy do you want to do more testing and create a PR?

**Comment by Kingsy** [comment]
ah, due to the issue I made a work around for my current project.
However, I would be happy to have a go at a PR. I'll put it on my list of things to do.

**Comment by anor731** [comment]
Can you please tell us how to work this out? I kinda need canvas for my project. Or latest node version it's working on.

**Comment by Kingsy** [comment]
@anor731 sorry I haven't had time to make a PR for this yet. But as @morgant stated above seems like a reasonable start.
Hopefully I will get time soon to have a look at this properly
