### ISSUE TITLE
canvas.loadImage(src) got exception "Out of memory"

### ISSUE THREAD

**Issue by VIIGstar** [Automattic/node-canvas#1735]
## Issue or Feature

Hi, I had trouble with load image by canvas that always got out of memory exception.
My device still can load image has size larger than 80MB without any problem except this image (16.8MB) `https://pbimg.btdmp.com/pbase/shop-id/10117363/artworks/2141699b41cb8b5b454ffbd0380e247b.png`

## Steps to Reproduce

```js
const _canvas = require('canvas')

_canvas.loadImage('https://pbimg.btdmp.com/pbase/shop-id/10117363/artworks/2141699b41cb8b5b454ffbd0380e247b.png')
    .catch((e) => {
      console.log(e)
  })
```

## Your Environment
* Version of node-canvas: 2.6.1
* Environment: Node v10.13, Ubuntu 18.04.4 LTS

**Comment by goldenjayr** [comment]
also getting the same problem

**Comment by zbjornson** [comment]
I can't reproduce this issue. The image loads successfully for me, with about 33,661,225 bytes of ArrayBuffers allocated. Can you provide more info please?

**Comment by VIIGstar** [comment]
Just run the above function then my app still crashed

> also getting the same problem

He got the same problem.

@zbjornson what kind of information do you want more?

**Comment by viktor-silakov** [comment]
I also have the same problem, the code is very simple:
```
const {loadImage} = require('canvas')
loadImage('605cccb8b4745c1f0d1a79c4.png').then((image) => {
})
```
Image
![605cccb8b4745c1f0d1a79c4](https://user-images.githubusercontent.com/23633060/113207635-e546f000-9281-11eb-9ead-88da16b2943b.png)

I reproduced this 100% both on Mac and Linux, at the same time - images with greater size (more than 10Mb) processing without problems, the problems are only with such certain images.

**Comment by NekoYasuii** [comment]
```js
  panel.body = await loadImage(process.cwd() + "/src/img/none/body.png");
  panel.banner = {};
  panel.banner.front = await loadImage(process.cwd() + "/src/img/none/banner-front.png");
  panel.banner.back = await loadImage(process.cwd() + "/src/img/none/banner-back.png");
  panel.avatar = {};
  panel.avatar.front = await loadImage(process.cwd() + "/src/img/none/avatar-front.png");
  panel.avatar.back = await loadImage(process.cwd() + "/src/img/none/avatar-back.png");

  const wallpaper = await loadImage(process.cwd() + "/src/img/blurple.png");
  const avatar = await loadImage(process.cwd() + "/src/img/blurple.png");
```

got this.. 
```xl
(node:6584) UnhandledPromiseRejectionWarning: Error: out of memory
    at setSource (C:\Users\Asus-Lapiz\Desktop\Canvas\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\Asus-Lapiz\Desktop\Canvas\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\Asus-Lapiz\Desktop\Canvas\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\Asus-Lapiz\Desktop\Canvas\node_modules\canvas\index.js:23:10)
    at C:\Users\Asus-Lapiz\Desktop\Canvas\src\app.js:43:22
    at Layer.handle [as handle_request] (C:\Users\Asus-Lapiz\Desktop\Canvas\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Asus-Lapiz\Desktop\Canvas\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Asus-Lapiz\Desktop\Canvas\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Asus-Lapiz\Desktop\Canvas\node_modules\express\lib\router\layer.js:95:5)
```

**Comment by thsking** [comment]
I'm aware it woudln't help for every case. But after looking for a solution for so many time. I finally find a work around ... 
Use .jpg image instead of a png.

**Comment by miroljub1995** [comment]
We have the same issue with version `2.11.2`.
