### ISSUE TITLE
[Windows] Unable to load shared library (canvas.node, 64bit)

### ISSUE THREAD

**Issue by GottZ** [Automattic/node-canvas#175]
hello there.
i did what was described there: https://github.com/LearnBoost/node-canvas/wiki/Installation---Windows
i downloaded gtk+-bundle_2.22.1-20101229_win64.zip (wich seems to be the latest 64bit package), i run node v0.6.18 in 64bit, i have python 2.7 64bit in my path, i've installed node-gyp, i have microsofts visual studio 2010 ultimate installed and so on and so on..

i downloaded node-canvas as .zip from github and simply extracted it to the following directory where i do all the following actions:

```
C:\node\node_modules\node-canvas>set path=%path%;c:\python27

C:\node\node_modules\node-canvas>node-gyp configure build
info it worked if it ends with ok
spawn python [ 'C:\\Users\\GottZ\\.node-gyp\\0.6.18\\tools\\gyp_addon',
  'binding.gyp',
  '-IC:\\node\\node_modules\\node-canvas\\build\\config.gypi',
  '-f',
  'msvs',
  '-G',
  'msvs_version=2010' ]
spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe [ 'build/binding
.sln',
  '/clp:Verbosity=minimal',
  '/nologo',
  '/p:Configuration=Release;Platform=x64' ]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(99
0,5): warning MSB8012: TargetPath(C:\node\node_modules\node-canvas\build\Releas
e\canvas.dll) does not match the Linker's OutputFile property value (C:\node\no
de_modules\node-canvas\build\Release\canvas.node). This may cause your project
to build incorrectly. To correct this, please make sure that $(OutDir), $(Targe
tName) and $(TargetExt) property values match the value specified in %(Link.Out
putFile). [C:\node\node_modules\node-canvas\build\canvas.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(99
1,5): warning MSB8012: TargetExt(.dll) does not match the Linker's OutputFile p
roperty value (.node). This may cause your project to build incorrectly. To cor
rect this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) prop
erty values match the value specified in %(Link.OutputFile). [C:\node\node_modu
les\node-canvas\build\canvas.vcxproj]
     Creating library C:\node\node_modules\node-canvas\build\Release\canvas.lib
   and object C:\node\node_modules\node-canvas\build\Release\canvas.exp
  Generating code
  Finished generating code
  canvas.vcxproj -> C:\node\node_modules\node-canvas\build\Release\canvas.dll
info done ok

C:\node\node_modules\node-canvas>cd test

C:\node\node_modules\node-canvas\test>node server.js

C:\node\node_modules\node-canvas\lib\bindings.js:9
  throw e;
        ^
Error: Cannot find module '../build/default/canvas'
    at Function._resolveFilename (module.js:337:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (C:\node\node_modules\node-canvas\lib\bindings.js:7:20
)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)

C:\node\node_modules\node-canvas\test>
```

i've also tried directly loading the canvas.node module wich results in this:

```
C:\node\node_modules\node-canvas\build\Release>node
> var can = require("./canvas");
Error: Unable to load shared library C:\node\node_modules\node-canvas\build\Rele
ase\canvas.node
    at Object..node (module.js:477:11)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at repl:1:11
    at REPLServer.eval (repl.js:80:21)
    at repl.js:190:20
    at REPLServer.eval (repl.js:87:5)
    at Interface.<anonymous> (repl.js:182:12)
>
```

any idea what could cause this? it seems like it compiles without any issue. only a creepy warning that says dll's should be .dll and not .node

besides that.. i've compiled node from source and voila.. same problem

should i try that again using 32bit stuff? (cairo, node)

thanks in advance.

**Comment by PawandeepKaur** [comment]
I have a same problem. Windows 8 64bit.  with depends.exe I  am getting the following error

API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL
API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-SHUTDOWN-L1-1-1.DLL
EXT-MS-WIN-NTUSER-UICONTEXT-EXT-L1-1-0.DLL

I have path set for GTK bin, I have downloaded 64bit GTK version. I have already found first 3 and dont know how can I get last 2. any suggestions
