### ISSUE TITLE
Debian build servers not downloading pre-built binaries

### ISSUE THREAD

**Issue by CabobeanFamilySearch** [Automattic/node-canvas#1759]
## Issue
npm install fails at canvas@2.6.1
```npm ERR! Failed at the canvas@2.6.1 install script.```

```
> canvas@2.6.1 install /builds/workspace/frontier-discovery-react-build-1223/checkout/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.6.1 and node@12.21.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error unable to get local issuer certificate 
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/fs/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/home/fs/.nvm/versions/node/v12.21.0/bin/node" "/home/fs/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/builds/workspace/frontier-discovery-react-build-1223/checkout/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/builds/workspace/frontier-discovery-react-build-1223/checkout/node_modules/canvas/build/Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /builds/workspace/frontier-discovery-react-build-1223/checkout/node_modules/canvas
gyp ERR! node -v v12.21.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/fs/.nvm/versions/node/v12.21.0/bin/node /home/fs/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/builds/workspace/frontier-discovery-react-build-1223/checkout/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/builds/workspace/frontier-discovery-react-build-1223/checkout/node_modules/canvas/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/builds/workspace/frontier-discovery-react-build-1223/checkout/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 4.9.0-8-amd64
node-pre-gyp ERR! command "/home/fs/.nvm/versions/node/v12.21.0/bin/node" "/builds/workspace/frontier-discovery-react-build-1223/checkout/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /builds/workspace/frontier-discovery-react-build-1223/checkout/node_modules/canvas
node-pre-gyp ERR! node -v v12.21.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
```

## Your Environment
Debian
Node version: 12.21.0
Canvas version: 2.6.1

**Comment by zbjornson** [comment]
`unable to get local issuer certificate` can mean your certificate authority bundle used by Python is old or missing certs for GitHub. These StackOverflow answers might help:

https://stackoverflow.com/questions/51925384/unable-to-get-local-issuer-certificate-when-using-requests-in-python
https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate

This is not really an issue with node-canvas and not an issue I can provide much help with.

*(copied from #1760)*
