### ISSUE TITLE
npm i --build-from-source canvas fails 

### ISSUE THREAD

**Issue by skaneprime** [Automattic/node-canvas#1788]
When I execute npm i --build-from-source. Canvas fails to build 
```
D:\WORK\bothub\discord-base-bot>npm i --build-from-source canvas
npm WARN deprecated node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

> canvas@2.7.0 install D:\WORK\bothub\discord-base-bot\node_modules\canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
Warning: Missing input files:
C:\GTK\bin\libpangoft2-1.0-0.dll
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libintl-8.dll
C:\GTK\bin\libgmodule-2.0-0.dll
C:\GTK\bin\libglib-2.0-0.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libgobject-2.0-0.dll
C:\GTK\bin\libgthread-2.0-0.dll
C:\GTK\bin\libpangocairo-1.0-0.dll
C:\GTK\bin\libfreetype-6.dll
C:\GTK\bin\libpango-1.0-0.dll
C:\GTK\bin\libpangowin32-1.0-0.dll
Выполняется последовательная сборка проектов в этом решении. Чтобы включить параллельную сборку, добавьте параметр "-m".
  Backend.cc
  ImageBackend.cc
  PdfBackend.cc
  SvgBackend.cc
  BMPParser.cc
  Backends.cc
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  closure.cc
  color.cc
D:\WORK\bothub\discord-base-bot\node_modules\canvas\src\CanvasPattern.h(5,10): fatal error C1083: Не удается открыть файл включение: cairo.h: No such file or directory, (компилируется исх
одный файл ..\src\CanvasPattern.cc) [D:\WORK\bothub\discord-base-bot\node_modules\canvas\build\canvas.vcxproj]
D:\WORK\bothub\discord-base-bot\node_modules\canvas\src\CanvasRenderingContext2d.h(5,10): fatal error C1083: Не удается открыть файл включение: cairo.h: No such file or directory, (компил
ируется исходный файл ..\src\CanvasRenderingContext2d.cc) [D:\WORK\bothub\discord-base-bot\node_modules\canvas\build\canvas.vcxproj]
D:\WORK\bothub\discord-base-bot\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Не удается открыть файл включение: cairo.h: No such file or directory, (компилируется и
сходный файл ..\src\backend\Backend.cc) [D:\WORK\bothub\discord-base-bot\node_modules\canvas\build\canvas.vcxproj]
D:\WORK\bothub\discord-base-bot\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Не удается открыть файл включение: cairo.h: No such file or directory, (компилируется и
сходный файл ..\src\backend\PdfBackend.cc) [D:\WORK\bothub\discord-base-bot\node_modules\canvas\build\canvas.vcxproj]
D:\WORK\bothub\discord-base-bot\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Не удается открыть файл включение: cairo.h: No such file or directory, (компилируется и
сходный файл ..\src\backend\SvgBackend.cc) [D:\WORK\bothub\discord-base-bot\node_modules\canvas\build\canvas.vcxproj]
D:\WORK\bothub\discord-base-bot\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Не удается открыть файл включение: cairo.h: No such file or directory, (компилируется и
сходный файл ..\src\Canvas.cc) [D:\WORK\bothub\discord-base-bot\node_modules\canvas\build\canvas.vcxproj]
D:\WORK\bothub\discord-base-bot\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Не удается открыть файл включение: cairo.h: No such file or directory, (компилируется и
сходный файл ..\src\backend\ImageBackend.cc) [D:\WORK\bothub\discord-base-bot\node_modules\canvas\build\canvas.vcxproj]
D:\WORK\bothub\discord-base-bot\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Не удается открыть файл включение: cairo.h: No such file or directory, (компилируется и
сходный файл ..\src\closure.cc) [D:\WORK\bothub\discord-base-bot\node_modules\canvas\build\canvas.vcxproj]
D:\WORK\bothub\discord-base-bot\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Не удается открыть файл включение: cairo.h: No such file or directory, (компилируется и
сходный файл ..\src\Backends.cc) [D:\WORK\bothub\discord-base-bot\node_modules\canvas\build\canvas.vcxproj]
  Image.cc
  ImageData.cc
  init.cc
  register_font.cc
  win_delay_load_hook.cc
D:\WORK\bothub\discord-base-bot\node_modules\canvas\src\register_font.h(3,10): fatal error C1083: Не удается открыть файл включение: pango/pango.h: No such file or directory, (компилирует
ся исходный файл ..\src\register_font.cc) [D:\WORK\bothub\discord-base-bot\node_modules\canvas\build\canvas.vcxproj]
D:\WORK\bothub\discord-base-bot\node_modules\canvas\src\init.cc(4,10): fatal error C1083: Не удается открыть файл включение: pango/pango.h: No such file or directory, [D:\WORK\bothub\disc
ord-base-bot\node_modules\canvas\build\canvas.vcxproj]
D:\WORK\bothub\discord-base-bot\node_modules\canvas\src\Image.h(5,10): fatal error C1083: Не удается открыть файл включение: cairo.h: No such file or directory, (компилируется исходный фа
йл ..\src\Image.cc) [D:\WORK\bothub\discord-base-bot\node_modules\canvas\build\canvas.vcxproj]
D:\WORK\bothub\discord-base-bot\node_modules\canvas\src\CanvasGradient.h(7,10): fatal error C1083: Не удается открыть файл включение: cairo.h: No such file or directory, (компилируется ис
ходный файл ..\src\CanvasGradient.cc) [D:\WORK\bothub\discord-base-bot\node_modules\canvas\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\WORK\\bothub\\discord-base-bot\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=D:\\WORK\\bothub\\discord-base-bot\\node_modules\\canvas\\build\\Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd D:\WORK\bothub\discord-base-bot\node_modules\canvas
gyp ERR! node -v v14.14.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\WORK\bothub\discord-base-bot\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=D:\WORK\bothub\discord-base-bot\node_modules\canvas\build\Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\WORK\bothub\discord-base-bot\node_modules\canvas\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.19041
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\WORK\\bothub\\discord-base-bot\\node_modules\\canvas\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\WORK\bothub\discord-base-bot\node_modules\canvas
node-pre-gyp ERR! node -v v14.14.0
node-pre-gyp ERR! node-pre-gyp -v v0.15.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\WORK\bothub\discord-base-bot\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=D:\WORK\bothub\discord-base-bot\node_modules\canvas\build\Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN discord-base-bot@1.0.0 No description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.7.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ASUS\AppData\Roaming\npm-cache\_logs\2021-04-22T08_40_09_452Z-debug.log
```

**Comment by zbjornson** [comment]
To build from source, you'll need to follow the instructions for compiling in the readme: https://github.com/Automattic/node-canvas#compiling.
