### ISSUE TITLE
rank card error 404

### ISSUE THREAD

**Issue by ManiacKun** [Automattic/node-canvas#1793]
this is the error that i got, the command was working some hours ago then it stopped and gave this error

2021-05-01T15:19:36.836587+00:00 app[Worker.1]: (node:4) UnhandledPromiseRejectionWarning: Error: Server responded with 404
2021-05-01T15:19:36.836614+00:00 app[Worker.1]:     at /app/node_modules/canvas/lib/image.js:56:28
2021-05-01T15:19:36.836615+00:00 app[Worker.1]:     at /app/node_modules/canvas/node_modules/simple-get/index.js:89:7
2021-05-01T15:19:36.836616+00:00 app[Worker.1]:     at PassThrough.<anonymous> (/app/node_modules/simple-concat/index.js:8:13)
2021-05-01T15:19:36.836617+00:00 app[Worker.1]:     at Object.onceWrapper (events.js:421:28)
2021-05-01T15:19:36.836617+00:00 app[Worker.1]:     at PassThrough.emit (events.js:315:20)
2021-05-01T15:19:36.836617+00:00 app[Worker.1]:     at endReadableNT (internal/streams/readable.js:1327:12)
2021-05-01T15:19:36.836618+00:00 app[Worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-05-01T15:19:36.836686+00:00 app[Worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by zbjornson** [comment]
> Server responded with 404

The server you're trying to load the image from is returning 404. This isn't an issue with node-canvas.

**Comment by acarslck** [comment]
![image](https://github.com/Automattic/node-canvas/assets/69026667/e8d0bee1-1405-4125-9661-47022423fe0e)

I have a similar problem, how can I solve it?
