### ISSUE TITLE
Docker build issue

### ISSUE THREAD

**Issue by Rmadhuprasanth** [Automattic/node-canvas#1814]
**Getting below error while taking Docker Build**
Any possible solution would be helpful
thanks

```
#10 103.5 node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v57-linux-musl-x64.tar.gz
#10 103.8 gyp ERR! configure error
#10 103.8 gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
#10 103.8 gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
#10 103.8 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
#10 103.8 gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
#10 103.8 gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
#10 103.8 gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
#10 103.8 gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
#10 103.8 gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
#10 103.8 gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
#10 103.8 gyp ERR! System Linux 5.4.72-microsoft-standard-WSL2
#10 103.8 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/app/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/app/node_modules/canvas/build/Release" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
#10 103.8 gyp ERR! cwd /app/node_modules/canvas
#10 103.8 gyp ERR! node -v v8.16.2
#10 103.8 gyp ERR! node-gyp -v v3.8.0
#10 103.8 gyp ERR! not ok
#10 103.8 node-pre-gyp ERR! build error
#10 103.9 node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/app/node_modules/canvas/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
#10 103.9 node-pre-gyp ERR! stack     at ChildProcess.cmd.on (/app/node_modules/canvas/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)    
#10 103.9 node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
#10 103.9 node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
#10 103.9 node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
#10 103.9 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
#10 103.9 node-pre-gyp ERR! System Linux 5.4.72-microsoft-standard-WSL2
#10 103.9 node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"    
#10 103.9 node-pre-gyp ERR! cwd /app/node_modules/canvas
#10 103.9 node-pre-gyp ERR! node -v v8.16.2
#10 103.9 node-pre-gyp ERR! node-pre-gyp -v v1.0.5
#10 103.9 node-pre-gyp ERR! not ok
#10 103.9 Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/app/node_modules/canvas/build/Release --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
#10 106.4 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
#10 106.4 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
#10 106.4 npm WARN @tensorflow-models/posenet@2.2.2 requires a peer of @tensorflow/tfjs-converter@^3.0.0-rc.1 but none is installed. You must install peer dependencies yourself.
#10 106.4 npm WARN @tensorflow-models/posenet@2.2.2 requires a peer of @tensorflow/tfjs-core@^3.0.0-rc.1 but none is installed. You must install peer dependencies yourself.
#10 106.4 npm WARN ws@7.4.6 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
#10 106.4 npm WARN ws@7.4.6 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
#10 106.4 npm WARN ws@7.2.5 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
#10 106.4 npm WARN ws@7.2.5 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
#10 106.4 npm WARN @apidevtools/swagger-parser@10.0.2 requires a peer of openapi-types@>=7 but none is installed. You must install peer dependencies yourself.
#10 106.4 npm WARN eslint-plugin-jest@24.3.6 requires a peer of @typescript-eslint/eslint-plugin@>= 4 but none is installed. You must install peer dependencies yourself.
#10 106.4 npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
#10 106.4 npm WARN jest-config@26.6.3 requires a peer of ts-node@>=9.0.0 but none is installed. You must install peer dependencies yourself.
#10 106.4
#10 106.4 npm ERR! code ELIFECYCLE
#10 106.4 npm ERR! errno 1
#10 106.4 npm ERR! canvas@2.8.0 install: `node-pre-gyp install --fallback-to-build`
#10 106.4 npm ERR! Exit status 1
#10 106.4 npm ERR!
#10 106.4 npm ERR! Failed at the canvas@2.8.0 install script.
#10 106.4 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#10 109.6
#10 109.6 npm ERR! A complete log of this run can be found in:
#10 109.6 npm ERR!     /root/.npm/_logs/2021-05-27T06_08_00_938Z-debug.log
------
executor failed running [/bin/sh -c npm install]: exit code: 1
```

**Comment by zbjornson** [comment]
> 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v57-linux-musl-x64.tar.gz

Please see the section in #1511 on Alpine linux/musl-libc: prebuilds aren't available for musl, so you'll need to build from source or use a distro that uses glibc.
