### ISSUE TITLE
Problem installing on MacOS with on node13+

### ISSUE THREAD

**Issue by SteffenAnders** [Automattic/node-canvas#1819]
## Issue
I am trying to install canvas on a Mac 10.15.7 with node 13+.
It is working with node10, node11 and node12 without any Problems, but a soon i am trying to install canvas with node12, node13 oder node15 i got follwing error output:

```
❯ npm install canvas

> fsevents@1.2.13 install /Users/sanders/projects/javascript/adup-node-html2image-service/node_modules/glob-watcher/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> canvas@2.5.0 install /Users/sanders/projects/javascript/adup-node-html2image-service/node_modules/color-thief/node_modules/canvas
> node-pre-gyp install --fallback-to-build

  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/backend/Backend.o
../src/backend/Backend.cc:111:10: warning: address of stack memory associated with local variable 'msg' returned [-Wreturn-stack-address]
  return msg.c_str();
         ^~~
1 warning generated.
  CXX(target) Release/obj.target/canvas/src/backend/ImageBackend.o
../src/backend/ImageBackend.cc:68:2: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
        target->Set(v8ctx,
        ^~~~~~~~~~~ ~~~~~~
1 warning generated.
  CXX(target) Release/obj.target/canvas/src/backend/PdfBackend.o
../src/backend/PdfBackend.cc:47:3: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
  target->Set(v8ctx,
  ^~~~~~~~~~~ ~~~~~~
1 warning generated.
  CXX(target) Release/obj.target/canvas/src/backend/SvgBackend.o
../src/backend/SvgBackend.cc:49:3: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
  target->Set(v8ctx,
  ^~~~~~~~~~~ ~~~~~~
1 warning generated.
  CXX(target) Release/obj.target/canvas/src/bmp/BMPParser.o
  CXX(target) Release/obj.target/canvas/src/Backends.o
../src/Backends.cc:18:3: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
  target->Set(v8ctx, Nan::New<String>("Backends").ToLocalChecked(), obj);
  ^~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
  CXX(target) Release/obj.target/canvas/src/Canvas.o
../src/Canvas.cc:327:13: error: no matching member function for call to 'Get'
  if (opts->Get(propName)->IsString()) {
      ~~~~~~^~~
/Users/sanders/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/sanders/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
../src/Canvas.cc:328:22: error: no matching member function for call to 'Get'
    auto val = opts->Get(propName);
               ~~~~~~^~~
/Users/sanders/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/sanders/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
../src/Canvas.cc:337:13: error: no matching member function for call to 'Get'
  if (opts->Get(propName)->IsDate()) {
      ~~~~~~^~~
/Users/sanders/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/sanders/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
../src/Canvas.cc:338:22: error: no matching member function for call to 'Get'
    auto val = opts->Get(propName).As<Date>();
               ~~~~~~^~~
/Users/sanders/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/sanders/Library/Caches/node-gyp/13.14.0/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
4 errors generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/sanders/.nvm/versions/node/v13.14.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/sanders/.nvm/versions/node/v13.14.0/bin/node" "/Users/sanders/.nvm/versions/node/v13.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/sanders/projects/javascript/adup-node-html2image-service/node_modules/color-thief/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/sanders/projects/javascript/adup-node-html2image-service/node_modules/color-thief/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd /Users/sanders/projects/javascript/adup-node-html2image-service/node_modules/color-thief/node_modules/canvas
gyp ERR! node -v v13.14.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/sanders/.nvm/versions/node/v13.14.0/bin/node /Users/sanders/.nvm/versions/node/v13.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/sanders/projects/javascript/adup-node-html2image-service/node_modules/color-thief/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/sanders/projects/javascript/adup-node-html2image-service/node_modules/color-thief/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/sanders/projects/javascript/adup-node-html2image-service/node_modules/color-thief/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 19.6.0
node-pre-gyp ERR! command "/Users/sanders/.nvm/versions/node/v13.14.0/bin/node" "/Users/sanders/projects/javascript/adup-node-html2image-service/node_modules/color-thief/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/sanders/projects/javascript/adup-node-html2image-service/node_modules/color-thief/node_modules/canvas
node-pre-gyp ERR! node -v v13.14.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/Users/sanders/.nvm/versions/node/v13.14.0/bin/node /Users/sanders/.nvm/versions/node/v13.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/sanders/projects/javascript/adup-node-html2image-service/node_modules/color-thief/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/sanders/projects/javascript/adup-node-html2image-service/node_modules/color-thief/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.5.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sanders/.npm/_logs/2021-06-01T16_10_29_878Z-debug.log
```

## Steps to reproduce
```
# does work
nvm install 12
nvm use 12
rm -rf node_modules
npm install canvas

# does not work
nvm install 13
nvm use 13
rm -rf node_modules
npm install canvas
```

## What i have tried so far
```
# clear npm cache
npm cache clean --force  

# remove node_modules folder
rm -rf node_modules 

# (re)installed node-gyp
npm uninstall -g node-gyp
npm install -g node-gyp

# (re)installed required packages
brew upgrade
brew update
brew install pkg-config cairo pango libpng jpeg giflib librsvg

# (re)installed xcode-select
xcode-select --install
```

## Your Environment
* MacOS: 10.15.7
* node 13.14.0 (managed by nvm)
* npm 6.14.4 (managed by nvm)

**Comment by SteffenAnders** [comment]
Can be closed ... an other dependency (color-thief) was using an old version of canvas.
