### ISSUE TITLE
Intermittent npm install failures for node-canvas on Windows

### ISSUE THREAD

**Issue by xonev** [Automattic/node-canvas#1821]
## Issue or Feature

Oftentimes, node-canvas installs on our build servers without issue, but sometimes it fails with the following output:

node-canvas 2.7.0:

```
> canvas@2.7.0 install C:\BuildAgent\work\757a28bcf1240baf\webserver\node_modules\canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! Completion callback never invoked! 
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Users\\Bamboo\\sq\\toolchain\\nodejs-12.13.0-64bit-windows\\files\\node.exe" "C:\\BuildAgent\\work\\757a28bcf1240baf\\webserver\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\BuildAgent\work\757a28bcf1240baf\webserver\node_modules\canvas
node-pre-gyp ERR! node -v v12.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.15.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! canvas@2.7.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the canvas@2.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bamboo\AppData\Roaming\npm-cache\_logs\2021-05-26T14_01_00_442Z-debug.log
```

node-canvas 2.6.1:

```
[18:10:38] :	 [Step 5/13] > canvas@2.6.1 install C:\BuildAgent\work\757a28bcf1240baf\webserver\node_modules\canvas
[18:10:38] :	 [Step 5/13] > node-pre-gyp install --fallback-to-build
[18:10:38] :	 [Step 5/13] 
[18:10:38] :	 [Step 5/13] node-pre-gyp WARN Using request for node-pre-gyp https download 
[18:11:04] :	 [Step 5/13] node-pre-gyp WARN Pre-built binaries not installable for canvas@2.6.1 and node@12.13.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
[18:11:04] :	 [Step 5/13] node-pre-gyp WARN Hit error read ECONNRESET 
[18:13:02] :	 [Step 5/13] gyp ERR! clean error 
[18:13:02] :	 [Step 5/13] gyp ERR! stack Error: EPERM: operation not permitted, unlink 'C:\BuildAgent\work\757a28bcf1240baf\webserver\node_modules\canvas\build\Release\obj\canvas\CanvasGradient.obj'
[18:13:02] :	 [Step 5/13] gyp ERR! System Windows_NT 6.3.9600
[18:13:02] :	 [Step 5/13] gyp ERR! command "C:\\Users\\Bamboo\\sq\\toolchain\\nodejs-12.13.0-64bit-windows\\files\\node.exe" "C:\\Users\\Bamboo\\sq\\toolchain\\nodejs-12.13.0-64bit-windows\\files\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "clean"
[18:13:02] :	 [Step 5/13] gyp ERR! cwd C:\BuildAgent\work\757a28bcf1240baf\webserver\node_modules\canvas
[18:13:02] :	 [Step 5/13] gyp ERR! node -v v12.13.0
[18:13:02] :	 [Step 5/13] gyp ERR! node-gyp -v v5.0.5
[18:13:02] :	 [Step 5/13] gyp ERR! not ok 
[18:13:02] :	 [Step 5/13] node-pre-gyp ERR! build error 
[18:13:02] :	 [Step 5/13] node-pre-gyp ERR! stack Error: Failed to execute 'C:\Users\Bamboo\sq\toolchain\nodejs-12.13.0-64bit-windows\files\node.exe C:\Users\Bamboo\sq\toolchain\nodejs-12.13.0-64bit-windows\files\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js clean' (1)
[18:13:02] :	 [Step 5/13] node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\BuildAgent\work\757a28bcf1240baf\webserver\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
[18:13:02] :	 [Step 5/13] node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
[18:13:02] :	 [Step 5/13] node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
[18:13:02] :	 [Step 5/13] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[18:13:02] :	 [Step 5/13] node-pre-gyp ERR! System Windows_NT 6.3.9600
[18:13:02] :	 [Step 5/13] node-pre-gyp ERR! command "C:\\Users\\Bamboo\\sq\\toolchain\\nodejs-12.13.0-64bit-windows\\files\\node.exe" "C:\\BuildAgent\\work\\757a28bcf1240baf\\webserver\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
[18:13:02] :	 [Step 5/13] node-pre-gyp ERR! cwd C:\BuildAgent\work\757a28bcf1240baf\webserver\node_modules\canvas
[18:13:02] :	 [Step 5/13] node-pre-gyp ERR! node -v v12.13.0
[18:13:02] :	 [Step 5/13] node-pre-gyp ERR! node-pre-gyp -v v0.11.0
[18:13:02] :	 [Step 5/13] node-pre-gyp ERR! not ok 
[18:13:02] :	 [Step 5/13] Failed to execute 'C:\Users\Bamboo\sq\toolchain\nodejs-12.13.0-64bit-windows\files\node.exe C:\Users\Bamboo\sq\toolchain\nodejs-12.13.0-64bit-windows\files\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js clean' (1)
[18:13:02] :	 [Step 5/13] npm ERR! code ELIFECYCLE
[18:13:02] :	 [Step 5/13] npm ERR! errno 1
[18:13:02] :	 [Step 5/13] npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
[18:13:02] :	 [Step 5/13] npm ERR! Exit status 1
[18:13:02] :	 [Step 5/13] npm ERR! 
[18:13:02] :	 [Step 5/13] npm ERR! Failed at the canvas@2.6.1 install script.
[18:13:02] :	 [Step 5/13] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[18:13:02] :	 [Step 5/13] 
[18:13:02] :	 [Step 5/13] npm ERR! A complete log of this run can be found in:
[18:13:02] :	 [Step 5/13] npm ERR!     C:\Users\Bamboo\AppData\Roaming\npm-cache\_logs\2021-01-29T02_13_02_558Z-debug.log
```

## Steps to Reproduce

- Add canvas 2.7.0 to package.json on Windows
- Run `npm install`

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): 2.7.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Windows_NT 6.3.9600, node 12.13.0

**Comment by xonev** [comment]
I believe that this error is caused by the pre-built binaries not being available. This triggers a fallback to building from source, which also fails.

node-pre-gyp specifically recommends against hosting pre-built binaries on Github (which might be part of the issue): https://github.com/mapbox/node-pre-gyp#host.

**Comment by xonev** [comment]
I am trying an upgrade to 2.8.0 to see if that helps, but I doubt it will since our build machines aren't configured to build the canvas binary and I doubt that the upgrade will improve the availability of the binaries from Github.

**Comment by zbjornson** [comment]
That looks like a spotty connection to GitHub based on the `ECONNRESET`. Is this still happening somewhat consistently?

**Comment by SkiBum326** [comment]
I wanted to note that I'm also experiencing the same issue when trying to install canvas on Windows:

 npm install

> CirkitStudio@0.5.4 postinstall C:\Users\Austin\Documents\git_repositories\ravendesktop
> electron-builder install-app-deps

  • electron-builder  version=22.9.1
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=canvas@2.8.0 platform=win32 arch=x64
  ⨯ cannot execute  cause=exit status 1
                    out=
    > canvas@2.8.0 install C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas
    > node-pre-gyp install --fallback-to-build

    Warning: Missing input files:
    C:\GTK\bin\libpangoft2-1.0-0.dll
    C:\GTK\bin\libfreetype-6.dll
    C:\GTK\bin\libpangowin32-1.0-0.dll
    C:\GTK\bin\zlib1.dll
    C:\GTK\bin\libgobject-2.0-0.dll
    C:\GTK\bin\libfontconfig-1.dll
    C:\GTK\bin\libpng14-14.dll
    C:\GTK\bin\libglib-2.0-0.dll
    C:\GTK\bin\libgthread-2.0-0.dll
    C:\GTK\bin\libexpat-1.dll
    C:\GTK\bin\libpango-1.0-0.dll
    C:\GTK\bin\libintl-8.dll
    C:\GTK\bin\libcairo-2.dll
    C:\GTK\bin\libpangocairo-1.0-0.dll
    C:\GTK\bin\libgmodule-2.0-0.dll
    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
      Backend.cc
      ImageBackend.cc
      PdfBackend.cc
      SvgBackend.cc
      BMPParser.cc
      Backends.cc
      Canvas.cc
      CanvasGradient.cc
      CanvasPattern.cc
      CanvasRenderingContext2d.cc
      closure.cc
      color.cc
    c:\users\austin\documents\git_repositories\ravendesktop\node_modules\canvas\src\backend\backend.h(3): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\backend\Backend.cc) [C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\canvas.vcxproj]
      Image.cc
    c:\users\austin\documents\git_repositories\ravendesktop\node_modules\canvas\src\backend\backend.h(3): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\backend\SvgBackend.cc) [C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\canvas.vcxproj]
    c:\users\austin\documents\git_repositories\ravendesktop\node_modules\canvas\src\backend\backend.h(3): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\backend\PdfBackend.cc) [C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\canvas.vcxproj]
    c:\users\austin\documents\git_repositories\ravendesktop\node_modules\canvas\src\backend\backend.h(3): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\backend\ImageBackend.cc) [C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\canvas.vcxproj]
      ImageData.cc
      init.cc
    c:\users\austin\documents\git_repositories\ravendesktop\node_modules\canvas\src\backend\backend.h(3): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Canvas.cc) [C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\canvas.vcxproj]
    c:\users\austin\documents\git_repositories\ravendesktop\node_modules\canvas\src\canvasrenderingcontext2d.h(5): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\CanvasRenderingContext2d.cc) [C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\canvas.vcxproj]
      register_font.cc
    c:\users\austin\documents\git_repositories\ravendesktop\node_modules\canvas\src\backend\backend.h(3): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\closure.cc) [C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\canvas.vcxproj]
    c:\users\austin\documents\git_repositories\ravendesktop\node_modules\canvas\src\canvaspattern.h(5): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\CanvasPattern.cc) [C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\canvas.vcxproj]
      win_delay_load_hook.cc
    c:\users\austin\documents\git_repositories\ravendesktop\node_modules\canvas\src\backend\backend.h(3): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Backends.cc) [C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\canvas.vcxproj]
    c:\users\austin\documents\git_repositories\ravendesktop\node_modules\canvas\src\register_font.h(3): fatal error C1083: Cannot open include file: 'pango/pango.h': No such file or directory (compiling source file ..\src\register_font.cc) [C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\canvas.vcxproj]
    c:\users\austin\documents\git_repositories\ravendesktop\node_modules\canvas\src\image.h(5): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Image.cc) [C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\canvas.vcxproj]
    c:\users\austin\documents\git_repositories\ravendesktop\node_modules\canvas\src\init.cc(4): fatal error C1083: Cannot open include file: 'pango/pango.h': No such file or directory [C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\canvas.vcxproj]
    c:\users\austin\.electron-gyp\9.0.5\include\node\v8.h(9116): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version. (compiling source file ..\src\ImageData.cc) [C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\canvas.vcxproj]
      c:\users\austin\.electron-gyp\9.0.5\include\node\v8.h(7345): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\ImageData.cc)
    c:\users\austin\.electron-gyp\9.0.5\include\node\v8.h(9124): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version. (compiling source file ..\src\ImageData.cc) [C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\canvas.vcxproj]
      c:\users\austin\.electron-gyp\9.0.5\include\node\v8.h(7345): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\ImageData.cc)
    c:\users\austin\.electron-gyp\9.0.5\include\node\v8.h(9116): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version. (compiling source file ..\src\CanvasGradient.cc) [C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\canvas.vcxproj]
      c:\users\austin\.electron-gyp\9.0.5\include\node\v8.h(7345): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\CanvasGradient.cc)
    c:\users\austin\.electron-gyp\9.0.5\include\node\v8.h(9124): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version. (compiling source file ..\src\CanvasGradient.cc) [C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\canvas.vcxproj]
      c:\users\austin\.electron-gyp\9.0.5\include\node\v8.h(7345): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\CanvasGradient.cc)
    c:\users\austin\documents\git_repositories\ravendesktop\node_modules\canvas\src\util.h(31): error C2039: 'toupper': is not a member of 'std' (compiling source file ..\src\ImageData.cc) [C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\canvas.vcxproj]
      c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.16.27023\include\queue(451): note: see declaration of 'std' (compiling source file ..\src\ImageData.cc)
    c:\users\austin\documents\git_repositories\ravendesktop\node_modules\canvas\src\canvasgradient.h(7): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\CanvasGradient.cc) [C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\canvas.vcxproj]
    Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v9.0' (1)

                    errorOut=node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-electron-v9.0-win32-unknown-x64.tar.gz
    node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and electron@9.0.5 (electron-v9.0 ABI, unknown) (falling back to source compile with node-gyp)
    node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-electron-v9.0-win32-unknown-x64.tar.gz
    gyp ERR! build error
    gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    gyp ERR! System Windows_NT 10.0.19041
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Austin\\Documents\\git_repositories\\ravendesktop\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\Austin\\Documents\\git_repositories\\ravendesktop\\node_modules\\canvas\\build\\Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v9.0"
    gyp ERR! cwd C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas
    gyp ERR! node -v v12.18.3
    gyp ERR! node-gyp -v v5.1.0
    gyp ERR! not ok
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas\build\Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v9.0' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Austin\Documents\git_repositories\RavenDesktop\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    node-pre-gyp ERR! System Windows_NT 10.0.19041
    node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Austin\\Documents\\git_repositories\\RavenDesktop\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd C:\Users\Austin\Documents\git_repositories\ravendesktop\node_modules\canvas
    node-pre-gyp ERR! node -v v12.18.3
    node-pre-gyp ERR! node-pre-gyp -v v1.0.5
    node-pre-gyp ERR! not ok
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! canvas@2.8.0 install: `node-pre-gyp install --fallback-to-build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the canvas@2.8.0 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\Austin\AppData\Roaming\npm-cache\_logs\2021-06-14T18_55_22_927Z-debug.log

                    command='C:\Program Files\nodejs\node.exe' 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js' rebuild canvas@2.8.0
                    workingDir=
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! CirkitStudio@0.5.4 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the CirkitStudio@0.5.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Austin\AppData\Roaming\npm-cache\_logs\2021-06-14T18_55_23_069Z-debug.log

**Comment by michael-letcher** [comment]
I also cannot install (on Mac).

v2.5.0 - v2.6.1 are no good.

v2.7.0 & v2.8.0 onwards are working

**Comment by lukebatchelor** [comment]
Had the same issues. Downgrading node from 14 to 12 fixed it for me. Also on Mac 10.15.7
