### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Zalleya** [Automattic/node-canvas#1831]
return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified procedure could not be found.
\\?\c:\me\node_modules\canvas\build\Release\canvas.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (c:\me\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)

**Comment by oallouch** [comment]
Same here
Try canvas 2.6

**Comment by Zalleya** [comment]
can help? yesterday it can be opened. now can't
[ERROR] Error: ENOENT, No such file or directory 'ERROR: 401'
    at setSource (c:\p\node_modules\canvas\lib\image.js:91:13)
    at Image.set (c:\p\node_modules\canvas\lib\image.js:62:9)
    at c:\p\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at Object.loadImage (c:\p\node_modules\canvas\index.js:23:10)
    at Welcome.toAttachment (c:\p\function\discord-canvas-balance\src\greetings\Base.js:152:37)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async msgHandler (c:\p\message\geps.js:1119:39) {
  errno: 2,
  code: 'ENOENT',
  path: 'ERROR: 401',
  syscall: 'fopen'
}
