### ISSUE TITLE
`GLIBC_2.18' not found

### ISSUE THREAD

**Issue by AdamBCo** [Automattic/node-canvas#1842]
I am currently using [chartjs-node-canvas](https://github.com/SeanSobey/ChartjsNodeCanvas), which relies on [Chart.js](https://github.com/chartjs/Chart.js). Locally everything works, but whenever I deploy my node application to AWS, I get the following crash. I already reported this [issue](https://github.com/chartjs/Chart.js/issues/9304#issuecomment-866496407) to Chart.js but was referred to node-canvas as the potential problem. Any help resolving this issue would be greatly appreciated. Thanks in advance!

## Issue or Feature

```js
internal/modules/cjs/loader.js:1057
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /var/app/current/node_modules/canvas/build/Release/librsvg-2.so.2)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/app/current/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/app/current/node_modules/canvas/lib/canvas.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/app/current/node_modules/canvas/index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

## Steps to Reproduce

1. `npm install chartjs-node-canvas chart.js`
2. Deploy to AWS elastic beanstalk
3. App crashes with the error above.

## AWS Environment
* Chart.js: 2.9.4
* Node: 12.21.0

## Local Environment
* Chart.js: 2.9.4
* Node: v14.16.0

**Comment by meetpaija** [comment]
Hey @zbjornson , do we have any updates here?
I'm also facing the same in AWS elastic beanstalk

**Comment by iodev** [comment]
Any suggestions on adding the glibc 2.18? Is it just that librsvg didn't get the message that these are not the droids it's looking for?

```
[ec2-user@ip-0-0-0-0 myproject]$ ldd node_modules/canvas/build/Release/canvas.node
node_modules/canvas/build/Release/canvas.node: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/librsvg-2.so.2)
node_modules/canvas/build/Release/canvas.node: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libstdc++.so.6)
	linux-vdso.so.1 =>  (0x00007ffcd0194000)
	libpixman-1.so.0 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libpixman-1.so.0 (0x00007ff95f9ac000)
	libcairo.so.2 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libcairo.so.2 (0x00007ff95f6b7000)
	libpng16.so.16 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libpng16.so.16 (0x00007ff95f482000)
	libz.so.1 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libz.so.1 (0x00007ff95f265000)
	libpangocairo-1.0.so.0 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libpangocairo-1.0.so.0 (0x00007ff95f055000)
	libpango-1.0.so.0 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libpango-1.0.so.0 (0x00007ff95ee03000)
	libgobject-2.0.so.0 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libgobject-2.0.so.0 (0x00007ff95eba0000)
	libglib-2.0.so.0 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libglib-2.0.so.0 (0x00007ff95e869000)
	libharfbuzz.so.0 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libharfbuzz.so.0 (0x00007ff95e55b000)
	libfreetype.so.6 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libfreetype.so.6 (0x00007ff95e2ad000)
	librsvg-2.so.2 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/librsvg-2.so.2 (0x00007ff95d6b4000)
	libgio-2.0.so.0 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libgio-2.0.so.0 (0x00007ff95d2d2000)
	libgdk_pixbuf-2.0.so.0 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libgdk_pixbuf-2.0.so.0 (0x00007ff95d0ab000)
	libjpeg.so.62 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libjpeg.so.62 (0x00007ff95ce11000)
	libgif.so.7 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libgif.so.7 (0x00007ff95cc07000)
	libstdc++.so.6 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libstdc++.so.6 (0x00007ff95c843000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ff95c541000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff95c32b000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff95c10f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff95bd41000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff95fea7000)
	libfontconfig.so.1 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libfontconfig.so.1 (0x00007ff95bafc000)
	librt.so.1 => /lib64/librt.so.1 (0x00007ff95b8f4000)
	libpangoft2-1.0.so.0 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libpangoft2-1.0.so.0 (0x00007ff95b6db000)
	libfribidi.so.0 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libfribidi.so.0 (0x00007ff95b4be000)
	libffi.so.7 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libffi.so.7 (0x00007ff95b2b1000)
	libpcre.so.1 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libpcre.so.1 (0x00007ff95b06c000)
	libcairo-gobject.so.2 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libcairo-gobject.so.2 (0x00007ff95ae62000)
	libxml2.so.2 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libxml2.so.2 (0x00007ff95aafa000)
	libexpat.so.1 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libexpat.so.1 (0x00007ff95a8cf000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007ff95a6cb000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ff95a4c7000)
	libgmodule-2.0.so.0 => /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/libgmodule-2.0.so.0 (0x00007ff95a2c2000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007ff95a0a8000)
[ec2-user@ip-0-0-0-0 myproject]$ node_modules/canvas/build/Release/canvas.node --help
Segmentation fault
[ec2-user@ip-0-0-0-0 myproject]$ cd node_modules/canvas/build/Release/ 
[ec2-user@ip-0-0-0-0 Release]$ gdb canvas.node
GNU gdb (GDB) Amazon Linux (7.6.1-64.33.amzn1)
Reading symbols from /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/canvas.node...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/ec2-user/dev/myproject/node_modules/canvas/build/Release/canvas.node 

Program received signal SIGSEGV, Segmentation fault.
0x0000000000013f36 in ?? ()
(gdb) bt
#0  0x0000000000013f36 in ?? ()
#1  0x00007ffff7dc3913 in SvgBackend::createSurface() [clone .part.23] ()
```
