### ISSUE TITLE
Terminal Installation Error !!

### ISSUE THREAD

**Issue by iamAlex107** [Automattic/node-canvas#1850]
So, I have tried all the installation procedure's stated in the wiki, but to no avail I was still getting while installing **Canvas** through **terminal of nodejs**. I have also faced this issue while downloading another package which was dependent on **Canvas** to work.

**OS:** Windows 10 20H2
**NodeJS:** v14.7.5
**Canvas Version (which I tried to install):** 2.8.0

Here is the error code:
```PS C:\Users\acer\Documents\Mod Bot> npm i canvas

> canvas@2.8.0 install C:\Users\acer\Documents\Mod Bot\node_modules\canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-win32-unknown-ia32.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@14.17.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-win32-unknown-ia32.tar.gz 
Warning: Missing input files:
C:\GTK\bin\libfreetype-6.dll
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libgthread-2.0-0.dll
C:\GTK\bin\libglib-2.0-0.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpango-1.0-0.dll
C:\GTK\bin\libintl-8.dll
C:\GTK\bin\libpangoft2-1.0-0.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libpangowin32-1.0-0.dll
C:\GTK\bin\libgmodule-2.0-0.dll
C:\GTK\bin\libpangocairo-1.0-0.dll
C:\GTK\bin\libgobject-2.0-0.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  ImageBackend.cc
  Backend.cc
  PdfBackend.cc
  SvgBackend.cc
C:\Users\acer\Documents\Mod Bot\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Cannot open include file: 'cairo.h': No such 
file or directory (compiling source file ..\src\backend\Backend.cc) [C:\Users\acer\Documents\Mod Bot\node_modules\canvas\build\canvas.vcxproj]
C:\Users\acer\Documents\Mod Bot\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Cannot open include file: 'cairo.h': No such 
file or directory (compiling source file ..\src\backend\PdfBackend.cc) [C:\Users\acer\Documents\Mod Bot\node_modules\canvas\build\canvas.vcxproj]
C:\Users\acer\Documents\Mod Bot\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Cannot open include file: 'cairo.h': No such 
file or directory (compiling source file ..\src\backend\SvgBackend.cc) [C:\Users\acer\Documents\Mod Bot\node_modules\canvas\build\canvas.vcxproj]
C:\Users\acer\Documents\Mod Bot\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Cannot open include file: 'cairo.h': No such 
file or directory (compiling source file ..\src\backend\ImageBackend.cc) [C:\Users\acer\Documents\Mod Bot\node_modules\canvas\build\canvas.vcxpro
j]
  BMPParser.cc
  Backends.cc
  Canvas.cc
  CanvasGradient.cc
C:\Users\acer\Documents\Mod Bot\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Cannot open include file: 'cairo.h': No such 
file or directory (compiling source file ..\src\Backends.cc) [C:\Users\acer\Documents\Mod Bot\node_modules\canvas\build\canvas.vcxproj]
C:\Users\acer\Documents\Mod Bot\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Cannot open include file: 'cairo.h': No such 
file or directory (compiling source file ..\src\Canvas.cc) [C:\Users\acer\Documents\Mod Bot\node_modules\canvas\build\canvas.vcxproj]
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
C:\Users\acer\Documents\Mod Bot\node_modules\canvas\src\CanvasPattern.h(5,10): fatal error C1083: Cannot open include file: 'cairo.h': No such fi
le or directory (compiling source file ..\src\CanvasPattern.cc) [C:\Users\acer\Documents\Mod Bot\node_modules\canvas\build\canvas.vcxproj]
C:\Users\acer\Documents\Mod Bot\node_modules\canvas\src\CanvasRenderingContext2d.h(5,10): fatal error C1083: Cannot open include file: 'cairo.h':
 No such file or directory (compiling source file ..\src\CanvasRenderingContext2d.cc) [C:\Users\acer\Documents\Mod Bot\node_modules\canvas\build\
canvas.vcxproj]
  closure.cc
  color.cc
C:\Users\acer\Documents\Mod Bot\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Cannot open include file: 'cairo.h': No such  
file or directory (compiling source file ..\src\closure.cc) [C:\Users\acer\Documents\Mod Bot\node_modules\canvas\build\canvas.vcxproj]
  Image.cc
C:\Users\acer\Documents\Mod Bot\node_modules\canvas\src\Image.h(5,10): fatal error C1083: Cannot open include file: 'cairo.h': No such file or di 
rectory (compiling source file ..\src\Image.cc) [C:\Users\acer\Documents\Mod Bot\node_modules\canvas\build\canvas.vcxproj]
  ImageData.cc
C:\Users\acer\Documents\Mod Bot\node_modules\canvas\src\bmp\BMPParser.cc(186,3): warning C4018: '>': signed/unsigned mismatch [C:\Users\acer\Docu
ments\Mod Bot\node_modules\canvas\build\canvas.vcxproj]
C:\Users\acer\Documents\Mod Bot\node_modules\canvas\src\bmp\BMPParser.cc(201,3): warning C4018: '>': signed/unsigned mismatch [C:\Users\acer\Docu
ments\Mod Bot\node_modules\canvas\build\canvas.vcxproj]
C:\Users\acer\Documents\Mod Bot\node_modules\canvas\src\CanvasGradient.h(7,10): fatal error C1083: Cannot open include file: 'cairo.h': No such f
ile or directory (compiling source file ..\src\CanvasGradient.cc) [C:\Users\acer\Documents\Mod Bot\node_modules\canvas\build\canvas.vcxproj]
  init.cc
C:\Users\acer\Documents\Mod Bot\node_modules\canvas\src\init.cc(4,10): fatal error C1083: Cannot open include file: 'pango/pango.h': No such file
 or directory [C:\Users\acer\Documents\Mod Bot\node_modules\canvas\build\canvas.vcxproj]
  register_font.cc
C:\Users\acer\Documents\Mod Bot\node_modules\canvas\src\register_font.h(3,10): fatal error C1083: Cannot open include file: 'pango/pango.h': No s
uch file or directory (compiling source file ..\src\register_font.cc) [C:\Users\acer\Documents\Mod Bot\node_modules\canvas\build\canvas.vcxproj]
  win_delay_load_hook.cc
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\acer\\Documents\\Mod Bot\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\acer\\Documents\\Mod Bot\\node_modules\\canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd C:\Users\acer\Documents\Mod Bot\node_modules\canvas
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\acer\Documents\Mod Bot\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\acer\Documents\Mod Bot\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\acer\Documents\Mod Bot\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.19043
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\acer\\Documents\\Mod Bot\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\acer\Documents\Mod Bot\node_modules\canvas
node-pre-gyp ERR! node -v v14.17.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.5
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\acer\Documents\Mod Bot\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\acer\Documents\Mod Bot\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN averion@1.1.5 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.8.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by iamAlex107** [comment]
i have found the issue. it was my node bit version (actually it should be 64bit instead of 32bit)
