### ISSUE TITLE
Canvas cannot be installed on openwrt

### ISSUE THREAD

**Issue by ITdesk01** [Automattic/node-canvas#1854]
```
root@OpenWrt:~# npm install canvas
npm info it worked if it ends with ok
npm info using npm@6.14.13
npm info using node@v14.17.1
npm http fetch GET 304 https://registry.npmjs.org/canvas 895ms (from cache)
npm timing stage:loadCurrentTree Completed in 954ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
npm http fetch GET 304 https://registry.npmjs.org/nan 247ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-get 612ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@mapbox%2fnode-pre-gyp 3501ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/npmlog 47ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/https-proxy-agent 278ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/make-dir 279ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/detect-libc 286ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/semver 646ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-fetch 656ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nopt 659ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar 657ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/rimraf 778ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/agent-base 239ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/debug 243ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ms 226ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/abbrev 225ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/are-we-there-yet 282ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/set-blocking 281ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/gauge 288ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/console-control-strings 294ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 242ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/delegates 253ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/core-util-is 318ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/inherits 320ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/process-nextick-args 321ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string_decoder 320ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/isarray 324ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/safe-buffer 322ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/util-deprecate 325ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/aproba 18ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string-width 277ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/object-assign 279ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wide-align 281ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/strip-ansi 282ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/has-unicode 285ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/signal-exit 287ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-fullwidth-code-point 242ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/code-point-at 255ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/number-is-nan 229ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ansi-regex 231ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/glob 218ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs.realpath 287ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/once 286ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/inflight 290ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minimatch 290ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/path-is-absolute 292ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wrappy 221ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/brace-expansion 222ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/balanced-match 233ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/concat-map 235ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lru-cache 214ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/yallist 216ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chownr 270ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-minipass 276ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minipass 276ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mkdirp 276ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minizlib 282ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/simple-concat 233ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/decompress-response 238ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/mimic-response 217ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 9559ms
npm timing stage:loadIdealTree Completed in 9628ms
npm timing stage:generateActionsToTake Completed in 18ms
npm timing action:extract Completed in 387ms
npm timing action:finalize Completed in 59ms
npm timing audit submit Completed in 610ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 610ms
npm timing audit body Completed in 1ms
npm timing action:refresh-package-json Completed in 178ms
npm info lifecycle abbrev@1.1.1~preinstall: abbrev@1.1.1
npm info lifecycle ansi-regex@2.1.1~preinstall: ansi-regex@2.1.1
npm info lifecycle aproba@1.2.0~preinstall: aproba@1.2.0
npm info lifecycle balanced-match@1.0.2~preinstall: balanced-match@1.0.2
npm info lifecycle chownr@2.0.0~preinstall: chownr@2.0.0
npm info lifecycle code-point-at@1.1.0~preinstall: code-point-at@1.1.0
npm info lifecycle concat-map@0.0.1~preinstall: concat-map@0.0.1
npm info lifecycle brace-expansion@1.1.11~preinstall: brace-expansion@1.1.11
npm info lifecycle console-control-strings@1.1.0~preinstall: console-control-strings@1.1.0
npm info lifecycle core-util-is@1.0.2~preinstall: core-util-is@1.0.2
npm info lifecycle delegates@1.0.0~preinstall: delegates@1.0.0
npm info lifecycle detect-libc@1.0.3~preinstall: detect-libc@1.0.3
npm info lifecycle fs.realpath@1.0.0~preinstall: fs.realpath@1.0.0
npm info lifecycle has-unicode@2.0.1~preinstall: has-unicode@2.0.1
npm info lifecycle inherits@2.0.4~preinstall: inherits@2.0.4
npm info lifecycle isarray@1.0.0~preinstall: isarray@1.0.0
npm info lifecycle semver@6.3.0~preinstall: semver@6.3.0
npm info lifecycle make-dir@3.1.0~preinstall: make-dir@3.1.0
npm info lifecycle mimic-response@2.1.0~preinstall: mimic-response@2.1.0
npm info lifecycle decompress-response@4.2.1~preinstall: decompress-response@4.2.1
npm info lifecycle minimatch@3.0.4~preinstall: minimatch@3.0.4
npm info lifecycle mkdirp@1.0.4~preinstall: mkdirp@1.0.4
npm info lifecycle ms@2.1.2~preinstall: ms@2.1.2
npm info lifecycle debug@4.3.2~preinstall: debug@4.3.2
npm info lifecycle agent-base@6.0.2~preinstall: agent-base@6.0.2
npm info lifecycle https-proxy-agent@5.0.0~preinstall: https-proxy-agent@5.0.0
npm info lifecycle node-fetch@2.6.1~preinstall: node-fetch@2.6.1
npm info lifecycle nopt@5.0.0~preinstall: nopt@5.0.0
npm info lifecycle number-is-nan@1.0.1~preinstall: number-is-nan@1.0.1
npm info lifecycle is-fullwidth-code-point@1.0.0~preinstall: is-fullwidth-code-point@1.0.0
npm info lifecycle object-assign@4.1.1~preinstall: object-assign@4.1.1
npm info lifecycle path-is-absolute@1.0.1~preinstall: path-is-absolute@1.0.1
npm info lifecycle process-nextick-args@2.0.1~preinstall: process-nextick-args@2.0.1
npm info lifecycle safe-buffer@5.1.2~preinstall: safe-buffer@5.1.2
npm info lifecycle set-blocking@2.0.0~preinstall: set-blocking@2.0.0
npm info lifecycle signal-exit@3.0.3~preinstall: signal-exit@3.0.3
npm info lifecycle simple-concat@1.0.1~preinstall: simple-concat@1.0.1
npm info lifecycle string_decoder@1.1.1~preinstall: string_decoder@1.1.1
npm info lifecycle strip-ansi@3.0.1~preinstall: strip-ansi@3.0.1
npm info lifecycle string-width@1.0.2~preinstall: string-width@1.0.2
npm info lifecycle util-deprecate@1.0.2~preinstall: util-deprecate@1.0.2
npm info lifecycle readable-stream@2.3.7~preinstall: readable-stream@2.3.7
npm info lifecycle are-we-there-yet@1.1.5~preinstall: are-we-there-yet@1.1.5
npm info lifecycle wide-align@1.1.3~preinstall: wide-align@1.1.3
npm info lifecycle gauge@2.7.4~preinstall: gauge@2.7.4
npm info lifecycle npmlog@4.1.2~preinstall: npmlog@4.1.2
npm info lifecycle wrappy@1.0.2~preinstall: wrappy@1.0.2
npm info lifecycle once@1.4.0~preinstall: once@1.4.0
npm info lifecycle inflight@1.0.6~preinstall: inflight@1.0.6
npm info lifecycle glob@7.1.7~preinstall: glob@7.1.7
npm info lifecycle canvas@2.8.0~preinstall: canvas@2.8.0
npm info lifecycle simple-get@3.1.0~preinstall: simple-get@3.1.0
npm info lifecycle nan@2.14.2~preinstall: nan@2.14.2
npm info lifecycle @mapbox/node-pre-gyp@1.0.5~preinstall: @mapbox/node-pre-gyp@1.0.5
npm info lifecycle tar@6.1.0~preinstall: tar@6.1.0
npm info lifecycle minizlib@2.1.2~preinstall: minizlib@2.1.2
npm info lifecycle fs-minipass@2.1.0~preinstall: fs-minipass@2.1.0
npm info lifecycle minipass@3.1.3~preinstall: minipass@3.1.3
npm info lifecycle semver@7.3.5~preinstall: semver@7.3.5
npm info lifecycle lru-cache@6.0.0~preinstall: lru-cache@6.0.0
npm info lifecycle yallist@4.0.0~preinstall: yallist@4.0.0
npm info lifecycle rimraf@3.0.2~preinstall: rimraf@3.0.2
npm timing action:preinstall Completed in 15ms
npm info linkStuff abbrev@1.1.1
npm info linkStuff ansi-regex@2.1.1
npm info linkStuff aproba@1.2.0
npm info linkStuff balanced-match@1.0.2
npm info linkStuff chownr@2.0.0
npm info linkStuff code-point-at@1.1.0
npm info linkStuff concat-map@0.0.1
npm info linkStuff brace-expansion@1.1.11
npm info linkStuff console-control-strings@1.1.0
npm info linkStuff core-util-is@1.0.2
npm info linkStuff delegates@1.0.0
npm info linkStuff detect-libc@1.0.3
npm info linkStuff fs.realpath@1.0.0
npm info linkStuff has-unicode@2.0.1
npm info linkStuff inherits@2.0.4
npm info linkStuff isarray@1.0.0
npm info linkStuff semver@6.3.0
npm info linkStuff make-dir@3.1.0
npm info linkStuff mimic-response@2.1.0
npm info linkStuff decompress-response@4.2.1
npm info linkStuff minimatch@3.0.4
npm info linkStuff mkdirp@1.0.4
npm info linkStuff ms@2.1.2
npm info linkStuff debug@4.3.2
npm info linkStuff agent-base@6.0.2
npm info linkStuff https-proxy-agent@5.0.0
npm info linkStuff node-fetch@2.6.1
npm info linkStuff nopt@5.0.0
npm info linkStuff number-is-nan@1.0.1
npm info linkStuff is-fullwidth-code-point@1.0.0
npm info linkStuff object-assign@4.1.1
npm info linkStuff path-is-absolute@1.0.1
npm info linkStuff process-nextick-args@2.0.1
npm info linkStuff safe-buffer@5.1.2
npm info linkStuff set-blocking@2.0.0
npm info linkStuff signal-exit@3.0.3
npm info linkStuff simple-concat@1.0.1
npm info linkStuff string_decoder@1.1.1
npm info linkStuff strip-ansi@3.0.1
npm info linkStuff string-width@1.0.2
npm info linkStuff util-deprecate@1.0.2
npm info linkStuff readable-stream@2.3.7
npm info linkStuff are-we-there-yet@1.1.5
npm info linkStuff wide-align@1.1.3
npm info linkStuff gauge@2.7.4
npm info linkStuff npmlog@4.1.2
npm info linkStuff wrappy@1.0.2
npm info linkStuff once@1.4.0
npm info linkStuff inflight@1.0.6
npm info linkStuff glob@7.1.7
npm info linkStuff rimraf@3.0.2
npm info linkStuff yallist@4.0.0
npm info linkStuff lru-cache@6.0.0
npm info linkStuff semver@7.3.5
npm info linkStuff minipass@3.1.3
npm info linkStuff fs-minipass@2.1.0
npm info linkStuff minizlib@2.1.2
npm info linkStuff tar@6.1.0
npm info linkStuff @mapbox/node-pre-gyp@1.0.5
npm info linkStuff nan@2.14.2
npm info linkStuff simple-get@3.1.0
npm info linkStuff canvas@2.8.0
npm timing action:build Completed in 36ms
npm info lifecycle abbrev@1.1.1~install: abbrev@1.1.1
npm info lifecycle ansi-regex@2.1.1~install: ansi-regex@2.1.1
npm info lifecycle aproba@1.2.0~install: aproba@1.2.0
npm info lifecycle balanced-match@1.0.2~install: balanced-match@1.0.2
npm info lifecycle chownr@2.0.0~install: chownr@2.0.0
npm info lifecycle code-point-at@1.1.0~install: code-point-at@1.1.0
npm info lifecycle concat-map@0.0.1~install: concat-map@0.0.1
npm info lifecycle brace-expansion@1.1.11~install: brace-expansion@1.1.11
npm info lifecycle console-control-strings@1.1.0~install: console-control-strings@1.1.0
npm info lifecycle core-util-is@1.0.2~install: core-util-is@1.0.2
npm info lifecycle delegates@1.0.0~install: delegates@1.0.0
npm info lifecycle detect-libc@1.0.3~install: detect-libc@1.0.3
npm info lifecycle fs.realpath@1.0.0~install: fs.realpath@1.0.0
npm info lifecycle has-unicode@2.0.1~install: has-unicode@2.0.1
npm info lifecycle inherits@2.0.4~install: inherits@2.0.4
npm info lifecycle isarray@1.0.0~install: isarray@1.0.0
npm info lifecycle semver@6.3.0~install: semver@6.3.0
npm info lifecycle make-dir@3.1.0~install: make-dir@3.1.0
npm info lifecycle mimic-response@2.1.0~install: mimic-response@2.1.0
npm info lifecycle decompress-response@4.2.1~install: decompress-response@4.2.1
npm info lifecycle minimatch@3.0.4~install: minimatch@3.0.4
npm info lifecycle mkdirp@1.0.4~install: mkdirp@1.0.4
npm info lifecycle ms@2.1.2~install: ms@2.1.2
npm info lifecycle debug@4.3.2~install: debug@4.3.2
npm info lifecycle agent-base@6.0.2~install: agent-base@6.0.2
npm info lifecycle https-proxy-agent@5.0.0~install: https-proxy-agent@5.0.0
npm info lifecycle node-fetch@2.6.1~install: node-fetch@2.6.1
npm info lifecycle nopt@5.0.0~install: nopt@5.0.0
npm info lifecycle number-is-nan@1.0.1~install: number-is-nan@1.0.1
npm info lifecycle is-fullwidth-code-point@1.0.0~install: is-fullwidth-code-point@1.0.0
npm info lifecycle object-assign@4.1.1~install: object-assign@4.1.1
npm info lifecycle path-is-absolute@1.0.1~install: path-is-absolute@1.0.1
npm info lifecycle process-nextick-args@2.0.1~install: process-nextick-args@2.0.1
npm info lifecycle safe-buffer@5.1.2~install: safe-buffer@5.1.2
npm info lifecycle set-blocking@2.0.0~install: set-blocking@2.0.0
npm info lifecycle signal-exit@3.0.3~install: signal-exit@3.0.3
npm info lifecycle simple-concat@1.0.1~install: simple-concat@1.0.1
npm info lifecycle string_decoder@1.1.1~install: string_decoder@1.1.1
npm info lifecycle strip-ansi@3.0.1~install: strip-ansi@3.0.1
npm info lifecycle string-width@1.0.2~install: string-width@1.0.2
npm info lifecycle util-deprecate@1.0.2~install: util-deprecate@1.0.2
npm info lifecycle readable-stream@2.3.7~install: readable-stream@2.3.7
npm info lifecycle are-we-there-yet@1.1.5~install: are-we-there-yet@1.1.5
npm info lifecycle wide-align@1.1.3~install: wide-align@1.1.3
npm info lifecycle gauge@2.7.4~install: gauge@2.7.4
npm info lifecycle npmlog@4.1.2~install: npmlog@4.1.2
npm info lifecycle wrappy@1.0.2~install: wrappy@1.0.2
npm info lifecycle once@1.4.0~install: once@1.4.0
npm info lifecycle inflight@1.0.6~install: inflight@1.0.6
npm info lifecycle glob@7.1.7~install: glob@7.1.7
npm info lifecycle rimraf@3.0.2~install: rimraf@3.0.2
npm info lifecycle yallist@4.0.0~install: yallist@4.0.0
npm info lifecycle lru-cache@6.0.0~install: lru-cache@6.0.0
npm info lifecycle semver@7.3.5~install: semver@7.3.5
npm info lifecycle minipass@3.1.3~install: minipass@3.1.3
npm info lifecycle fs-minipass@2.1.0~install: fs-minipass@2.1.0
npm info lifecycle minizlib@2.1.2~install: minizlib@2.1.2
npm info lifecycle tar@6.1.0~install: tar@6.1.0
npm info lifecycle @mapbox/node-pre-gyp@1.0.5~install: @mapbox/node-pre-gyp@1.0.5
npm info lifecycle nan@2.14.2~install: nan@2.14.2
npm info lifecycle simple-get@3.1.0~install: simple-get@3.1.0
npm info lifecycle canvas@2.8.0~install: canvas@2.8.0

> canvas@2.8.0 install /root/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.5
node-pre-gyp info using node@14.17.1 | linux | x64
node-pre-gyp info check checked for "/root/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-linux-musl-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-linux-musl-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@14.17.1 (node-v83 ABI, musl) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-linux-musl-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.17.1 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.17.1 | linux | x64
gyp info find Python using Python version 3.9.5 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/14.17.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.17.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.17.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
/bin/sh: pkg-config: not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.10.43
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/root/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/root/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /root/node_modules/canvas
gyp ERR! node -v v14.17.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/root/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.10.43
node-pre-gyp ERR! command "/usr/bin/node" "/root/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/node_modules/canvas
node-pre-gyp ERR! node -v v14.17.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.5
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/root/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm info lifecycle canvas@2.8.0~install: Failed to exec install script
npm timing action:install Completed in 3319ms
npm timing stage:rollbackFailedOptional Completed in 106ms
npm timing stage:runTopLevelLifecycles Completed in 14794ms
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.8.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm timing npm Completed in 15327ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-13T09_31_22_808Z-debug.log
```

**Comment by ITdesk01** [comment]
Please adapt to openwrt, thank you

**Comment by zbjornson** [comment]
Prebuilds aren't available for msul libc. More info in the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511):

#### If you're on Alpine Linux or another distro using [musl-libc](https://www.musl-libc.org/)
The log may look like 

```
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.0/canvas-v2.6.0-node-v64-linux-musl-x64.tar.gz
```

Prebuilds are only available for glibc, not musl-libc. See https://github.com/node-gfx/node-canvas-prebuilt/issues/77, which includes information on building from source.
