### ISSUE TITLE
ERROR OPEN

### ISSUE THREAD

**Issue by Zalleya** [Automattic/node-canvas#1856]
yesterday it can be opened. now can't
-
[ERROR] Error: ENOENT, No such file or directory 'ERROR: 401'
    at setSource (c:\p\node_modules\canvas\lib\image.js:91:13)
    at Image.set (c:\p\node_modules\canvas\lib\image.js:62:9)
    at c:\p\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at Object.loadImage (c:\p\node_modules\canvas\index.js:23:10)
    at Welcome.toAttachment (c:\p\function\discord-canvas-balance\src\greetings\Base.js:152:37)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async msgHandler (c:\p\message\geps.js:1119:39) {
  errno: 2,
  code: 'ENOENT',
  path: 'ERROR: 401',
  syscall: 'fopen'
}

**Comment by zbjornson** [comment]
That error means the URL you're trying to fetch is returning 401, it's not an issue with node-canvas.
