### ISSUE TITLE
Having trouble using loadImage with a specific image link

### ISSUE THREAD

**Issue by ucelery** [Automattic/node-canvas#1863]
## Issue or Feature

(node:19548) UnhandledPromiseRejectionWarning: Error: Unsupported image type
    at setSource (\~\node_modules\canvas\lib\image.js:91:13)
    at (\~\node_modules\canvas\lib\image.js:59:11
    at (\~\node_modules\simple-get\index.js:89:7
    at IncomingMessage.<anonymous> (\~\node_modules\simple-concat\index.js:8:13)
    at Object.onceWrapper (events.js:482:28)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19548) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19548) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Steps to Reproduce

```js
const { loadImage } = require('canvas');
await loadImage('https://cdn.discordapp.com/attachments/853143746794356767/866988314401308672/2hl8hvfjwqj51.png');
```

## Your Environment
-- canvas@2.8.0
-- node v14.17.0

**Comment by chearon** [comment]
Closing because this issue is old and the URL no longer works. We need a working PNG link and then I can reopen if the PNG is valid.
