### ISSUE TITLE
Node-Canvas don't work

### ISSUE THREAD

**Issue by Grifed-source** [Automattic/node-canvas#1870]
## My Node-Canvas error

```js
internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/shares/public/iobot/iomusic/node_modules/node-canvas/build/Release/canvas.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/shares/public/iobot/iomusic/node_modules/node-canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

## Steps to Reproduce
```js
const { createCanvas, loadImage } = require('canvas');
const { messageAttachment } = require('discord.js')
const { join } = require("path");
const fs = require('fs');
const discord = require('discord.js');
const client = new discord.Client();

module.exports = {
    name: 'test',
    aliases: [],
    category: '',
    utilisation: '{prefix}test',

    async execute(client, message, args) {

        message.channel.send('Text with menu!', select);

        const member = message.mentions.members.first() || message.guild.members.cache.get(args[0]) || message.member;
        const xp = JSON.parse(fs.readFileSync('./levels.json'));

        if (!xp[message.author.id]) {
            xp[message.author.id] = {
                xp: 10,
                level: 0
            };

            const canvas = createCanvas(1000, 333);
            const ctx = canvas.getContext('2d');
            const background = await loadImage(join(__dirname, "..", "img", "1500x500.png"));
            ctx.drawImage(background, 0, 0, canvas.width, canvas.height);

            ctx.beginPath();
            ctx.lineWidth = 4;
            ctx.strokeStyle = "#ffffff"
            ctx.globalAlpha = 0.2;
            ctx.fillStyle = "#000000"
            ctx.fillRect(180, 216, 770, 65);
            ctx.fill();
            ctx.globalAlpha = 1;
            ctx.strokeRect(180, 216, 770, 65);
            ctx.stroke();

            ctx.fillStyle = "#e67e22"
            ctx.globalAlpha = 0.6;
            ctx.fillRect(180, 216, xp[message.author.id].level)
            ctx.fill();
            ctx.globalAlpha = 1;

            ctx.font = "30px Arial";
            ctx.textAlign = "center";
            ctx.fillStyle = "#ffffff"
            ctx.fillText(`${xp[message.author.id].level} XP`)

            ctx.textAlign = "left";
            ctx.fillText(member.user.tag, 300, 120)

            ctx.font = "50px Arial";
            ctx.fillText("Level:", 300, 180);
            ctx.fillText(Math.round(xp[message.author.id].xp), 470, 180);

            ctx.arc(170, 160, 120, 0, Math.PI * 2, true);
            ctx.lineWidth = 6;
            ctx.strokeStyle = "#ffffff"
            ctx.stroke();
            ctx.closePath();
            ctx.clip();
            const avatar = await loadImage(member.user.displayAvatarURL({ format: "jpg" }));
            ctx.drawImage(avatar, 40, 40, 250, 250);

            const attachment = new MessageAttachment(canvas.ToBuffer(), "rank.png");
            message.channel.send(`Voici ton rank **${member.user.username}**`, attachment)
        }
    },
};
```

## Your Environment
* Version of node-canvas: node-canvas@2.7.0 extraneous
* Environment: node 14.17.0 / 15.14.3 on Raspbian

**Comment by milenien** [comment]
Je vous propose de vous donner mes services : voici mes contact: discord.gg/gay

**Comment by milenien** [comment]
Est-ce que t'as a un sac da winnnnnnnnnnnnnnnnx

**Comment by zbjornson** [comment]
That most likely means that the MacOS or Win canvas build is being used on Linux.

**Comment by luoxzhg** [comment]
```
internal/modules/cjs/loader.js:1144
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /app/node_modules/canvas/build/Release/canvas.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/app/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

ENV

`node:14-slim`

**Comment by robinma** [comment]
you have to use same node version.

if you use node 4.0 install node-canvas.  then you have to use node 4.0 run node-canvas
