### ISSUE TITLE
Installation fails: "../src/backend/Backend.h:3:10: fatal error: 'cairo.h' file not found"

### ISSUE THREAD

**Issue by coldstone** [Automattic/node-canvas#1896]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

## Steps to Reproduce

1. I've already installed dependencies like this, and It's successful: 
``` shell
brew install pkg-config cairo pango libpng jpeg giflib librsvg
```
2. I've already re-installed the xcode-select tool with `xcode-select --install`.
3. Then I use 'npm install canvas' to install node-canvas, it goes error:
``` shell
$ npm install -g canvas
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! SOLINK_MODULE(target) Release/canvas-postbuild.node
npm ERR!   CXX(target) Release/obj.target/canvas/src/backend/Backend.o
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@12.18.3 | darwin | x64
npm ERR! gyp info find Python using Python version 3.9.7 found at "/usr/local/opt/python@3.9/bin/python3.9"
npm ERR! gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/tazen/Library/Caches/node-gyp/12.18.3/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/tazen/Library/Caches/node-gyp/12.18.3',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/tazen/Library/Caches/node-gyp/12.18.3/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/backend/Backend.cc:1:
npm ERR! ../src/backend/Backend.h:3:10: fatal error: 'cairo.h' file not found
npm ERR! #include <cairo.h>
npm ERR!          ^~~~~~~~~
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/canvas/src/backend/Backend.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/local/lib/node_modules/canvas
npm ERR! gyp ERR! node -v v12.18.3
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
```

## Your Environment
* Version of node-canvas: Not installed yet.
* Environment: Mac OS X11.5.2, Node v12.18.3

**Comment by Nico-Guyon** [comment]
Do you have by any chance an apple silicon ?

If you have you may be encountering the same problem I have / had : https://github.com/Automattic/node-canvas/issues/1898
I explained the steps I used as a workaround for now.

If you're interested I also forked the lib and edited the binding.gyp file here : https://github.com/Nico-Guyon/node-canvas
I'm not sure why but you'll also have to create a giflib.pc file on your system with the correct homebrew install path in order for this workaround to work.

**Comment by coldstone** [comment]
> Do you have by any chance apple silicon?
> 
> If you have you may be encountering the same problem I have / had: #1898
> I explained the steps I used as a workaround for now.
> 
> If you're interested I also forked the lib and edited the binding.gyp file here: https://github.com/Nico-Guyon/node-canvas
> I'm not sure why but you'll also have to create a giflib.pc file on your system with the correct homebrew install path in order for this workaround to work.

Thanks for your help. But I'm not on apple silicon. My laptop is MacBook Pro (15-inch, 2017).

I've tried to create a `giflib.pc` file and link it to `/usr/local/lib/pkgconfig` just like you said. But it does not help.
It still looks like the very same error: `'cairo.h' file not found.`
