### ISSUE TITLE
Can I registerFont from an URL like https://fonts.gstatic.com/s/pacifico/v17/FwZY7-Qmy14u9lezJ96A4sijpFu_.ttf

### ISSUE THREAD

**Issue by wentin** [Automattic/node-canvas#1900]
## Issue or Feature
Is it possible to registerFont from an URL like 
```
https://fonts.gstatic.com/s/pacifico/v17/FwZY7-Qmy14u9lezJ96A4sijpFu_.ttf
```
When I run my code like this:
```
const { registerFont, createCanvas, loadImage } = require("canvas");
registerFont(
    "https://fonts.gstatic.com/s/pacifico/v17/FwZY7-Qmy14u9lezJ96A4sijpFu_.ttf",
    { family: "Poppins" }
);
```
I get an error:
```
Error: ENOENT: no such file or directory, lstat '/Users/wentin/Documents/GitHub/Live Image/https:'
    at Object.realpathSync (fs.js:1796:7)
    at registerFont (/Users/wentin/Documents/GitHub/Live Image/node_modules/canvas/index.js:48:34)
    at Object.<anonymous> (/Users/wentin/Documents/GitHub/Live Image/app.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): canvas@2.8.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node v14.17.6 Mac OS 11.6 (20G165)

**Comment by wentin** [comment]
Same issue as https://github.com/Automattic/node-canvas/issues/1605
Short answer: it is not currently supported as of Sep, 2021
