### ISSUE TITLE
Source build issues

### ISSUE THREAD

**Issue by rcketscientist** [Automattic/node-canvas#1906]
## Issue or Feature
- [ x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

Build crashes immediately with:
```
gyp ERR! System Linux 3.10.0-1127.el7.x86_64
gyp ERR! command "/home/osi/.local/node-v14.15.4-linux-x64/bin/node" "/home/osi/.local/node-v14.15.4-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/osi/disp/vob/web/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/osi/disp/vob/web/node_modules/canvas/build/Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /osi/disp/vob/web/node_modules/canvas
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/osi/.local/node-v14.15.4-linux-x64/bin/node /home/osi/.local/node-v14.15.4-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/osi/disp/vob/web/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/osi/disp/vob/web/node_modules/canvas/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/osi/disp/vob/web/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 3.10.0-1127.el7.x86_64
node-pre-gyp ERR! command "/home/osi/.local/node-v14.15.4-linux-x64/bin/node" "/osi/disp/vob/web/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /osi/disp/vob/web/node_modules/canvas
node-pre-gyp ERR! node -v v14.15.4
node-pre-gyp ERR! node-pre-gyp -v v1.0.5
node-pre-gyp ERR! not ok 
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): 2.8.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 14.15.4 on rhel 7

**Comment by stevenKirill** [comment]
I have the same problem, does anybody know how to solve it ?
