### ISSUE TITLE
error starting

### ISSUE THREAD

**Issue by LucasB25** [Automattic/node-canvas#1932]
[2021-11-19 17:28:36] Uncaught Promise Error:
[2021-11-19 17:28:36] Error: The module '/home/pi/SITE2/node_modules/canvas/build/Release/canvas.node'
[2021-11-19 17:28:36] was compiled against a different Node.js version using
[2021-11-19 17:28:36] NODE_MODULE_VERSION 72. This version of Node.js requires
[2021-11-19 17:28:36] NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
[2021-11-19 17:28:36] the module (for instance, using `npm rebuild` or `npm install`).
[2021-11-19 17:28:36]     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
[2021-11-19 17:28:36]     at Module.load (node:internal/modules/cjs/loader:981:32)
[2021-11-19 17:28:36]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[2021-11-19 17:28:36]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[2021-11-19 17:28:36]     at require (node:internal/modules/cjs/helpers:102:18)
[2021-11-19 17:28:36]     at Object.<anonymous> (/home/pi/SITE2/node_modules/canvas/lib/bindings.js:3:18)
[2021-11-19 17:28:36]     at Module._compile (node:internal/modules/cjs/loader:1101:14)
[2021-11-19 17:28:36]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
[2021-11-19 17:28:36]     at Module.load (node:internal/modules/cjs/loader:981:32)
[2021-11-19 17:28:36]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[2021-11-19 17:28:36]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[2021-11-19 17:28:36]     at require (node:internal/modules/cjs/helpers:102:18)
[2021-11-19 17:28:36]     at Object.<anonymous> (/home/pi/SITE2/node_modules/canvas/lib/canvas.js:9:18)
[2021-11-19 17:28:36]     at Module._compile (node:internal/modules/cjs/loader:1101:14)
[2021-11-19 17:28:36]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
[2021-11-19 17:28:36]     at Module.load (node:internal/modules/cjs/loader:981:32)

canvas: 2.8.0
Nodejs: 12

**Comment by zbjornson** [comment]
Please see the "I get a NODE_MODULE_VERSION error" section of the troubleshooting guide (#1511) that was in the issue template.

**Comment by LucasB25** [comment]
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v72-linux-glibc-arm.tar.gz

**Comment by zbjornson** [comment]
That is also in the troubleshooting guide under "Installation fails with a 404 in the log ... If you have an ARM CPU."

**Comment by LucasB25** [comment]
I followed the page that encountered a my system that does not solve anything
