### ISSUE TITLE
Cannot able to install i.e. error 404

### ISSUE THREAD

**Issue by bilal-08** [Automattic/node-canvas#1938]
I'm having this problem for quite a while, didnt solved till now
i installed the windows-build-tools as someone suggested it before but the error is still not clear

![image](https://user-images.githubusercontent.com/77657831/143534278-4f2afd3e-878c-44f0-976f-d6c517935347.png)
![image](https://user-images.githubusercontent.com/77657831/143534303-810a03fd-b87f-487f-8ad7-c66b19372dae.png)

## Steps to Reproduce
npm i canvas

## Your Environment
node v14.17.0
windows 10

**Comment by bilal-08** [comment]
```js
> node-canvas@2.7.0 install G:\Synthesized-infinity\kaoi\node_modules\node-canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v83-win32-unknown-ia32.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for node-canvas@2.7.0 and node@14.17.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v83-win32-unknown-ia32.tar.gz 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Backend.cc
  ImageBackend.cc
  PdfBackend.cc
  SvgBackend.cc
  BMPParser.cc
  Backends.cc
  Canvas.cc
  CanvasGradient.cc
g:\synthesized-infinity\kaoi\node_modules\node-canvas\src\bmp\bmpparser.cc(186): warning C4018: '>': signed/unsigned mismatch
 [G:\Synthesized-infinity\kaoi\node_modules\node-canvas\build\canvas.vcxproj]
g:\synthesized-infinity\kaoi\node_modules\node-canvas\src\bmp\bmpparser.cc(201): warning C4018: '>': signed/unsigned mismatch
 [G:\Synthesized-infinity\kaoi\node_modules\node-canvas\build\canvas.vcxproj]
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  closure.cc
  color.cc
  Image.cc
g:\synthesized-infinity\kaoi\node_modules\node-canvas\src\util.h(31): error C2039: 'toupper': is not a member of 'std' (compi
ling source file ..\src\CanvasRenderingContext2d.cc) [G:\Synthesized-infinity\kaoi\node_modules\node-canvas\build\canvas.vcxp
roj]
  c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\map(20): note: see declarat
  ion of 'std' (compiling source file ..\src\CanvasRenderingContext2d.cc)
  ImageData.cc
  init.cc
  register_font.cc
g:\synthesized-infinity\kaoi\node_modules\node-canvas\src\util.h(31): error C2039: 'toupper': is not a member of 'std' (compi
ling source file ..\src\Image.cc) [G:\Synthesized-infinity\kaoi\node_modules\node-canvas\build\canvas.vcxproj]
  c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\queue(451): note: see decla
  ration of 'std' (compiling source file ..\src\Image.cc)
  win_delay_load_hook.cc
g:\synthesized-infinity\kaoi\node_modules\node-canvas\src\util.h(31): error C2039: 'toupper': is not a member of 'std' (compi
ling source file ..\src\ImageData.cc) [G:\Synthesized-infinity\kaoi\node_modules\node-canvas\build\canvas.vcxproj]
  c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\queue(451): note: see decla
  ration of 'std' (compiling source file ..\src\ImageData.cc)
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=G:\\Synthesized-infinity\\kaoi\\node_modules\\node-canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=G:\\Synthesized-infinity\\kaoi\\node_modules\\node-canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd G:\Synthesized-infinity\kaoi\node_modules\node-canvas
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=G:\Synthesized-infinity\kaoi\node_modules\node-canvas\build\Release\canvas.node --module_name=canvas --module_path=G:\Synthesized-infinity\kaoi\node_modules\node-canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (G:\Synthesized-infinity\kaoi\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "G:\\Synthesized-infinity\\kaoi\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd G:\Synthesized-infinity\kaoi\node_modules\node-canvas
node-pre-gyp ERR! node -v v14.17.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.7
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=G:\Synthesized-infinity\kaoi\node_modules\node-canvas\build\Release\canvas.node --module_name=canvas --module_path=G:\Synthesized-infinity\kaoi\node_modules\node-canvas\build\Release --napi_version=8 
--node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-canvas@2.7.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-canvas@2.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bilal\AppData\Roaming\npm-cache\_logs\2021-11-28T16_59_45_797Z-debug.log
```

just the whole error log

**Comment by zbjornson** [comment]
See #1511:

> If you're using 32-bit Node.js
> 
> The log will include a 404 and ia32. Node-canvas does not readily compile on 32-bit platforms because the necessary dependencies are hard to obtain. Use 64-bit Node.js instead, especially because 32-bit Node.js is only experimentally supported by the Node foundation.
