### ISSUE TITLE
debian 10: err_dlopen_failed, undefined symbol: g_ptr_array_copy

### ISSUE THREAD

**Issue by ekorolevanyrun** [Automattic/node-canvas#1939]
## Issue

Got the ERR_DLOPEN_FAILED error right after `const canvas = require('canvas');`. I have solution for that issue,  I can just build canvas from source with `npm i --build-from-source canvas` command, but that solution isn't acceptable variant for some reasons. 

It seems wrong prebuilt packages had been downloaded during `npm install`. How to fix it to use `canvas` without building from source?

## Error logs
```
Error: /var/www/core/node_modules/canvas/build/Release/libpango-1.0.so.0: undefined symbol: g_ptr_array_copy
     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
     at Module.load (internal/modules/cjs/loader.js:950:32)
     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
     at Module.require (internal/modules/cjs/loader.js:974:19)
     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
     at require (internal/modules/cjs/helpers.js:93:18)
     at Object.<anonymous> (/var/www/core/node_modules/canvas/lib/bindings.js:3:18)
     at Module._compile (internal/modules/cjs/loader.js:1085:14)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
     at Module.load (internal/modules/cjs/loader.js:950:32)
     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
     at Module.require (internal/modules/cjs/loader.js:974:19)
     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
     at require (internal/modules/cjs/helpers.js:93:18)
     at Object.<anonymous> (/var/www/core/node_modules/canvas/lib/canvas.js:9:18)
     at Module._compile (internal/modules/cjs/loader.js:1085:14) {
   code: 'ERR_DLOPEN_FAILED'
 }
```

## Your Environment
* canvas@2.8.0
* node v14.18.1, Debian GNU/Linux 10 (buster)

**Comment by skuznetsov** [comment]
For AWS Lambda image I fixed it by setting environment variable this way:
LD_LIBRARY_PATH="/var/task/node_modules/canvas/build/Release:/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib"
I added it into Lambda function env variables.

It turned out that default image settings have glib preinstalled, but it is quite outdated and has a smaller size than the glib library that comes with canvas.

**Comment by fsobh** [comment]
> For AWS Lambda image I fixed it by setting environment variable this way: LD_LIBRARY_PATH="/var/task/node_modules/canvas/build/Release:/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib" I added it into Lambda function env variables.
> 
> It turned out that default image settings have glib preinstalled, but it is quite outdated and has a smaller size than the glib library that comes with canvas.

Could you explain how you did that? im still facing the issue

**Comment by skuznetsov** [comment]
> Could you explain how you did that? im still facing the issue

I use Pulumi (https://pulumi.com) for deployment, so I can show you the piece of my code that shows the usage:

```
lambdaFunction = new aws.lambda.Function("eventsProcessorFunction", {
    packageType: "Image",
    imageUri: image.imageValue,
    role: lambdaRole.arn,
    environment: {
        variables: {
            TOKEN: accessToken,
            BUCKET_NAME: bucket.bucket,
            LD_LIBRARY_PATH: "/var/task/node_modules/canvas/build/Release:/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib"
        }
    }
});

```

So depending on what do you use for a deployment, you can use a similar approach to set up your environment variables.

**Comment by ekorolevanyrun** [comment]
Hi! Sorry for delay, I have been faced with another tasks.

I've tried your solution, but it doesn't help. @skuznetsov , which version of preinstalled glib do you have, and which versions is needed?
