### ISSUE TITLE
Error in instalation

### ISSUE THREAD

**Issue by itsmeclancy** [Automattic/node-canvas#1973]
![Screenshot_2022-01-23-21-42-59-586_com microsoft rdc androidx](https://user-images.githubusercontent.com/80187036/150684023-d96266d1-8815-4b7a-89d4-1ae2bd1c5f77.jpg)

How ro fix this?

Windows 11
Nodejs v16.13.2.
npn 8.1.2

**Comment by Doughp** [comment]
I am having same issue, by chance is this when installing solana dev tools?

**Comment by wsoeltz** [comment]
Same issue -
MacOS Monterey 12.2
Node v16.13.2
NPM v8.1.2

Including relevant error logs -

```
2813 error code 1
2814 error path /Users/username/git/reponame/node_modules/canvas
2815 error command failed
2816 error command sh -c node-pre-gyp install --fallback-to-build
2817 error Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/username/git/reponame/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/username/git/reponame/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
2818 error node-pre-gyp info it worked if it ends with ok
2818 error node-pre-gyp info using node-pre-gyp@0.11.0
2818 error node-pre-gyp info using node@16.13.2 | darwin | arm64
2818 error node-pre-gyp WARN Using needle for node-pre-gyp https download
2818 error node-pre-gyp info check checked for "/Users/username/git/reponame/node_modules/canvas/build/Release/canvas.node" (not found)
2818 error node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-darwin-unknown-arm64.tar.gz
2818 error node-pre-gyp http 404 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-darwin-unknown-arm64.tar.gz
2818 error node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-darwin-unknown-arm64.tar.gz
2818 error node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@16.13.2 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
2818 error node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-darwin-unknown-arm64.tar.gz
2818 error gyp info it worked if it ends with ok
2818 error gyp info using node-gyp@8.3.0
2818 error gyp info using node@16.13.2 | darwin | arm64
2818 error gyp info ok
2818 error gyp info it worked if it ends with ok
2818 error gyp info using node-gyp@8.3.0
2818 error gyp info using node@16.13.2 | darwin | arm64
2818 error gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
2818 error gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
2818 error gyp info spawn args [
2818 error gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2818 error gyp info spawn args   'binding.gyp',
2818 error gyp info spawn args   '-f',
2818 error gyp info spawn args   'make',
2818 error gyp info spawn args   '-I',
2818 error gyp info spawn args   '/Users/username/git/reponame/node_modules/canvas/build/config.gypi',
2818 error gyp info spawn args   '-I',
2818 error gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2818 error gyp info spawn args   '-I',
2818 error gyp info spawn args   '/Users/username/Library/Caches/node-gyp/16.13.2/include/node/common.gypi',
2818 error gyp info spawn args   '-Dlibrary=shared_library',
2818 error gyp info spawn args   '-Dvisibility=default',
2818 error gyp info spawn args   '-Dnode_root_dir=/Users/username/Library/Caches/node-gyp/16.13.2',
2818 error gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
2818 error gyp info spawn args   '-Dnode_lib_file=/Users/username/Library/Caches/node-gyp/16.13.2/<(target_arch)/node.lib',
2818 error gyp info spawn args   '-Dmodule_root_dir=/Users/username/git/reponame/node_modules/canvas',
2818 error gyp info spawn args   '-Dnode_engine=v8',
2818 error gyp info spawn args   '--depth=.',
2818 error gyp info spawn args   '--no-parallel',
2818 error gyp info spawn args   '--generator-output',
2818 error gyp info spawn args   'build',
2818 error gyp info spawn args   '-Goutput_dir=.'
2818 error gyp info spawn args ]
2818 error /bin/sh: pkg-config: command not found
2818 error gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
2818 error gyp ERR! configure error
2818 error gyp ERR! stack Error: `gyp` failed with exit code: 1
2818 error gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
2818 error gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
2818 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
2818 error gyp ERR! System Darwin 21.3.0
2818 error gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/username/git/reponame/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/username/git/reponame/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
2818 error gyp ERR! cwd /Users/username/git/reponame/node_modules/canvas
2818 error gyp ERR! node -v v16.13.2
2818 error gyp ERR! node-gyp -v v8.3.0
2818 error gyp ERR! not ok
2818 error node-pre-gyp ERR! build error
2818 error node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/username/git/reponame/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/username/git/reponame/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
2818 error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/username/git/reponame/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
2818 error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
2818 error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
2818 error node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
2818 error node-pre-gyp ERR! System Darwin 21.3.0
2818 error node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/username/git/reponame/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
2818 error node-pre-gyp ERR! cwd /Users/username/git/reponame/node_modules/canvas
2818 error node-pre-gyp ERR! node -v v16.13.2
2818 error node-pre-gyp ERR! node-pre-gyp -v v0.11.0
2818 error node-pre-gyp ERR! not ok
2819 verbose exit 1
```

**Comment by LinusU** [comment]
@zeezxyz 

```
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodeis/node-gyp#on-windows
```

You need to install Visual Studio.

more info: https://github.com/Automattic/node-canvas/wiki/Installation%3A-Windows

-----

@wsoeltz 

```
2818 error /bin/sh: pkg-config: command not found
2818 error gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
2818 error gyp ERR! configure error
```

You need to install `pkg-config`.

more info: https://github.com/Automattic/node-canvas/wiki/Installation%3A-Mac-OS-X
