### ISSUE TITLE
Hello very good, I need urgent help with a problem that constantly gives me the code, thank you very much for the help

### ISSUE THREAD

**Issue by Diegoecoms** [Automattic/node-canvas#1993]
Error: The module '\\?\C:\Users\Usuario\Downloads\Goat Club c D p g h y s n e i\hashlips_art_engine-1.1.2_patch_v5\node_modules\canvas\build\Release\canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\Users\Usuario\Downloads\Goat Club c D p g h y s n e i\hashlips_art_engine-1.1.2_patch_v5\node_modules\canvas\lib\bindings.js:3:18)

**Comment by zbjornson** [comment]
This is covered in the troubleshooting guide that was in the issue template:

> ## I get a `NODE_MODULE_VERSION` error
> 
> The log may look like
> 
> ```
> ...was compiled against a different Node.js version using NODE_MODULE_VERSION 72.
> This version of Node.js requires NODE_MODULE_VERSION 64. Please try re-compiling or
> re-installing the module
> ```
> 
> This could mean you upgraded Node.js without re-installing canvas. Try running `yarn` or `npm install` again.
> 
> This can also happen if you're using Electron. The version of Node wrapped by Electron must match the version of Node that you used to build/install canvas.
