### ISSUE TITLE
cannot read file data

### ISSUE THREAD

**Issue by yi-xiaobai** [Automattic/node-canvas#1995]
**node_modules/canvas/build/Release/libharfbuzz.so.0: cannot read file data**

**node_modules/canvas/build/Release/libharfbuzz.so.0: cannot read file data**
 at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module.Hook._require.Module.require (/home/azureuser/.nvm/versions/node/v10.24.1/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:

**Comment by zbjornson** [comment]
This doesn't appear to be a problem with node-canvas, so I'd suggest searching other forums for support.
