### ISSUE TITLE
Can't install canvas

### ISSUE THREAD

**Issue by Dennny559** [Automattic/node-canvas#2057]
I have been trying to install node-canvas for about a day and have tried everything on the internet. I still can't figure out how to install it so I was hoping someone here could help me.

## Error

```
PS C:\Users\cryst\OneDrive\Desktop\IB> npm i canvas

> canvas@2.9.1 install C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v83-win32-unknown-ia32.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.1 and node@14.17.5 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v83-win32-unknown-ia32.tar.gz 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFramew
orkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
  Backend.cc
  ImageBackend.cc
  PdfBackend.cc
  SvgBackend.cc
  BMPParser.cc
  Backends.cc
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  closure.cc
  color.cc
c:\users\cryst\appdata\local\node-gyp\cache\14.17.5\include\node\uv/win.h(33): fatal error C1083: Cannot open include file: 'winsock2.h': No such file or directory (compiling so
urce file ..\src\backend\Backend.cc) [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
  Image.cc
c:\users\cryst\appdata\local\node-gyp\cache\14.17.5\include\node\uv/win.h(33): fatal error C1083: Cannot open include file: 'winsock2.h': No such file or directory (compiling so 
urce file ..\src\backend\PdfBackend.cc) [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
  ImageData.cc
c:\users\cryst\appdata\local\node-gyp\cache\14.17.5\include\node\uv/win.h(33): fatal error C1083: Cannot open include file: 'winsock2.h': No such file or directory (compiling so
urce file ..\src\CanvasPattern.cc) [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
c:\users\cryst\appdata\local\node-gyp\cache\14.17.5\include\node\uv/win.h(33): fatal error C1083: Cannot open include file: 'winsock2.h': No such file or directory (compiling so 
urce file ..\src\backend\ImageBackend.cc) [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
  init.cc
  register_font.cc
c:\users\cryst\appdata\local\node-gyp\cache\14.17.5\include\node\uv/win.h(33): fatal error C1083: Cannot open include file: 'winsock2.h': No such file or directory (compiling so
urce file ..\src\CanvasGradient.cc) [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
c:\users\cryst\appdata\local\node-gyp\cache\14.17.5\include\node\uv/win.h(33): fatal error C1083: Cannot open include file: 'winsock2.h': No such file or directory (compiling so 
urce file ..\src\backend\SvgBackend.cc) [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
  win_delay_load_hook.cc
c:\users\cryst\appdata\local\node-gyp\cache\14.17.5\include\node\uv/win.h(33): fatal error C1083: Cannot open include file: 'winsock2.h': No such file or directory (compiling so
urce file ..\src\CanvasRenderingContext2d.cc) [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
c:\users\cryst\appdata\local\node-gyp\cache\14.17.5\include\node\uv/win.h(33): fatal error C1083: Cannot open include file: 'winsock2.h': No such file or directory (compiling so 
urce file ..\src\Canvas.cc) [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc(18): fatal error C1083: Cannot open include file: 'windows.h': No such file or di 
rectory [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
c:\users\cryst\appdata\local\node-gyp\cache\14.17.5\include\node\uv/win.h(33): fatal error C1083: Cannot open include file: 'winsock2.h': No such file or directory (compiling so 
urce file ..\src\Backends.cc) [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
c:\users\cryst\appdata\local\node-gyp\cache\14.17.5\include\node\uv/win.h(33): fatal error C1083: Cannot open include file: 'winsock2.h': No such file or directory (compiling so
urce file ..\src\ImageData.cc) [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
c:\users\cryst\appdata\local\node-gyp\cache\14.17.5\include\node\uv/win.h(33): fatal error C1083: Cannot open include file: 'winsock2.h': No such file or directory (compiling so
urce file ..\src\closure.cc) [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
..\src\bmp\BMPParser.cc(186): warning C4018: '>': signed/unsigned mismatch [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
..\src\bmp\BMPParser.cc(201): warning C4018: '>': signed/unsigned mismatch [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
c:\users\cryst\appdata\local\node-gyp\cache\14.17.5\include\node\uv/win.h(33): fatal error C1083: Cannot open include file: 'winsock2.h': No such file or directory (compiling so 
urce file ..\src\init.cc) [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
..\src\bmp\BMPParser.cc(385): warning C4127: conditional expression is constant [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
  ..\src\bmp\BMPParser.cc(64): note: see reference to function template instantiation 'T BMPParser::Parser::get<uint32_t,true>(void)' being compiled
          with
          [
              T=uint32_t
          ]
..\src\bmp\BMPParser.cc(393): warning C4127: conditional expression is constant [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
  ..\src\bmp\BMPParser.cc(249): note: see reference to function template instantiation 'T BMPParser::Parser::get<uint8_t,true>(uint8_t *)' being compiled
          with
          [
              T=uint8_t
          ]
..\src\color.cc(640): warning C4127: conditional expression is constant [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
..\src\color.cc(665): warning C4127: conditional expression is constant [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
c:\users\cryst\appdata\local\node-gyp\cache\14.17.5\include\node\uv/win.h(33): fatal error C1083: Cannot open include file: 'winsock2.h': No such file or directory (compiling so
urce file ..\src\Image.cc) [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\canvas.vcxproj]
..\src\register_font.cc(11): fatal error C1083: Cannot open include file: 'windows.h': No such file or directory [C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\ca
nvas.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.22000
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\cryst\\OneDrive\\Desktop\\IB\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\cryst\\OneDrive\\Desktop\\IB\\node_modules\\canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas
gyp ERR! node -v v14.17.5
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)      
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.22000
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\cryst\\OneDrive\\Desktop\\IB\\node_modules\\canvas\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas
node-pre-gyp ERR! node -v v14.17.5
node-pre-gyp ERR! node-pre-gyp -v v1.0.9
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\cryst\OneDrive\Desktop\IB\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN ib@1.0.0 No description
npm WARN ib@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-android-arm64@0.1.20 (node_modules\@napi-rs\canvas-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-android-arm64@0.1.20: wanted {"os":"android","arch":"arm64"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-arm-gnueabihf@0.1.20 (node_modules\@napi-rs\canvas-linux-arm-gnueabihf):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-linux-arm-gnueabihf@0.1.20: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-darwin-arm64@0.1.20 (node_modules\@napi-rs\canvas-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-darwin-arm64@0.1.20: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-darwin-x64@0.1.20 (node_modules\@napi-rs\canvas-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-darwin-x64@0.1.20: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-arm64-gnu@0.1.20 (node_modules\@napi-rs\canvas-linux-arm64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-linux-arm64-gnu@0.1.20: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-arm64-musl@0.1.20 (node_modules\@napi-rs\canvas-linux-arm64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-linux-arm64-musl@0.1.20: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-x64-musl@0.1.20 (node_modules\@napi-rs\canvas-linux-x64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-linux-x64-musl@0.1.20: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-linux-x64-gnu@0.1.20 (node_modules\@napi-rs\canvas-linux-x64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-linux-x64-gnu@0.1.20: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/canvas-win32-x64-msvc@0.1.20 (node_modules\@napi-rs\canvas-win32-x64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/canvas-win32-x64-msvc@0.1.20: wanted {"os":"win32","arch":"x64"} (current: {"os":"win32","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.9.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.9.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cryst\AppData\Roaming\npm-cache\_logs\2022-06-20T18_30_11_685Z-debug.log
```

I'm currently using Windows 11 64x.

**Comment by Dennny559** [comment]
> Had similar issue, downgrading node version resolved the error

Worked like a charm! Thank you very much!

**Comment by maietta** [comment]
Downgrading didn't work for me.
