### ISSUE TITLE
Can't install canvas with electron on Windows Server 2022 in GitHub Actions

### ISSUE THREAD

**Issue by maoqxxmm** [Automattic/node-canvas#2102]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

I'm using GitHub Actions to build package on Windows. I have downloaded GTK 2 by shell commands. And I have tried many versions of Node. None of them works.

## Steps to Reproduce

refer to https://github.com/zhxie/anioke/pull/79
```js
name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install canvas dependencies on Windows
        run: mkdir C:\\GTK && curl -o gtk.zip https://mirror.ossplanet.net/gnome/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip && tar xvf gtk.zip -C C:\\GTK

      - name: Install dependencies
        run: npm install
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): 2.9.3
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 18.8.0, electron: 18.3.5, Windows Server 2022

## The error log
```shell
⨯ cannot execute  cause=exit status 1
                    errorOut=npm ERR! code 1
    npm ERR! path D:\a\anioke\anioke\node_modules\canvas
    npm ERR! command failed
    npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build --update-binary
    npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
    npm ERR!   Backend.cc
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(537,1): warning C4127: conditional expression is constant [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(469): message : see reference to function template instantiation 'T v8::internal::Internals::ReadRawField<uint16_t>(v8::internal::Address,int)' being compiled [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR!           with
    npm ERR!           [
    npm ERR!               T=uint16_t
    npm ERR!           ]
    npm ERR!   ImageBackend.cc
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(537,1): warning C4127: conditional expression is constant [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(469): message : see reference to function template instantiation 'T v8::internal::Internals::ReadRawField<uint16_t>(v8::internal::Address,int)' being compiled [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR!           with
    npm ERR!           [
    npm ERR!               T=uint16_t
    npm ERR!           ]
    npm ERR!   PdfBackend.cc
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(537,1): warning C4127: conditional expression is constant [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(469): message : see reference to function template instantiation 'T v8::internal::Internals::ReadRawField<uint16_t>(v8::internal::Address,int)' being compiled [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR!           with
    npm ERR!           [
    npm ERR!               T=uint16_t
    npm ERR!           ]
    npm ERR!   SvgBackend.cc
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(537,1): warning C4127: conditional expression is constant [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(469): message : see reference to function template instantiation 'T v8::internal::Internals::ReadRawField<uint16_t>(v8::internal::Address,int)' being compiled [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR!           with
    npm ERR!           [
    npm ERR!               T=uint16_t
    npm ERR!           ]
    npm ERR!   BMPParser.cc
    npm ERR!   Backends.cc
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(537,1): warning C4127: conditional expression is constant [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(469): message : see reference to function template instantiation 'T v8::internal::Internals::ReadRawField<uint16_t>(v8::internal::Address,int)' being compiled [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR!           with
    npm ERR!           [
    npm ERR!               T=uint16_t
    npm ERR!           ]
    npm ERR!   Canvas.cc
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(537,1): warning C4127: conditional expression is constant [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(469): message : see reference to function template instantiation 'T v8::internal::Internals::ReadRawField<uint16_t>(v8::internal::Address,int)' being compiled [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR!           with
    npm ERR!           [
    npm ERR!               T=uint16_t
    npm ERR!           ]
    npm ERR!   CanvasGradient.cc
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(537,1): warning C4127: conditional expression is constant [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(469): message : see reference to function template instantiation 'T v8::internal::Internals::ReadRawField<uint16_t>(v8::internal::Address,int)' being compiled [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR!           with
    npm ERR!           [
    npm ERR!               T=uint16_t
    npm ERR!           ]
    npm ERR!   CanvasPattern.cc
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(537,1): warning C4127: conditional expression is constant [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(469): message : see reference to function template instantiation 'T v8::internal::Internals::ReadRawField<uint16_t>(v8::internal::Address,int)' being compiled [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR!           with
    npm ERR!           [
    npm ERR!               T=uint16_t
    npm ERR!           ]
    npm ERR!   CanvasRenderingContext2d.cc
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(537,1): warning C4127: conditional expression is constant [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(469): message : see reference to function template instantiation 'T v8::internal::Internals::ReadRawField<uint16_t>(v8::internal::Address,int)' being compiled [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR!           with
    npm ERR!           [
    npm ERR!               T=uint16_t
    npm ERR!           ]
    npm ERR!   closure.cc
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(537,1): warning C4127: conditional expression is constant [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(469): message : see reference to function template instantiation 'T v8::internal::Internals::ReadRawField<uint16_t>(v8::internal::Address,int)' being compiled [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR!           with
    npm ERR!           [
    npm ERR!               T=uint16_t
    npm ERR!           ]
    npm ERR!   color.cc
    npm ERR!   Image.cc
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(537,1): warning C4127: conditional expression is constant [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(469): message : see reference to function template instantiation 'T v8::internal::Internals::ReadRawField<uint16_t>(v8::internal::Address,int)' being compiled [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR!           with
    npm ERR!           [
    npm ERR!               T=uint16_t
    npm ERR!           ]
    npm ERR!   ImageData.cc
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(537,1): warning C4127: conditional expression is constant [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(469): message : see reference to function template instantiation 'T v8::internal::Internals::ReadRawField<uint16_t>(v8::internal::Address,int)' being compiled [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR!           with
    npm ERR!           [
    npm ERR!               T=uint16_t
    npm ERR!           ]
    npm ERR!   init.cc
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(537,1): warning C4127: conditional expression is constant [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR! C:\Users\runneradmin\.electron-gyp\18.3.5\include\node\v8-internal.h(469): message : see reference to function template instantiation 'T v8::internal::Internals::ReadRawField<uint16_t>(v8::internal::Address,int)' being compiled [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR!           with
    npm ERR!           [
    npm ERR!               T=uint16_t
    npm ERR!           ]
    npm ERR!   register_font.cc
    npm ERR!   win_delay_load_hook.cc
    npm ERR!      Creating library D:\a\anioke\anioke\node_modules\canvas\build\Release\canvas.lib and object D:\a\anioke\anioke\node_modules\canvas\build\Release\canvas.exp
    npm ERR! Canvas.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::shared_ptr<class v8::BackingStore> __cdecl v8::ArrayBuffer::GetBackingStore(void)" (__imp_?GetBackingStore@ArrayBuffer@v8@@QEAA?AV?$shared_ptr@VBackingStore@v8@@@std@@XZ) referenced in function "void __cdecl parsePNGArgs(class v8::Local<class v8::Value>,struct PngClosure &)" (?parsePNGArgs@@YAXV?$Local@VValue@v8@@@v8@@AEAUPngClosure@@@Z) [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR! CanvasRenderingContext2d.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class std::shared_ptr<class v8::BackingStore> __cdecl v8::ArrayBuffer::GetBackingStore(void)" (__imp_?GetBackingStore@ArrayBuffer@v8@@QEAA?AV?$shared_ptr@VBackingStore@v8@@@std@@XZ) [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR! ImageData.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class std::shared_ptr<class v8::BackingStore> __cdecl v8::ArrayBuffer::GetBackingStore(void)" (__imp_?GetBackingStore@ArrayBuffer@v8@@QEAA?AV?$shared_ptr@VBackingStore@v8@@@std@@XZ) [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR! D:\a\anioke\anioke\node_modules\canvas\build\Release\canvas.node : fatal error LNK1120: 1 unresolved externals [D:\a\anioke\anioke\node_modules\canvas\build\canvas.vcxproj]
    npm ERR! Failed to execute 'C:\hostedtoolcache\windows\node\18.8.0\x64\node.exe C:\hostedtoolcache\windows\node\18.8.0\x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --update-binary --module=D:\a\anioke\anioke\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=D:\a\anioke\anioke\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v18.3' (1)
    npm ERR! node-pre-gyp info it worked if it ends with ok
    npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
    npm ERR! node-pre-gyp info using node@18.8.0 | win32 | x64
    npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.3/canvas-v2.9.3-electron-v18.3-win32-unknown-x64.tar.gz
    npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.3/canvas-v2.9.3-electron-v18.3-win32-unknown-x64.tar.gz 
    npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.3 and electron@18.3.5 (electron-v18.3 ABI, unknown) (falling back to source compile with node-gyp) 
    npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.3/canvas-v2.9.3-electron-v18.3-win32-unknown-x64.tar.gz 
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.1.0
    npm ERR! gyp info using node@18.8.0 | win32 | x64
    npm ERR! gyp info ok 
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.1.0
    npm ERR! gyp info using node@18.8.0 | win32 | x64
    npm ERR! gyp info find Python using Python version 3.9.13 found at "C:\hostedtoolcache\windows\Python\3.9.13\x64\python3.exe"
    npm ERR! gyp http GET https://electronjs.org/headers/v18.3.5/node-v18.3.5-headers.tar.gz
    npm ERR! gyp http 200 https://artifacts.electronjs.org/headers/dist/v18.3.5/node-v18.3.5-headers.tar.gz
    npm ERR! gyp http GET https://electronjs.org/headers/v18.3.5/SHASUMS256.txt
    npm ERR! gyp http GET https://electronjs.org/headers/v18.3.5/win-x64/node.lib
    npm ERR! gyp http GET https://electronjs.org/headers/v18.3.5/win-x86/node.lib
    npm ERR! gyp http GET https://electronjs.org/headers/v18.3.5/win-arm64/node.lib
    npm ERR! gyp http 200 https://artifacts.electronjs.org/headers/dist/v18.3.5/SHASUMS256.txt
    npm ERR! gyp http 200 https://artifacts.electronjs.org/headers/dist/v18.3.5/win-x86/node.lib
    npm ERR! gyp http 200 https://artifacts.electronjs.org/headers/dist/v18.3.5/win-arm64/node.lib
    npm ERR! gyp http 200 https://artifacts.electronjs.org/headers/dist/v18.3.5/win-x64/node.lib
    npm ERR! gyp info find VS using VS2022 (17.3.32811.3[15](https://github.com/zhxie/anioke/runs/8058376426?check_suite_focus=true#step:7:16)) found at:
    npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
    npm ERR! gyp info find VS run with --verbose for detailed information
    npm ERR! gyp info spawn C:\hostedtoolcache\windows\Python\3.9.13\x64\python3.exe
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   'C:\\hostedtoolcache\\windows\\node\\18.8.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'msvs',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'D:\\a\\anioke\\anioke\\node_modules\\canvas\\build\\config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\hostedtoolcache\\windows\\node\\18.8.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\Users\\runneradmin\\.electron-gyp\\18.3.5\\include\\node\\common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\runneradmin\\.electron-gyp\\18.3.5',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\hostedtoolcache\\windows\\node\\18.8.0\\x64\\node_modules\\npm\\node_modules\\node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\runneradmin\\\\.electron-gyp\\\\18.3.5\\\\<(target_arch)\\\\node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=D:\\a\\anioke\\anioke\\node_modules\\canvas',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'D:\\a\\anioke\\anioke\\node_modules\\canvas\\build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp info ok 
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.1.0
    npm ERR! gyp info using node@18.8.0 | win32 | x64
    npm ERR! gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   'build/binding.sln',
    npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
    npm ERR! gyp info spawn args   '/nologo',
    npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp ERR! build error 
    npm ERR! gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
    npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\hostedtoolcache\windows\node\18.8.0\x64\node_modules\npm\node_modules\node-gyp\lib\build.js:201:23)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
    npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    npm ERR! gyp ERR! System Windows_NT 10.0.20348
    npm ERR! gyp ERR! command "C:\\hostedtoolcache\\windows\\node\\18.8.0\\x64\\node.exe" "C:\\hostedtoolcache\\windows\\node\\18.8.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--update-binary" "--module=D:\\a\\anioke\\anioke\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=D:\\a\\anioke\\anioke\\node_modules\\canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v18.3"
    npm ERR! gyp ERR! cwd D:\a\anioke\anioke\node_modules\canvas
    npm ERR! gyp ERR! node -v v18.8.0
    npm ERR! gyp ERR! node-gyp -v v9.1.0
    npm ERR! gyp ERR! not ok 
    npm ERR! node-pre-gyp ERR! build error 
    npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\hostedtoolcache\windows\node\18.8.0\x64\node.exe C:\hostedtoolcache\windows\node\18.8.0\x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --update-binary --module=D:\a\anioke\anioke\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=D:\a\anioke\anioke\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v18.3' (1)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\a\anioke\anioke\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
    npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:[16](https://github.com/zhxie/anioke/runs/8058376426?check_suite_focus=true#step:7:17))
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.20348
    npm ERR! node-pre-gyp ERR! command "C:\\hostedtoolcache\\windows\\node\\[18](https://github.com/zhxie/anioke/runs/8058376426?check_suite_focus=true#step:7:19).8.0\\x64\\node.exe" "D:\\a\\anioke\\anioke\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
    npm ERR! node-pre-gyp ERR! cwd D:\a\anioke\anioke\node_modules\canvas
    npm ERR! node-pre-gyp ERR! node -v v18.8.0
    npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
    npm ERR! node-pre-gyp ERR! not ok
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\npm\cache\_logs\[20](https://github.com/zhxie/anioke/runs/8058376426?check_suite_focus=true#step:7:21)[22](https://github.com/zhxie/anioke/runs/8058376426?check_suite_focus=true#step:7:23)-08-28T14_38_29_813Z-debug-0.log
    
                    command='C:\hostedtoolcache\windows\node\18.8.0\x64\node.exe' 'C:\hostedtoolcache\windows\node\18.8.0\x64\node_modules\npm\bin\npm-cli.js' rebuild canvas@2.9.3
                    workingDir=
npm ERR! code 1
npm ERR! path D:\a\anioke\anioke
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c electron-builder install-app-deps && cp node_modules/@jellyfin/libass-wasm/dist/js/subtitles-octopus-worker.* public/

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm\cache\_logs\2022-08-28T14_37_07_[26](https://github.com/zhxie/anioke/runs/8058376426?check_suite_focus=true#step:7:27)8Z-debug-0.log
```

**Comment by maoqxxmm** [comment]
Guys, I've found another canvas library for node: https://github.com/Brooooooklyn/canvas.
It is pre-built and requires no dependency been pre-installed.

**Comment by GitMurf** [comment]
@maoqxxmm I am required to use this Canvas library as it is a dependency for another library. Did you ever figure out what the problem was here and a way to fix it? Thanks!

**Comment by coycoylaniba** [comment]
@GitMurf did figure this out?

**Comment by GitMurf** [comment]
@coycoylaniba I suspect this issue was due to node-canvas not using the node-addon-api in the past. Just recently the team has finished a PR for moving to use the node-addon-api and should have a new release (sounds like v3.0) soon! See here: https://github.com/Automattic/node-canvas/pull/2235

**Comment by coycoylaniba** [comment]
this sounds, im excited for this fix. thanks man
