### ISSUE TITLE
Can't Install on Heroku

### ISSUE THREAD

**Issue by imbkz** [Automattic/node-canvas#2146]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

## Steps to Reproduce

```
npm i canvas
```
Complete log:

```
Enumerating objects: 24, done.
Counting objects: 100% (24/24), done.
Delta compression using up to 6 threads
Compressing objects: 100% (23/23), done.
Writing objects: 100% (24/24), 18.47 KiB | 9.24 MiB/s, done.
Total 24 (delta 8), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Building on the Heroku-22 stack
remote: -----> Determining which buildpack to use for this app
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        USE_YARN_CACHE=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  unspecified
remote:        engines.npm (package.json):   unspecified (use default)
remote:        engines.yarn (package.json):  unspecified (use default)
remote:
remote:        Resolving node version 18.x...
remote:        Downloading and installing node 18.12.0...
remote:        Using default npm version: 8.19.2
remote:        Resolving yarn version 1.22.x...
remote:        Downloading and installing yarn (1.22.19)
remote:        Installed yarn 1.22.19
remote:
remote: -----> Installing dependencies
remote:        Installing node modules (yarn.lock)
remote:        yarn install v1.22.19
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        [3/4] Linking dependencies...
remote:        [4/4] Building fresh packages...
remote:        error /tmp/build_5042c9b0/node_modules/canvas: Command failed.
remote:        Exit code: 1
remote:        Command: node-pre-gyp install --fallback-to-build --update-binary
remote:        Arguments:
remote:        Directory: /tmp/build_5042c9b0/node_modules/canvas
remote:        Output:
remote:        node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.10.1/canvas-v2.10.1-node-v108-linux-glibc-x64.tar.gz
remote:        Package pangocairo was not found in the pkg-config search path.
remote:        Perhaps you should add the directory containing `pangocairo.pc'
remote:        to the PKG_CONFIG_PATH environment variable
remote:        No package 'pangocairo' found
remote:        gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
remote:        gyp ERR! configure error
remote:        gyp ERR! stack Error: `gyp` failed with exit code: 1
remote:        gyp ERR! stack     at ChildProcess.onCpExit (/tmp/build_5042c9b0/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:284:16)
remote:        gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
remote:        gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
remote:        gyp ERR! System Linux 4.4.0-1104-aws
remote:        gyp ERR! command "/tmp/build_5042c9b0/.heroku/node/bin/node" "/tmp/build_5042c9b0/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/tmp/build_5042c9b0/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/tmp/build_5042c9b0/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
remote:        gyp ERR! cwd /tmp/build_5042c9b0/node_modules/canvas
remote:        gyp ERR! node -v v18.12.0
remote:        gyp ERR! node-gyp -v v9.1.0
remote:        gyp ERR! not ok
remote:        node-pre-gyp ERR! build error
remote:        node-pre-gyp ERR! stack Error: Failed to execute '/tmp/build_5042c9b0/.heroku/node/bin/node /tmp/build_5042c9b0/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/tmp/build_5042c9b0/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/tmp/build_5042c9b0/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
remote:        node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/build_5042c9b0/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
remote:        node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
remote:        node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
remote:        node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
remote:        node-pre-gyp ERR! System Linux 4.4.0-1104-aws
remote:        node-pre-gyp ERR! command "/tmp/build_5042c9b0/.heroku/node/bin/node" "/tmp/build_5042c9b0/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
remote:        node-pre-gyp ERR! cwd /tmp/build_5042c9b0/node_modules/canvas
remote:        node-pre-gyp ERR! node -v v18.12.0
remote:        node-pre-gyp ERR! node-pre-gyp -v v1.0.10
remote:        node-pre-gyp ERR! not ok
remote:        Failed to execute '/tmp/build_5042c9b0/.heroku/node/bin/node /tmp/build_5042c9b0/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/tmp/build_5042c9b0/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/tmp/build_5042c9b0/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
remote:        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        Some possible problems:
remote:
remote:        - Node version not specified in package.json
remote:          https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to .
remote:
To https://git.heroku.com/
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): ` v1.22.19`
* Environment
* Node `16.13.2`

**Comment by zbjornson** [comment]
node-canvas v2.10.2 is now published with support for Node 18. (Your logs say you're using 18, not 16.)
