### ISSUE TITLE
Fallback compilation not working on ARM mac

### ISSUE THREAD

**Issue by smichaelsen** [Automattic/node-canvas#2161]
## Issue: Installation help
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

* I'm currently updating my project from node 14 to node 16.
* I'm trying to install `canvas` 2.10.2 as a dependency of `webdriver-image-comparison` as a dependency of `wdio-image-comparison-service`.
* I understand there are no prebuilds available for arm macs.
* I installed the requested brew packages `pkg-config cairo pango libpng jpeg giflib librsvg pixman`

`npm i` gives me:

```
npm ERR! code 1
npm ERR! path /Users/smic/PhpstormProjects/my-project/visual-tests/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build --update-binary
npm ERR! Failed to execute '/opt/homebrew/Cellar/node@16/16.18.0/bin/node /opt/homebrew/Cellar/node@16/16.18.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/smic/PhpstormProjects/my-project/visual-tests/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/smic/PhpstormProjects/my-project/visual-tests/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@16.18.0 | darwin | arm64
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.10.2/canvas-v2.10.2-node-v93-darwin-unknown-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.10.2/canvas-v2.10.2-node-v93-darwin-unknown-arm64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.10.2 and node@16.18.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.10.2/canvas-v2.10.2-node-v93-darwin-unknown-arm64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.18.0 | darwin | arm64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.18.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.10.8 found at "/opt/homebrew/opt/python@3.10/bin/python3.10"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.18.0/node-v16.18.0-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v16.18.0/node-v16.18.0-headers.tar.gz failed, reason: unable to get local issuer certificate
npm ERR! gyp ERR! stack     at ClientRequest.<anonymous> (/opt/homebrew/Cellar/node@16/16.18.0/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm ERR! gyp ERR! stack     at ClientRequest.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:494:9)
npm ERR! gyp ERR! stack     at TLSSocket.emit (node:events:525:35)
npm ERR! gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR! gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Darwin 22.1.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node@16/16.18.0/bin/node" "/opt/homebrew/Cellar/node@16/16.18.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/Users/smic/PhpstormProjects/my-project/visual-tests/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/smic/PhpstormProjects/my-project/visual-tests/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /Users/smic/PhpstormProjects/my-project/visual-tests/node_modules/canvas
npm ERR! gyp ERR! node -v v16.18.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/opt/homebrew/Cellar/node@16/16.18.0/bin/node /opt/homebrew/Cellar/node@16/16.18.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/smic/PhpstormProjects/my-project/visual-tests/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/smic/PhpstormProjects/my-project/visual-tests/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/smic/PhpstormProjects/my-project/visual-tests/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1100:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm ERR! node-pre-gyp ERR! System Darwin 22.1.0
npm ERR! node-pre-gyp ERR! command "/opt/homebrew/Cellar/node@16/16.18.0/bin/node" "/Users/smic/PhpstormProjects/my-project/visual-tests/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
npm ERR! node-pre-gyp ERR! cwd /Users/smic/PhpstormProjects/my-project/visual-tests/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v16.18.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/smic/.npm/_logs/2022-11-15T14_44_42_906Z-debug-0.log

```

## Your Environment
* node-canvas: 2.10.2
* node: 16.18.0
* npm: 8.19.2
* macOS: 13.0.1
* Chip: Apple M1 Pro

**Comment by LinusU** [comment]
> request to https://nodejs.org/download/release/v16.18.0/node-v16.18.0-headers.tar.gz failed, reason: unable to get local issuer certificate

Hmm, I can download that file just fine. Could it be a something with your internet connection? Are you on a corporate network? Or maybe it was a temporary problem with the nodejs.org site...

**Comment by smichaelsen** [comment]
A bit embarrassing, but you're right. It's an issue within our corporate network. Thanks for the pointer!
