### ISSUE TITLE
Throws 404 after I restart the code around 5 times

### ISSUE THREAD

**Issue by DaKing01** [Automattic/node-canvas#2163]
I was updating code elsewhere on my bot (restarted about 6 times) then every time it kept throwing this error until I deleted node_moduals then re-installed the npm then it started to work

```js
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: Server responded with 404
    at /home/container/node_modules/canvas/lib/image.js:59:28
    at /home/container/node_modules/simple-get/index.js:97:7
    at IncomingMessage.<anonymous> (/home/container/node_modules/simple-concat/index.js:8:13)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:384:10)
    at processTicksAndRejections (node:internal/process/task_queues:85:21)
    ```

**Comment by LinusU** [comment]
It seems like you are loading in an image for which the server gives you a 404 error.

I don't believe that this is an issue in Canvas, and without more information there isn't really anything that we can do on our side...

Happy to reopen if you can provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)!
