### ISSUE TITLE
Error during electron-rebuild

### ISSUE THREAD

**Issue by gabidut** [Automattic/node-canvas#2168]
## Steps to Reproduce
Simply run  `.\node_modules\.bin\electron-rebuild` in Powershell

Error : 

```
An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'F:\.0A\zgen\caisse\node_modules\canvas'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1



Error: node-gyp failed to rebuild 'F:\.0A\zgen\caisse\node_modules\canvas'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1


    at NodeGyp.rebuildModule (F:\.0A\zgen\caisse\node_modules\electron-rebuild\lib\src\module-type\node-gyp.js:120:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ModuleRebuilder.rebuildNodeGypModule (F:\.0A\zgen\caisse\node_modules\electron-rebuild\lib\src\module-rebuilder.js:98:9)
    at async ModuleRebuilder.rebuild (F:\.0A\zgen\caisse\node_modules\electron-rebuild\lib\src\module-rebuilder.js:128:14)
    at async Rebuilder.rebuildModuleAt (F:\.0A\zgen\caisse\node_modules\electron-rebuild\lib\src\rebuild.js:149:13)
    at async Rebuilder.rebuild (F:\.0A\zgen\caisse\node_modules\electron-rebuild\lib\src\rebuild.js:112:17)
    at async F:\.0A\zgen\caisse\node_modules\electron-rebuild\lib\src\cli.js:158:9
```

## Your Environment
* Version of node-canva : canvas@2.10.2
* Environment : Node v18.12.1 on Windows 11 22H2 (22621.819)

**Comment by LinusU** [comment]
> For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Could you do this and post the output?
