### ISSUE TITLE
node-gyp crash on `npm install --save canvas@2.8.0` with Node.js v19.2.0

### ISSUE THREAD

**Issue by tirithen** [Automattic/node-canvas#2173]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

The issue that I have **is** related to installation described in the "troubleshooting guide" but I was not able to find my solution there.

I'm trying to install "canvas" version 2.8.0 with stable Node.js 19.2.0 and I get both 404 failed downloads of pre-built packages and node-gyp compilation errors.

How can I have the command `npm install --save canvas@2.8.0` working again?

## Steps to Reproduce

1. Install Node.js version 19.2.0 on a Linux x86 machine/docker image

2. Install canvas 2.8.0 in a new project:

```
mkdir canvastest
cd canvastest
echo "{}" > package.json
npm install --save canvas2.8.0
```

3. Inspect the resulting compilation error

```
npm ERR! code 1
npm ERR! path /home/user/Projects/canvastest/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build
npm ERR! make: Går till katalogen ”/home/user/Projects/canvastest/node_modules/canvas/build”
npm ERR!   SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
npm ERR!   COPY Release/canvas-postbuild.node
npm ERR!   CXX(target) Release/obj.target/canvas/src/backend/Backend.o
npm ERR!   CXX(target) Release/obj.target/canvas/src/backend/ImageBackend.o
npm ERR!   CXX(target) Release/obj.target/canvas/src/backend/PdfBackend.o
npm ERR!   CXX(target) Release/obj.target/canvas/src/backend/SvgBackend.o
npm ERR!   CXX(target) Release/obj.target/canvas/src/bmp/BMPParser.o
npm ERR!   CXX(target) Release/obj.target/canvas/src/Backends.o
npm ERR!   CXX(target) Release/obj.target/canvas/src/Canvas.o
npm ERR! make: Lämnar katalogen ”/home/user/Projects/canvastest/node_modules/canvas/build”
npm ERR! Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/user/Projects/canvastest/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/user/Projects/canvastest/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v111' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@19.2.0 | linux | x64
npm ERR! node-pre-gyp info check checked for "/home/user/Projects/canvastest/node_modules/canvas/build/Release/canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v111-linux-glibc-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v111-linux-glibc-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@19.2.0 (node-v111 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v111-linux-glibc-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@19.2.0 | linux | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@19.2.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.10.8 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/user/Projects/canvastest/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/user/.cache/node-gyp/19.2.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/user/.cache/node-gyp/19.2.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/user/.cache/node-gyp/19.2.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/user/Projects/canvastest/node_modules/canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@19.2.0 | linux | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! I filen inkluderad ifrån /home/user/.cache/node-gyp/19.2.0/include/node/v8-object.h:10,
npm ERR!                    ifrån /home/user/.cache/node-gyp/19.2.0/include/node/v8-array-buffer.h:13,
npm ERR!                    ifrån /home/user/.cache/node-gyp/19.2.0/include/node/v8.h:24,
npm ERR!                    ifrån /home/user/.cache/node-gyp/19.2.0/include/node/node.h:73,
npm ERR!                    ifrån ../../nan/nan.h:60,
npm ERR!                    ifrån ../src/backend/Backend.h:6,
npm ERR!                    ifrån ../src/backend/Backend.cc:1:
npm ERR! I medlemsfunktion ”bool v8::PersistentBase<T>::IsEmpty() const [with T = v8::Object]”,
npm ERR!     inline:ad från ”void v8::PersistentBase<T>::Reset() [with T = v8::Object]” vid /home/user/.cache/node-gyp/19.2.0/include/node/v8-persistent-handle.h:474:20,
npm ERR!     inline:ad från ”void v8::PersistentBase<T>::Reset(v8::Isolate*, const v8::Local<S>&) [with S = v8::Object; T = v8::Object]” vid /home/user/.cache/node-gyp/19.2.0/include/node/v8-persistent-handle.h:487:8,
npm ERR!     inline:ad från ”void Nan::Persistent<T, M>::Reset(const v8::Local<S>&) [with S = v8::Object; T = v8::Object; M = v8::NonCopyablePersistentTraits<v8::Object>]” vid ../../nan/nan_persistent_12_inl.h:29:33,
npm ERR!     inline:ad från ”void Nan::ObjectWrap::Wrap(v8::Local<v8::Object>)” vid ../../nan/nan_object_wrap.h:56:23,
npm ERR!     inline:ad från ”static void Backend::init(const Nan::FunctionCallbackInfo<v8::Value>&)” vid ../src/backend/Backend.cc:23:16:
npm ERR! /home/user/.cache/node-gyp/19.2.0/include/node/v8-persistent-handle.h:116:43: varning: vektorindexet 0 är utanför vektorgränserna för ”Nan::Persistent<v8::Object> [0]” [-Warray-bounds]
npm ERR!   116 |   V8_INLINE bool IsEmpty() const { return val_ == nullptr; }
npm ERR!       |                                           ^~~~
npm ERR! I medlemsfunktion ”void v8::PersistentBase<T>::Reset() [with T = v8::Object]”,
npm ERR!     inline:ad från ”void v8::PersistentBase<T>::Reset(v8::Isolate*, const v8::Local<S>&) [with S = v8::Object; T = v8::Object]” vid /home/user/.cache/node-gyp/19.2.0/include/node/v8-persistent-handle.h:487:8,
npm ERR!     inline:ad från ”void Nan::Persistent<T, M>::Reset(const v8::Local<S>&) [with S = v8::Object; T = v8::Object; M = v8::NonCopyablePersistentTraits<v8::Object>]” vid ../../nan/nan_persistent_12_inl.h:29:33,
npm ERR!     inline:ad från ”void Nan::ObjectWrap::Wrap(v8::Local<v8::Object>)” vid ../../nan/nan_object_wrap.h:56:23,
npm ERR!     inline:ad från ”static void Backend::init(const Nan::FunctionCallbackInfo<v8::Value>&)” vid ../src/backend/Backend.cc:23:16:
npm ERR! /home/user/.cache/node-gyp/19.2.0/include/node/v8-persistent-handle.h:476:8: varning: vektorindexet 0 är utanför vektorgränserna för ”Nan::Persistent<v8::Object> [0]” [-Warray-bounds]
npm ERR!   476 |   val_ = nullptr;
npm ERR!       |   ~~~~~^~~~~~~~~
npm ERR! I medlemsfunktion ”void v8::PersistentBase<T>::Reset(v8::Isolate*, const v8::Local<S>&) [with S = v8::Object; T = v8::Object]”,
npm ERR!     inline:ad från ”void Nan::Persistent<T, M>::Reset(const v8::Local<S>&) [with S = v8::Object; T = v8::Object; M = v8::NonCopyablePersistentTraits<v8::Object>]” vid ../../nan/nan_persistent_12_inl.h:29:33,
npm ERR!     inline:ad från ”void Nan::ObjectWrap::Wrap(v8::Local<v8::Object>)” vid ../../nan/nan_object_wrap.h:56:23,
npm ERR!     inline:ad från ”static void Backend::init(const Nan::FunctionCallbackInfo<v8::Value>&)” vid ../src/backend/Backend.cc:23:16:
npm ERR! /home/user/.cache/node-gyp/19.2.0/include/node/v8-persistent-handle.h:489:14: varning: vektorindexet 0 är utanför vektorgränserna för ”Nan::Persistent<v8::Object> [0]” [-Warray-bounds]
npm ERR!   489 |   this->val_ = New(isolate, other.val_);
npm ERR!       |   ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! I filen inkluderad ifrån ../src/Canvas.cc:21:
npm ERR! ../src/Util.h: I funktion ”void SetProtoAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::FunctionTemplate>)”:
npm ERR! ../src/Util.h:25:21: fel: ”v8::AccessorSignature” har inte deklarerats
npm ERR!    25 |                 v8::AccessorSignature::New(v8::Isolate::GetCurrent(), ctor)
npm ERR!       |                     ^~~~~~~~~~~~~~~~~
npm ERR! make: *** [canvas.target.mk:162: Release/obj.target/canvas/src/Canvas.o] Fel 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Linux 6.0.11-zen1-1-zen
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/user/Projects/canvastest/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/user/Projects/canvastest/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v111"
npm ERR! gyp ERR! cwd /home/user/Projects/canvastest/node_modules/canvas
npm ERR! gyp ERR! node -v v19.2.0
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/user/Projects/canvastest/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/user/Projects/canvastest/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v111' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/user/Projects/canvastest/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm ERR! node-pre-gyp ERR! System Linux 6.0.11-zen1-1-zen
npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/home/user/Projects/canvastest/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /home/user/Projects/canvastest/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v19.2.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-12-12T15_33_17_528Z-debug-0.log
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): 2.8.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): npm 8.19.0, Node.js v19.2.0 on Arch Linux

**Comment by Sceat** [comment]
You can't install `2.8.0`, [you need to upgrade to 2.10.x](https://github.com/Automattic/node-canvas/issues/2144)
