### ISSUE TITLE
Google Cloud Virtual Machine Linux error

### ISSUE THREAD

**Issue by M-Darksider** [Automattic/node-canvas#2177]
Google Cloud VM Server responded with 404

on the virtual machine, the user profile that was created using the canvas module stopped working correctly, giving the error Server responded with 404

**Comment by M-Darksider** [comment]
Error: Server responded with 404
    at /home/your_senpai131/pushBot/node_modules/canvas/lib/image.js:59:28
    at /home/your_senpai131/pushBot/node_modules/simple-get/index.js:97:7
    at IncomingMessage.<anonymous> (/home/your_senpai131/pushBot/node_modules/simple-concat/index.js:8:13)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by LinusU** [comment]
> Error: Server responded with 404

This means that the server that you tried to load an image from is responding with a 404 status code.

Without a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) I cannot help you further...
