### ISSUE TITLE
Can't load images from long path

### ISSUE THREAD

**Issue by KennyHarrer** [Automattic/node-canvas#2230]
## Issue or Feature
The loadImage function doesn't work with long paths, error thrown is unhelpful. Files can be access normally through explorer, and fs.access.

## Steps to Reproduce
store image in a long path, load image, get the following error.

```
SetSource.call(img, src)
            ^

Error: ENOENT, No such file or directory 'C:\Users\k\Desktop\Programming\github\--------------------\temp\---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\firstFrame.jpg'
    at setSource (C:\Users\k\Desktop\Programming\github\--------------------\node_modules\canvas\lib\image.js:94:13)
    at Image.set (C:\Users\k\Desktop\Programming\github\--------------------\node_modules\canvas\lib\image.js:65:9)
    at C:\Users\k\Desktop\Programming\github\--------------------\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\k\Desktop\Programming\github\--------------------\node_modules\canvas\index.js:23:10)
    at C:\Users\k\Desktop\Programming\github\--------------------\textbox.js:4:11
    at Object.<anonymous> (C:\Users\k\Desktop\Programming\github\--------------------\textbox.js:46:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  errno: 2,
  code: 'ENOENT',
  path: 'C:\\Users\\k\\Desktop\\Programming\\github\\--------------------\\temp\\---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\\firstFrame.jpg',
  syscall: 'fopen'
}
```

## Your Environment
win 11, node v18.15.0, canvas@2.11.2

**Comment by zbjornson** [comment]
You can probably work around this by setting `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled` (Type: REG_DWORD) to 1. See https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry.

**Comment by LinusU** [comment]
> Files can be access normally through explorer, and fs.access.

Can you also read the file using `fs.readFile`?

> In the Windows API (with some exceptions discussed in the following paragraphs), the maximum length for a path is MAX_PATH, which is defined as 260 characters.

In that case, we might be able to use fs.readFile if path.length >= 260? 🤔

**Comment by thot-experiment** [comment]
I'm having the same error, however my file path is only 114 characters in length but *does* have diacritics (`g:/.../Mucha/Alfons_Mucha_-_F._Champenois_Imprimeur-Éditeur.jpg`) and the results is the same error. Reading the full as well as a relative path with `fs.readfileSync` in the node REPL works just fine.

```
SetSource.call(img, src)
            ^

Error: ENOENT, No such file or directory

  ..... 

  errno: 2,
  code: 'ENOENT',
  path: 'g:/.../Alfons_Mucha_-_F._Champenois_Imprimeur-Éditeur.jpg',
  syscall: 'fopen'
}
```

I'm on win 10 node 20 canvas 2.11.2
