### ISSUE TITLE
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found 

### ISSUE THREAD

**Issue by pruteanualex** [Automattic/node-canvas#2256]
## Issue or Feature
- [ ] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

## Steps to Reproduce

```js
const GIFEncoder = require('gifencoder');
const { createCanvas, loadImage} = require('canvas');;
const canvas = createCanvas(width , height );
const ctx = canvas.getContext('2d');

// Encode gif settings
    const encoder = new GIFEncoder(width , height );
    encoder.createReadStream().pipe(fs.createWriteStream(tempPath+'/user_gif_'+clientID+'/gif/giff_generated.gif'));
    encoder.start();
    encoder.setRepeat(0);
    encoder.setDelay(gif_delay);
    encoder.setQuality(gif_quality);
    
    // read image
    const imgList = fs.readdirSync(tempPath+'/user_gif_'+clientID+'/converted');
    imgList.forEach(async (f, i) => {
        let imagePath = `${tempPath}/user_gif_${clientID}/converted/${f}`;
        const image =  await loadImage(imagePath);
        if(image){
            ctx.drawImage(image, 0, 0, image.width, image.height, 0, 0, canvas.width, canvas.height);
            encoder.addFrame(ctx);
            if (i === imgList.length - 1) {
                encoder.finish();
                next()
            }
        }
    });
// etc.
```
## Error
```
App 13130 output: node:internal/modules/cjs/loader:1280
App 13130 output:   return process.dlopen(module, path.toNamespacedPath(filename));
App 13130 output:                  ^
App 13130 output: Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /..../node_modules/canvas/build/Release/canvas.node)
App 13130 output:     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1280:18)
App 13130 output:     at Module.load (node:internal/modules/cjs/loader:1074:32)
App 13130 output:     at Function.Module._load (node:internal/modules/cjs/loader:909:12)
App 13130 output:     at Module.require (node:internal/modules/cjs/loader:1098:19)
App 13130 output:     at Module.require (/opt/cpanel/ea-ruby27/root/usr/share/passenger/helper-scripts/node-loader.js:80:25)
App 13130 output:     at require (node:internal/modules/cjs/helpers:108:18)
App 13130 output:     at Object.<anonymous> (/home/wdupbwbc/nodevenv/image-gif.whm360.ro/16/lib/node_modules/canvas/lib/bindings.js:3:18)
App 13130 output:     at Module._compile (node:internal/modules/cjs/loader:1196:14)
App 13130 output:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
App 13130 output:     at Module.load (node:internal/modules/cjs/loader:1074:32) {
App 13130 output:   code: 'ERR_DLOPEN_FAILED'
App 13130 output: }
```

## Your Environment
* Version of node-canvas (output of `npm list canvas@2.11.2`):
* Environment (e.g. node 16.20.0 on Linux):

**Comment by diamont1001** [comment]
any solutions?

**Comment by pruteanualex** [comment]
Yes, I found a solution, it's not the cleanest approximation, but for me the application works without problems.
I downloaded the code source for the **gifencoder** version **2.0.1** module locally and uploaded it to the online server, which I added to the **modules** folder <<[https://mega.nz/folder/DtZFhTYQ#GrYM57_-kZQzp0qUWmYnzA](https://mega.nz/folder/DtZFhTYQ#GrYM57_-kZQzp0qUWmYnzA)>> from here you can download the code I have.

const GIFEncoder = require('../modules/gifencoder');
const { createCanvas, loadImage} = require('canvas');  **"canvas": "^2.9.3",**

`exports.convertImageToGif = catchAsync(async(req,res,next)=>{
    console.log('Convert gif start')

    //create a canvas
    const canvas = createCanvas(width , height );
    const ctx = canvas.getContext('2d');


    // Encode gif settings
    const encoder = new GIFEncoder(width , height );
    encoder.createReadStream().pipe(fs.createWriteStream('randomIdGif.gif'));
    encoder.start();
    encoder.setRepeat(0);
    encoder.setDelay(gif_delay);
    encoder.setQuality(gif_quality);

    
    // read image
    const imgList = fs.readdirSync('converted-images-folder');

    let createGifPromise = new Promise((resolve, reject) => {
        imgList.forEach(async (f, i) => {
            let imagePath = `${tempPath}/user_gif_${clientID}/converted/${f}`;
            const image =  await loadImage(imagePath);
            if(image){
                ctx.drawImage(image, 0, 0, image.width, image.height, 0, 0, canvas.width, canvas.height);
                encoder.addFrame(ctx);
                if (i === imgList.length - 1) {
                    encoder.finish();
                    resolve();
                }
            }
        });
    });

    createGifPromise.then(() => {
        // set local data
        console.log('Gif Created Succesfully')
        next();
    }).catch(e =>{
 
        res.status(404).json({
            status:"failed",
            error:"Error create gif:"+e
        })
    });
});`
