### ISSUE TITLE
Cannot install on Windows 7 x64

### ISSUE THREAD

**Issue by Fauntleroy** [Automattic/node-canvas#226]
I've tried everything I can to install node-canvas on my Windows machine, but I've hit a brick wall here. Any idea what my issue is?

```
C:\Users\Timothy\Repos\tandem.io-drawing\node_modules\canvas>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@0.7.1
gyp info using node@0.8.11 | win32 | x64
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/property:TargetExt=.node',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platf
orm for project 'canvas.vcxproj' is invalid.  Platform='x64'. You may be seeing this message because you are trying to
build a project without a solution file, and have specified a non-default Platform that doesn't exist for this project.
 [C:\Users\Timothy\Repos\tandem.io-drawing\node_modules\canvas\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Timothy\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:236:2
3)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:96:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "node" "C:\\Users\\Timothy\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\Users\Timothy\Repos\tandem.io-drawing\node_modules\canvas
gyp ERR! node -v v0.8.11
gyp ERR! node-gyp -v v0.7.1
gyp ERR! not ok```

**Comment by zorobabel** [comment]
Hey guys, I've posted [a solution](https://github.com/Automattic/node-canvas/issues/619) for this.

**Comment by LinusU** [comment]
Please see the posted solution, or the updated wiki-page...
