### ISSUE TITLE
npm ERR! gyp http GET https://atom.io/download/electron/v5.0.13/node-v5.0.13-headers.tar.gz  on MacOS

### ISSUE THREAD

**Issue by luohao8023** [Automattic/node-canvas#2265]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

## Steps to Reproduce

`npm install canvas`   
```
npm ERR! code 1
npm ERR! path /Volumes/canvasTest/node_modules/node-canvas
npm ERR! command failed
npm ERR! command sh -c -- node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.20.1 | darwin | x64
npm ERR! gyp info find Python using Python version 3.8.2 found at "/Library/Frameworks/Python.framework/Versions/3.8/bin/python3"
npm ERR! gyp http GET https://atom.io/download/electron/v5.0.13/node-v5.0.13-headers.tar.gz
npm ERR! gyp http 200 https://github.blog/2022-06-08-sunsetting-atom/
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: TAR_BAD_ARCHIVE: Unrecognized archive format
npm ERR! gyp ERR! stack     at Unpack.warn (/Users/Robinhood/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/tar/lib/warn-mixin.js:19:40)
npm ERR! gyp ERR! stack     at Unpack.warn (/Users/Robinhood/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/tar/lib/unpack.js:220:18)
npm ERR! gyp ERR! stack     at Unpack.<anonymous> (/Users/Robinhood/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:81:14)
npm ERR! gyp ERR! stack     at Unpack.emit (node:events:525:35)
npm ERR! gyp ERR! stack     at Unpack.[emit] (/Users/Robinhood/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:285:12)
npm ERR! gyp ERR! stack     at Unpack.[maybeEnd] (/Users/Robinhood/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:401:17)
npm ERR! gyp ERR! stack     at Unpack.[consumeChunk] (/Users/Robinhood/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:432:21)
npm ERR! gyp ERR! stack     at Unpack.write (/Users/Robinhood/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:364:25)
npm ERR! gyp ERR! stack     at Unpack.end (/Users/Robinhood/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:477:14)
npm ERR! gyp ERR! stack     at ShaSum.onend (node:internal/streams/readable:693:10)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/Users/Robinhood/.nvm/versions/node/v16.20.1/bin/node" "/Users/Robinhood/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Volumes/canvasTest/node_modules/node-canvas
npm ERR! gyp ERR! node -v v16.20.1
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Robinhood/.npm/_logs/2023-07-06T06_16_08_623Z-debug-0.log
```
Node-gyp tried to download something from [https://atom.io/download/electron/v5.0.13/node-v5.0.13-headers.tar.gz](https://atom.io/download/electron/v5.0.13/node-v5.0.13-headers.tar.gz)which was redirected to https://github.blog/2022-06-08-sunsetting-atom/ and returns nothing,but I'm not use canvas with Electron.
## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`):2.11.0
* Environment (e.g. node 4.2.0 on Mac OS X 10.8):node 16.20.1 on Mac OS Monterey 12.5

**Comment by luohao8023** [comment]
```
Failed to execute '/Users/Robinhood/.nvm/versions/node/v16.20.1/bin/node /Users/Robinhood/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/Robinhood/Desktop/node-canvas-master/build/Release/canvas.node --module_name=canvas --module_path=/Users/Robinhood/Desktop/node-canvas-master/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v5.0 --python=/Library/Frameworks/Python.framework/Versions/2.7/bin/python'
```
I'm not install with Electron,how can I change this arg `--node_napi_label=electron-v5.0`?

**Comment by luohao8023** [comment]
Run `npm config ls`:
```
; "env" config from environment

arch = "x64" 
build-from-source = true 
disturl = "https://atom.io/download/electron" 
runtime = "electron" 
target = "5.0.13" 
target-arch = "x64" 

; node bin location = /usr/local/bin/node
; node version = v16.20.1
; npm local prefix = /Users/Robinhood
; npm version = 8.19.4
; cwd = /Users/Robinhood
; HOME = /Users/Robinhood
; Run `npm config ls -l` to show all defaults.
```
The default disturl is https://atom.io/download/electron  which dosen't exist now. So I tried this:
```
node-gyp install 16.20.1 --dist-url=https://nodejs.org/download/release/
node-gyp configure --nodedir=/Users/Robinhood/Library/Caches/node-gyp/16.20.1
npm install canvas --build-from-source --nodedir=/Users/Robinhood/Library/Caches/node-gyp/16.20.1
```
it worked for me.
