### ISSUE TITLE
/home/runner/2019204310240160Blu/node_modules/canvas/lib/image.js:94   SetSource.call(img, src)             ^  Error: Unsupported image type     at setSource

### ISSUE THREAD

**Issue by alepop123** [Automattic/node-canvas#2275]
## Issue or Feature
/home/runner/2019204310240160Blu/node_modules/canvas/lib/image.js:94
  SetSource.call(img, src)
            ^

Error: Unsupported image type
    at setSource (/home/runner/2019204310240160Blu/node_modules/canvas/lib/image.js:94:13)
    at /home/runner/2019204310240160Blu/node_modules/canvas/lib/image.js:62:11
    at /home/runner/2019204310240160Blu/node_modules/canvas/node_modules/simple-get/index.js:97:7
    at IncomingMessage.<anonymous> (/home/runner/2019204310240160Blu/node_modules/simple-concat/index.js:8:13)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)

repl process died unexpectedly: exit status 1

## Steps to Reproduce

```js
exports.run = async (client, message, args) => {

  let bubblet = message.mentions.members.first() || message.guild.members.cache.get(args[0]) || message.member;

  let nick = await db.fetch(`nick_${bubblet.id}`)
  let amigo1 = await db.fetch(`amigo1_${bubblet.id}`)
  let amigo2 = await db.fetch(`amigo2_${bubblet.id}`)
  let amigo3 = await db.fetch(`amigo3_${bubblet.id}`)
  let cod1 = await db.fetch(`cod1_${bubblet.id}`)
  let cod2 = await db.fetch(`cod2_${bubblet.id}`)
  let cod3 = await db.fetch(`cod3_${bubblet.id}`)
  let cod4 = await db.fetch(`cod4_${bubblet.id}`)
  let cod5 = await db.fetch(`cod5_${bubblet.id}`)

  let bedbed = new Discord.MessageEmbed()
  .setColor('RED')
  .setDescription(`
<:methods_icon_remove:1137551740670058607> | **Voce deve registrar seu nick para usar esse comando!**\n\n Digite **b!regis**`)
  .setFooter(`Bubblet - Sua Bolha de Entretenimento!`)
  .setTimestamp()

  if(nick === null){

  message.channel.send(bedbed)

  } else {

  let perfil = 'https://i.imgur.com/pydQIq6.png'
  let boneco = `https://imager.bubblet.com.br/?user=${nick}&action=&gesture=sml&direction=2&head_direction=3&headonly=false&size=b&img_format=&dance=&effect=&frame_num=30.png`

  let amg1 = `https://imager.bubblet.com.br/?user=${amigo1}&action=&gesture=std&direction=4&head_direction=4&headonly=true&size=b&img_format=&dance=&effect=&frame_num=30.png`
  if(amg1 === null) amg1 = `https://i.imgur.com/JAJWayY.png`;
  let amg2 = `https://imager.bubblet.com.br/?user=${amigo2}&action=&gesture=std&direction=4&head_direction=4&headonly=true&size=b&img_format=&dance=&effect=&frame_num=30.png`
  if(amg2 === null) amg2 = `https://i.imgur.com/JAJWayY.png`;
  let amg3 = `https://imager.bubblet.com.br/?user=${amigo3}&action=&gesture=std&direction=4&head_direction=4&headonly=true&size=b&img_format=&dance=&effect=&frame_num=30.png`
  if(amg3 === null) amg3 = `https://i.imgur.com/JAJWayY.png`;

  const canvas = Canvas.createCanvas(567, 314);
  const ctx = canvas.getContext('2d');
  const background = await Canvas.loadImage(perfil);
  const bonec = await Canvas.loadImage(boneco);
  const a1 = await Canvas.loadImage(amg1);
  const a2 = await Canvas.loadImage(amg2);
  const a3 = await Canvas.loadImage(amg3);


  
  ctx.drawImage(background, 0, 0, canvas.width, canvas.height);
  ctx.drawImage(bonec, 10, 50)
  ctx.drawImage(a1, 470, 70)
  ctx.drawImage(a2, 470, 120)
  ctx.drawImage(a3, 470, 170)



                
  const arte = new Discord.MessageAttachment(canvas.toBuffer(), 'uiui.png')


  let bedd = new Discord.MessageEmbed()
  .setColor('#ff53a3')
  .attachFiles([arte]).setImage('attachment://uiui.png')
  .setFooter(`Bubblet - Sua Bolha de Entretenimento!`)
  .setTimestamp()

   
 message.lineReply(bedd)

  } 

}
```

## Your Environment
Canvas: ^2.8.0
Discord.JS: ^12.5.3
Node-Fetch: ^2.6.1

**Comment by zbjornson** [comment]
One of your URLs is likely responding with a non-success error code, potentially because of rate limiting. Please provide a minimal reproducible example and/or try asking on StackOverflow.
