### ISSUE TITLE
Out of memory on load image

### ISSUE THREAD

**Issue by Ellathet** [Automattic/node-canvas#2278]
When a load a image, in my production enviroment canvas returns me a out of memory error. I'm loading a 1920x1920px image.
In my windows (dev env) works with no more problems.
```
2023-08-27T15:54:56.137218+00:00 app[web.1]: Error: out of memory
2023-08-27T15:54:56.137219+00:00 app[web.1]: at setSource (/app/node_modules/canvas/lib/image.js:94:13)
2023-08-27T15:54:56.137224+00:00 app[web.1]: at Image.set (/app/node_modules/canvas/lib/image.js:68:7)
2023-08-27T15:54:56.137225+00:00 app[web.1]: at /app/node_modules/canvas/index.js:34:15
2023-08-27T15:54:56.137225+00:00 app[web.1]: at new Promise (<anonymous>)
2023-08-27T15:54:56.137226+00:00 app[web.1]: at Object.loadImage (/app/node_modules/canvas/index.js:23:10)
2023-08-27T15:54:56.137226+00:00 app[web.1]: at CommissionService.genImage (/app/dist/commission/commission.service.js:139:40)
2023-08-27T15:54:56.137227+00:00 app[web.1]: at async CommissionService.create (/app/dist/commission/commission.service.js:119:34)
2023-08-27T15:54:56.137227+00:00 app[web.1]: at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
2023-08-27T15:54:56.137228+00:00 app[web.1]: at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

## Steps to Reproduce
```ts
canvas.registerFont(this.FONT_DIR, {
        family: 'Co Headline',
      });

const foundImage = await fs.promises.readFile(props[type].imagePath);

const image = await canvas.loadImage(foundImage);
const createdCanvas = canvas.createCanvas(image.width, image.height);
const ctx = createdCanvas.getContext('2d');
```

### Production
Heroku dyno
- 512mb memory
- Node 16x

### Dev
- Win 10
- 32gb memory
- Node 16x

**Comment by Ellathet** [comment]
I change the image type in loading to jpeg and works!

**Comment by Ellathet** [comment]
When a need using a png image, I exported from photoshop as a web image
