### ISSUE TITLE
install error with node 18.18.2

### ISSUE THREAD

**Issue by jswith** [Automattic/node-canvas#2306]
Hi. When I install dependencies with "pnpm install", I get the response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-linux-glibc-arm64.tar.gz error.

## Issue
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

## Steps to Reproduce
```
+ pnpm install
Scope: all 8 workspace projects
 WARN  There are cyclic workspace dependencies
Lockfile is up to date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +2404
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 2404, reused 0, downloaded 0, added 0
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/ec2-user/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 2404, reused 155, downloaded 1, added 151
Progress: resolved 2404, reused 651, downloaded 1, added 652
Progress: resolved 2404, reused 1192, downloaded 1, added 1205
Progress: resolved 2404, reused 1755, downloaded 1, added 1772
Progress: resolved 2404, reused 2325, downloaded 1, added 2340
Progress: resolved 2404, reused 2373, downloaded 1, added 2390
Progress: resolved 2404, reused 2382, downloaded 1, added 2393
Progress: resolved 2404, reused 2386, downloaded 1, added 2404, done
.../canvas@2.11.2/node_modules/canvas install$ node-pre-gyp install --fallback-to-build --update-binary
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp info it worked if it ends with ok
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp info using node-pre-gyp@1.0.11
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp info using node@18.18.2 | linux | arm64
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-linux-glibc-arm64.tar.gz
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-linux-glibc-arm64.tar.gz 
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@18.18.2 (node-v108 ABI, glibc) (falling back to source compile with node-gyp) 
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-linux-glibc-arm64.tar.gz 
.../canvas@2.11.2/node_modules/canvas install: gyp info it worked if it ends with ok
.../canvas@2.11.2/node_modules/canvas install: gyp info using node-gyp@9.3.1
.../canvas@2.11.2/node_modules/canvas install: gyp info using node@18.18.2 | linux | arm64
.../canvas@2.11.2/node_modules/canvas install: gyp info ok 
.../canvas@2.11.2/node_modules/canvas install: gyp info it worked if it ends with ok
.../canvas@2.11.2/node_modules/canvas install: gyp info using node-gyp@9.3.1
.../canvas@2.11.2/node_modules/canvas install: gyp info using node@18.18.2 | linux | arm64
.../canvas@2.11.2/node_modules/canvas install: gyp info find Python using Python version 3.9.16 found at "/usr/bin/python3"
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn /usr/bin/python3
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args [
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '/var/lib/jenkins-slave/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/node_js_18.18.2/lib/node_modules/pnpm/dist/node_modules/node-gyp/gyp/gyp_main.py',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   'binding.gyp',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-f',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   'make',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-I',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '/var/lib/jenkins-slave/workspace/directory/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/config.gypi',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-I',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '/var/lib/jenkins-slave/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/node_js_18.18.2/lib/node_modules/pnpm/dist/node_modules/node-gyp/addon.gypi',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-I',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '/home/ec2-user/.cache/node-gyp/18.18.2/include/node/common.gypi',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-Dlibrary=shared_library',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-Dvisibility=default',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-Dnode_root_dir=/home/ec2-user/.cache/node-gyp/18.18.2',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-Dnode_gyp_dir=/var/lib/jenkins-slave/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/node_js_18.18.2/lib/node_modules/pnpm/dist/node_modules/node-gyp',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-Dnode_lib_file=/home/ec2-user/.cache/node-gyp/18.18.2/<(target_arch)/node.lib',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-Dmodule_root_dir=/var/lib/jenkins-slave/workspace/directory/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-Dnode_engine=v8',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '--depth=.',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '--no-parallel',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '--generator-output',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   'build',
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args   '-Goutput_dir=.'
.../canvas@2.11.2/node_modules/canvas install: gyp info spawn args ]
.../canvas@2.11.2/node_modules/canvas install: Package pixman-1 was not found in the pkg-config search path.
.../canvas@2.11.2/node_modules/canvas install: Perhaps you should add the directory containing `pixman-1.pc'
.../canvas@2.11.2/node_modules/canvas install: to the PKG_CONFIG_PATH environment variable
.../canvas@2.11.2/node_modules/canvas install: Package 'pixman-1', required by 'virtual:world', not found
.../canvas@2.11.2/node_modules/canvas install: gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
.../canvas@2.11.2/node_modules/canvas install: gyp ERR! configure error 
.../canvas@2.11.2/node_modules/canvas install: gyp ERR! stack Error: `gyp` failed with exit code: 1
.../canvas@2.11.2/node_modules/canvas install: gyp ERR! stack     at ChildProcess.onCpExit (/var/lib/jenkins-slave/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/node_js_18.18.2/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/configure.js:325:16)
.../canvas@2.11.2/node_modules/canvas install: gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
.../canvas@2.11.2/node_modules/canvas install: gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
.../canvas@2.11.2/node_modules/canvas install: gyp ERR! System Linux 6.1.56-82.125.amzn2023.aarch64
.../canvas@2.11.2/node_modules/canvas install: gyp ERR! command "/home/ec2-user/.local/share/pnpm/nodejs/18.18.2/bin/node" "/var/lib/jenkins-slave/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/node_js_18.18.2/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/var/lib/jenkins-slave/workspace/directory/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/var/lib/jenkins-slave/workspace/directory/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
.../canvas@2.11.2/node_modules/canvas install: gyp ERR! cwd /var/lib/jenkins-slave/workspace/directory/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas
.../canvas@2.11.2/node_modules/canvas install: gyp ERR! node -v v18.18.2
.../canvas@2.11.2/node_modules/canvas install: gyp ERR! node-gyp -v v9.3.1
.../canvas@2.11.2/node_modules/canvas install: gyp ERR! not ok 
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! build error 
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! stack Error: Failed to execute '/home/ec2-user/.local/share/pnpm/nodejs/18.18.2/bin/node /var/lib/jenkins-slave/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/node_js_18.18.2/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/var/lib/jenkins-slave/workspace/sdirectory/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/var/lib/jenkins-slave/workspace/directory/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/lib/jenkins-slave/workspace/directory/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! System Linux 6.1.56-82.125.amzn2023.aarch64
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! command "/home/ec2-user/.local/share/pnpm/nodejs/18.18.2/bin/node" "/var/lib/jenkins-slave/workspace/directory/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! cwd /var/lib/jenkins-slave/workspace/directory/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! node -v v18.18.2
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! node-pre-gyp -v v1.0.11
.../canvas@2.11.2/node_modules/canvas install: node-pre-gyp ERR! not ok 
.../canvas@2.11.2/node_modules/canvas install: Failed to execute '/home/ec2-user/.local/share/pnpm/nodejs/18.18.2/bin/node /var/lib/jenkins-slave/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/node_js_18.18.2/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/var/lib/jenkins-slave/workspace/directory/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/var/lib/jenkins-slave/workspace/directory/node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
.../canvas@2.11.2/node_modules/canvas install: Failed
```

## Your Environment
* node-canvas 2.11.2
* node.js 18.18.2
* amazon linux 2023 aarch64

**Comment by otecMuxah** [comment]
try this step prior to npm install

`brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman`

**Comment by mduivcap** [comment]
`brew` is for OSX right? 
I'm on Windows, what can I do to resolve this?

**Comment by otecMuxah** [comment]
> `brew` is for OSX right? I'm on Windows, what can I do to resolve this?

author has missing package called 'pixman' he needs to install it and run npm i again. My guess it should be like `choco install pixman`

**Comment by DemiSlot** [comment]
I'm also a Windows user. I followed the troubleshooting bit on the bottom of the page on https://github.com/Andremoniy/cypress-visual-regression-resemble-js , I still get the same ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v115-win32-unknown-x64.tar.gz   

choco install pixman does not work either, it gives me a "pixman not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'" error.
