### ISSUE TITLE
Not able to install the package

### ISSUE THREAD

**Issue by ram-uitoux** [Automattic/node-canvas#2326]
While running sudo npm install receiving the following errors. My node version is 14.21.3

Error: The module 'node_modules/canvas/build/Release/canvas.node' was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1173:18)
at Module.load (internal/modules/cjs/loader.js:979:32)
at Function.Module._load (internal/modules/cjs/loader.js:819:12)
at Module.require (internal/modules/cjs/loader.js:1003:19)
at Module.Hook._require.Module.require (/home/ubuntu/.nvm/versions/node/v14.21.3/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
 at require (internal/modules/cjs/helpers.js:107:18)
at Object.<anonymous> (/var/www/tvscrm/backend/RSA-CRM-API-Gateway/node_modules/canvas/lib/bindings.js:3:18)
at Module._compile (internal/modules/cjs/loader.js:1114:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
at Module.load (internal/modules/cjs/loader.js:979:32)

**Comment by RSS1102** [comment]
It seems that your node version is incorrect

**Comment by zbjornson** [comment]
Please see the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511) linked in the issue template for guidance on this.
