### ISSUE TITLE
The specified procedure could not be found.

### ISSUE THREAD

**Issue by Dev-ingame** [Automattic/node-canvas#2330]
## Issue or Feature
- [ ] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

node:internal/modules/cjs/loader:1327
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified procedure could not be found.
\\?\C:\Users\ADMIN\Documents\ict\fb\node_modules\canvas\build\Release\canvas.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1327:18)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\ict\fb\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\ict\fb\node_modules\canvas\lib\canvas.js:9:18)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\ict\fb\node_modules\canvas\index.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at C:\Users\ADMIN\Documents\ict\fb\commands\id.js:14:41
    at CommandBuilder.handleChatMessage (C:\Users\ADMIN\Documents\ict\fb\modules\commandbuilder.js:36:25) {
  code: 'ERR_DLOPEN_FAILED'
}

## Steps to Reproduce

```js
    var Canvas = require('canvas');

```

## Your Environment
* 2.11.2
* node v20.10.0

**Comment by jieLi086** [comment]
+1

**Comment by jieLi086** [comment]
node:internal/modules/cjs/loader:1473
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\xxx\node_modules\canvas\build\Release\canvas.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\xxx\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\xxx\node_modules\canvas\lib\canvas.js:9:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v20.11.0

**Comment by officefish** [comment]
⨯ Error: The specified procedure could not be found.
\\?\D:\nest\preview-master\node_modules\canvas\build\Release\canvas.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.call (node:internal/modules/cjs/loader:1235:19)
    at Module.mod.require (D:\nest\preview-master\node_modules\next\src\server\require-hook.ts:70:26)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\nest\preview-master\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.call (node:internal/modules/cjs/loader:1235:19)
    at Module.mod.require (D:\nest\preview-master\node_modules\next\src\server\require-hook.ts:70:26)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\nest\preview-master\node_modules\canvas\lib\canvas.js:9:18) {
  code: 'ERR_DLOPEN_FAILED',

**Comment by mn4367** [comment]
Is anybody of you all using `canvas` together with the module `sharp`?

**Comment by officefish** [comment]
> Is anybody of you all using `canvas` together with the module `sharp`?

I am. Moreover I also use nestjs and sharp was imported with nest-sharp so in my way the solution was importing canvas before I initializing main nestjs app. Bese rule is to import canvas before sharp.

**Comment by justorez** [comment]
Same error

**Comment by nihirv** [comment]
> > Is anybody of you all using `canvas` together with the module `sharp`?
> 
> I am. Moreover I also use nestjs and sharp was imported with nest-sharp so in my way the solution was importing canvas before I initializing main nestjs app. Bese rule is to import canvas before sharp.

Tried this.. doesn't seem to work for me

**Comment by Pickles-wave** [comment]
I'm running into this issue as well，i got a solution. Maybe you guys can try.

If you're an x86 program, this issue may occur, and if you look at canvas.node with [Dependency Walker](http://www.dependencywalker.com/), you'll see that it may be missing **freetype6.dll** and **intl.dll**, in fact, this comes from the GTK, but when you compile the 32-bit canvas, the library name it copies is libfreetype-6.dll and libintl-8.dll, which is the name of the 64-bit compilation from C:\GTK\bin, and the copy fails here, but it is just a warning, and if you look at the full log of npm install, you will see this warning.

To put it simply, copying all the .dlls in C:\GTK\bin into node_modules\canvas\build\Release seems to be a workaround.

**Comment by zbjornson** [comment]
There's an incompatibility with sharp mentioned in the troubleshooting guide:

> ## I get a `the specified procedure could not be found` error
> If you have Sharp.js also installed, there's an incompatibility between their build of Cairo and our build of Cairo. See #930.

Is anyone *not* using sharp?

**Comment by devansh424** [comment]
+1

**Comment by devansh424** [comment]
Hi, I solved this error, for me this issue was being caused by module I was using called "captcha-canvas"
