### ISSUE TITLE
Cannot open include file: 'cairo-features.h' during compile step on Windows x64

### ISSUE THREAD

**Issue by Fauntleroy** [Automattic/node-canvas#234]
I've gone through all of the steps outlined in https://github.com/LearnBoost/node-canvas/wiki/Installation---Windows and now I've run into another problem. node-gyp now attempts to install node-canvas, but fails during a number of steps--all of which say that it cannot find "cairo-features.h".:

```
C:\Users\Timothy\Repos\tandem.io>npm install canvas
npm http GET https://registry.npmjs.org/canvas
npm http 304 https://registry.npmjs.org/canvas

> canvas@0.13.1 install C:\Users\Timothy\Repos\tandem.io\node_modules\canvas
> node-gyp rebuild


C:\Users\Timothy\Repos\tandem.io\node_modules\canvas>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..
\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
  CanvasRenderingContext2d.cc
  CanvasPattern.cc
  color.cc
  PixelArray.cc
..\src\color.cc(353): warning C4305: 'initializing' : truncation from 'double' to 'float' [C:\Users\Timothy\Repos\tande
m.io\node_modules\canvas\build\canvas.vcxproj]
..\src\color.cc(356): warning C4305: '*=' : truncation from 'double' to 'float' [C:\Users\Timothy\Repos\tandem.io\node_
modules\canvas\build\canvas.vcxproj]
  ImageData.cc
C:\GTK\include\cairo/cairo.h(41): fatal error C1083: Cannot open include file: 'cairo-features.h': No such file or dire
ctory [C:\Users\Timothy\Repos\tandem.io\node_modules\canvas\build\canvas.vcxproj]
  Canvas.cc
C:\GTK\include\cairo/cairo.h(41): fatal error C1083: Cannot open include file: 'cairo-features.h': No such file or dire
ctory [C:\Users\Timothy\Repos\tandem.io\node_modules\canvas\build\canvas.vcxproj]
C:\GTK\include\cairo/cairo.h(41): fatal error C1083: Cannot open include file: 'cairo-features.h': No such file or dire
ctory [C:\Users\Timothy\Repos\tandem.io\node_modules\canvas\build\canvas.vcxproj]
  init.cc
  Image.cc
C:\GTK\include\cairo/cairo.h(41): fatal error C1083: Cannot open include file: 'cairo-features.h': No such file or dire
ctory [C:\Users\Timothy\Repos\tandem.io\node_modules\canvas\build\canvas.vcxproj]
  CanvasGradient.cc
C:\GTK\include\cairo/cairo.h(41): fatal error C1083: Cannot open include file: 'cairo-features.h': No such file or dire
ctory [C:\Users\Timothy\Repos\tandem.io\node_modules\canvas\build\canvas.vcxproj]
C:\GTK\include\cairo/cairo.h(41): fatal error C1083: Cannot open include file: 'cairo-features.h': No such file or dire
ctory [C:\Users\Timothy\Repos\tandem.io\node_modules\canvas\build\canvas.vcxproj]
C:\GTK\include\cairo/cairo.h(41): fatal error C1083: Cannot open include file: 'cairo-features.h': No such file or dire
ctory [C:\Users\Timothy\Repos\tandem.io\node_modules\canvas\build\canvas.vcxproj]
C:\GTK\include\cairo/cairo.h(41): fatal error C1083: Cannot open include file: 'cairo-features.h': No such file or dire
ctory [C:\Users\Timothy\Repos\tandem.io\node_modules\canvas\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
36:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuil
d"
gyp ERR! cwd C:\Users\Timothy\Repos\tandem.io\node_modules\canvas
gyp ERR! node -v v0.8.15
gyp ERR! node-gyp -v v0.7.1
gyp ERR! not ok
npm ERR! canvas@0.13.1 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the canvas@0.13.1 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
 "install" "canvas"
npm ERR! cwd C:\Users\Timothy\Repos\tandem.io
npm ERR! node -v v0.8.15
npm ERR! npm -v 1.1.66
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Timothy\Repos\tandem.io\npm-debug.log
npm ERR! not ok code 0
```

I manually checked the folder it's supposedly looking in for "cairo-features.h" and it's there, so I'm not entirely sure what's going on.

**Comment by zorobabel** [comment]
Hey guys, I've posted [a solution](https://github.com/Automattic/node-canvas/issues/619) for this.
