### ISSUE TITLE
Canvas installation failure with Node v20.12.1

### ISSUE THREAD

**Issue by Vishwas2707** [Automattic/node-canvas#2374]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

Getting this error only in node version of 20 above works fine with LTS version 18.20.1 

## Steps to Reproduce
```js
> canvas@2.9.0 install
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@20.12.1 | darwin | arm64
node-pre-gyp info build requesting source compile
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@20.12.1 | darwin | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@20.12.1 | darwin | arm64
gyp info find Python using Python version 3.11.4 found at "/Library/Frameworks/Python.framework/Versions/3.11/bin/python3"

gyp info spawn /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
gyp info spawn args [
gyp info spawn args '/Users/vishwas/.nvm/versions/node/v20.12.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/Users/vishwas/.nvm/versions/node/v20.12.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/Users/vishwas/Library/Caches/node-gyp/20.12.1/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/Users/vishwas/Library/Caches/node-gyp/20.12.1',
gyp info spawn args '-Dnode_gyp_dir=/Users/vishwas/.nvm/versions/node/v20.12.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/Users/vishwas/Library/Caches/node-gyp/20.12.1/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@20.12.1 | darwin | arm64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/backend/Backend.o
In file included from ../src/backend/Backend.cc:1:
../src/backend/Backend.h:60:14: warning: private field 'backend' is not used [-Wunused-private-field]
    Backend* backend;
             ^
1 warning generated.
  CXX(target) Release/obj.target/canvas/src/backend/ImageBackend.o
  CXX(target) Release/obj.target/canvas/src/backend/PdfBackend.o
  CXX(target) Release/obj.target/canvas/src/backend/SvgBackend.o
  CXX(target) Release/obj.target/canvas/src/bmp/BMPParser.o
  CXX(target) Release/obj.target/canvas/src/Backends.o
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:21:
../src/Util.h:25:7: error: no member named 'AccessorSignature' in namespace 'v8'
                v8::AccessorSignature::New(v8::Isolate::GetCurrent(), ctor)
                ~~~~^
1 error generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (/Users/vishwas/.nvm/versions/node/v20.12.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
gyp ERR! System Darwin 23.4.0
gyp ERR! command "/Users/vishwas/.nvm/versions/node/v20.12.1/bin/node" "/Users/vishwas/.nvm/versions/node/v20.12.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v115"
gyp ERR! cwd /Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas
gyp ERR! node -v v20.12.1
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/vishwas/.nvm/versions/node/v20.12.1/bin/node /Users/vishwas/.nvm/versions/node/v20.12.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
node-pre-gyp ERR! System Darwin 23.4.0
node-pre-gyp ERR! command "/Users/vishwas/.nvm/versions/node/v20.12.1/bin/node" "/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas
node-pre-gyp ERR! node -v v20.12.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok 
Failed to execute '/Users/vishwas/.nvm/versions/node/v20.12.1/bin/node /Users/vishwas/.nvm/versions/node/v20.12.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
npm ERR! code 1
npm ERR! path /Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): installing latest 2.11.2
* Environment (e.g. node 20.9.0 on macOS 14.1.1): node LTS v20.12.1

**Comment by TrevorSayre** [comment]
I'm able to install on Node 20.12.2 on macOS 14.4.1

```sh
brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman
```
```sh
rm -rf node_modules
```
```sh
npm install
```

If you don't have the `brew` command from homebrew: https://brew.sh

**Comment by Vishwas2707** [comment]
Thanks Trevor for replying, I did brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman python@3.12
with Node 20.12.2 on macOS 14.4.1
```
brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman python@3.12
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS.
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
ffmpeg@6                                                     logdy                                                        parsedmarc
==> New Casks
yandex-music

You have 2 outdated formulae installed.

Warning: pkg-config 0.29.2_3 is already installed and up-to-date.
To reinstall 0.29.2_3, run:
  brew reinstall pkg-config
Warning: cairo 1.18.0 is already installed and up-to-date.
To reinstall 1.18.0, run:
  brew reinstall cairo
Warning: pango 1.52.2 is already installed and up-to-date.
To reinstall 1.52.2, run:
  brew reinstall pango
Warning: libpng 1.6.43 is already installed and up-to-date.
To reinstall 1.6.43, run:
  brew reinstall libpng
Warning: jpeg 9f is already installed and up-to-date.
To reinstall 9f, run:
  brew reinstall jpeg
Warning: giflib 5.2.1 is already installed and up-to-date.
To reinstall 5.2.1, run:
  brew reinstall giflib
Warning: librsvg 2.58.0 is already installed and up-to-date.
To reinstall 2.58.0, run:
  brew reinstall librsvg
Warning: pixman 0.42.2 is already installed and up-to-date.
To reinstall 0.42.2, run:
  brew reinstall pixman
Warning: python@3.12 3.12.2_1 is already installed and up-to-date.
To reinstall 3.12.2_1, run:
  brew reinstall python@3.12
```


and ran npm run clean for cleaning node modules  
npm install but still running into same error -     

```
> ua-packages@1.1.0 postinstall
> check-node-version --package && lerna bootstrap --hoist --ignore-scripts && node scripts/lifecycles-deps.js

lerna notice cli v6.6.2
lerna info Bootstrapping 23 packages
lerna WARN EHOIST_PKG_VERSION "@spm/core" package depends on superagent@^8.0.10, which differs from the hoisted superagent@^8.0.9.
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna info hoist Finished bootstrapping root
lerna info Symlinking packages and binaries
lerna success Bootstrapped 23 packages
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> canvas@2.9.0 install
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@20.12.2 | darwin | arm64
node-pre-gyp info build requesting source compile
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@20.12.2 | darwin | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@20.12.2 | darwin | arm64
gyp info find Python using Python version 3.11.4 found at "/Library/Frameworks/Python.framework/Versions/3.11/bin/python3"

gyp http GET https://nodejs.org/download/release/v20.12.2/node-v20.12.2-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v20.12.2/node-v20.12.2-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v20.12.2/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v20.12.2/SHASUMS256.txt
gyp info spawn /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
gyp info spawn args [
gyp info spawn args '/Users/vishwas/.nvm/versions/node/v20.12.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/Users/vishwas/.nvm/versions/node/v20.12.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/Users/vishwas/Library/Caches/node-gyp/20.12.2/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/Users/vishwas/Library/Caches/node-gyp/20.12.2',
gyp info spawn args '-Dnode_gyp_dir=/Users/vishwas/.nvm/versions/node/v20.12.2/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/Users/vishwas/Library/Caches/node-gyp/20.12.2/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@20.12.2 | darwin | arm64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/backend/Backend.o
In file included from ../src/backend/Backend.cc:1:
../src/backend/Backend.h:60:14: warning: private field 'backend' is not used [-Wunused-private-field]
    Backend* backend;
             ^
1 warning generated.
  CXX(target) Release/obj.target/canvas/src/backend/ImageBackend.o
  CXX(target) Release/obj.target/canvas/src/backend/PdfBackend.o
  CXX(target) Release/obj.target/canvas/src/backend/SvgBackend.o
  CXX(target) Release/obj.target/canvas/src/bmp/BMPParser.o
  CXX(target) Release/obj.target/canvas/src/Backends.o
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:21:
../src/Util.h:25:7: error: no member named 'AccessorSignature' in namespace 'v8'
                v8::AccessorSignature::New(v8::Isolate::GetCurrent(), ctor)
                ~~~~^
1 error generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (/Users/vishwas/.nvm/versions/node/v20.12.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
gyp ERR! System Darwin 23.4.0
gyp ERR! command "/Users/vishwas/.nvm/versions/node/v20.12.2/bin/node" "/Users/vishwas/.nvm/versions/node/v20.12.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v115"
gyp ERR! cwd /Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas
gyp ERR! node -v v20.12.2
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/vishwas/.nvm/versions/node/v20.12.2/bin/node /Users/vishwas/.nvm/versions/node/v20.12.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
node-pre-gyp ERR! System Darwin 23.4.0
node-pre-gyp ERR! command "/Users/vishwas/.nvm/versions/node/v20.12.2/bin/node" "/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas
node-pre-gyp ERR! node -v v20.12.2
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok 
Failed to execute '/Users/vishwas/.nvm/versions/node/v20.12.2/bin/node /Users/vishwas/.nvm/versions/node/v20.12.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
npm ERR! code 1
npm ERR! path /Users/vishwas/CitizenEngagement/SPM-WebApps/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build

npm ERR! A complete log of this run can be found in: /Users/vishwas/.npm/_logs/2024-04-12T05_16_43_467Z-debug-0.log

> puppeteer@13.7.0 install
> node install.js

**INFO** Skipping browser download. "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" environment variable was found.

added 2276 packages, and audited 2278 packages in 5m

320 packages are looking for funding
  run `npm fund` for details

23 vulnerabilities (1 low, 15 moderate, 6 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

**Comment by Aarbel** [comment]
Solution that definitely solved the problem for us, just run the npm install or yarn inside python environment:

```
python3 -m venv venv
source venv/bin/activate
pip install setuptools wheel

yarn

deactivate 
```
