### ISSUE TITLE
Canvas won't run in a docker container

### ISSUE THREAD

**Issue by Vigintillionn** [Automattic/node-canvas#2413]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

I've been trying to get canvas to work in a docker container, running a discord bot. I can install canvas without issues, the problem is canvas won't run. Nor on node:20 nor node:20-alpine. Has anyone had this happen to them and possibly knows a solution to this? Here's the error I'm getting 
```
obsidian-dev  | Error: libjpeg.so.8: cannot open shared object file: No such file or directory
obsidian-dev  |     at Module._extensions..node (node:internal/modules/cjs/loader:1454:18)
obsidian-dev  |     at Object.nodeDevHook [as .node] (/usr/src/node_modules/ts-node-dev/lib/hook.js:63:13)
obsidian-dev  |     at Module.load (node:internal/modules/cjs/loader:1208:32)
obsidian-dev  |     at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
obsidian-dev  |     at Module.require (node:internal/modules/cjs/loader:1233:19)
obsidian-dev  |     at require (node:internal/modules/helpers:179:18)
obsidian-dev  |     at Object.<anonymous> (/usr/src/node_modules/canvas/lib/bindings.js:3:18)
obsidian-dev  |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
obsidian-dev  |     at Module._compile (/usr/src/node_modules/source-map-support/source-map-support.js:568:25)
obsidian-dev  |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
obsidian-dev  | [ERROR] 14:04:23 Error: libjpeg.so.8: cannot open shared object file: No such file or directory
```
libjpeg8 is no longer part of debian nor alpine. I tried installing it but that didn't work either. Then I tried installing `libjpeg62-turbo` and create a symlink, but that didn't work either.

The code runs fine outside of my container (on my arch machine). 

## Steps to Reproduce
Here's my docker container:
```Docker
# Base image with Node.js
FROM node:20 as base

# Create and set the working directory
RUN mkdir -p /usr/src
WORKDIR /usr/src

RUN apt-get update && apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Production build
FROM base as production
ENV NODE_ENV=production
CMD ["npm", "run", "start"]

# Development build
FROM base as development
ENV NODE_ENV=development
CMD ["npm", "run", "dev"]
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): canvas@2.11.2
* Environment (e.g. node 20.9.0 on macOS 14.1.1): docker container, tried both images node:20 and node:20-alpine

**Comment by igorrogi1603** [comment]
I'm facing the same issue. If you manage to solve it, let me know.

**Comment by igorrogi1603** [comment]
I managed to solve the problem. The issue lies in the node_modules folder. Once Canvas is installed in node_modules on the local machine (in my case, Windows), and you try to create the Docker image from your local machine, for some reason, Canvas throws an error. I believe it signs something in its package specific to that environment, and when the Docker image is generated, it tries to use the node_modules from the PC, causing an issue. Either you delete the node_modules folder from the project before generating the Docker image, or you add a .dockerignore file and ignore node_modules, similar to how .gitignore works.

**Comment by Vigintillionn** [comment]
I already have a dockerignore file with node_modules in.

**Comment by igorrogi1603** [comment]
# Use the Node.js base image
FROM node:20

# Install system dependencies necessary for native modules like `canvas`
RUN apt-get update && apt-get install -y \
  build-essential \
  libcairo2-dev \
  libpango1.0-dev \
  libjpeg-dev \
  libgif-dev \
  librsvg2-dev \
  libtool \
  autoconf \
  automake \
  && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy "package.json" and "yarn.lock" before other files
# Use Docker cache to avoid reinstalling dependencies if they haven't changed
COPY package.json yarn.lock ./

# Install dependencies using Yarn
RUN yarn

# Reinstall canvas separately - sometimes needed locally
RUN yarn add canvas

# Copy all files
COPY . .

# Build the application (if necessary)
RUN yarn build

# Install PM2 globally
RUN yarn global add pm2

# Expose the listening port
EXPOSE 3333

# Run migrations before starting the application with PM2
RUN ./node_modules/.bin/typeorm migration:run

# Use PM2 to start the application in cluster mode
CMD ["pm2-runtime", "start", "ecosystem.config.js"]

**Comment by Vigintillionn** [comment]
This unfortunately did not resolve my issue. I still am receiving the same error.

**Comment by igorrogi1603** [comment]
Access the node-canvas documentation -> https://www.npmjs.com/package/canvas
Sometimes you might be using methods that are only supported in the browser and not in the backend.

**Comment by Vigintillionn** [comment]
I'm only using the createCanvas method.

**Comment by s-skubedin** [comment]
I added `RUN apt-get update` before `RUN apt-get install -y build-essential...`
This solved the error

**Comment by Malith-Rukshan** [comment]
This is working for me with `node:22.12.0-alpine` | `pnpm`

```dockerfile
FROM node:22.12.0-alpine AS builder
WORKDIR /app

# Copy only package files first to leverage Docker cache
COPY package.json ./

RUN apk update && apk add build-base g++ cairo-dev pango-dev giflib-dev

# Install pnpm and install all dependencies
RUN npm install -g pnpm \
    && pnpm install
```

**Comment by augustoximenes** [comment]
###################
# BUILD FOR LOCAL DEVELOPMENT
###################

FROM node:20-alpine AS development

# Install dependencies
RUN apk add build-base g++ cairo-dev pango-dev giflib-dev py-setuptools

# Create app directory
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure copying both package.json AND package-lock.json (when available).
# Copying this first prevents re-running npm install on every code change.
COPY --chown=node:node package*.json ./

# Install app dependencies using the `npm ci` command instead of `npm install`
RUN npm ci

# Bundle app source
COPY --chown=node:node . .

# Use the node user from the image (instead of the root user)
USER node
