### ISSUE TITLE
GitLab CI/CD npm errors & wrong dist link

### ISSUE THREAD

**Issue by jmbluethner** [Automattic/node-canvas#2414]
## Issue

When installing canvas locally on my Windows machine, all works just fine. However, once I try to build a docker image by using GitLab CI/CD, I get a lot of errors caused by canvas / npm.  

The most interesting thing is, that there appears to be an HTTP 404 for a canvas release download link which appears in the logs.  
Here's the full log: 

<details>
<summary>CI/CD log</summary>

```
#8 17.91 npm error code 1
#8 17.91 npm error path /usr/src/app/node_modules/canvas
#8 17.91 npm error command failed
#8 17.91 npm error command sh -c node-pre-gyp install --fallback-to-build --update-binary
#8 17.91 npm error Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/usr/src/app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/src/app/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
#8 17.91 npm error node-pre-gyp info it worked if it ends with ok
#8 17.91 npm error node-pre-gyp info using node-pre-gyp@1.0.11
#8 17.91 npm error node-pre-gyp info using node@22.5.1 | linux | x64
#8 17.91 npm error (node:18) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
#8 17.91 npm error (Use `node --trace-deprecation ...` to show where the warning was created)
#8 17.91 npm error node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz
#8 17.91 npm error node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz 
#8 17.91 npm error node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@22.5.1 (node-v127 ABI, glibc) (falling back to source compile with node-gyp) 
#8 17.91 npm error node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz 
#8 17.91 npm error gyp info it worked if it ends with ok
#8 17.91 npm error gyp info using node-gyp@10.1.0
#8 17.91 npm error gyp info using node@22.5.1 | linux | x64
#8 17.91 npm error gyp info ok 
#8 17.91 npm error gyp info it worked if it ends with ok
#8 17.91 npm error gyp info using node-gyp@10.1.0
#8 17.91 npm error gyp info using node@22.5.1 | linux | x64
#8 17.91 npm error gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
#8 17.91 npm error gyp http GET https://nodejs.org/download/release/v22.5.1/node-v22.5.1-headers.tar.gz
#8 17.91 npm error gyp http 200 https://nodejs.org/download/release/v22.5.1/node-v22.5.1-headers.tar.gz
#8 17.91 npm error gyp http GET https://nodejs.org/download/release/v22.5.1/SHASUMS256.txt
#8 17.91 npm error gyp http 200 https://nodejs.org/download/release/v22.5.1/SHASUMS256.txt
#8 17.91 npm error gyp info spawn /usr/bin/python3
#8 17.91 npm error gyp info spawn args [
#8 17.91 npm error gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
#8 17.91 npm error gyp info spawn args 'binding.gyp',
#8 17.91 npm error gyp info spawn args '-f',
#8 17.91 npm error gyp info spawn args 'make',
#8 17.91 npm error gyp info spawn args '-I',
#8 17.91 npm error gyp info spawn args '/usr/src/app/node_modules/canvas/build/config.gypi',
#8 17.91 npm error gyp info spawn args '-I',
#8 17.91 npm error gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
#8 17.91 npm error gyp info spawn args '-I',
#8 17.91 npm error gyp info spawn args '/root/.cache/node-gyp/22.5.1/include/node/common.gypi',
#8 17.91 npm error gyp info spawn args '-Dlibrary=shared_library',
#8 17.91 npm error gyp info spawn args '-Dvisibility=default',
#8 17.91 npm error gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/22.5.1',
#8 17.91 npm error gyp info spawn args '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
#8 17.91 npm error gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/22.5.1/<(target_arch)/node.lib',
#8 17.91 npm error gyp info spawn args '-Dmodule_root_dir=/usr/src/app/node_modules/canvas',
#8 17.91 npm error gyp info spawn args '-Dnode_engine=v8',
#8 17.91 npm error gyp info spawn args '--depth=.',
#8 17.91 npm error gyp info spawn args '--no-parallel',
#8 17.91 npm error gyp info spawn args '--generator-output',
#8 17.91 npm error gyp info spawn args 'build',
#8 17.91 npm error gyp info spawn args '-Goutput_dir=.'
#8 17.91 npm error gyp info spawn args ]
#8 17.91 npm error Package pangocairo was not found in the pkg-config search path.
#8 17.91 npm error Perhaps you should add the directory containing `pangocairo.pc'
#8 17.91 npm error to the PKG_CONFIG_PATH environment variable
#8 17.91 npm error Package 'pangocairo', required by 'virtual:world', not found
#8 17.91 npm error gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
#8 17.91 npm error gyp ERR! configure error 
#8 17.91 npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
#8 17.91 npm error gyp ERR! stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:297:18)
#8 17.91 npm error gyp ERR! stack at ChildProcess.emit (node:events:520:28)
#8 17.91 npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
#8 17.91 npm error gyp ERR! System Linux 5.15.154+
#8 17.91 npm error gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/usr/src/app/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/usr/src/app/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v[127](https://gitlab.com/proalpha/proalpha-api/-/jobs/7459330065#L127)"
#8 17.91 npm error gyp ERR! cwd /usr/src/app/node_modules/canvas
#8 17.91 npm error gyp ERR! node -v v22.5.1
#8 17.91 npm error gyp ERR! node-gyp -v v10.1.0
#8 17.91 npm error gyp ERR! not ok 
#8 17.91 npm error node-pre-gyp ERR! build error 
#8 17.91 npm error node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/usr/src/app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/src/app/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
#8 17.91 npm error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/src/app/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
#8 17.91 npm error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
#8 17.91 npm error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
#8 17.91 npm error node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
#8 17.91 npm error node-pre-gyp ERR! System Linux 5.15.154+
#8 17.91 npm error node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
#8 17.91 npm error node-pre-gyp ERR! cwd /usr/src/app/node_modules/canvas
#8 17.91 npm error node-pre-gyp ERR! node -v v22.5.1
#8 17.91 npm error node-pre-gyp ERR! node-pre-gyp -v v1.0.11
#8 17.91 npm error node-pre-gyp ERR! not ok
#8 17.92 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-07-30T07_48_30_535Z-debug-0.log
#8 ERROR: process "/bin/sh -c npm install" did not complete successfully: exit code: 1
------
 > [4/4] RUN npm install:
17.91 npm error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
17.91 npm error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
17.91 npm error node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
17.91 npm error node-pre-gyp ERR! System Linux 5.15.[154](https://gitlab.com/proalpha/proalpha-api/-/jobs/7459330065#L154)+
17.91 npm error node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
17.91 npm error node-pre-gyp ERR! cwd /usr/src/app/node_modules/canvas
17.91 npm error node-pre-gyp ERR! node -v v22.5.1
17.91 npm error node-pre-gyp ERR! node-pre-gyp -v v1.0.11
17.91 npm error node-pre-gyp ERR! not ok
17.92 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-07-30T07_48_30_535Z-debug-0.log
```

</details>

What stands out to me is this line:

```
#8 17.91 npm error node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz
```

The requested release package, `canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz`, does in fact not exist in https://github.com/Automattic/node-canvas/releases/tag/v2.11.2  

But why is that `GET` even needed? If I'm not entirely stupid, the `canvas` package gets pulled directly from https://registry.npmjs.org/ doesn`t it?

## Steps to Reproduce

- Build a simple node app which has `"canvas": "^2.11.2"` in the `package.json`
- Create a `Dockerfile`

```
FROM node:latest
WORKDIR /usr/src/app
COPY /src ./
RUN npm install
EXPOSE 8080
CMD [ "node", "app.js" ]
```

- Create a `.gitlab-ci.yml`

```yml
stages:
  - build

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - export VERSION=$(date +%y)
    - docker build --pull -t $CI_REGISTRY_IMAGE .
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:latest
    - docker tag $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:$VERSION.$CI_PIPELINE_IID
    - docker push $CI_REGISTRY_IMAGE:$VERSION.$CI_PIPELINE_IID
    - docker push $CI_REGISTRY_IMAGE:latest
```

## Your Environment

`dind` public runner using `docker:latest`

**Comment by jmbluethner** [comment]
Found the solution. 

The Problem is, that `node:latest`, which was defined in `Dockerfile`, is node `v22.5.1`.  
But `node-canvas` doesn't provide a build for that yet. The latest node version is the reason why, during `npm install`, gyp tries to fetch `canvas v127`, but fails, because said build doesn't exist.  

The solution was, to change `node:latest` to `node:20.16.0`, which currently is the latest **LTS** build.
