### ISSUE TITLE
Windows can't find prebuilds for 3.0.0-rc2

### ISSUE THREAD

**Issue by Maxim-Mazurok** [Automattic/node-canvas#2415]
## Issue or Feature
- [x] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

Tried to `npm install canvas@next` on Windows with node 20 and 22, but it failed to find prebuilds:
```
npm error prebuild-install warn install No prebuilt binaries found (target=7 runtime=napi arch=x64 libc= platform=win32)
```

## Your Environment
* Version of node-canvas (output of ``npm list canvas`` or `yarn list canvas`): `3.0.0-rc2`
* Environment (e.g. node 20.9.0 on macOS 14.1.1): 	Node `v22.6.0` on Windows 11

---

I know that I probably can do manual build, but I would rather not, will probably use Node v20 with canvas@2 prebuilds, just wanted to give feedback on the RC, cheers!

**Comment by zbjornson** [comment]
Does the install log show the URL that it tried to fetch?

**Comment by Maxim-Mazurok** [comment]
I don't see it, here's a full log:

```
0 verbose cli C:\Users\maxim.mazurok\AppData\Local\nvs\node\20.16.0\x64\node.exe C:\Users\maxim.mazurok\AppData\Local\nvs\node\20.16.0\x64\node_modules\npm\bin\npm-cli.js
1 info using npm@10.8.1
2 info using node@v20.16.0
3 silly config load:file:C:\Users\maxim.mazurok\AppData\Local\nvs\node\20.16.0\x64\node_modules\npm\npmrc
4 silly config load:file:C:\Users\maxim.mazurok\tmp\.npmrc
5 silly config load:file:C:\Users\maxim.mazurok\.npmrc
6 silly config load:file:C:\Users\maxim.mazurok\AppData\Local\nvs\node\20.16.0\x64\etc\npmrc
7 verbose title npm install canvas@next
8 verbose argv "install" "canvas@next"
9 verbose logfile logs-max:10 dir:C:\Users\maxim.mazurok\AppData\Local\npm-cache\_logs\2024-08-17T09_34_26_172Z-
10 verbose logfile C:\Users\maxim.mazurok\AppData\Local\npm-cache\_logs\2024-08-17T09_34_26_172Z-debug-0.log
11 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
12 silly logfile start cleaning logs, removing 1 files
13 silly logfile done cleaning log files
14 silly packumentCache corgi:https://registry.npmjs.org/canvas cache-miss
15 http fetch GET 200 https://registry.npmjs.org/canvas 15ms (cache hit)
16 silly packumentCache corgi:https://registry.npmjs.org/canvas set size:126767 disposed:false
17 silly idealTree buildDeps
18 silly fetch manifest canvas@3.0.0-rc2
19 silly packumentCache full:https://registry.npmjs.org/canvas cache-miss
20 http fetch GET 200 https://registry.npmjs.org/canvas 11ms (cache hit)
21 silly packumentCache full:https://registry.npmjs.org/canvas set size:637051 disposed:false
22 silly placeDep ROOT canvas@3.0.0-rc2 OK for: tmp@1.0.0 want: 3.0.0-rc2
23 silly fetch manifest node-addon-api@^7.0.0
24 silly packumentCache full:https://registry.npmjs.org/node-addon-api cache-miss
25 silly fetch manifest prebuild-install@^7.1.1
26 silly packumentCache full:https://registry.npmjs.org/prebuild-install cache-miss
27 silly fetch manifest simple-get@^3.0.3
28 silly packumentCache full:https://registry.npmjs.org/simple-get cache-miss
29 http fetch GET 200 https://registry.npmjs.org/node-addon-api 10ms (cache hit)
30 silly packumentCache full:https://registry.npmjs.org/node-addon-api set size:262335 disposed:false
31 http fetch GET 200 https://registry.npmjs.org/simple-get 14ms (cache hit)
32 silly packumentCache full:https://registry.npmjs.org/simple-get set size:90014 disposed:false
33 http fetch GET 200 https://registry.npmjs.org/prebuild-install 16ms (cache hit)
34 silly packumentCache full:https://registry.npmjs.org/prebuild-install set size:175769 disposed:false
35 silly placeDep ROOT node-addon-api@7.1.1 OK for: canvas@3.0.0-rc2 want: ^7.0.0
36 silly placeDep ROOT prebuild-install@7.1.2 OK for: canvas@3.0.0-rc2 want: ^7.1.1
37 silly placeDep ROOT simple-get@3.1.1 OK for: canvas@3.0.0-rc2 want: ^3.0.3
38 silly fetch manifest detect-libc@^2.0.0
39 silly packumentCache full:https://registry.npmjs.org/detect-libc cache-miss
40 silly fetch manifest expand-template@^2.0.3
41 silly packumentCache full:https://registry.npmjs.org/expand-template cache-miss
42 silly fetch manifest github-from-package@0.0.0
43 silly packumentCache full:https://registry.npmjs.org/github-from-package cache-miss
44 silly fetch manifest minimist@^1.2.3
45 silly packumentCache full:https://registry.npmjs.org/minimist cache-miss
46 silly fetch manifest mkdirp-classic@^0.5.3
47 silly packumentCache full:https://registry.npmjs.org/mkdirp-classic cache-miss
48 silly fetch manifest napi-build-utils@^1.0.1
49 silly packumentCache full:https://registry.npmjs.org/napi-build-utils cache-miss
50 silly fetch manifest node-abi@^3.3.0
51 silly packumentCache full:https://registry.npmjs.org/node-abi cache-miss
52 silly fetch manifest pump@^3.0.0
53 silly packumentCache full:https://registry.npmjs.org/pump cache-miss
54 silly fetch manifest rc@^1.2.7
55 silly packumentCache full:https://registry.npmjs.org/rc cache-miss
56 silly fetch manifest simple-get@^4.0.0
57 silly packumentCache full:https://registry.npmjs.org/simple-get cache-hit
58 silly fetch manifest tar-fs@^2.0.0
59 silly packumentCache full:https://registry.npmjs.org/tar-fs cache-miss
60 silly fetch manifest tunnel-agent@^0.6.0
61 silly packumentCache full:https://registry.npmjs.org/tunnel-agent cache-miss
62 silly fetch manifest decompress-response@^4.2.0
63 silly packumentCache full:https://registry.npmjs.org/decompress-response cache-miss
64 silly fetch manifest once@^1.3.1
65 silly packumentCache full:https://registry.npmjs.org/once cache-miss
66 silly fetch manifest simple-concat@^1.0.0
67 silly packumentCache full:https://registry.npmjs.org/simple-concat cache-miss
68 http fetch GET 200 https://registry.npmjs.org/detect-libc 31ms (cache hit)
69 silly packumentCache full:https://registry.npmjs.org/detect-libc set size:36376 disposed:false
70 http fetch GET 200 https://registry.npmjs.org/mkdirp-classic 31ms (cache hit)
71 silly packumentCache full:https://registry.npmjs.org/mkdirp-classic set size:5503 disposed:false
72 http fetch GET 200 https://registry.npmjs.org/tar-fs 28ms (cache hit)
73 silly packumentCache full:https://registry.npmjs.org/tar-fs set size:100330 disposed:false
74 http fetch GET 200 https://registry.npmjs.org/rc 30ms (cache hit)
75 silly packumentCache full:https://registry.npmjs.org/rc set size:70435 disposed:false
76 http fetch GET 200 https://registry.npmjs.org/tunnel-agent 30ms (cache hit)
77 silly packumentCache full:https://registry.npmjs.org/tunnel-agent set size:12847 disposed:false
78 http fetch GET 200 https://registry.npmjs.org/github-from-package 35ms (cache hit)
79 silly packumentCache full:https://registry.npmjs.org/github-from-package set size:3718 disposed:false
80 http fetch GET 200 https://registry.npmjs.org/pump 32ms (cache hit)
81 silly packumentCache full:https://registry.npmjs.org/pump set size:34436 disposed:false
82 http fetch GET 200 https://registry.npmjs.org/expand-template 36ms (cache hit)
83 silly packumentCache full:https://registry.npmjs.org/expand-template set size:23203 disposed:false
84 http fetch GET 200 https://registry.npmjs.org/simple-concat 31ms (cache hit)
85 silly packumentCache full:https://registry.npmjs.org/simple-concat set size:6304 disposed:false
86 http fetch GET 200 https://registry.npmjs.org/minimist 36ms (cache hit)
87 silly packumentCache full:https://registry.npmjs.org/minimist set size:77097 disposed:false
88 http fetch GET 200 https://registry.npmjs.org/node-abi 35ms (cache hit)
89 silly packumentCache full:https://registry.npmjs.org/node-abi set size:255091 disposed:false
90 http fetch GET 200 https://registry.npmjs.org/napi-build-utils 38ms (cache hit)
91 silly packumentCache full:https://registry.npmjs.org/napi-build-utils set size:11428 disposed:false
92 http fetch GET 200 https://registry.npmjs.org/decompress-response 36ms (cache hit)
93 silly packumentCache full:https://registry.npmjs.org/decompress-response set size:34164 disposed:false
94 http fetch GET 200 https://registry.npmjs.org/once 37ms (cache hit)
95 silly packumentCache full:https://registry.npmjs.org/once set size:11768 disposed:false
96 silly placeDep ROOT detect-libc@2.0.3 OK for: prebuild-install@7.1.2 want: ^2.0.0
97 silly placeDep ROOT expand-template@2.0.3 OK for: prebuild-install@7.1.2 want: ^2.0.3
98 silly placeDep ROOT github-from-package@0.0.0 OK for: prebuild-install@7.1.2 want: 0.0.0
99 silly placeDep ROOT minimist@1.2.8 OK for: prebuild-install@7.1.2 want: ^1.2.3
100 silly placeDep ROOT mkdirp-classic@0.5.3 OK for: prebuild-install@7.1.2 want: ^0.5.3
101 silly placeDep ROOT napi-build-utils@1.0.2 OK for: prebuild-install@7.1.2 want: ^1.0.1
102 silly placeDep ROOT node-abi@3.65.0 OK for: prebuild-install@7.1.2 want: ^3.3.0
103 silly placeDep ROOT pump@3.0.0 OK for: prebuild-install@7.1.2 want: ^3.0.0
104 silly placeDep ROOT rc@1.2.8 OK for: prebuild-install@7.1.2 want: ^1.2.7
105 silly placeDep node_modules/prebuild-install simple-get@4.0.1 OK for: prebuild-install@7.1.2 want: ^4.0.0
106 silly placeDep ROOT tar-fs@2.1.1 OK for: prebuild-install@7.1.2 want: ^2.0.0
107 silly placeDep ROOT tunnel-agent@0.6.0 OK for: prebuild-install@7.1.2 want: ^0.6.0
108 silly fetch manifest semver@^7.3.5
109 silly packumentCache full:https://registry.npmjs.org/semver cache-miss
110 silly fetch manifest end-of-stream@^1.1.0
111 silly packumentCache full:https://registry.npmjs.org/end-of-stream cache-miss
112 silly fetch manifest deep-extend@^0.6.0
113 silly packumentCache full:https://registry.npmjs.org/deep-extend cache-miss
114 silly fetch manifest ini@~1.3.0
115 silly packumentCache full:https://registry.npmjs.org/ini cache-miss
116 silly fetch manifest strip-json-comments@~2.0.1
117 silly packumentCache full:https://registry.npmjs.org/strip-json-comments cache-miss
118 silly fetch manifest decompress-response@^6.0.0
119 silly packumentCache full:https://registry.npmjs.org/decompress-response cache-hit
120 silly fetch manifest chownr@^1.1.1
121 silly packumentCache full:https://registry.npmjs.org/chownr cache-miss
122 silly fetch manifest tar-stream@^2.1.4
123 silly packumentCache full:https://registry.npmjs.org/tar-stream cache-miss
124 silly fetch manifest safe-buffer@^5.0.1
125 silly packumentCache full:https://registry.npmjs.org/safe-buffer cache-miss
126 http fetch GET 200 https://registry.npmjs.org/end-of-stream 24ms (cache hit)
127 silly packumentCache full:https://registry.npmjs.org/end-of-stream set size:26267 disposed:false
128 http fetch GET 200 https://registry.npmjs.org/chownr 22ms (cache hit)
129 silly packumentCache full:https://registry.npmjs.org/chownr set size:22157 disposed:false
130 http fetch GET 200 https://registry.npmjs.org/semver 25ms (cache hit)
131 silly packumentCache full:https://registry.npmjs.org/semver set size:215945 disposed:false
132 http fetch GET 200 https://registry.npmjs.org/safe-buffer 24ms (cache hit)
133 silly packumentCache full:https://registry.npmjs.org/safe-buffer set size:41183 disposed:false
134 http fetch GET 200 https://registry.npmjs.org/tar-stream 25ms (cache hit)
135 silly packumentCache full:https://registry.npmjs.org/tar-stream set size:132366 disposed:false
136 http fetch GET 200 https://registry.npmjs.org/strip-json-comments 28ms (cache hit)
137 silly packumentCache full:https://registry.npmjs.org/strip-json-comments set size:39591 disposed:false
138 http fetch GET 200 https://registry.npmjs.org/deep-extend 29ms (cache hit)
139 silly packumentCache full:https://registry.npmjs.org/deep-extend set size:34472 disposed:false
140 http fetch GET 200 https://registry.npmjs.org/ini 30ms (cache hit)
141 silly packumentCache full:https://registry.npmjs.org/ini set size:52407 disposed:false
142 silly placeDep ROOT semver@7.6.3 OK for: node-abi@3.65.0 want: ^7.3.5
143 silly placeDep ROOT end-of-stream@1.4.4 OK for: pump@3.0.0 want: ^1.1.0
144 silly placeDep ROOT once@1.4.0 OK for: pump@3.0.0 want: ^1.3.1
145 silly fetch manifest once@^1.4.0
146 silly packumentCache full:https://registry.npmjs.org/once cache-hit
147 silly fetch manifest wrappy@1
148 silly packumentCache full:https://registry.npmjs.org/wrappy cache-miss
149 http fetch GET 200 https://registry.npmjs.org/wrappy 4ms (cache hit)
150 silly packumentCache full:https://registry.npmjs.org/wrappy set size:7682 disposed:false
151 silly placeDep ROOT wrappy@1.0.2 OK for: once@1.4.0 want: 1
152 silly placeDep ROOT deep-extend@0.6.0 OK for: rc@1.2.8 want: ^0.6.0
153 silly placeDep ROOT ini@1.3.8 OK for: rc@1.2.8 want: ~1.3.0
154 silly placeDep ROOT strip-json-comments@2.0.1 OK for: rc@1.2.8 want: ~2.0.1
155 silly placeDep ROOT decompress-response@4.2.1 OK for: simple-get@3.1.1 want: ^4.2.0
156 silly placeDep ROOT simple-concat@1.0.1 OK for: simple-get@3.1.1 want: ^1.0.0
157 silly fetch manifest mimic-response@^2.0.0
158 silly packumentCache full:https://registry.npmjs.org/mimic-response cache-miss
159 http fetch GET 200 https://registry.npmjs.org/mimic-response 6ms (cache hit)
160 silly packumentCache full:https://registry.npmjs.org/mimic-response set size:20174 disposed:false
161 silly placeDep ROOT mimic-response@2.1.0 OK for: decompress-response@4.2.1 want: ^2.0.0
162 silly placeDep ROOT chownr@1.1.4 OK for: tar-fs@2.1.1 want: ^1.1.1
163 silly placeDep ROOT tar-stream@2.2.0 OK for: tar-fs@2.1.1 want: ^2.1.4
164 silly fetch manifest bl@^4.0.3
165 silly packumentCache full:https://registry.npmjs.org/bl cache-miss
166 silly fetch manifest fs-constants@^1.0.0
167 silly packumentCache full:https://registry.npmjs.org/fs-constants cache-miss
168 silly fetch manifest inherits@^2.0.3
169 silly packumentCache full:https://registry.npmjs.org/inherits cache-miss
170 silly fetch manifest readable-stream@^3.1.1
171 silly packumentCache full:https://registry.npmjs.org/readable-stream cache-miss
172 http fetch GET 200 https://registry.npmjs.org/bl 12ms (cache hit)
173 silly packumentCache full:https://registry.npmjs.org/bl set size:150889 disposed:false
174 http fetch GET 200 https://registry.npmjs.org/readable-stream 12ms (cache hit)
175 silly packumentCache full:https://registry.npmjs.org/readable-stream set size:272167 disposed:false
176 http fetch GET 200 https://registry.npmjs.org/inherits 15ms (cache hit)
177 silly packumentCache full:https://registry.npmjs.org/inherits set size:12925 disposed:false
178 http fetch GET 200 https://registry.npmjs.org/fs-constants 16ms (cache hit)
179 silly packumentCache full:https://registry.npmjs.org/fs-constants set size:3522 disposed:false
180 silly placeDep ROOT bl@4.1.0 OK for: tar-stream@2.2.0 want: ^4.0.3
181 silly placeDep ROOT fs-constants@1.0.0 OK for: tar-stream@2.2.0 want: ^1.0.0
182 silly placeDep ROOT inherits@2.0.4 OK for: tar-stream@2.2.0 want: ^2.0.3
183 silly placeDep ROOT readable-stream@3.6.2 OK for: tar-stream@2.2.0 want: ^3.1.1
184 silly fetch manifest buffer@^5.5.0
185 silly packumentCache full:https://registry.npmjs.org/buffer cache-miss
186 silly fetch manifest inherits@^2.0.4
187 silly packumentCache full:https://registry.npmjs.org/inherits cache-hit
188 silly fetch manifest readable-stream@^3.4.0
189 silly packumentCache full:https://registry.npmjs.org/readable-stream cache-hit
190 silly fetch manifest string_decoder@^1.1.1
191 silly packumentCache full:https://registry.npmjs.org/string_decoder cache-miss
192 silly fetch manifest util-deprecate@^1.0.1
193 silly packumentCache full:https://registry.npmjs.org/util-deprecate cache-miss
194 http fetch GET 200 https://registry.npmjs.org/string_decoder 8ms (cache hit)
195 silly packumentCache full:https://registry.npmjs.org/string_decoder set size:28441 disposed:false
196 http fetch GET 200 https://registry.npmjs.org/buffer 10ms (cache hit)
197 silly packumentCache full:https://registry.npmjs.org/buffer set size:280480 disposed:false
198 http fetch GET 200 https://registry.npmjs.org/util-deprecate 12ms (cache hit)
199 silly packumentCache full:https://registry.npmjs.org/util-deprecate set size:6674 disposed:false
200 silly placeDep ROOT buffer@5.7.1 OK for: bl@4.1.0 want: ^5.5.0
201 silly fetch manifest base64-js@^1.3.1
202 silly packumentCache full:https://registry.npmjs.org/base64-js cache-miss
203 silly fetch manifest ieee754@^1.1.13
204 silly packumentCache full:https://registry.npmjs.org/ieee754 cache-miss
205 http fetch GET 200 https://registry.npmjs.org/base64-js 8ms (cache hit)
206 silly packumentCache full:https://registry.npmjs.org/base64-js set size:41270 disposed:false
207 http fetch GET 200 https://registry.npmjs.org/ieee754 8ms (cache hit)
208 silly packumentCache full:https://registry.npmjs.org/ieee754 set size:34910 disposed:false
209 silly placeDep ROOT base64-js@1.5.1 OK for: buffer@5.7.1 want: ^1.3.1
210 silly placeDep ROOT ieee754@1.2.1 OK for: buffer@5.7.1 want: ^1.1.13
211 silly placeDep ROOT string_decoder@1.3.0 OK for: readable-stream@3.6.2 want: ^1.1.1
212 silly placeDep ROOT util-deprecate@1.0.2 OK for: readable-stream@3.6.2 want: ^1.0.1
213 silly fetch manifest safe-buffer@~5.2.0
214 silly packumentCache full:https://registry.npmjs.org/safe-buffer cache-hit
215 silly placeDep ROOT safe-buffer@5.2.1 OK for: string_decoder@1.3.0 want: ~5.2.0
216 silly placeDep node_modules/prebuild-install decompress-response@6.0.0 OK for: simple-get@4.0.1 want: ^6.0.0
217 silly fetch manifest mimic-response@^3.1.0
218 silly packumentCache full:https://registry.npmjs.org/mimic-response cache-hit
219 silly placeDep node_modules/prebuild-install mimic-response@3.1.0 OK for: decompress-response@6.0.0 want: ^3.1.0
220 silly reify moves {}
221 silly audit bulk request {
221 silly audit   canvas: [ '3.0.0-rc2' ],
221 silly audit   'node-addon-api': [ '7.1.1' ],
221 silly audit   'prebuild-install': [ '7.1.2' ],
221 silly audit   'simple-get': [ '3.1.1', '4.0.1' ],
221 silly audit   'detect-libc': [ '2.0.3' ],
221 silly audit   'expand-template': [ '2.0.3' ],
221 silly audit   'github-from-package': [ '0.0.0' ],
221 silly audit   minimist: [ '1.2.8' ],
221 silly audit   'mkdirp-classic': [ '0.5.3' ],
221 silly audit   'napi-build-utils': [ '1.0.2' ],
221 silly audit   'node-abi': [ '3.65.0' ],
221 silly audit   pump: [ '3.0.0' ],
221 silly audit   rc: [ '1.2.8' ],
221 silly audit   'tar-fs': [ '2.1.1' ],
221 silly audit   'tunnel-agent': [ '0.6.0' ],
221 silly audit   semver: [ '7.6.3' ],
221 silly audit   'end-of-stream': [ '1.4.4' ],
221 silly audit   once: [ '1.4.0' ],
221 silly audit   wrappy: [ '1.0.2' ],
221 silly audit   'deep-extend': [ '0.6.0' ],
221 silly audit   ini: [ '1.3.8' ],
221 silly audit   'strip-json-comments': [ '2.0.1' ],
221 silly audit   'decompress-response': [ '4.2.1', '6.0.0' ],
221 silly audit   'simple-concat': [ '1.0.1' ],
221 silly audit   'mimic-response': [ '2.1.0', '3.1.0' ],
221 silly audit   chownr: [ '1.1.4' ],
221 silly audit   'tar-stream': [ '2.2.0' ],
221 silly audit   bl: [ '4.1.0' ],
221 silly audit   'fs-constants': [ '1.0.0' ],
221 silly audit   inherits: [ '2.0.4' ],
221 silly audit   'readable-stream': [ '3.6.2' ],
221 silly audit   buffer: [ '5.7.1' ],
221 silly audit   'base64-js': [ '1.5.1' ],
221 silly audit   ieee754: [ '1.2.1' ],
221 silly audit   string_decoder: [ '1.3.0' ],
221 silly audit   'util-deprecate': [ '1.0.2' ],
221 silly audit   'safe-buffer': [ '5.2.1' ]
221 silly audit }
222 info run canvas@3.0.0-rc2 install node_modules/canvas prebuild-install -r napi || node-gyp rebuild
223 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 275ms
224 silly audit report {}
225 info run canvas@3.0.0-rc2 install { code: 1, signal: null }
226 verbose stack Error: command failed
226 verbose stack     at promiseSpawn (C:\Users\maxim.mazurok\AppData\Local\nvs\node\20.16.0\x64\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:22:22)
226 verbose stack     at spawnWithShell (C:\Users\maxim.mazurok\AppData\Local\nvs\node\20.16.0\x64\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:124:10)
226 verbose stack     at promiseSpawn (C:\Users\maxim.mazurok\AppData\Local\nvs\node\20.16.0\x64\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:12:12)
226 verbose stack     at runScriptPkg (C:\Users\maxim.mazurok\AppData\Local\nvs\node\20.16.0\x64\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script-pkg.js:77:13)
226 verbose stack     at runScript (C:\Users\maxim.mazurok\AppData\Local\nvs\node\20.16.0\x64\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script.js:9:12)
226 verbose stack     at C:\Users\maxim.mazurok\AppData\Local\nvs\node\20.16.0\x64\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\rebuild.js:329:17
226 verbose stack     at run (C:\Users\maxim.mazurok\AppData\Local\nvs\node\20.16.0\x64\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:67:22)
226 verbose stack     at C:\Users\maxim.mazurok\AppData\Local\nvs\node\20.16.0\x64\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:84:9
226 verbose stack     at new Promise (<anonymous>)
226 verbose stack     at callLimit (C:\Users\maxim.mazurok\AppData\Local\nvs\node\20.16.0\x64\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:35:69)
227 verbose pkgid canvas@3.0.0-rc2
228 error code 1
229 error path C:\Users\maxim.mazurok\tmp\node_modules\canvas
230 error command failed
231 error command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install -r napi || node-gyp rebuild
232 error Warning: Missing input files:
232 error C:\GTK\bin\libintl-8.dll
232 error C:\GTK\bin\libpangowin32-1.0-0.dll
232 error C:\GTK\bin\zlib1.dll
232 error C:\GTK\bin\libpng14-14.dll
232 error C:\GTK\bin\libfreetype-6.dll
232 error C:\GTK\bin\libgthread-2.0-0.dll
232 error C:\GTK\bin\libglib-2.0-0.dll
232 error C:\GTK\bin\libpangoft2-1.0-0.dll
232 error C:\GTK\bin\libgmodule-2.0-0.dll
232 error C:\GTK\bin\libgobject-2.0-0.dll
232 error C:\GTK\bin\libpango-1.0-0.dll
232 error C:\GTK\bin\libexpat-1.dll
232 error C:\GTK\bin\libpangocairo-1.0-0.dll
232 error C:\GTK\bin\libfontconfig-1.dll
232 error C:\GTK\bin\libcairo-2.dll
232 error
232 error   Backend.cc
232 error C:\Users\maxim.mazurok\tmp\node_modules\canvas\src\backend\Backend.h(3,10): error C1083: Cannot open include file: 'cairo.h': No such file or directory [C:\Users\maxim.mazurok\tmp\node_modules\canvas\build\canvas.vcxproj]
233 error prebuild-install warn install No prebuilt binaries found (target=7 runtime=napi arch=x64 libc= platform=win32)
233 error gyp info it worked if it ends with ok
233 error gyp info using node-gyp@10.1.0
233 error gyp info using node@20.16.0 | win32 | x64
233 error gyp info find Python using Python version 3.10.6 found at "C:\Users\maxim.mazurok\AppData\Local\Programs\Python\Python310\python.exe"
233 error gyp info find VS using VS2022 (17.10.35122.118) found at:
233 error gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Professional"
233 error gyp info find VS run with --verbose for detailed information
233 error gyp info spawn C:\Users\maxim.mazurok\AppData\Local\Programs\Python\Python310\python.exe
233 error gyp info spawn args [
233 error gyp info spawn args 'C:\\Users\\maxim.mazurok\\AppData\\Local\\nvs\\node\\20.16.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
233 error gyp info spawn args 'binding.gyp',
233 error gyp info spawn args '-f',
233 error gyp info spawn args 'msvs',
233 error gyp info spawn args '-I',
233 error gyp info spawn args 'C:\\Users\\maxim.mazurok\\tmp\\node_modules\\canvas\\build\\config.gypi',
233 error gyp info spawn args '-I',
233 error gyp info spawn args 'C:\\Users\\maxim.mazurok\\AppData\\Local\\nvs\\node\\20.16.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
233 error gyp info spawn args '-I',
233 error gyp info spawn args 'C:\\Users\\maxim.mazurok\\AppData\\Local\\node-gyp\\Cache\\20.16.0\\include\\node\\common.gypi',
233 error gyp info spawn args '-Dlibrary=shared_library',
233 error gyp info spawn args '-Dvisibility=default',
233 error gyp info spawn args '-Dnode_root_dir=C:\\Users\\maxim.mazurok\\AppData\\Local\\node-gyp\\Cache\\20.16.0',
233 error gyp info spawn args '-Dnode_gyp_dir=C:\\Users\\maxim.mazurok\\AppData\\Local\\nvs\\node\\20.16.0\\x64\\node_modules\\npm\\node_modules\\node-gyp',
233 error gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\maxim.mazurok\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\20.16.0\\\\<(target_arch)\\\\node.lib',
233 error gyp info spawn args '-Dmodule_root_dir=C:\\Users\\maxim.mazurok\\tmp\\node_modules\\canvas',
233 error gyp info spawn args '-Dnode_engine=v8',
233 error gyp info spawn args '--depth=.',
233 error gyp info spawn args '--no-parallel',
233 error gyp info spawn args '--generator-output',
233 error gyp info spawn args 'C:\\Users\\maxim.mazurok\\tmp\\node_modules\\canvas\\build',
233 error gyp info spawn args '-Goutput_dir=.'
233 error gyp info spawn args ]
233 error gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe
233 error gyp info spawn args [
233 error gyp info spawn args 'build\\binding.sln',
233 error gyp info spawn args '/clp:Verbosity=minimal',
233 error gyp info spawn args '/nologo',
233 error gyp info spawn args '/p:Configuration=Release;Platform=x64'
233 error gyp info spawn args ]
233 error gyp ERR! build error 
233 error gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
233 error gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\maxim.mazurok\AppData\Local\nvs\node\20.16.0\x64\node_modules\npm\node_modules\node-gyp\lib\build.js:209:23)
233 error gyp ERR! stack at ChildProcess.emit (node:events:519:28)
233 error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
233 error gyp ERR! System Windows_NT 10.0.22631
233 error gyp ERR! command "C:\\Users\\maxim.mazurok\\AppData\\Local\\nvs\\node\\20.16.0\\x64\\node.exe" "C:\\Users\\maxim.mazurok\\AppData\\Local\\nvs\\node\\20.16.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
233 error gyp ERR! cwd C:\Users\maxim.mazurok\tmp\node_modules\canvas
233 error gyp ERR! node -v v20.16.0
233 error gyp ERR! node-gyp -v v10.1.0
233 error gyp ERR! not ok
234 silly unfinished npm timer reify 1723887266515
235 silly unfinished npm timer reify:build 1723887266976
236 silly unfinished npm timer build 1723887266976
237 silly unfinished npm timer build:deps 1723887266976
238 silly unfinished npm timer build:run:install 1723887267005
239 silly unfinished npm timer build:run:install:node_modules/canvas 1723887267006
240 verbose cwd C:\Users\maxim.mazurok\tmp
241 verbose os Windows_NT 10.0.22631
242 verbose node v20.16.0
243 verbose npm  v10.8.1
244 verbose exit 1
245 verbose code 1
246 error A complete log of this run can be found in: C:\Users\maxim.mazurok\AppData\Local\npm-cache\_logs\2024-08-17T09_34_26_172Z-debug-0.log

```

**Comment by Snuffleupagus** [comment]
> Seems like `unknown` part of `canvas-v3.0.0-rc2-napi-v7-win32unknown-x64.tar.gz` published file name is an extra, if it wasn't for it - prebuild would've been found.

With the caveat that I don't know anything about `node-canvas` development, the following code is perhaps relevant here since the "unknown"-string is the fallback-value for the `libc` parameter that's used when creating the filename:
https://github.com/Automattic/node-canvas/blob/8b238beb3c2c2569843ff672afbe731f15fd5769/prebuild/tarball.sh#L2-L9

**Comment by zbjornson** [comment]
Thanks, I fixed the name of the bundle for both Windows and MacOS. Can you give it another try please?

**Comment by acalcutt** [comment]
Seems like it works for me now.

**Comment by Maxim-Mazurok** [comment]
Works on Windows with 3.0.0-rc2 on node 20, closing, thanks!
