### ISSUE TITLE
Install issues advice

### ISSUE THREAD

**Issue by tkovis** [Automattic/node-canvas#2417]
In addition to following the readme instructions, on macos Sonoma 14.4 you might also need `brew install python-setuptools` or you end up with:
```
│ Traceback (most recent call last):
│   File "/Users/tuomaskoivistoinen/Library/pnpm/nodejs/18.17.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
│     import gyp  # noqa: E402
│     ^^^^^^^^^^
│   File "/Users/tuomaskoivistoinen/Library/pnpm/nodejs/18.17.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
│     import gyp.input
│   File "/Users/tuomaskoivistoinen/Library/pnpm/nodejs/18.17.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
│     from distutils.version import StrictVersion
```
while pnpm installing.

Just leaving this here in case someone else has issues with install.

**Comment by tkovis** [comment]
Wait just noticed it actually is in the readme and I have must have missed it or used some other list
