### ISSUE TITLE
pnpm  install  canvas successfully , but     importing  and   requiring  all   lead to  the  result of   ' can't find module   ' 

### ISSUE THREAD

**Issue by Super1Windcloud** [Automattic/node-canvas#2423]
A:\nvm_node_list\nodejs\node.exe --import tsx A:\Webstorm\awesome_example\pokerMagic\vue-demo\src\utils\poker.ts
A:\Webstorm\awesome_example\pokerMagic\vue-demo\src\utils
node:internal/modules/cjs/loader:1186
  const err = new Error(message);
              ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- A:\Webstorm\awesome_example\node_modules\.pnpm\canvas@2.11.2\node_modules\canvas\lib\bindings.js
- A:\Webstorm\awesome_example\node_modules\.pnpm\canvas@2.11.2\node_modules\canvas\lib\canvas.js
- A:\Webstorm\awesome_example\node_modules\.pnpm\canvas@2.11.2\node_modules\canvas\index.js
- A:\Webstorm\awesome_example\pokerMagic\vue-demo\src\utils\poker.ts
    at Module._resolveFilename (node:internal/modules/cjs/loader:1186:15)
    at m._resolveFilename (file:///A:/Webstorm/awesome_example/node_modules/.pnpm/tsx@4.17.0/node_modules/tsx/dist/register-BArwRho-.mjs:1:789)
    at nextResolveSimple (A:\Webstorm\awesome_example\node_modules\.pnpm\tsx@4.17.0\node_modules\tsx\dist\register-C1urN2EO.cjs:3:942)
    at A:\Webstorm\awesome_example\node_modules\.pnpm\tsx@4.17.0\node_modules\tsx\dist\register-C1urN2EO.cjs:2:2486
    at A:\Webstorm\awesome_example\node_modules\.pnpm\tsx@4.17.0\node_modules\tsx\dist\register-C1urN2EO.cjs:2:1560
    at resolveTsPaths (A:\Webstorm\awesome_example\node_modules\.pnpm\tsx@4.17.0\node_modules\tsx\dist\register-C1urN2EO.cjs:3:760)
    at Function._resolveFilename (A:\Webstorm\awesome_example\node_modules\.pnpm\tsx@4.17.0\node_modules\tsx\dist\register-C1urN2EO.cjs:3:1035)
    at Module._load (node:internal/modules/cjs/loader:1012:27)
    at Module.require (node:internal/modules/cjs/loader:1271:19)
    at require (node:internal/modules/helpers:123:16) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'A:\\Webstorm\\awesome_example\\node_modules\\.pnpm\\canvas@2.11.2\\node_modules\\canvas\\lib\\bindings.js',
    'A:\\Webstorm\\awesome_example\\node_modules\\.pnpm\\canvas@2.11.2\\node_modules\\canvas\\lib\\canvas.js',
    'A:\\Webstorm\\awesome_example\\node_modules\\.pnpm\\canvas@2.11.2\\node_modules\\canvas\\index.js',
    'A:\\Webstorm\\awesome_example\\pokerMagic\\vue-demo\\src\\utils\\poker.ts'
  ]
}

Node.js v22.2.0

进程已结束，退出代码为 1

**Comment by 34j** [comment]
```
pnpm approve-builds
```

should resolve this

**Comment by yuewen-zm** [comment]
How to solve this problem

**Comment by 34j** [comment]
Run pnpm approve-builds and select node-canvas.

**Comment by yuewen-zm** [comment]
<img width="555" alt="Image" src="https://github.com/user-attachments/assets/4702940c-09cb-4eca-a8e2-02e0b1a4f4fe" />

> Run pnpm approve-builds and select node-canvas.


Help me I added it, but it still gives an error.

**Comment by 34j** [comment]
@yuewen-zm Since this is no longer related to node-canvas, I suggest you read https://github.com/pnpm/pnpm/issues/9124 and ask your question there.

**Comment by yuewen-zm** [comment]
> [@yuewen-zm](https://github.com/yuewen-zm) Since this is no longer related to node-canvas, I suggest you read [pnpm/pnpm#9124](https://github.com/pnpm/pnpm/issues/9124) and ask your question there.

Thanks, I changed to npm and it works fine now
