### ISSUE TITLE
^ Error: Cannot find module '../build/default/canvas'

### ISSUE THREAD

**Issue by BigSmurf** [Automattic/node-canvas#243]
hi everybody

i have follow all the instruction in https://github.com/LearnBoost/node-canvas/wiki/Installation---Amazon-Linux-AMI-(EC2)

and the installation seems ok
```
info it worked if it ends with ok 
spawn python [ '/root/.node-gyp/0.6.17/tools/gyp_addon',
  'binding.gyp',
  '-I/mnt/hgfs/git/node.js/node_modules/canvas/build/config.gypi',
  '-f',
  'make' ]
spawn make [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/mnt/hgfs/git/node.js/node_modules/canvas/build'
  CXX(target) Release/obj.target/canvas/src/Canvas.o
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
  CXX(target) Release/obj.target/canvas/src/color.o
  CXX(target) Release/obj.target/canvas/src/Image.o
  CXX(target) Release/obj.target/canvas/src/ImageData.o
  CXX(target) Release/obj.target/canvas/src/init.o
  CXX(target) Release/obj.target/canvas/src/PixelArray.o
  SOLINK_MODULE(target) Release/obj.target/canvas.node
  SOLINK_MODULE(target) Release/obj.target/canvas.node: Finished
  COPY Release/canvas.node
make: Leaving directory `/mnt/hgfs/git/node.js/node_modules/canvas/build'
info done ok 
```

but now when i try to start my application i get this message:
```
Error: Unable to load shared library /mnt/hgfs/git/node.js/node_modules/canvas/build/Release/canvas.node
    at Object..node (module.js:472:11)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/mnt/hgfs/git/node.js/node_modules/canvas/lib/bindings.js:2:18)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
```

i simple do Canvas = require('canvas')

this is very strange... anyone have a solution??

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
