### ISSUE TITLE
404 Not Found on canvas-v2.11.2-node-v127-win32-unknown-x64.tar.gz

### ISSUE THREAD

**Issue by xalteropsx** [Automattic/node-canvas#2430]
tried npm clean cache 
also install node-pre-gyp fresh 

window 11 
latest node version

error X:\sad\practice\Ragna\node_modules\canvas: Command failed.
Exit code: 7
Command: node-pre-gyp install --fallback-to-build --update-binary
Arguments:
Directory: X:\sad\practice\Ragna\node_modules\canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@22.9.0 | win32 | x64
(node:14152) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-win32-unknown-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-win32-unknown-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@22.9.0 (node-v127 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-win32-unknown-x64.tar.gz
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack Error: spawn EINVAL
node-pre-gyp ERR! stack     at ChildProcess.spawn (node:internal/child_process:420:11)
node-pre-gyp ERR! stack     at Object.spawn (node:child_process:761:9)
node-pre-gyp ERR! stack     at module.exports.run_gyp (X:\sad\practice\Ragna\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:80:18)
node-pre-gyp ERR! stack     at build (X:\sad\practice\Ragna\node_modules\@mapbox\node-pre-gyp\lib\build.js:41:13)
node-pre-gyp ERR! stack     at self.commands.<computed> [as build] (X:\sad\practice\Ragna\node_modules\@mapbox\node-pre-gyp\lib\node-pre-gyp.js:86:37)
node-pre-gyp ERR! stack     at run (X:\sad\practice\Ragna\node_modules\@mapbox\node-pre-gyp\lib\main.js:81:30)
node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
node-pre-gyp ERR! System Windows_NT 10.0.22631
node-pre-gyp ERR! command "X:\\z\\nodejs\\node.exe" "X:\\sad\\practice\\Ragna\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--update-binary"

X:\sad\practice\Ragna>node-pre-gyp install --fallback-to-build --update-binary
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.17.0
node-pre-gyp info using node@22.9.0 | win32 | x64
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: amd package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties:
node-pre-gyp ERR! stack main
node-pre-gyp ERR! stack binary.module_name
node-pre-gyp ERR! stack binary.module_path
node-pre-gyp ERR! stack binary.host
node-pre-gyp ERR! stack     at validate_config (C:\Users\haide\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\versioning.js:220:15)
node-pre-gyp ERR! stack     at module.exports.evaluate (C:\Users\haide\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\versioning.js:279:5)
node-pre-gyp ERR! stack     at install (C:\Users\haide\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\install.js:241:31)
node-pre-gyp ERR! stack     at self.commands.<computed> [as install] (C:\Users\haide\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\node-pre-gyp.js:52:37)
node-pre-gyp ERR! stack     at run (C:\Users\haide\AppData\Roaming\npm\node_modules\node-pre-gyp\bin\node-pre-gyp:82:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (C:\Users\haide\AppData\Roaming\npm\node_modules\node-pre-gyp\bin\node-pre-gyp:134:1)
node-pre-gyp ERR! stack     at Module._compile (node:internal/modules/cjs/loader:1546:14)
node-pre-gyp ERR! stack     at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
node-pre-gyp ERR! stack     at Module.load (node:internal/modules/cjs/loader:1317:32)
node-pre-gyp ERR! stack     at Module._load (node:internal/modules/cjs/loader:1127:12)
node-pre-gyp ERR! System Windows_NT 10.0.22631
node-pre-gyp ERR! command "X:\\z\\nodejs\\node.exe" "C:\\Users\\haide\\AppData\\Roaming\\npm\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
node-pre-gyp ERR! cwd X:\sad\practice\Ragna
node-pre-gyp ERR! node -v v22.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.17.0
node-pre-gyp ERR! not ok
amd package.json is not node-pre-gyp ready:
package.json must declare these properties:
main
binary.module_name
binary.module_path
binary.host

**Comment by Downchuck** [comment]
This is for node v22 which was released in 2024, where the canvas pre-built binaries were released a year prior.

Note that canvas@next has a more recent build.

**Comment by rynop** [comment]
@Downchuck canvas v3/next is not prod ready (it is still RC).

Are there any plans for node v22 pre-built binaries as it is the current and soon to be active LTS?  @see https://nodejs.org/en/about/previous-releases

**Comment by Downchuck** [comment]
@rynop I'm not a part of the maintainers - but you make a good argument for a node v22 pre build of the prior version.  It would have made my life a bit easier last week to have that, as well as an available musl build for alpine images.

Hoping to get some time in shortly to see if I can put together a PR.

**Comment by mikhailbartashevich** [comment]
Same issue for Linux node@22.9.0
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz

**Comment by alumni** [comment]
node@22.11.0 is now LTS

It would be great to have prebuilds to make our life easier.

**Comment by dalyr95** [comment]
Any news on this? Especially with node 18 EOL, a lot of people will be upgrading. There’s 2.5 million downloads per week and if they all have to compile binaries think of the wasted CPU and $$$.

**Comment by chearon** [comment]
Yes, I posted an update here: https://github.com/Automattic/node-canvas/issues/2448#issuecomment-2520347619

Sorry but people will probably have to upgrade to 3.0 when I release it in order to get prebuilds for node 22. 3.0 changes the prebuild script significantly, which already breaks often and often takes days to fix, so we can't afford to maintain scripts for 2.11. I will try though.

**Comment by karlhorky** [comment]
@chearon why was this closed as "not planned"?

**Comment by alumni** [comment]
@karlhorky `canvas@3` is already fixing it by switching to n-api v7 (compatible with node 8+). There's no need to worry about `canvas@2` anymore :)
