### ISSUE TITLE
NPM Not Installing - Can't find -lcairo

### ISSUE THREAD

**Issue by joemccann** [Automattic/node-canvas#259]
Really bizarre because when I clone the node-canvas repo and run the tests, all tests pass.

Yet running

`npm i canvas`

I get the following:

```
> canvas@1.0.0 install /Users/joemccann/Documents/workspace/imgcmp/node_modules/canvas
> node-gyp rebuild

  CXX(target) Release/obj.target/canvas/src/Canvas.o
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
  CXX(target) Release/obj.target/canvas/src/color.o
  CXX(target) Release/obj.target/canvas/src/Image.o
  CXX(target) Release/obj.target/canvas/src/ImageData.o
  CXX(target) Release/obj.target/canvas/src/init.o
  CXX(target) Release/obj.target/canvas/src/PixelArray.o
  CXX(target) Release/obj.target/canvas/src/FontFace.o
  SOLINK_MODULE(target) Release/canvas.node
ld: library not found for -lcairo
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/canvas.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:255:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:674:10)
gyp ERR! System Darwin 11.4.2
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/joemccann/Documents/workspace/imgcmp/node_modules/canvas
gyp ERR! node -v v0.8.7
gyp ERR! node-gyp -v v0.8.4
gyp ERR! not ok 
npm ERR! canvas@1.0.0 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the canvas@1.0.0 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "i" "canvas"
npm ERR! cwd /Users/joemccann/Documents/workspace/imgcmp
npm ERR! node -v v0.8.7
npm ERR! npm -v 1.2.12
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/joemccann/Documents/workspace/imgcmp/npm-debug.log
npm ERR! not ok code 0
```

**Comment by mltucker** [comment]
Were you able to solve this?  It sounds like a pkg-config issue.  Did you set the `PKG_CONFIG_PATH`?

```
$ export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig
```

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
