### ISSUE TITLE
Package 'fontconfig', required by 'cairo', not found

### ISSUE THREAD

**Issue by feross** [Automattic/node-canvas#260]
Getting this error after updating from pre-1.0 version of node-canvas. On OS X 10.8.2.

```
fullmetal ~/code/node-simple-build master ✹ ✭ $ npm install canvas     
npm http GET https://registry.npmjs.org/canvas
npm http 304 https://registry.npmjs.org/canvas
npm http GET https://registry.npmjs.org/canvas/-/canvas-1.0.1.tgz
npm http 200 https://registry.npmjs.org/canvas/-/canvas-1.0.1.tgz

> canvas@1.0.1 install /Users/feross/code/node-simple-build/node_modules/canvas
> node-gyp rebuild

Package fontconfig was not found in the pkg-config search path.
Perhaps you should add the directory containing `fontconfig.pc'
to the PKG_CONFIG_PATH environment variable
Package 'fontconfig', required by 'cairo', not found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:416:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Darwin 12.2.1
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/feross/code/node-simple-build/node_modules/canvas
gyp ERR! node -v v0.8.20
gyp ERR! node-gyp -v v0.8.4
gyp ERR! not ok 
npm ERR! canvas@1.0.1 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the canvas@1.0.1 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.2.1
npm ERR! command "node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! cwd /Users/feross/code/node-simple-build
npm ERR! node -v v0.8.20
npm ERR! npm -v 1.2.11
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/feross/code/node-simple-build/npm-debug.log
npm ERR! not ok code 0
```

**Comment by ngoldman** [comment]
:fireworks: for @mbostock

**Comment by senica** [comment]
Quick note, if you have to install npm packages with `sudo npm install` then put a sudo in the front of this command so the full command not in front of npm in this command `sudo PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig/ npm install canvas`

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
