### ISSUE TITLE
Failed to install canvas 1.0.2

### ISSUE THREAD

**Issue by justin-john** [Automattic/node-canvas#282]
I was installing the [node-captcha](https://github.com/napa3um/node-captcha) to Express App. But it failed to install with following error.

	Package cairo was not found in the pkg-config search path.
	Perhaps you should add the directory containing `cairo.pc'
	to the PKG_CONFIG_PATH environment variable
	No package 'cairo' found
	Traceback (most recent call last):
	  File "/home/justin/.node-gyp/0.8.2/tools/gyp/gyp", line 18, in <module>
	    sys.exit(gyp.main(sys.argv[1:]))
	  File "/home/justin/.node-gyp/0.8.2/tools/gyp/pylib/gyp/__init__.py", line 471, in main
	    options.circular_check)
	  File "/home/justin/.node-gyp/0.8.2/tools/gyp/pylib/gyp/__init__.py", line 111, in Load
	    depth, generator_input_info, check, circular_check)
	  File "/home/justin/.node-gyp/0.8.2/tools/gyp/pylib/gyp/input.py", line 2378, in Load
	    depth, check)
	  File "/home/justin/.node-gyp/0.8.2/tools/gyp/pylib/gyp/input.py", line 384, in LoadTargetBuildFile
	    build_file_data, PHASE_EARLY, variables, build_file_path)
	  File "/home/justin/.node-gyp/0.8.2/tools/gyp/pylib/gyp/input.py", line 1027, in ProcessVariablesAndConditionsInDict
	    ProcessConditionsInDict(the_dict, phase, variables, build_file)
	  File "/home/justin/.node-gyp/0.8.2/tools/gyp/pylib/gyp/input.py", line 904, in ProcessConditionsInDict
	    variables, build_file)
	  File "/home/justin/.node-gyp/0.8.2/tools/gyp/pylib/gyp/input.py", line 975, in ProcessVariablesAndConditionsInDict
	    variables, build_file, 'variables')
	  File "/home/justin/.node-gyp/0.8.2/tools/gyp/pylib/gyp/input.py", line 982, in ProcessVariablesAndConditionsInDict
	    expanded = ExpandVariables(value, phase, variables, build_file)
	  File "/home/justin/.node-gyp/0.8.2/tools/gyp/pylib/gyp/input.py", line 714, in ExpandVariables
	    (contents, p.returncode))
	Exception: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
	gyp ERR! configure error 
	gyp ERR! stack Error: `gyp` failed with exit code: 1
	gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:350:16)
	gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:91:17)
	gyp ERR! stack     at Process._handle.onexit (child_process.js:674:10)
	gyp ERR! System Linux 2.6.35-22-generic
	gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /home/justin/www/test/node_modules/captcha/node_modules/canvas
	gyp ERR! node -v v0.8.2
	gyp ERR! node-gyp -v v0.7.1
	gyp ERR! not ok 
	npm ERR! canvas@1.0.2 install: `node-gyp rebuild`
	npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
	npm ERR! 
	npm ERR! Failed at the canvas@1.0.2 install script.

How to correct this error?

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
