### ISSUE TITLE
NAN Compile Errors on OSX 10.8.4 and 

### ISSUE THREAD

**Issue by guomo** [Automattic/node-canvas#325]
Had this working a few months back with 1.02 but the new release seems to have broken something related to NAN (saw an update to that 12 days ago so maybe....). I followed the instructions on the wiki and installed to a T everything else. Here are my errors all related :
```
    > node-gyp rebuild

      CXX(target) Release/obj.target/canvas/src/Canvas.o
    In file included from ../src/Canvas.cc:7:
    In file included from ../src/Canvas.h:22:
    ../src/nan.h:188:13: error: no member named 'smalloc' in namespace 'node'
          node::smalloc::FreeCallback callback,
          ~~~~~~^
    ../src/nan.h:203:26: error: no member named 'Use' in 'node::Buffer'
        return node::Buffer::Use(data, size);
               ~~~~~~~~~~~~~~^
    In file included from ../src/Canvas.cc:7:
    ../src/Canvas.h:56:12: error: no type named 'FunctionCallbackInfo' in namespace 'v8'
        static NAN_METHOD(New);
               ^~~~~~~~~~~~~~~
    ../src/nan.h:102:37: note: expanded from macro 'NAN_METHOD'
    # define NAN_METHOD(name) void name(_NAN_METHOD_ARGS)
                                        ^~~~~~~~~~~~~~~~
    ../src/nan.h:101:37: note: expanded from macro '_NAN_METHOD_ARGS'
    # define _NAN_METHOD_ARGS const v8::FunctionCallbackInfo<v8::Value>& args
                                    ~~~~^
    In file included from ../src/Canvas.cc:7:
    ../src/Canvas.h:56:12: error: expected ')'
        static NAN_METHOD(New);
               ^
    ../src/nan.h:102:37: note: expanded from macro 'NAN_METHOD'
    # define NAN_METHOD(name) void name(_NAN_METHOD_ARGS)
                                        ^
    ../src/nan.h:101:57: note: expanded from macro '_NAN_METHOD_ARGS'
    # define _NAN_METHOD_ARGS const v8::FunctionCallbackInfo<v8::Value>& args
                                                            ^
    ../src/Canvas.h:56:12: note: to match this '('
        static NAN_METHOD(New);
               ^

(snip more of the same macro error)

               ^~~~~~~~~~~~~~~~~~~
    ../src/nan.h:105:47: note: expanded from macro 'NAN_GETTER'
        void name(v8::Local<v8::String> property, _NAN_GETTER_ARGS)
                                                  ^~~~~~~~~~~~~~~~
 
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:100:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
    gyp ERR! System Darwin 12.4.0
    gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Volumes/Annex/sources/cloud-tot/siren/services/mediabot/node_modules/canvas
    gyp ERR! node -v v0.11.2
    gyp ERR! node-gyp -v v0.9.5
    gyp ERR! not ok 
    npm ERR! weird error 1
    npm ERR! not ok code 0
```

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
