### ISSUE TITLE
Problem with installing canvas

### ISSUE THREAD

**Issue by Vadorequest** [Automattic/node-canvas#330]
Hi.
I can't install canvas, there are a lot of errors.
I followed all instructions here:
https://github.com/LearnBoost/node-canvas/wiki/Installation---Windows
And all works. (I have already installed MVS 2010 ultimate and 2012 ultimate before)

The file cairo.h cannot found:
 No such file or directory [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]

**I have installed**:
G:\Programmation perso\Ninja\Librairies\sheetengine-examples>**python**
Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win32

G:\Programmation perso\Ninja\Librairies\sheetengine-examples>**node-gyp -v**
v0.10.10

node-gyp configure build
Works correctly, no error. OK.

G:\Programmation perso\Ninja\Librairies\sheetengine-examples>**pkg-config --cflags gtk+-2.0**
-mms-bitfields -IC:/GTK/include/gtk-2.0 -IC:/GTK/lib/gtk-2.0/include -IC:/GTK/include/atk-1.0 -IC:/GTK/include/cairo -IC:/GTK/include/gdk-pixbuf-2.0 -IC:/GTK/include/pango-1.0 -IC:/GTK/include/glib-2.0 -IC:/GTK/lib/glib-2.0/include -IC:/GTK/include -IC:/GTK/include/freetype2 -IC:/GTK/include/libpng14

G:\Programmation perso\Ninja\Librairies\sheetengine-examples>**gtk-demo**
Works. (Display an interface)

G:\Programmation perso\Ninja\Librairies\sheetengine-examples>npm install canvas
npm http GET https://registry.npmjs.org/canvas
npm http 304 https://registry.npmjs.org/canvas

> canvas@1.1.0 install G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas
> node-gyp rebuild

Do you have any idea ?
Thank you.

Details: (^^)
```
G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
  CanvasRenderingContext2d.cc
  CanvasPattern.cc
  color.cc
  PixelArray.cc
..\src\color.cc(353): warning C4305: 'initialisation' : troncation de 'double' à 'float' [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\color.cc(356): warning C4305: '*=' : troncation de 'double' à 'float' [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
  ImageData.cc
C:\Users\Ambroise\.node-gyp\0.8.20\deps\v8\include\v8.h(178): warning C4506: aucune définition pour la fonction inline 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\Users\Ambroise\.node-gyp\0.8.20\deps\v8\include\v8.h(178): warning C4506: aucune définition pour la fonction inline 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
          with
          [
              T=v8::FunctionTemplate
          ]
  Canvas.cc
C:\Users\Ambroise\.node-gyp\0.8.20\deps\v8\include\v8.h(178): warning C4506: aucune définition pour la fonction inline 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\Users\Ambroise\.node-gyp\0.8.20\deps\v8\include\v8.h(178): warning C4506: aucune définition pour la fonction inline 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\Users\Ambroise\.node-gyp\0.8.20\deps\v8\include\v8.h(178): warning C4506: aucune définition pour la fonction inline 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
          with
          [
              T=v8::FunctionTemplate
          ]
C:\Users\Ambroise\.node-gyp\0.8.20\deps\v8\include\v8.h(178): warning C4506: aucune définition pour la fonction inline 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
          with
          [
              T=v8::FunctionTemplate
          ]
  init.cc
  Image.cc
..\src\CanvasRenderingContext2d.cc(636): warning C4244: '=' : conversion de 'double' en 'int', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(637): warning C4244: '=' : conversion de 'double' en 'int', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(638): warning C4244: '=' : conversion de 'double' en 'int', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(639): warning C4244: '=' : conversion de 'double' en 'int', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(640): warning C4244: '=' : conversion de 'double' en 'int', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(641): warning C4244: '=' : conversion de 'double' en 'int', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(642): warning C4244: '=' : conversion de 'double' en 'int', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(643): warning C4244: '=' : conversion de 'double' en 'int', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(647): warning C4244: '=' : conversion de 'double' en 'int', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(648): warning C4244: '=' : conversion de 'double' en 'int', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(649): warning C4244: '=' : conversion de 'double' en 'int', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(650): warning C4244: '=' : conversion de 'double' en 'int', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(654): warning C4244: '=' : conversion de 'double' en 'int', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(655): warning C4244: '=' : conversion de 'double' en 'int', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(676): warning C4244: '/=' : conversion de 'float' en 'int', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(677): warning C4244: '/=' : conversion de 'float' en 'int', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(708): warning C4244: '=' : conversion de 'double' en 'float', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(927): warning C4244: 'initialisation' : conversion de 'double' en 'int', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(2154): warning C4244: 'argument' : conversion de 'double' en 'float', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(2154): warning C4244: 'argument' : conversion de 'double' en 'float', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(2157): warning C4244: 'argument' : conversion de 'double' en 'float', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(2157): warning C4244: 'argument' : conversion de 'double' en 'float', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(2160): warning C4244: 'argument' : conversion de 'double' en 'float', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(2160): warning C4244: 'argument' : conversion de 'double' en 'float', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(2162): warning C4244: 'initialisation' : conversion de 'double' en 'float', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(2187): warning C4244: 'argument' : conversion de 'double' en 'float', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(2187): warning C4244: 'argument' : conversion de 'double' en 'float', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(2192): warning C4244: 'initialisation' : conversion de 'double' en 'float', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(2209): warning C4244: '=' : conversion de 'double' en 'float', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
..\src\CanvasRenderingContext2d.cc(2219): warning C4244: '=' : conversion de 'double' en 'float', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
g:\programmation perso\ninja\librairies\sheetengine-examples\node_modules\canvas\src\PNG.h(5): fatal error C1083: Impossible d'ouvrir le fichier include : 'cairo.h' : No such file or directory [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
  CanvasGradient.cc
C:\Users\Ambroise\.node-gyp\0.8.20\deps\v8\include\v8.h(217): warning C4506: aucune définition pour la fonction inline 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\Users\Ambroise\.node-gyp\0.8.20\deps\v8\include\v8.h(217): warning C4506: aucune définition pour la fonction inline 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
          with
          [
              T=v8::FunctionTemplate
          ]
..\src\Image.cc(185): warning C4267: 'initialisation' : conversion de 'size_t' en 'unsigned int', perte possible de données [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
C:\Users\Ambroise\.node-gyp\0.8.20\deps\v8\include\v8.h(178): warning C4506: aucune définition pour la fonction inline 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\Users\Ambroise\.node-gyp\0.8.20\deps\v8\include\v8.h(178): warning C4506: aucune définition pour la fonction inline 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
          with
          [
              T=v8::FunctionTemplate
          ]
C:\Users\Ambroise\.node-gyp\0.8.20\deps\v8\include\v8.h(178): warning C4506: aucune définition pour la fonction inline 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\Users\Ambroise\.node-gyp\0.8.20\deps\v8\include\v8.h(217): warning C4506: aucune définition pour la fonction inline 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\Users\Ambroise\.node-gyp\0.8.20\deps\v8\include\v8.h(217): warning C4506: aucune définition pour la fonction inline 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas\build\canvas.vcxproj]
          with
          [
              T=v8::FunctionTemplate
          ]
gyp ERR! build error
gyp ERR! stack Error: `c:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:256:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd G:\Programmation perso\Ninja\Librairies\sheetengine-examples\node_modules\canvas
gyp ERR! node -v v0.8.20
gyp ERR! node-gyp -v v0.8.5
gyp ERR! not ok
npm ERR! canvas@1.1.0 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the canvas@1.1.0 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "canvas"
npm ERR! cwd G:\Programmation perso\Ninja\Librairies\sheetengine-examples
npm ERR! node -v v0.8.20
npm ERR! npm -v 1.2.11
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     G:\Programmation perso\Ninja\Librairies\sheetengine-examples\npm-debug.log
npm ERR! not ok code 0

G:\Programmation perso\Ninja\Librairies\sheetengine-examples>


```

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
