### ISSUE TITLE
sudo npm install canvas error

### ISSUE THREAD

**Issue by johnfelipe** [Automattic/node-canvas#401]
```
    > canvas@1.1.3 install /home/notroot/node_modules/canvas
    > node-gyp rebuild

    /bin/sh: 1: node: not found
    gyp: Call to 'node -p -e "require('path').relative('.', require('path').dirname(require.resolve('nan')))"' returned exit status 127. while trying to load binding.gyp
    gyp ERR! configure error
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
    gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
    gyp ERR! System Linux 3.11.0-12-generic
    gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
    gyp ERR! cwd /home/notroot/node_modules/canvas
    gyp ERR! node -v v0.10.15
    gyp ERR! node-gyp -v v0.10.9
    gyp ERR! not ok
    npm WARN This failure might be due to the use of legacy binary "node"
    npm WARN For further explanations, please read
    /usr/share/doc/nodejs/README.Debian

    npm ERR! canvas@1.1.3 install: `node-gyp rebuild`
    npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
    npm ERR!
    npm ERR! Failed at the canvas@1.1.3 install script.
    npm ERR! This is most likely a problem with the canvas package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls canvas
    npm ERR! There is likely additional logging output above.

    npm ERR! System Linux 3.11.0-12-generic
    npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "canvas"
    npm ERR! cwd /home/notroot
    npm ERR! node -v v0.10.15
    npm ERR! npm -v 1.2.18
    npm ERR! code ELIFECYCLE
    npm ERR!
    npm ERR! Additional logging details can be found in:
    npm ERR!     /home/notroot/npm-debug.log
    npm ERR! not ok code 0
```

**Comment by suresh-mits** [comment]
Is this issue resolved? i am getting the same one, need help...

**Comment by LinusU** [comment]
@suresh-mits This isn't a problem with node-canvas and shouldn't be solved here.

Are you sure you are hitting this exact problem thought? What does `node --version` output?
