### ISSUE TITLE
npm install fails on "Call to './util/has_lib.sh jpeg'" with OS X 10.8.5

### ISSUE THREAD

**Issue by ghost** [Automattic/node-canvas#419]
Step 1 (Success):

```
curl https://raw.githubusercontent.com/LearnBoost/node-canvas/master/install | sh
```

Step 2 (FAIL): 

```
npm install canvas
npm WARN package.json Shopland@5.0.0 No repository field.
npm http GET https://registry.npmjs.org/canvas
npm http 304 https://registry.npmjs.org/canvas
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> canvas@1.1.3 install /Users/vdiaz/Documents/_Git/Shopland/node_modules/canvas
> node-gyp rebuild

which: no ldconfig in (/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/vdiaz/Documents/_Git/Shopland/node_modules/canvas/node_modules/.bin:/Users/vdiaz/Documents/_Git/Shopland/node_modules/.bin:/usr/local/bin:/Users/vDiaz/bin/Sencha/Cmd/3.0.0.250:/usr/local/share/npm/bin/:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/adt-bundle-mac-x86_64-20130917/sdk/platform-tools/:/sbin)
gyp: Call to './util/has_lib.sh jpeg' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Darwin 12.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/vdiaz/Documents/_Git/Shopland/node_modules/canvas
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm ERR! canvas@1.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.1.3 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.5.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! cwd /Users/vdiaz/Documents/_Git/Shopland
npm ERR! node -v v0.11.13
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/vdiaz/Documents/_Git/Shopland/npm-debug.log
npm ERR! not ok code 0
```

Tried with node version 0.10.26 and 0.11.13 with same results. Did full cache clear on node each time.

**Comment by simenbrekken** [comment]
@ziyunfei Works like a charm. thanks!

**Comment by LinusU** [comment]
@simenbrekken That shouldn't be needed anymore, did you really need to do it? Are you installing the latest version?

**Comment by simenbrekken** [comment]
@LinusU I'm not sure, this was in attempt to revive an old project. I'll try to get around to checking it but it's probably just my old setup.

**Comment by ifahrentholz** [comment]
I had the same issue last day. The solution @ziyunfei provided works but is not very comfortable to use.

**Comment by zhuweiyou** [comment]
> @vdiaz212
> I found a solution:
> 
> ```shell
> sudo echo > /usr/local/bin/ldconfig
> sudo chmod +x /usr/local/bin/ldconfig
> npm install canvas
> sudo rm -f /usr/local/bin/ldconfig
> ```

thank you
