### ISSUE TITLE
Build failure on Mac OS X due to /util/has_lib.sh linuxism

### ISSUE THREAD

**Issue by acuster** [Automattic/node-canvas#436]
The build of current Git (2014-06-11) fails on Mac OS X due to /util/has_lib.sh checking for 'ldconfig' which does not exist on Mac OS X.  This is fixed by commenting out lines 10-12 in /util/has_lib.sh. A proper fix would be to check for 'ldconfig' only on linux.

[1] build log with failure (on 12th line)
```
PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig/ npm install canvas
npm http GET https://registry.npmjs.org/canvas
npm http 304 https://registry.npmjs.org/canvas
npm http GET https://registry.npmjs.org/canvas/-/canvas-1.1.4.tgz
npm http 200 https://registry.npmjs.org/canvas/-/canvas-1.1.4.tgz
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> canvas@1.1.4 install /Users/acuster/node_modules/canvas
> node-gyp rebuild

which: no ldconfig in (/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/acuster/node_modules/canvas/node_modules/.bin:/Users/acuster/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/git/bin:/usr/texbin:/sbin)
gyp: Call to './util/has_lib.sh jpeg' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Darwin 13.2.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/acuster/node_modules/canvas
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! canvas@1.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.1.4 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! cwd /Users/acuster/temp
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/acuster/temp/npm-debug.log
npm ERR! not ok code 0
```

[2] Diff that enables the build
```
diff --git a/util/has_lib.sh b/util/has_lib.sh
index 27911b6..d615ec7 100755
--- a/util/has_lib.sh
+++ b/util/has_lib.sh
@@ -7,9 +7,9 @@ has_lib() {
   PATH="$PATH:/sbin"
   export PATH
   # Try using ldconfig on linux systems
-  for LINE in `which ldconfig > /dev/null && ldconfig -p 2>/dev/null | grep -E $regex`; do
-    return 0
-  done
+#  for LINE in `which ldconfig > /dev/null && ldconfig -p 2>/dev/null | grep -E $regex`; do
+#    return 0
+#  done
 
   # Try just checking common library locations
   for dir in /lib /usr/lib /usr/local/lib /opt/local/lib /usr/lib/x86_64-linux-gnu /usr/lib/i386-linux-gnu; do
```

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
