### ISSUE TITLE
Installation Amazon Linux AMI (EC2) fails

### ISSUE THREAD

**Issue by joe-singer** [Automattic/node-canvas#445]
After installing multiple times per the instructions I continually encounter the following error when attempting to launch my app.

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: libcairo.so.2: cannot open shared object file: No such file or directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ec2-user/projects/scramble/dev/node_modules/canvas/lib/bindings.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by LinusU** [comment]
The following should work:

```sh
sudo yum install cairo cairo-devel cairomm-devel libjpeg-turbo-devel pango pango-devel pangomm pangomm-devel giflib-devel
```
