### ISSUE TITLE
Keep getting error trying to install canvas on Win 8.1

### ISSUE THREAD

**Issue by Frank84** [Automattic/node-canvas#469]
I followed the instruction from this Wiki: https://github.com/Automattic/node-canvas/wiki/Installation---Windows, but i'm always getting the same error: (full error output below)

```
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:1001:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

Here is my configuration:
Windows 8.1
Node v0.10.31
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
Microsoft Visual C++ 2010 Express

I tried to install Node & Python in both 32-bits and both in 64-bits, but without any success. Here is the full output for the command `npm install canvas --msvs_version=2012 -verbose`

```
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
npm verb cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   'canvas',
npm verb cli   '--msvs_version=2012',
npm verb cli   '-verbose' ]
npm info using npm@1.4.23
npm info using node@v0.10.31
npm verb node symlink C:\Program Files (x86)\nodejs\\node.exe
npm WARN package.json francisbolduc.com@0.1.0 homepage field must start with a protocol.
npm verb readDependencies using package.json deps
npm verb cache add [ 'canvas', null ]
npm verb cache add name=undefined spec="canvas" args=["canvas",null]
npm verb parsed url { protocol: null,
npm verb parsed url   slashes: null,
npm verb parsed url   auth: null,
npm verb parsed url   host: null,
npm verb parsed url   port: null,
npm verb parsed url   hostname: null,
npm verb parsed url   hash: null,
npm verb parsed url   search: null,
npm verb parsed url   query: null,
npm verb parsed url   pathname: 'canvas',
npm verb parsed url   path: 'canvas',
npm verb parsed url   href: 'canvas' }
npm verb lock canvas C:\Users\Francis\AppData\Roaming\npm-cache\7aa15835-canvas.lock
npm verb addNamed [ 'canvas', '' ]
npm verb addNamed [ null, '*' ]
npm verb lock canvas@ C:\Users\Francis\AppData\Roaming\npm-cache\7328b956-canvas.lock
npm verb request where is /canvas
npm verb request registry https://registry.npmjs.org/
npm verb request id 4b792ccac2f9fedd
npm verb url raw /canvas
npm verb url resolving [ 'https://registry.npmjs.org/', './canvas' ]
npm verb url resolved https://registry.npmjs.org/canvas
npm verb request where is https://registry.npmjs.org/canvas
npm info trying registry request attempt 1 at 22:28:03
npm verb etag "5KVUSXX6078BQYPYHUJ12R9AS"
npm http GET https://registry.npmjs.org/canvas
npm http 304 https://registry.npmjs.org/canvas
npm verb etag https://registry.npmjs.org/canvas from cache
npm verb addNamed [ 'canvas', '1.1.6' ]
npm verb addNamed [ '1.1.6', '1.1.6' ]
npm verb lock canvas@1.1.6 C:\Users\Francis\AppData\Roaming\npm-cache\4f76786f-canvas-1-1-6.lock
npm info install canvas@1.1.6 into C:\Users\Francis\Developer\fb.com
npm info installOne canvas@1.1.6
npm verb node_modules\canvas unbuild
npm verb tar unpack C:\Users\Francis\AppData\Roaming\npm-cache\canvas\1.1.6\package.tgz
npm verb lock tar://C:\Users\Francis\Developer\fb.com\node_modules\canvas C:\Users\Francis\AppData\Roaming\npm-cache\8f67bcd2-loper-fb-com-node-modules-canvas.lock npm verb lock tar://C:\Users\Francis\AppData\Roaming\npm-cache\canvas\1.1.6\package.tgz C:\Users\Francis\AppData\Roaming\npm-cache\e866554d-m-cache-canvas-1-1-6-package-tgz.lock
npm info preinstall canvas@1.1.6
npm verb readDependencies using package.json deps
npm verb readDependencies using package.json deps
npm verb cache add [ 'nan@~1.2.0', null ]
npm verb cache add name=undefined spec="nan@~1.2.0" args=["nan@~1.2.0",null]
npm verb parsed url { protocol: null,
npm verb parsed url   slashes: null,
npm verb parsed url   auth: null,
npm verb parsed url   host: null,
npm verb parsed url   port: null,
npm verb parsed url   hostname: null,
npm verb parsed url   hash: null,
npm verb parsed url   search: null,
npm verb parsed url   query: null,
npm verb parsed url   pathname: 'nan@~1.2.0',
npm verb parsed url   path: 'nan@~1.2.0',
npm verb parsed url   href: 'nan@~1.2.0' }
npm verb cache add name="nan" spec="~1.2.0" args=["nan","~1.2.0"]
npm verb parsed url { protocol: null,
npm verb parsed url   slashes: null,
npm verb parsed url   auth: null,
npm verb parsed url   host: null,
npm verb parsed url   port: null,
npm verb parsed url   hostname: null,
npm verb parsed url   hash: null,
npm verb parsed url   search: null,
npm verb parsed url   query: null,
npm verb parsed url   pathname: '~1.2.0',
npm verb parsed url   path: '~1.2.0',
npm verb parsed url   href: '~1.2.0' }
npm verb addNamed [ 'nan', '~1.2.0' ]
npm verb addNamed [ null, '>=1.2.0-0 <1.3.0-0' ]
npm verb lock nan@~1.2.0 C:\Users\Francis\AppData\Roaming\npm-cache\6bb36ab7-nan-1-2-0.lock
npm verb request where is /nan
npm verb request registry https://registry.npmjs.org/
npm verb url raw /nan
npm verb url resolving [ 'https://registry.npmjs.org/', './nan' ]
npm verb url resolved https://registry.npmjs.org/nan
npm verb request where is https://registry.npmjs.org/nan
npm info trying registry request attempt 1 at 22:28:06
npm verb etag "2708DUO6NXF17XBKNCFQPD9W0"
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm verb etag https://registry.npmjs.org/nan from cache
npm verb addNamed [ 'nan', '1.2.0' ]
npm verb addNamed [ '1.2.0', '1.2.0' ]
npm verb lock nan@1.2.0 C:\Users\Francis\AppData\Roaming\npm-cache\859d0f28-nan-1-2-0.lock
npm info install nan@1.2.0 into C:\Users\Francis\Developer\fb.com\node_modules\canvas
npm info installOne nan@1.2.0
npm verb node_modules\canvas\node_modules\nan unbuild
npm verb tar unpack C:\Users\Francis\AppData\Roaming\npm-cache\nan\1.2.0\package.tgz
npm verb lock tar://C:\Users\Francis\Developer\fb.com\node_modules\canvas\node_modules\nan C:\Users\Francis\AppData\Roaming\npm-cache\700c5b6d--modules-canvas-node-modules-nan.lock
npm verb lock tar://C:\Users\Francis\AppData\Roaming\npm-cache\nan\1.2.0\package.tgz C:\Users\Francis\AppData\Roaming\npm-cache\4fc532e0--npm-cache-nan-1-2-0-package-tgz.lock
npm info preinstall nan@1.2.0
npm verb readDependencies using package.json deps
npm verb readDependencies using package.json deps
npm verb about to build C:\Users\Francis\Developer\fb.com\node_modules\canvas\node_modules\nan
npm info build C:\Users\Francis\Developer\fb.com\node_modules\canvas\node_modules\nan
npm verb linkStuff [ false,
npm verb linkStuff   false,
npm verb linkStuff   false,
npm verb linkStuff   'C:\\Users\\Francis\\Developer\\fb.com\\node_modules\\canvas\\node_modules' ]
npm info linkStuff nan@1.2.0
npm verb linkBins nan@1.2.0
npm verb linkMans nan@1.2.0
npm verb rebuildBundles nan@1.2.0
npm info install nan@1.2.0
npm info postinstall nan@1.2.0
npm verb about to build C:\Users\Francis\Developer\fb.com\node_modules\canvas
npm info build C:\Users\Francis\Developer\fb.com\node_modules\canvas
npm verb linkStuff [ false,
npm verb linkStuff   false,
npm verb linkStuff   false,
npm verb linkStuff   'C:\\Users\\Francis\\Developer\\fb.com\\node_modules' ]
npm info linkStuff canvas@1.1.6
npm verb linkBins canvas@1.1.6
npm verb linkMans canvas@1.1.6
npm verb rebuildBundles canvas@1.1.6
npm verb rebuildBundles [ 'nan' ]
npm info install canvas@1.1.6

> canvas@1.1.6 install C:\Users\Francis\Developer\fb.com\node_modules\canvas
> node-gyp rebuild


C:\Users\Francis\Developer\fb.com\node_modules\canvas>node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp info it worked if it ends with ok
gyp verb cli [ 'node',
gyp verb cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@1.0.1
gyp info using node@0.10.31 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/path/to/executable/python2.7" in the PATH
gyp verb `which` succeeded /path/to/executable/python2.7 /path/to/executable/python2.7
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:1001:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:792:34)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Francis\Developer\fb.com\node_modules\canvas
gyp ERR! node -v v0.10.31
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm verb unsafe-perm in lifecycle true
npm info canvas@1.1.6 Failed to exec install script
npm verb node_modules\canvas unbuild
npm info preuninstall canvas@1.1.6
npm info uninstall canvas@1.1.6
npm verb true,C:\Users\Francis\Developer\fb.com\node_modules,C:\Users\Francis\Developer\fb.com\node_modules unbuild canvas@1.1.6
npm info postuninstall canvas@1.1.6
npm ERR! canvas@1.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.1.6 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "canvas" "--msvs_version=2012" "-verbose"
npm ERR! cwd C:\Users\Francis\Developer\fb.com\node_modules
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm verb exit [ 1, true ]
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Francis\Developer\fb.com\node_modules\npm-debug.log
npm ERR! not ok code 0
```

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
