### ISSUE TITLE
Installing node-canvas in ubuntu using dokku

### ISSUE THREAD

**Issue by figalex** [Automattic/node-canvas#483]
I'm having problems trying to deploy my app using dokku. When npm tries to install node-canvas it throws this error:

```
In file included from ../src/CanvasPattern.cc:9:0:
       ../src/Image.h:19:21: fatal error: gif_lib.h: No such file or directory
       compilation terminated.
       make: *** [Release/obj.target/canvas/src/CanvasPattern.o] Error 1
       make: Leaving directory `/build/app/node_modules/canvas/build'
       gyp ERR! build error
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/build/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
       gyp ERR! System Linux 3.13.0-32-generic
       gyp ERR! command "node" "/build/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /build/app/node_modules/canvas
       gyp ERR! node -v v0.10.33
       gyp ERR! node-gyp -v v1.0.1
       gyp ERR! not ok
```

I followed the steps on the wiki for installing canvas dependencies on Ubuntu and even try again:
`sudo apt-get install libgif-dev` but still doesn't find the gif_lib.h . Has anyone deployed an app using node-canvas on dokku ?

**Comment by antongorodezkiy** [comment]
Thanks @figalex `sudo apt-get install libgif-dev` solved issue for me
