### ISSUE TITLE
doesn't install on OSX 10.9.5 and node 0.10.35

### ISSUE THREAD

**Issue by mgenev** [Automattic/node-canvas#503]
npm install canvas gives the following error:

```
server|master⚡ ⇒ npm install canvas
\
> canvas@1.1.6 install /Users/martin.genev/Projects/how-to/server/node_modules/canvas
> node-gyp rebuild

./util/has_cairo_freetype.sh: line 4: pkg-config: command not found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/martin.genev/.nvm/v0.10.35/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/Users/martin.genev/.nvm/v0.10.35/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/martin.genev/Projects/how-to/server/node_modules/canvas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! canvas@1.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.1.6 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild 
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "/Users/martin.genev/.nvm/v0.10.35/bin/node" "/Users/martin.genev/.nvm/v0.10.35/bin/npm" "install" "canvas"
npm ERR! cwd /Users/martin.genev/Projects/how-to/server
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

other packages using "node-gyp rebuild" work well

**Comment by mltucker** [comment]
Did you read the [installation guide](https://github.com/Automattic/node-canvas/wiki/installation---osx)?  You need to install pkg-config.

**Comment by mgenev** [comment]
Sorry, no it was a sub-dependency for something so I hadn't come across this. Makes sense now.

**Comment by mltucker** [comment]
Great :)
