### ISSUE TITLE
Install failed in Window

### ISSUE THREAD

**Issue by kinglion** [Automattic/node-canvas#510]
When I use "node-gyp configure build",I got the error message like this~How do I fix it?

```javascript
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:1001:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:792:
34)
```

**Comment by froatsnook** [comment]
With google I found a similar issue [here](https://github.com/TooTallNate/node-gyp/issues/277).  Try this:

```
fredpantuzza commented on Jul 12, 2013
I was getting the same problem. Solved defining the env variables:

PYTHONPATH=C:\Pyhon
PYTHON=%PYTHONPATH%\python.exe

Worked like charm
```

**Comment by kinglion** [comment]
tks.Finally I found my python version doesn't match gyp
```javascript
gyp ERR! configure error
gyp ERR! stack Error: Python executable "d:\Python34\python.exe" is v3.4.2, whic
h is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & <
 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\np
m\node_modules\node-gyp\lib\configure.js:108:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:97:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:646:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:756:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:969:11)
gyp ERR! stack     at Socket.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:465:12)
```
