### ISSUE TITLE
io.js 1.2 Error

### ISSUE THREAD

**Issue by willin** [Automattic/node-canvas#523]
```
Error: Module did not self-register.
   at Error (native)
   at Module.load (module.js:341:32)
   at Function.Module._load (module.js:296:12)
   at Module.require (module.js:351:17)
   at require (module.js:370:17)
   at Object.<anonymous> (/Users/willin/Documents/wulian/node/open-api/node_modules/canvas/lib/bindings.js:2:18)
   at Module._compile (module.js:446:26)
   at Object.Module._extensions..js (module.js:464:10)
   at Module.load (module.js:341:32)
   at Function.Module._load (module.js:296:12)
```

**Comment by kangax** [comment]
Should be fixed with https://github.com/Automattic/node-canvas/pull/522
