### ISSUE TITLE
No package 'pangocairo' found

### ISSUE THREAD

**Issue by equiet** [Automattic/node-canvas#599]
Hi,

I'm running an application on Heroku and my builds suddenly stopped working. Here's the relevant output:

```
remote:        Resolving node version (latest stable) via semver.io...
remote:        Downloading and installing node 0.12.7...
remote:        Using default npm version: 2.11.3
remote:
remote: -----> Restoring cache
remote:        Skipping cache (new runtime signature)
remote:
remote: -----> Building dependencies
remote:        Pruning any extraneous modules
remote:        Installing node modules (package.json)
remote:
remote:        > canvas@1.2.4 install /tmp/build_8e7d47039f66a696c657cbb579c67ad1/node_modules/canvas
remote:        > node-gyp rebuild
remote:
remote:        Package pangocairo was not found in the pkg-config search path.
remote:        Perhaps you should add the directory containing `pangocairo.pc'
remote:        to the PKG_CONFIG_PATH environment variable
remote:        No package 'pangocairo' found
remote:        gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1. while trying to load binding.gyp
remote:        gyp ERR! configure error
remote:        gyp ERR! stack Error: `gyp` failed with exit code: 1
remote:        gyp ERR! stack     at ChildProcess.onCpExit (/tmp/build_8e7d47039f66a696c657cbb579c67ad1/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
remote:        gyp ERR! System Linux 3.13.0-57-generic
remote:        gyp ERR! command "node" "/tmp/build_8e7d47039f66a696c657cbb579c67ad1/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_8e7d47039f66a696c657cbb579c67ad1/node_modules/canvas
remote:        gyp ERR! node -v v0.12.7
remote:        gyp ERR! node-gyp -v v2.0.1
remote:        gyp ERR! not ok
remote:        npm ERR! Linux 3.13.0-57-generic
remote:        npm ERR! argv "/tmp/build_8e7d47039f66a696c657cbb579c67ad1/.heroku/node/bin/node" "/tmp/build_8e7d47039f66a696c657cbb579c67ad1/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_8e7d47039f66a696c657cbb579c67ad1/.npmrc"
remote:        npm ERR! node v0.12.7
remote:        npm ERR! npm  v2.11.3
remote:        npm ERR! code ELIFECYCLE
remote:
remote:        npm ERR! canvas@1.2.4 install: `node-gyp rebuild`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the canvas@1.2.4 install script 'node-gyp rebuild'.
remote:        npm ERR! This is most likely a problem with the canvas package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     node-gyp rebuild
remote:        npm ERR! You can get their info via:
remote:        npm ERR!     npm owner ls canvas
remote:        npm ERR! There is likely additional logging output above.
remote:
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_8e7d47039f66a696c657cbb579c67ad1/npm-debug.log
```

I tried both `1.2.3` and `1.2.4` today and neither worked, so it might not be related to the latest update. My last deploy was on July 22 and that worked without any issues, using `1.2.3` I believe.

Thanks.

**Comment by LinusU** [comment]
Version 1.2.4 will never work because of #596 so try with `1.2.3` 'til somebody can release `1.2.5`.

I think that you problem is that it thinks that you have pangocairo installed when you actually don't (or maybe you just have the binaries...). What does `util/has_lib.sh pangocairo` output?

**Comment by equiet** [comment]
I see. I forced `1.2.3`, but still doesn't work (the output is the same). `util/has_lib.sh pangocairo` returns `true`

**Comment by LinusU** [comment]
And I'm guessing that `pkg-config --cflags pangocairo` gives an error?

**Comment by equiet** [comment]
Correct. It's:
```
Package pangocairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `pangocairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pangocairo' found
```

**Comment by LinusU** [comment]
Could you try out the instructions in #600 and see if it fixes the problem for you please :)

**Comment by automata** [comment]
Getting the same here:

```
remote:        > canvas@1.3.5 install /tmp/build_a76fe56dab9b1330d005287dedfc74c2/node_modules/face-detect/node_modules/canvas
remote:        > node-gyp rebuild
remote:        
remote:        Package pangocairo was not found in the pkg-config search path.
remote:        Perhaps you should add the directory containing `pangocairo.pc'
remote:        to the PKG_CONFIG_PATH environment variable
remote:        No package 'pangocairo' found
remote:        gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1. while trying to load binding.gyp
remote:        gyp ERR! configure error
remote:        gyp ERR! stack Error: `gyp` failed with exit code: 1
remote:        gyp ERR! stack     at ChildProcess.onCpExit (/tmp/build_a76fe56dab9b1330d005287dedfc74c2/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1075:12)
remote:        gyp ERR! System Linux 3.13.0-71-generic
remote:        gyp ERR! command "node" "/tmp/build_a76fe56dab9b1330d005287dedfc74c2/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_a76fe56dab9b1330d005287dedfc74c2/node_modules/face-detect/node_modules/canvas
remote:        gyp ERR! node -v v0.12.9
remote:        gyp ERR! node-gyp -v v1.0.3
remote:        gyp ERR! not ok
remote:        npm ERR! Linux 3.13.0-71-generic
remote:        npm ERR! argv "node" "/tmp/build_a76fe56dab9b1330d005287dedfc74c2/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_a76fe56dab9b1330d005287dedfc74c2/.npmrc"
remote:        npm ERR! node v0.12.9
remote:        npm ERR! npm  v2.10.1
remote:        npm ERR! code ELIFECYCLE
remote:        
remote:        npm ERR! canvas@1.3.5 install: `node-gyp rebuild`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the canvas@1.3.5 install script 'node-gyp rebuild'.
remote:        npm ERR! This is most likely a problem with the canvas package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     node-gyp rebuild
remote:        npm ERR! You can get their info via:
remote:        npm ERR!     npm owner ls canvas
remote:        npm ERR! There is likely additional logging output above.
remote:        
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_a76fe56dab9b1330d005287dedfc74c2/npm-debug.log
remote: 
remote: -----> Build failed
```

**Comment by tomasdev** [comment]
I'm getting the same but ```[ec2-user@ip-172-31-8-195 node-canvas]$ util/has_lib.sh pangocairo
Unknown library: pangocairo```

**Comment by solumos** [comment]
@tomasdev you updated the installation instructions for the Amazon Linux AMI (not Fedora)

None of these packages are available via the Amazon AMIs, which is the part of the wiki you updated.
```
cairomm-devel
pangomm
pangomm-devel
```
The Fedora instructions are here - https://github.com/Automattic/node-canvas/wiki/Installation---Fedora

**Comment by tomasdev** [comment]
@solumos I was talking about AMI indeed. I am using the official Linux AMI, not Fedora. More specifically, talking about the downloadable Amazon Linux AMI that is used as a base for local development of Lambda functions (a.k.a building node-canvas to deploy them for use in Lambda)

**Comment by wagenaartje** [comment]
Getting the same error with Travis CI testing.

**Comment by luxueyan** [comment]
node: v7.9.0
npm: 5.5.1 
os: macos 10.12.6
The same error too!

**Comment by matteo-harpoon** [comment]
If you're getting this error on Mac OSX ensure to run `$ brew install cairo` and `$ brew install pango`

**Comment by tracyscott** [comment]
Not sure if it is something with my setup or the brew pango package, but brew install pango didn't create the pangocairo pkg-config file /opt/local/lib/pkgconfig/pangocairo.pc  .  I ran brew uninstall pango and then port install pango

**Comment by zbjornson** [comment]
Newer versions just work on the vanilla heroku-16 stack thanks to prebuilds, without needing to deal with pkg-config.

**Comment by jsolly** [comment]
> If you're getting this error on Mac OSX ensure to run `$ brew install cairo` and `$ brew install pango`

Worked for me in 2022!

**Comment by meysampg** [comment]
On Ubuntu: `sudo apt install libsdl-pango-dev`

**Comment by Anthonypugliese1709** [comment]
> If you're getting this error on Mac OSX ensure to run $ brew install cairo and $ brew install pango

Also worked for me in 2022 ! Thanks !

**Comment by wy1027** [comment]
> If you're getting this error on Mac OSX ensure to run `$ brew install cairo` and `$ brew install pango`

Also worked for me in 2023! Thanks

**Comment by OsKaR31415** [comment]
For me, the problem was that I had 2 installations of `pkg-config`, and that the homebrew one wouldn't be the one used by default. Changing the `$PATH` in my `.zshrc` did the trick (after hours searching).

The thing is, if you just use the right `pkg-config` instance to setup the required packages, the other app you are installing will still use the wrong version of `pkg-config`. So really, you have to make sure `/opt/homebrew/bin` is the first on your path (or at least before the installation location of the default `pkg-config`).

**Comment by AnilAntony3134** [comment]
> 

This worked for me

**Comment by kamkrish** [comment]
> On Ubuntu: `sudo apt install libsdl-pango-dev`

worked for issues regarding Ubuntu 23

**Comment by xxhls** [comment]
> If you're getting this error on Mac OSX ensure to run `$ brew install cairo` and `$ brew install pango`

Worked for me, thank you!!!

**Comment by skobaken7** [comment]
`sudo apt install libpango1.0-dev` also worked on Ubuntu.
