### ISSUE TITLE
can't install canvas on centos 6.5

### ISSUE THREAD

**Issue by caomu** [Automattic/node-canvas#601]
OS info:CentOS release 6.5 (Final)
Kernel \r on an \m
Linux version 2.6.32-431.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Fri Nov 22 03:15:09 UTC 2013

when i install canvas,system says:

```text
.........................
.........................
../src/Canvas.cc:65: error: expected constructor, destructor, or type conversion before ‘(’ token
../src/Canvas.cc:85: error: expected constructor, destructor, or type conversion before ‘(’ token
../src/Canvas.cc:95: error: expected constructor, destructor, or type conversion before ‘(’ token
../src/Canvas.cc:105: error: expected constructor, destructor, or type conversion before ‘(’ token
../src/PNG.h:215: warning: ‘cairo_status_t canvas_write_to_png_stream(cairo_surface_t*, cairo_status_t (*)(void*, const unsigned char*, unsigned int), void*)’ defined but not used
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
make: Leaving directory `/home/rd/caomu/node_modules/canvas/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/rd/node-v0.12.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-431.el6.x86_64
gyp ERR! command "node" "/home/rd/node-v0.12.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rd/caomu/node_modules/canvas
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/home/rd/node-v0.12.2-linux-x64/bin/node" "/home/rd/node-v0.12.2-linux-x64/bin/npm" "install" "canvas"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.2.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rd/caomu/npm-debug.log
```

pls,give me some help.thanks a lot.

**Comment by LinusU** [comment]
I believe that this should be fixed with version `1.2.5`, could you please try with that?

**Comment by caomu** [comment]
yes! it is fixed,thanks a lot

**Comment by LinusU** [comment]
No problem, great :+1:
