### ISSUE TITLE
font loading issue in latest version

### ISSUE THREAD

**Issue by diwu1989** [Automattic/node-canvas#618]
I see this when deploying 1.2.x to heroku with the proper buildpack
```
2015-08-28T19:01:32.628424+00:00 app[web.1]: /app/node_modules/canvas/lib/canvas.js:80
2015-08-28T19:01:32.628428+00:00 app[web.1]:     var face = new FontFace(path, idx || 0);
2015-08-28T19:01:32.628430+00:00 app[web.1]:                ^
2015-08-28T19:01:32.628432+00:00 app[web.1]: Error: Could not load font in FontConfig
2015-08-28T19:01:32.628433+00:00 app[web.1]:     at Error (native)
2015-08-28T19:01:32.628437+00:00 app[web.1]:     at Font.addFace (/app/node_modules/canvas/lib/canvas.js:80:16)
2015-08-28T19:01:32.628438+00:00 app[web.1]:     at new Font (/app/node_modules/canvas/lib/canvas.js:73:10)
2015-08-28T19:01:32.628440+00:00 app[web.1]:     at Object.<anonymous> (/app/routes/index.js:13:12)
2015-08-28T19:01:32.628441+00:00 app[web.1]:     at Module._compile (module.js:460:26)
2015-08-28T19:01:32.628443+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:478:10)
2015-08-28T19:01:32.628444+00:00 app[web.1]:     at Module.load (module.js:355:32)
2015-08-28T19:01:32.628445+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2015-08-28T19:01:32.628447+00:00 app[web.1]:     at Function.cls_wrapMethod (/app/node_modules/newrelic/lib/shimmer.js:230:38)
2015-08-28T19:01:32.628449+00:00 app[web.1]:     at Module.require (module.js:365:17)
2015-08-28T19:01:32.635535+00:00 app[web.1]: /app/node_modules/canvas/lib/canvas.js:80
2015-08-28T19:01:32.635542+00:00 app[web.1]:     var face = new FontFace(path, idx || 0);
```
switching back to 1.1.x works

**Comment by dotnil** [comment]
I've got this issue with 1.3.5 on RHEL too. With pango disabled as the way detailed in #628 , this issue no longer persist. So +1 from me for disabling pango.
