### ISSUE TITLE
node-gyp rebuild fails Windows 8.1 node v0.12.0 node-gyp v3.0.2

### ISSUE THREAD

**Issue by Alexnder** [Automattic/node-canvas#627]
node-gyp rebuild --msvs_version=2013 --python=python27 > log.txt
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.2
gyp info using node@0.12.0 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2013',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Projects\\node\\testProject\\node_modules\\node-canvas\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\user\\.node-gyp\\0.12.0\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\user\\.node-gyp\\0.12.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Projects\\node\\testProject\\node_modules\\node-canvas',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Projects\\node\\testProject\\node_modules\\node-canvas\\build', gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\user\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--msvs_version=2013" "--python=python27"
gyp ERR! cwd D:\Projects\node\testProject\node_modules\node-canvas
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v3.0.2
gyp ERR! not ok
```
Common errors:
node-canvas\src\Image.h(34): error C2143: syntax error : missing ';' before '*' (..\src\CanvasPattern.cc)
..\src\ImageData.cc(18): error C3861: 'NanScope': identifier not found
..\src\ImageData.cc(21): error C2065: 'NanNew' : undeclared identifier
..\src\ImageData.cc(21): error C2275: 'v8::FunctionTemplate' : illegal use of this type as an expression

all errors link: https://gist.github.com/Alexnder/cb534917372c95d7ee4e

**Comment by tonbz** [comment]
Please check that you use nan  module version 1.8.0 or 1.9.0 (canvas not support nan version 2.0)

**Comment by Alexnder** [comment]
I fully reinstall nodejs (At first it was 4.0.0 with node-gyp 3.0.2)
Get GTK from https://github.com/hexchat/gtk-win32/blob/master/README.md
Copy file `C:\GTK\lib\libpng16.lib` to `C:\GTK\lib\libpng.lib`
And install via `npm install canvas`
If help to get it to my word pc. If I get it to my home PC I close the issue.
