### ISSUE TITLE
npm install failed in OSX 10.10.5 Yosemite

### ISSUE THREAD

**Issue by ChenLiZhan** [Automattic/node-canvas#634]
* node version: v0.12.4
* OSX: 10.10.5

While I ran ``` npm install canvas```, I got following error message: 
````
 canvas@1.2.9 install /Users/chenlizhan/Desktop/Lee/Programming/dcard/Dcard/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/canvas-postbuild.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/chenlizhan/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Users/chenlizhan/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/chenlizhan/Desktop/Lee/Programming/dcard/Dcard/node_modules/canvas
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/chenlizhan/.nvm/versions/node/v0.12.4/bin/node" "/Users/chenlizhan/.nvm/versions/node/v0.12.4/bin/npm" "i"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.2.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.2.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chenlizhan/Desktop/Lee/Programming/dcard/Dcard/npm-debug.log
````

I don't know if it's related to gcc library problem. Can anyone help me figure out?

Many thanks!😀

**Comment by jrmce** [comment]
This isn't a node-canvas issue, but updating Xcode to 7 fixed this for me. I believe if you took the latest command line tools update without updating to Xcode 7, you'll get this error.

**Comment by ChenLiZhan** [comment]
I resolved problem by updating Xcode.
Thank you😀
