### ISSUE TITLE
Server tests don't work if jpeg is not available

### ISSUE THREAD

**Issue by zbjornson** [Automattic/node-canvas#647]
My mistake...

```
...\node-canvas\lib\jpegstream.js:43
    canvas[method](options.bufsize, options.quality, options.progressive, function(err, chunk){
                  ^

TypeError: canvas[method] is not a function
    at ...\node-canvas\lib\jpegstream.js:43:19
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

**Comment by LinusU** [comment]
Oops, we could probably check runtime if the build has jpeg support, and only then turn on the serving of jpegs?
