### ISSUE TITLE
`nod-gyp rebuild` Error Installing on Heroku

### ISSUE THREAD

**Issue by omidahourai** [Automattic/node-canvas#699]
Can't seem to build successfully... This is actually caused when it tries to install the dependency "fabric": "^1.6.0-rc.1"

```
remote: -----> Using set buildpack heroku/nodejs
remote: -----> Node.js app detected
remote: 
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote: 
remote: -----> Installing binaries
remote:        engines.node (package.json):  5.3.0
remote:        engines.npm (package.json):   3.3.12
remote:        
remote:        Downloading and installing node 5.3.0...

remote:        npm 3.3.12 already installed with node
remote: 
remote: -----> Restoring cache
remote:        Skipping cache restore (new runtime signature)
remote: 
remote: -----> Building dependencies
remote:        Pruning any extraneous modules
remote:        Installing node modules (package.json)


remote:        
remote:        > contextify@0.1.15 install /tmp/build_0ea4504f013e9959fff9eac3c707bc28/node_modules/contextify
remote:        > node-gyp rebuild
remote:        
remote:        make: Entering directory `/tmp/build_0ea4504f013e9959fff9eac3c707bc28/node_modules/contextify/build'
remote:        CXX(target) Release/obj.target/contextify/src/contextify.o
remote:        SOLINK_MODULE(target) Release/obj.target/contextify.node
remote:        COPY Release/contextify.node
remote:        make: Leaving directory `/tmp/build_0ea4504f013e9959fff9eac3c707bc28/node_modules/contextify/build'
remote:        
remote:        > canvas@1.1.6 install /tmp/build_0ea4504f013e9959fff9eac3c707bc28/node_modules/canvas
remote:        > node-gyp rebuild
remote:        
remote:        make: Entering directory `/tmp/build_0ea4504f013e9959fff9eac3c707bc28/node_modules/canvas/build'
remote:        SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
remote:        COPY Release/canvas-postbuild.node
remote:        CXX(target) Release/obj.target/canvas/src/Canvas.o
remote:        In file included from ../src/Canvas.h:22:0,
remote:        from ../src/Canvas.cc:7:
remote:        ../../nan/nan.h: In function ‘v8::Local<v8::Signature> NanNew(v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
remote:        ../../nan/nan.h:342:78: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)’
remote:        return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
remote:        ^
remote:        ../../nan/nan.h:342:78: note: candidate is:
remote:        In file included from ../src/Canvas.h:11:0,
remote:        from ../src/Canvas.cc:7:
remote:        /app/.node-gyp/5.3.0/include/node/v8.h:4674:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
remote:        static Local<Signature> New(
remote:        ^
remote:        /app/.node-gyp/5.3.0/include/node/v8.h:4674:27: note:   candidate expects 2 arguments, 4 provided
remote:        In file included from ../src/Canvas.h:22:0,
remote:        from ../src/Canvas.cc:7:
remote:        ../../nan/nan.h: At global scope:
remote:        ../../nan/nan.h:424:3: error: redefinition of ‘v8::Local<T> NanNew(P) [with T = v8::StringObject; P = v8::Local<v8::String>]’
remote:        NanNew<v8::StringObject, v8::Handle<v8::String> >(
remote:        ^
remote:        ../../nan/nan.h:417:3: error: ‘v8::Local<T> NanNew(P) [with T = v8::StringObject; P = v8::Local<v8::String>]’ previously declared here
remote:        NanNew<v8::StringObject, v8::Local<v8::String> >(
remote:        ^
remote:        ../../nan/nan.h:442:36: error: redefinition of ‘template<class T> v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>, v8::RegExp::Flags)’
remote:        NAN_INLINE v8::Local<v8::RegExp> NanNew(
remote:        ^
remote:        ../../nan/nan.h:436:36: error: ‘template<class T> v8::Local<v8::RegExp> NanNew(v8::Handle<v8::String>, v8::RegExp::Flags)’ previously declared here
remote:        NAN_INLINE v8::Local<v8::RegExp> NanNew(
remote:        ^
remote:        ../../nan/nan.h:454:36: error: redefinition of ‘template<class T, class P> v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>, v8::RegExp::Flags)’
remote:        NAN_INLINE v8::Local<v8::RegExp> NanNew(
remote:        ^
remote:        ../../nan/nan.h:448:36: error: ‘template<class T, class P> v8::Local<v8::RegExp> NanNew(v8::Handle<v8::String>, v8::RegExp::Flags)’ previously declared here
remote:        NAN_INLINE v8::Local<v8::RegExp> NanNew(
remote:        ^
remote:        ../../nan/nan.h:623:19: error: ‘NanNew’ declared as an ‘inline’ variable
remote:        v8::String::ExternalAsciiStringResource *resource) {
remote:        ^
remote:        ../../nan/nan.h:623:19: warning: ‘always_inline’ attribute ignored [-Wattributes]
remote:        ../../nan/nan.h:623:19: error: ‘v8::Local<v8::String> NanNew’ redeclared as different kind of symbol
remote:        ../../nan/nan.h:617:36: error: previous declaration of ‘v8::Local<v8::String> NanNew(v8::String::ExternalStringResource*)’
remote:        NAN_INLINE v8::Local<v8::String> NanNew(
remote:        ^
remote:        ../../nan/nan.h:623:7: error: ‘ExternalAsciiStringResource’ is not a member of ‘v8::String’
remote:        v8::String::ExternalAsciiStringResource *resource) {
remote:        ^
remote:        ../../nan/nan.h:623:48: error: ‘resource’ was not declared in this scope
remote:        v8::String::ExternalAsciiStringResource *resource) {
remote:        ^
remote:        ../../nan/nan.h:637:27: error: redefinition of ‘template<class T> v8::Local<T> _NanEscapeScopeHelper(v8::Local<T>)’
remote:        NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Local<T> val) {
remote:        ^
remote:        ../../nan/nan.h:632:27: error: ‘template<class T> v8::Local<T> _NanEscapeScopeHelper(v8::Handle<T>)’ previously declared here
remote:        NAN_INLINE v8::Local<T> _NanEscapeScopeHelper(v8::Handle<T> val) {
remote:        ^
remote:        ../../nan/nan.h:889:13: error: ‘node::smalloc’ has not been declared
remote:        , node::smalloc::FreeCallback callback
remote:        ^
remote:        ../../nan/nan.h:889:35: error: expected ‘,’ or ‘...’ before ‘callback’
remote:        , node::smalloc::FreeCallback callback
remote:        ^
remote:        ../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
remote:        ../../nan/nan.h:893:50: error: ‘callback’ was not declared in this scope
remote:        v8::Isolate::GetCurrent(), data, length, callback, hint);
remote:        ^
remote:        ../../nan/nan.h:893:60: error: ‘hint’ was not declared in this scope
remote:        v8::Isolate::GetCurrent(), data, length, callback, hint);
remote:        ^
remote:        ../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
remote:        ../../nan/nan.h:900:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
remote:        return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
remote:        ^
remote:        ../../nan/nan.h:900:67: note: candidates are:
remote:        In file included from ../../nan/nan.h:179:0,
remote:        from ../src/Canvas.h:22,
remote:        from ../src/Canvas.cc:7:
remote:        /app/.node-gyp/5.3.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
remote:        NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
remote:        ^
remote:        /app/.node-gyp/5.3.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
remote:        /app/.node-gyp/5.3.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
remote:        NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
remote:        ^
remote:        /app/.node-gyp/5.3.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
remote:        In file included from ../src/Canvas.h:22:0,
remote:        from ../src/Canvas.cc:7:
remote:        ../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
remote:        ../../nan/nan.h:904:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
remote:        return node::Buffer::New(v8::Isolate::GetCurrent(), size);
remote:        ^
remote:        ../../nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
remote:        ../../nan/nan.h:911:12: error: ‘Use’ is not a member of ‘node::Buffer’
remote:        return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
remote:        ^
remote:        ../../nan/nan.h: In function ‘bool _NanGetExternalParts(v8::Handle<v8::Value>, const char**, size_t*)’:
remote:        ../../nan/nan.h:1993:12: error: ‘class v8::String’ has no member named ‘IsExternalAscii’
remote:        if (str->IsExternalAscii()) {
remote:        ^
remote:        ../../nan/nan.h:1994:11: error: ‘ExternalAsciiStringResource’ in ‘class v8::String’ does not name a type
remote:        const v8::String::ExternalAsciiStringResource* ext;
remote:        ^
remote:        ../../nan/nan.h:1995:5: error: ‘ext’ was not declared in this scope
remote:        ext = str->GetExternalAsciiStringResource();
remote:        ^
remote:        ../../nan/nan.h:1995:16: error: ‘class v8::String’ has no member named ‘GetExternalAsciiStringResource’
remote:        ext = str->GetExternalAsciiStringResource();
remote:        ^
remote:        ../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
remote:        ../../nan/nan.h:901:3: warning: control reaches end of non-void function [-Wreturn-type]
remote:        }
remote:        ^
remote:        make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
remote:        make: Leaving directory `/tmp/build_0ea4504f013e9959fff9eac3c707bc28/node_modules/canvas/build'
remote:        gyp ERR! build error
remote:        gyp ERR! stack Error: `make` failed with exit code: 2
remote:        gyp ERR! stack     at ChildProcess.onExit (/tmp/build_0ea4504f013e9959fff9eac3c707bc28/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
remote:        gyp ERR! stack     at emitTwo (events.js:87:13)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
remote:        gyp ERR! System Linux 3.13.0-71-generic
remote:        gyp ERR! command "/tmp/build_0ea4504f013e9959fff9eac3c707bc28/.heroku/node/bin/node" "/tmp/build_0ea4504f013e9959fff9eac3c707bc28/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_0ea4504f013e9959fff9eac3c707bc28/node_modules/canvas
remote:        gyp ERR! node -v v5.3.0
remote:        gyp ERR! node-gyp -v v3.0.3
remote:        gyp ERR! not ok
remote:        arka-customizer@1.0.0 /tmp/build_0ea4504f013e9959fff9eac3c707bc28
remote:        ├── jquery@2.1.4
remote:        ├── jsdom@1.1.0  extraneous
remote:        ├── three@0.73.0
remote:        ├── tween.js@16.3.1
remote:        └── xmldom@0.1.19  extraneous
remote:        
remote:        npm ERR! Linux 3.13.0-71-generic
remote:        npm ERR! argv "/tmp/build_0ea4504f013e9959fff9eac3c707bc28/.heroku/node/bin/node" "/tmp/build_0ea4504f013e9959fff9eac3c707bc28/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_0ea4504f013e9959fff9eac3c707bc28/.npmrc"
remote:        npm ERR! node v5.3.0
remote:        npm ERR! npm  v3.3.12
remote:        npm ERR! code ELIFECYCLE
remote:        
remote:        npm ERR! canvas@1.1.6 install: `node-gyp rebuild`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the canvas@1.1.6 install script 'node-gyp rebuild'.
remote:        npm ERR! Make sure you have the latest version of node.js and npm installed.
remote:        npm ERR! If you do, this is most likely a problem with the canvas package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     node-gyp rebuild
remote:        npm ERR! You can get their info via:
remote:        npm ERR!     npm owner ls canvas
remote:        npm ERR! There is likely additional logging output above.
remote:        
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_0ea4504f013e9959fff9eac3c707bc28/npm-debug.log
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:        
remote:        Love,
remote:        Heroku
```

Any ideas?

**Comment by dogagenc** [comment]
Same error here.

I can't even install it locally.

**Comment by LinusU** [comment]
That is an quite old version of canvas, could you please try with the latest, currently 1.3.10?

**Comment by adamlacoste** [comment]
I'm not using Heroku, but I get a very similar error when installing 1.3.10

```
$ npm install canvas

> canvas@1.3.10 install /Users/adam/Development/automation/node_modules/canvas
> node-gyp rebuild

./util/has_lib.sh: line 30: pkg-config: command not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/adam/Development/automation/node_modules/canvas
gyp ERR! node -v v5.1.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN core-automation@0.1.0 No license field.
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! node v5.1.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.3.10 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adam/Development/automation/npm-debug.log
```

**Comment by LinusU** [comment]
@adamlacoste That is another issue, you don't have `pkg-config` installed. Please follow the installation instructions in the readme. https://github.com/Automattic/node-canvas/blob/master/Readme.md#installation

**Comment by adamlacoste** [comment]
Sorry I missed that, this package was a dependency of another I'm trying to use so I didn't read this one's install instructions.  I do question what the point is of having an NPM package if it can't install all the dependencies though.  Thanks for your help.

**Comment by LinusU** [comment]
I understand your frustation, I would love to have prebuilt statically linked binaries...

**Comment by zbjornson** [comment]
I just successfully installed canvas 2.0.0-alpha.12 and 1.6.11 on the vanilla heroku-16 stack. Both just worked thanks to prebuilds. If anyone has a need to make a from-source build work, I can look into it.

**Comment by JordanTreDaniel** [comment]
I am having the same problem in 2023 with node v20 and "canvas": "^2.11.2". Can't upgrade to the proper stack because of this. On my local mac, I fixed this problem by running: `brew install pkg-config cairo pango libpng jpeg giflib librsvg`
