### ISSUE TITLE
ld: library not found for -lgcc_s.10.5

### ISSUE THREAD

**Issue by ZeningQu** [Automattic/node-canvas#713]
I ran into an error when running 
`$ npm install canvas`

Here's my `PKG_CONFIG_PATH`
`$ echo $PKG_CONFIG_PATH`
`/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig`

I'm on `Yosemite 10.10.5` with `node -v = v4.1.1`

Here's the error message:
$ npm install canvas
\
> canvas@1.3.10 install /Users/zeningqu/Code/vega-lite/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/canvas-postbuild.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/zeningqu/.node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/Users/zeningqu/.node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/zeningqu/Code/vega-lite/node_modules/canvas
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/Users/zeningqu/.node/bin/npm" "install" "canvas"
npm ERR! node v4.1.1
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.3.10 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zeningqu/Code/vega-lite/bin/npm-debug.log

Finally, the debug.log file (I converted it to txt)
[npm-debug.txt](https://github.com/Automattic/node-canvas/files/124172/npm-debug.txt)

**Comment by ZeningQu** [comment]
This solved my problem:
```
cd /usr/local/lib
sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib
```
