### ISSUE TITLE
Possible to render three.js on serverside?

### ISSUE THREAD

**Issue by zettam** [Automattic/node-canvas#730]
I was planning to use node-canvas to render out three.js on server side, using the canvas renderer.
I didn't have any successful results so far.

Any help is appreciated.

**Comment by zbjornson** [comment]
three.js uses the "webgl" canvas context, which isn't supported.

**Comment by zettam** [comment]
there is a canvas renderer as well

**Comment by zettam** [comment]
http://threejs.org/docs/#Reference/Renderers/CanvasRenderer

**Comment by zbjornson** [comment]
Ah, didn't realize that, thanks for the link. Can you post the code you've tried, please?

**Comment by zettam** [comment]
I've added this section to the begginning of the three.js file (maybe it's not a right ting to modify the source but oh well, I couldn't come up with any other solutions)

```
var Canvas = require('canvas');

var self = self || {}; // File:src/Three.js

var canvasWidth = 1024;
var canvasHeight = 1024;

var window = {
	innerWidth: canvasWidth,
	innerHeight: canvasHeight
};

var document = {
	createElement: function(name) {
		if (name == "canvas") {
			return new Canvas(canvasWidth, canvasHeight);
		}
	}
};
```

now it doesn ot give me any errors when I do this in my app.js


```
var THREE = require("three");



var scene, camera, renderer;
var geometry, material, mesh;


init();

function init() {

	scene = new THREE.Scene();

	camera = new THREE.PerspectiveCamera(75, 1, 1, 10000);
	camera.position.z = 1000;

	geometry = new THREE.BoxGeometry(200, 200, 200);
	material = new THREE.MeshBasicMaterial({
		color: 0xff0000,
		wireframe: true
	});

	mesh = new THREE.Mesh(geometry, material);
	scene.add(mesh);

	renderer = new THREE.CanvasRenderer();
	renderer.setSize(200, 200);

	renderer.render(scene, camera);

	//document.body.appendChild(renderer.domElement);
}
```


however, this is not rendering anything as you may expect.
What do you think?

**Comment by zbjornson** [comment]
Started to work on your code, but turns out someone already made a node module wrapping three.js that is backed by canvas: https://github.com/nulltask/node-three.js (and http://stackoverflow.com/questions/19162510/how-do-i-render-three-js-in-node-js). Does that help?

Also came across some discussion here: https://github.com/mrdoob/three.js/issues/7085

**Comment by zettam** [comment]
I've came across these three links, they're mostly out of date (or there is another problem which does not let things work).

Maybe I'm doing some mistake.

**Comment by zettam** [comment]
https://www.npmjs.com/package/three.js also, fyi - this module is deprecated.

**Comment by zbjornson** [comment]
Sorry for the delay. The below seems to work, although CanvasRenderer lacks some WebGL features, which I think causes the geometry to render incorrectly (note that the plane below the cube intersects the cube).

Required three.js files are these -- [CanvasRenderer was moved out of core three.js](https://github.com/mrdoob/three.js/issues/5548) and it requires the projector file:
https://github.com/mrdoob/three.js/blob/master/build/three.js
https://github.com/mrdoob/three.js/blob/master/examples/js/renderers/CanvasRenderer.js
https://github.com/mrdoob/three.js/blob/master/examples/js/renderers/Projector.js

```javascript
// Assign this to global so that the subsequent modules can extend it:
global.THREE = require("./three.js");
require("./three-canvasrenderer.js");
require("./three-projector.js");

var fs = require("fs");
var Canvas = require("canvas");

var w = 200;
var h = 200;

var scene = new THREE.Scene();

var camera = new THREE.PerspectiveCamera(70, 1, 1, 10000);
camera.position.y = 150;
camera.position.z = 400;

var geometry = new THREE.BoxGeometry(200, 200, 200);
for ( var i = 0; i < geometry.faces.length; i += 2 ) {
    var hex = Math.random() * 0xffffff;
    geometry.faces[ i ].color.setHex( hex );
    geometry.faces[ i + 1 ].color.setHex( hex );
}

var material = new THREE.MeshBasicMaterial( { vertexColors: THREE.FaceColors, overdraw: 0.5 } );

cube = new THREE.Mesh(geometry, material);
cube.position.y = 150;
cube.rotation.y = 45;
scene.add(cube);

var geometry = new THREE.PlaneBufferGeometry( 200, 200 );
geometry.rotateX( - Math.PI / 2 );

var material = new THREE.MeshBasicMaterial( { color: 0xe0e0e0, overdraw: 0.5 } );

plane = new THREE.Mesh( geometry, material );
scene.add( plane );

var canvas = new Canvas(w, h);
canvas.style = {}; // dummy shim to prevent errors during render.setSize
var renderer = new THREE.CanvasRenderer({
    canvas: canvas
});

renderer.setClearColor(0xffffff, 0);
renderer.setSize(200, 200);

renderer.render(scene, camera);

var out = fs.createWriteStream("./test-out.png");
var canvasStream = canvas.pngStream();
canvasStream.on("data", function (chunk) { out.write(chunk); });
canvasStream.on("end", function () { console.log("done"); });
```

![test-out](https://cloud.githubusercontent.com/assets/469365/13731645/a0e7bfca-e92b-11e5-8d4a-062f6126a774.png)

**Comment by zettam** [comment]
Hm, there is already a three package
npm install three
would it be possible to make this work with it?

Thanks for the effort!

**Comment by zettam** [comment]
Error: Cannot find module './three-canvasrenderer.js'

I have all the files in the same directory with my app.js

**Comment by zettam** [comment]
Oh nevermind, looks like it worked, my bad, that I didn't replace the file names to match your script!

Thank you!

**Comment by zettam** [comment]
One final issue/question.
It's normally possible to load textures and render them via canvas renderer.
When I try to do the following:
`THREE.TextureLoader().load( 'gradient.png' )`
I get the following error:
`ReferenceError: document is not defined`

Since, earlier it was all about the "document is not defined" error (the reason I was defining document in my earlier post), and since you fixed it without making that definition anywhere, I thought maybe it would be possible to solve this somehow.

Any ideas?

**Comment by zbjornson** [comment]
I haven't tested this, but I think the following will work:

```javascript
global.document = {
  createElement: function (tag) {
    if (tag === "img") {
      return new Canvas.Image();
    }
  }
};
```

If you find more missing APIs, you might want to use node-canvas via jsdom, as that provides the `document` element.

**Comment by makc** [comment]
@zbjornson much thanks for your sample code here, it appears renderer.setSize(200, 200) is critical for this to work, even if you pass the canvas that is already 200x200, otherwise the png is blank (which is the issue I was facing).

**Comment by verina09** [comment]
hi, I tried running the code posted above to draw the cube, however the .png produced is just a transparent png.

This is the error message produced from CanvasRenderer:
THREE.CanvasRenderer.render: camera is not an instance of THREE.Camera
According to #3209 possibly there is duplication in declaration of three.js (but I simply copy paste the code above).

I also tried ignoring the isCamera === undefined in CanvasRenderer and just set it to isCamera = true (I know this shouldnt be done, but this is also not working).

Any idea how to make the code work? What am I missing?

Thank you!

**Comment by dbkaplun** [comment]
I've taken @zbjornson's idea and turned it into an [NPM module](https://github.com/dbkaplun/node-three-screenshot)! Thanks @zbjornson!

```js
import { toPNG } from 'node-three-screenshot';

fs.writeFileSync('out.png', toPNG(scene));
```

![screenshot](https://raw.githubusercontent.com/dbkaplun/node-three-screenshot/master/test/__image_snapshots__/to-png-test-js-to-png-should-create-a-png-snapshot-for-a-three-object-3-d-1-snap.png)

**Comment by zbjornson** [comment]
Awesome! :)

**Comment by robert-cooper-developer** [comment]
/var/www/render/node_modules/three/build/three.js:32184
                        image.addEventListener( 'load', onImageLoad, false );
                              ^
    TypeError: image.addEventListener is not a function

Getting that error when I try to use new Canvas.Image as the document images

**Comment by makc** [comment]
I used to load it by hand:
```javascript
  fs.readFile(path, function (error, data) {
    if (error) throw error;

    var image = new Image;
    image.src = data;

    var texture = new THREE.Texture(image);
    texture.needsUpdate = true;
```

it is probably possible to patch things to make 3js loaders work, but I did not care to do it.

**Comment by zbjornson** [comment]
Just opened #1218 for that issue.

**Comment by frankleonrose** [comment]
@robert-cooper-developer Note monkey-patch in node-three.js lib at https://github.com/nulltask/node-three.js/blob/master/lib/three.js#L21 to add `addEventListener` to Image.

**Comment by szwbuaa** [comment]
Hi, How can I load a json model on serverside? When I use ObjectLoader to parse json, it give me a prompt message as following.

```
ReferenceError: window is not defined
    at ObjectLoader.parseGeometries (\node_modules\three\build\three.js:39019:24)
    at ObjectLoader.parse (\node_modules\three\build\three.js:38716:26)
```

Thanks

**Comment by makc** [comment]
@szwbuaa 

> window is not defined

well, define it :) it seems the only use of window in ObjectLoader is for 
> if ( 'THREE' in window && 'LegacyJSONLoader' in THREE ) {

check, so you could do something like
> global.window = { THREE: THREE }

**Comment by forsnowlove** [comment]
> I know this is kinda late but...
> 
> ```
> /var/www/render/node_modules/three/build/three.js:32184
>                     image.addEventListener( 'load', onImageLoad, false );
>                           ^
> TypeError: image.addEventListener is not a function
> ```
> 
> Getting that error when I try to use new Canvas.Image as the document images.
> 
> P.S. I'm trying to use this with OBJLoader and MTLLoader to render stuff on my server. Got everything working but the texture will not load for some reason.

hey,did you finally slove this problem? I am tring to read obj file by nodejs and success,but failed to peocess mtf file through MTLLoader

**Comment by makc** [comment]
@forsnowlove scroll [up](https://github.com/Automattic/node-canvas/issues/730#issuecomment-415565981).

**Comment by manu4gmz** [comment]
For those having trouble, the last version of three.js which still has `CanvasRenderer` is `0.97.0`

I also used version `2.6.1` for `canvas` module

```json
"canvas": "^2.6.1",
"three": "^0.97.0"
```

This is how I imported the modules and implemented de renderer part
```js
global.THREE = require("three"); // Important to assign it to global
// These files doesn't export anything, the CanvasRenderer is assigned to THREE global variable
require("three/examples/js/renderers/CanvasRenderer");
require("three/examples/js/renderers/Projector");

const { Canvas } = require("canvas");
const canvas = new Canvas(width, height);
canvas.style = { width, height }; // This was necessary to prevent an error from CanvasRenderer

const renderer = new THREE.CanvasRenderer({ canvas: canvas });
```

**Comment by DOEHOONLEE** [comment]
I did work on showing boxes and spheres on the server side, but anybody succeeded importing a `.gltf` from the server side??
