### ISSUE TITLE
Centos 7 - runtime error

### ISSUE THREAD

**Issue by hklsk** [Automattic/node-canvas#736]
canvas version: 1.3.12 [I have tried 1.2 & 1.1]
node version 5.8 [I have tried 4.x, 0.x, iojs]

There is a runtime error

Error: /home/canvas_test/node_modules/canvas/build/Release/canvas.node: undefined symbol: _Z22jpeg_resync_to_restartP22jpeg_decompress_structi

my script:

```
var canvas = require('canvas');
```

Error

```
module.js:440
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /home/canvas_test/node_modules/canvas/build/Release/canvas.node: undefined symbol: _Z22jpeg_resync_to_restartP22jpeg_decompress_structi
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/canvas_test/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

```

Please help
Thanks

**Comment by me2i** [comment]
Hi @hklsk 

Were you able to eventually fix this issue? Because I'm currently running in the exact same issue and can't seem to figure out how to fix it.

Thanks!

**Comment by zbjornson** [comment]
That error suggests that libjpeg was improperly installed (or maybe a very old version). Try removing and reinstalling it.

Closing because this is a year old, but will reopen if you have issues still.
