### ISSUE TITLE
'error while reading from input stream' with jpegs on Windows

### ISSUE THREAD

**Issue by skywickenden** [Automattic/node-canvas#738]
When I try to read in a jpeg image to draw on a canvas I get an error.

For example If I run the [crop.js](https://github.com/Automattic/node-canvas/blob/master/examples/crop.js) example I get:

```
C:\ProjectPath\node_modules\canvas\examples> node crop.js
C:\ProjectPath\node_modules\canvas\examples\crop.js:12
  throw err;
  ^

Error: error while reading from input stream
    at Error (native)
    at Image.src (C:\ProjectPath\node_modules\canvas\lib\image.js:30:17)
    at Object.<anonymous> (C:\ProjectPath\node_modules\canvas\examples\crop.js:33:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

I've followed the instructions on the wiki. Tried uninstalling and reinstalling everything twice. Tried a different version of libjpeg-turbo (I checked that everything is 64bit versions).

It works fine with png images.

No clue how to investigate this. Any ideas?

**Comment by qwemaze** [comment]
Same problem

**Comment by zbjornson** [comment]
JPEG support for Windows was added in 2.x (currently in alpha). 🎉
