### ISSUE TITLE
pngStream memory leak

### ISSUE THREAD

**Issue by d3zza** [Automattic/node-canvas#744]
I am to trying to use node canvas to render an animation as a sequence of images. The following function is called for each frame. The update() call after writing has finished will rerun this function after the canvas has been updated. 

``` javascript
ImageRenderer.prototype = {

....

writeImage : function( canvas ){

        this.frame++;
        var imagePath = this.getCurrentOutputImagePath();

        var writeStream = fs.createWriteStream( imagePath );
        // var readStream = canvas.jpegStream({quality:100}); // works without issue
        var readStream = canvas.pngStream(); // causes memory error

        this.renderedImages.push( imagePath );

        var renderer = this;

        writeStream.once('finish', function(){
            if( renderer.progressCallback ){
                renderer.progressCallback({
                    progress: renderer.frame,
                    total: renderer.totalFrames()
                });
            }

            console.log('finished writing frame', renderer.time );
            renderer.update( renderer.interval );
        });

        readStream.pipe( writeStream );
    },

...
}
```

When using pngStream(), after about 60 frames I get the following error:

```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: out of memory
    at Error (native)
    at /Volumes/Data/Users/derekm/Documents/work/projects/html.animrender/website/node_modules/canvas/lib/pngstream.js:43:19
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
```

The same function changed to use either a jpegStream, or a native readStream seems to work without issue.  

Thanks in advance.

**Comment by pengyanb** [comment]
Try something like this:
```javascript
readstream.on('data', function(chunk){
    writestream.write(chunk);
});
readstream.on('end', function(){
    writestream.end();
});
writestream.on('close', function(){
     done(null);    // wait till the writestream is fully closed before trigger the next iteration
})
```

**Comment by zbjornson** [comment]
I think this is fixed, but please leave a comment if you can still repro a leak.
