### ISSUE TITLE
Build fails on FreeBSD (Node 5)

### ISSUE THREAD

**Issue by hakkiplaten** [Automattic/node-canvas#751]
Used to work back when I had Node 0.10.x. Upgraded to 5.x recently and am now getting:

```
% npm install canvas
-
> canvas@1.3.12 install /usr/home/test/node_modules/canvas
> node-gyp rebuild

./util/has_lib.sh: not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System FreeBSD 10.2-RELEASE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/test/node_modules/canvas
gyp ERR! node -v v5.9.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! FreeBSD 10.2-RELEASE
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! node v5.9.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.3.12 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/home/test/npm-debug.log
```

Related dependencies:

```
% pkg info
cairo-1.14.6,2
freetype2-2.6.3
giflib-5.1.3
jpeg-8_6
png-1.6.21
```

**Comment by hakkiplaten** [comment]
@tj can you merge https://github.com/Automattic/node-canvas/pull/754 and close this issue?

Thanks.

**Comment by yshybeka** [comment]
the reason is that ./util/has_lib.sh begins with "#!/bin/bash"

**Comment by hakkiplaten** [comment]
True. See https://github.com/Automattic/node-canvas/pull/754 for more.
