### ISSUE TITLE
npm ERR! Failed at the canvas@1.4.0 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by kaytrance** [Automattic/node-canvas#788]
I am trying to deploy my app to `digitalocean` with `dokku`. Even if I have ssh'ed to digitalocean machine and ran a command to install all dependencies as is stated in wiki (`sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++`), I still receive the following error:

```
-----> Building dependencies
       Pruning any extraneous modules
       Installing node modules (package.json)

       > canvas@1.4.0 install /tmp/build/node_modules/canvas
       > node-gyp rebuild

       make: Entering directory `/tmp/build/node_modules/canvas/build'
       SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
       COPY Release/canvas-postbuild.node
       CXX(target) Release/obj.target/canvas/src/Canvas.o
       CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
       CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
       In file included from ../src/CanvasPattern.cc:9:0:
       ../src/Image.h:19:21: fatal error: gif_lib.h: No such file or directory
       #include <gif_lib.h>
       ^
       compilation terminated.
       make: *** [Release/obj.target/canvas/src/CanvasPattern.o] Error 1
       make: Leaving directory `/tmp/build/node_modules/canvas/build'
       gyp ERR! build error
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
       gyp ERR! stack     at emitTwo (events.js:87:13)
       gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
       gyp ERR! System Linux 3.13.0-85-generic
       gyp ERR! command "/tmp/build/.heroku/node/bin/node" "/tmp/build/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       gyp ERR! cwd /tmp/build/node_modules/canvas
       gyp ERR! node -v v4.4.5
       gyp ERR! node-gyp -v v3.3.1
       gyp ERR! not ok
```

Specs: Ubuntu 14.04, dokku 0.6.3, node 4.4.5, npm 2.15.5

**Comment by tarun1793** [comment]
`sudo apt-get install libgif-dev` should do it

**Comment by MarkehMe** [comment]
This solve the issue for me: http://stackoverflow.com/questions/22100213/package-cairo-was-not-found-in-the-pkg-config-search-path-node-j-s-install-canv

**Comment by BogusCurry** [comment]
Hello ;D
I have the same problem .. http://paste.md-5.net/hefahuyiye.vbs

**Comment by EddieOne** [comment]
What about windoz 10?

**Comment by bakeruk** [comment]
Simular issue using AWS Red Hat 7 (Centos)...

```
root@presenter-app-1a-247-1 npm]# sudo npm install canvas

> canvas@1.4.0 install /srv/www/presenter_app/releases/20160823093039/bundle/programs/server/npm/node_modules/canvas
> node-gyp rebuild

Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.14-24.50.amzn1.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/www/presenter_app/releases/20160823093039/bundle/programs/server/npm/node_modules/canvas
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/srv/www/presenter_app/releases/20160823093039/bundle/programs/server/npm/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/srv/www/presenter_app/releases/20160823093039/bundle/programs/server/npm/node_modules/meteor/package.json'
npm WARN npm No description
npm WARN npm No repository field.
npm WARN npm No README data
npm WARN npm No license field.
npm ERR! Linux 4.4.14-24.50.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.4.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.
```

**Comment by s7dhansh** [comment]
I am getting the same error on ubuntu 16.04

**Comment by cbob3000** [comment]
I'm suffering from this too, on Xubuntu 16.04. Any ideas? Or guestimates regarding a fix?

**Comment by LinusU** [comment]
What libraries have you tried installing on Ubuntu/Xubuntu? Have you tried `sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++`?

**Comment by cbob3000** [comment]
Yes I have. Here's a fresh output from running that: 

 % sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
[sudo] password for xxxx: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
g++ is already the newest version (4:5.3.1-1ubuntu1).
libcairo2-dev is already the newest version (1.14.6-1).
libjpeg8-dev is already the newest version (8c-2ubuntu8).
libpango1.0-dev is already the newest version (1.38.1-1).
libgif-dev is already the newest version (5.1.4-0.3~16.04).

**Comment by LinusU** [comment]
Hmm, that's interesting... Maybe the version of libgif-dev is too new...

What is the exact output when trying to install node-canvas?

**Comment by cbob3000** [comment]
Full output:

` % sudo npm install canvas     

> canvas@1.6.0 install /home/cbob/workspace/icebox/client/trunk/protobuf_shared/node_modules/canvas
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-36-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/xxxx/
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/xxxx/package.json'
npm WARN protobuf_shared No description
npm WARN protobuf_shared No repository field.
npm WARN protobuf_shared No README data
npm WARN protobuf_shared No license field.
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "canvas"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.6.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xxxx/npm-debug.log
`

Interestingly, the npm-debug.log file is not there, so maybe the installer fails to write to the disk for some reason?

**Comment by cbob3000** [comment]
I ran it again and this time I did indeed get the npm-debug-file, attached. 

[npm-debug.txt](https://github.com/Automattic/node-canvas/files/533595/npm-debug.txt)

**Comment by LinusU** [comment]
`/bin/sh: 1: node: not found`

It seems like `node` is not in your path...

**Comment by cbob3000** [comment]
Ah right! Naturally the binary is called 'nodejs' when installed from the general Ubuntu repository, so a simple `sudo ln -s /usr/bin/nodejs /usr/bin/node` fixed it. I bet there's a dozen guys having the same issue, so I hope google got you all here! ;) 

Thanks, @LinusU !

**Comment by LinusU** [comment]
Ahh, I believe you can fix that by installing Node.js from nodesource, or by installing the `nodejs-legacy` package

**Comment by kleeb** [comment]
the same on Ubuntu 14

```
Failed at the canvas@1.2.11 install script 'node-gyp rebuild'
```

**Comment by mfeuermann** [comment]
same here

**Comment by kleeb** [comment]
updating node, npm and node-gyp fixed the problem

**Comment by spiotr12** [comment]
Hello. I have similar problem

To start: I have Ubuntu 14 server
I've installed node-canvas (globally) as explained in wiki. 
I'm building meteor js app
I'm using nvm (node and npm versions match between the server / my computer [6.10.1 / 3.10.10])
I need it for FabricJS. 

The problem occurs when I deploy to server. That is my log file:
[npm-debug.txt](https://github.com/Automattic/node-canvas/files/870182/npm-debug.txt)
```
1839 info lifecycle canvas@1.6.5~install: canvas@1.6.5
1840 verbose lifecycle canvas@1.6.5~install: unsafe-perm in lifecycle true
1841 verbose lifecycle canvas@1.6.5~install: PATH: /opt/nodejs/lib/node_modules/npm/bin/node-gyp-bin:/bundle/bundle/programs/server/npm/node_modules/canvas/node_modules/.bin:/bundle/bundle/programs/server/npm/node_modules/.bin:/opt/nodejs/bin:/opt/nodejs/lib/node_modules/npm/bin/node-gyp-bin:/bundle/bundle/programs/server/node_modules/.bin:/opt/nodejs/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
1842 verbose lifecycle canvas@1.6.5~install: CWD: /bundle/bundle/programs/server/npm/node_modules/canvas
1843 silly lifecycle canvas@1.6.5~install: Args: [ '-c', 'node-gyp rebuild' ]
1844 silly lifecycle canvas@1.6.5~install: Returned: code: 1  signal: null
1845 info lifecycle canvas@1.6.5~install: Failed to exec install script
1846 verbose stack Error: canvas@1.6.5 install: `node-gyp rebuild`
1846 verbose stack Exit status 1
1846 verbose stack     at EventEmitter.<anonymous> (/opt/nodejs/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
1846 verbose stack     at emitTwo (events.js:87:13)
1846 verbose stack     at EventEmitter.emit (events.js:172:7)
1846 verbose stack     at ChildProcess.<anonymous> (/opt/nodejs/lib/node_modules/npm/lib/utils/spawn.js:40:14)
1846 verbose stack     at emitTwo (events.js:87:13)
1846 verbose stack     at ChildProcess.emit (events.js:172:7)
1846 verbose stack     at maybeClose (internal/child_process.js:854:16)
1846 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
1847 verbose pkgid canvas@1.6.5
1848 verbose cwd /bundle/bundle/programs/server/npm
1849 error Linux 4.4.0-34-generic
1850 error argv "/opt/nodejs/bin/node" "/opt/nodejs/bin/npm" "rebuild" "--update-binary"
1851 error node v4.8.0
1852 error npm  v3.10.10
1853 error code ELIFECYCLE
1854 error canvas@1.6.5 install: `node-gyp rebuild`
1854 error Exit status 1
1855 error Failed at the canvas@1.6.5 install script 'node-gyp rebuild'.
1855 error Make sure you have the latest version of node.js and npm installed.
1855 error If you do, this is most likely a problem with the canvas package,
1855 error not with npm itself.
1855 error Tell the author that this fails on your system:
1855 error     node-gyp rebuild
1855 error You can get information on how to open an issue for this project with:
1855 error     npm bugs canvas
1855 error Or if that isn't available, you can get their info via:
1855 error     npm owner ls canvas
1855 error There is likely additional logging output above.
1856 verbose exit [ 1, true ]
```

When I just copy files to the server and run my meteor project from there (as I would do it in the development mode) it works - no problem. This above problem occurs only while deploying with meteor up. 

I have now idea where the problem is. 

(Also, the error shows different version of node - I don't know why but this might be a problem?)

I anyone has came across with this or could help that'd be great! Thanks!

**Comment by CrizzzSombiii** [comment]
Same on windows 10...

**Comment by maheshaddepalli** [comment]
It was really fatal bugging from long time but the official guide canvas installation link by @bakeruk nailed my issue. Just straight forward. Missing dependencies need to be installed.

**Comment by chrisguida** [comment]
I am getting this error too, and updating all the dependencies as in @bakeruk's comment did not fix the issue. I'm still getting:

```
$ sudo npm install -g canvas@1.6.13

> canvas@1.6.13 install /usr/local/lib/node_modules/canvas
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/canvas/build'
gyp ERR! System Linux 4.15.0-55-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/canvas
gyp ERR! node -v v12.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.6.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chris/.npm/_logs/2019-09-17T20_39_13_514Z-debug.log

```

Any idea what's going on? Thanks!!

**Comment by zbjornson** [comment]
@chrisguida canvas 1.x and Node.js 12.x are not compatible. Can you use canvas 2.x instead? But you also have a permission error related to using `sudo npm install -g`; can you do a normal local install instead (`npm install canvas`)?

**Comment by bakeruk** [comment]
@chrisguida do you have the right write permissions for your environment?

Ref ‘stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/canvas/build'’ in your log above.

What OS are you running?

**Comment by chrisguida** [comment]
> @chrisguida canvas 1.x and Node.js 12.x are not compatible. Can you use canvas 2.x instead? 

I can't use canvas 2.x because I'm trying to install and run this app, which uses canvas 1.6.13: https://github.com/ElementsProject/filebazaar. Perhaps I can fork it if it's a problem.

>But you also have a permission error related to using `sudo npm install -g`; can you do a normal local install instead (`npm install canvas`)?

I get permission errors when I try to run without sudo:

```
$ npm install -g filebazaar
npm ERR! path /home/chris/.npm/_logs/2019-09-17T20_06_01_212Z-debug.log
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink
npm ERR! Error: EACCES: permission denied, unlink '/home/chris/.npm/_logs/2019-09-17T20_06_01_212Z-debug.log'
npm ERR!     at Object.unlinkSync (fs.js:976:3)
npm ERR!     at Function.rimrafSync [as sync] (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:306:17)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/npm.js:333:20
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:151:7)
npm ERR!     at Glob.emit (events.js:200:13)
npm ERR!     at Glob._finish (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:197:8)
npm ERR!     at done (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:182:14)
npm ERR!     at Glob._processReaddir2 (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:434:12)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:371:17
npm ERR!     at RES (/usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:31:16)
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob._readdirEntries (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:578:10)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:555:12
npm ERR!     at go$readdir$cb (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:162:14)
npm ERR!     at FSReqCallback.oncomplete (fs.js:153:23)
npm ERR!  Error: EACCES: permission denied, unlink '/home/chris/.npm/_logs/2019-09-17T20_06_01_212Z-debug.log'
npm ERR!     at Object.unlinkSync (fs.js:976:3)
npm ERR!     at Function.rimrafSync [as sync] (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:306:17)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/npm.js:333:20
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:151:7)
npm ERR!     at Glob.emit (events.js:200:13)
npm ERR!     at Glob._finish (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:197:8)
npm ERR!     at done (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:182:14)
npm ERR!     at Glob._processReaddir2 (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:434:12)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:371:17
npm ERR!     at RES (/usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:31:16)
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob._readdirEntries (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:578:10)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:555:12
npm ERR!     at go$readdir$cb (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:162:14)
npm ERR!     at FSReqCallback.oncomplete (fs.js:153:23) {
npm ERR!   stack: "Error: EACCES: permission denied, unlink '/home/chris/.npm/_logs/2019-09-17T20_06_01_212Z-debug.log'\n" +
npm ERR!     '    at Object.unlinkSync (fs.js:976:3)\n' +
npm ERR!     '    at Function.rimrafSync [as sync] (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:306:17)\n' +
npm ERR!     '    at /usr/local/lib/node_modules/npm/lib/npm.js:333:20\n' +
npm ERR!     '    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)\n' +
npm ERR!     '    at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:151:7)\n' +
npm ERR!     '    at Glob.emit (events.js:200:13)\n' +
npm ERR!     '    at Glob._finish (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:197:8)\n' +
npm ERR!     '    at done (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:182:14)\n' +
npm ERR!     '    at Glob._processReaddir2 (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:434:12)\n' +
npm ERR!     '    at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:371:17\n' +
npm ERR!     '    at RES (/usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:31:16)\n' +
npm ERR!     '    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)\n' +
npm ERR!     '    at Glob._readdirEntries (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:578:10)\n' +
npm ERR!     '    at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:555:12\n' +
npm ERR!     '    at go$readdir$cb (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:162:14)\n' +
npm ERR!     '    at FSReqCallback.oncomplete (fs.js:153:23)',
npm ERR!   errno: -13,
npm ERR!   syscall: 'unlink',
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/chris/.npm/_logs/2019-09-17T20_06_01_212Z-debug.log'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/usr/local/lib/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
```

**Comment by chrisguida** [comment]
> @chrisguida do you have the right write permissions for your environment?
> 

I'm not sure, I'm a bit new to npm, what should they look like?

> 
> What OS are you running?

Ubuntu 18.04

**Comment by chrisguida** [comment]
@zbjornson I can also downgrade node, which version would be compatible with canvas@1.6.13?

**Comment by chrisguida** [comment]
@bakeruk 

> @chrisguida do you have the right write permissions for your environment?

I'm running the command as root, I'm not sure why I wouldn't have write permissions.

**Comment by chrisguida** [comment]
I figured it out, my local user needed access to a bunch of npm-related directories. Sorry.

**Comment by Timmmm** [comment]
Ok so `OTHER_CFLAGS` definitely doesn't work anymore. You can verify by running

```
npm_config_loglevel=verbose npm install canvas
```

which shows the actual build commands. However a Stackoverflow answer suggested a hackier solution that *does* work:

```
# As before: `xcode-select --install` didn't actually do anything for me but definitely worth a try.
xcode-select --install
npm install node-gyp -g
brew install giflib cairo libjpeg giflib pixman
export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig

# Now instead:
export CXX="clang++ -I/usr/local/include -L/usr/local/lib"
npm install canvas
```

Also, why the hell is `node-gyp` written in Python? Wtf? It's also completely untyped Python which makes following the code impossible and also drastically lowers my level of surprise that it doesn't work properly.

I just looked into it and I didn't even realise that `node-gyp` is based on [GYP]() - a build system from Google that literally nobody else uses that was abandoned in 2016.

[cmake-js](https://www.npmjs.com/package/cmake-js) seems to be the sensible alternative. I mean CMake is terrible too but at least it's standard and very well documented. Maybe consider switching to that?
