### ISSUE TITLE
Node: Module did not self-register

### ISSUE THREAD

**Issue by CharlotteDunois** [Automattic/node-canvas#869]
I've installed v2.0, because v1.x is failure (`registerFont is not a function`). Now it works fine, until to the point I want to reload a `require`d file (purge module cache and require file again), where canvas is `require`d. Then it fails due to the fact, that canvas does not self-register. This has nothing to do with #573, as I don't have upgraded node or anything else. `node-gyp rebuild` does not help too.

Error:

    Error while trying to read module "weather". Error: Error: Module did not self-register.
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\*\Downloads\discord\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\*\Downloads\discord\node_modules\canvas\lib\canvas.js:13:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

I'm running node v7.4 on Windows 7 x64 Pro. Canvas works so far, but it refuses to self-register.

**Comment by zbjornson** [comment]
Native modules cannot be reloaded. (See [docs](https://nodejs.org/docs/latest/api/globals.html#globals_require_cache).)

I'm curious why you're trying to do this; I might be able to offer advice for alternative approaches.

**Comment by LinusU** [comment]
> Note that this does not apply to native addons, for which reloading will result in an Error.

As @zbjornson said this is a limitation of Node.js, not specific in node-canvas. I'm closing this but feel free to continue the discussion! I'm also interested in the use case of this :)
