### ISSUE TITLE
What this can be?

### ISSUE THREAD

**Issue by Rawnly** [Automattic/node-canvas#888]
## Issue or Feature

```
C:\Users\fedev>npm i -g splash-cli
C:\Users\fedev\AppData\Roaming\npm\splash -> C:\Users\fedev\AppData\Roaming\npm\node_modules\splash-cli\cli.js

> canvas@1.2.11 install C:\Users\fedev\AppData\Roaming\npm\node_modules\splash-cli\node_modules\canvas
> node-gyp rebuild


C:\Users\fedev\AppData\Roaming\npm\node_modules\splash-cli\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\fedev\AppData\Roaming\npm\node_modules\splash-cli\node_modules\canvas
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
C:\Users\fedev\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "splash-cli"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.2.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.2.11 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\fedev\npm-debug.log
npm ERR! code 1
```

## Steps to Reproduce

Installing my own client package. [Here](https://gist.github.com/Rawnly/0df6102cecfbd5874ea1e4339fd8879a) a link to **npm-debug.log**

## Your Environment
* Version of node-canvas (e.g. 1.4.0): 1.2.11
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): MacOs 10.12.3 & Win10

**Comment by LinusU** [comment]
> Error: Can't find Python executable "python", you can set the PYTHON env variable.

You need to have python installed in order to build native dependencies...
