### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Yaojian** [Automattic/node-canvas#890]
When install node-canvas with

```
npm install canvas --save-dev
```
it shows:
```
npm WARN skippingAction Module is inside a symlinked module: not running move nan@2.5.1 node_modules/canvas/node_modules/nan
```

and 
```
$node
> typeof require('canvas');
Error: Cannot find module '../build/Release/canvas'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/yaojian/Documents/Projects/RedSight/devel/sources/webui/node_modules/.1.6.4@canvas/lib/bindings.js:3:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
> exit
```

## Your Environment
* Version of node-canvas (1.6.4):
* Environment: node 6.9.1 on Mac OS X 10.11.6), npm 3.10.8

**Comment by LinusU** [comment]
It seems like some of your dependencies are symlinked, can you remove `node_modules` and try again?

**Comment by abhisheksoni27** [comment]
I have the same issue. I removed `node_modules`, then tried again but I still get the same error.
