### ISSUE TITLE
Problem with installing Canvas on Debian 8

### ISSUE THREAD

**Issue by giangdhwhtbr** [Automattic/node-canvas#897]
## Issue

Problem with installing canvas on Debian 8.
```
> canvas@1.3.16 install /home/giangdh10/williwaw/node_modules/canvas
> node-gyp rebuild

make: Entering directory '/home/giangdh10/williwaw/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
../src/Canvas.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Canvas::ToBuffer(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/Canvas.cc:325:14: warning: ‘v8::TryCatch::TryCatch()’ is deprecated (declared at /home/giangdh10/.node-gyp/6.9.1/include/node/v8.h:6771): Use isolate version [-Wdeprecated-declarations]
     TryCatch try_catch;
              ^
../src/Canvas.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Canvas::StreamPNGSync(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/Canvas.cc:417:12: warning: ‘v8::TryCatch::TryCatch()’ is deprecated (declared at /home/giangdh10/.node-gyp/6.9.1/include/node/v8.h:6771): Use isolate version [-Wdeprecated-declarations]
   TryCatch try_catch;
            ^
../src/Canvas.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Canvas::StreamJPEGSync(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/Canvas.cc:458:12: warning: ‘v8::TryCatch::TryCatch()’ is deprecated (declared at /home/giangdh10/.node-gyp/6.9.1/include/node/v8.h:6771): Use isolate version [-Wdeprecated-declarations]
   TryCatch try_catch;
            ^
/home/giangdh10/williwaw/node_modules/.bin/touch: 1: /home/giangdh10/williwaw/node_modules/.bin/touch: Syntax error: "(" unexpected
canvas.target.mk:124: recipe for target 'Release/obj.target/canvas/src/Canvas.o' failed
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 2
make: Leaving directory '/home/giangdh10/williwaw/node_modules/canvas/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/giangdh10/williwaw/node_modules/canvas
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN angular-material@1.1.1 requires a peer of angular@>=1.3 <1.6 but none was installed.
npm WARN angular-material@1.1.1 requires a peer of angular-animate@>=1.3 <1.6 but none was installed.
npm WARN angular-material@1.1.1 requires a peer of angular-aria@>=1.3 <1.6 but none was installed.
npm WARN EventApp@0.0.1 No description
npm WARN EventApp@0.0.1 No repository field.
npm WARN EventApp@0.0.1 No license field.
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "canvas" "--unsafe-perm"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.3.16 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/giangdh10/williwaw/npm-debug.log
``` 
## My Environment
* Environment:
OS: Debian 8
Node version: 6.9.1
NPM version: 3.4.0

**Comment by zbjornson** [comment]
I see three warnings for canvas, and an error for `touch` (which I assume is https://www.npmjs.com/package/touch), which seems to have bubbled up to a failure for canvas. In an empty directory, does `npm install canvas` work? I'm not sure how `touch` is affecting things here.

**Comment by giangdhwhtbr** [comment]
@zbjornson thank you so much, finally I can install it :+1:

**Comment by francisrod01** [comment]
I have the same problem. Should I open a new issue?
https://github.com/aslansky/css-sprite/issues/84
