### ISSUE TITLE
Error: libgif.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Jom3es12** [Automattic/node-canvas#921]
I recently changed my VPS provider and now canvas doesn't work. Node crashes when i try running my project. 
```
module.js:488
  Module._extensions[extension](this, filename);
                               ^

Error: libgif.so.4: cannot open shared object file: No such file or directory
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jom3es12/jimv3/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jom3es12/jimv3/node_modules/canvas/lib/canvas.js:13:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jom3es12/jimv3/commands/general/stats.js:6:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```
in case you're wondering i'm running a discord bot. It worked fine on the other vps. ¯\_(ツ)_/¯

**Comment by Jom3es12** [comment]
it works fine on the alpha version just tried lol
