### ISSUE TITLE
canvas fails to install on macOS High Sierra Beta

### ISSUE THREAD

**Issue by bsgbryan** [Automattic/node-canvas#927]
I'm trying out the macOS High Sierra Beta.

I had canvas installed and working before I upgraded to High Sierra. I made sure all my brew installs were up to date after I upgraded to High Sierra.

I tried executing `brew install pkg-config cairo pango libpng jpeg giflib` but all the packages were already installed. cairo had an update, so I executed `brew upgrade cairo`. I also executed `xcode-select --install`. I even executed `xcode-select -s` to ensure I was pointing to the correct version of Xcode (I have both the current version and the beta for 9.0 installed).

When I execute `npm install canvas` now, I get the following:

```
> canvas@1.6.5 install /Users/fo/Code/Skyll/node_modules/canvas
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
2017-06-20 23:54:58.937 xcodebuild[41296:701785] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:20:
../src/JPEGStream.h:10:10: fatal error: 'jpeglib.h' file not found
#include <jpeglib.h>
         ^
1 error generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/fo/.nvm/versions/node/v7.7.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 17.0.0
gyp ERR! command "/Users/fo/.nvm/versions/node/v7.7.2/bin/node" "/Users/fo/.nvm/versions/node/v7.7.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/fo/Code/Skyll/node_modules/canvas
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by zbjornson** [comment]
> brew install pkg-config cairo pango libpng jpeg giflib

I don't have an OSX machine to test on, but I think that might need to be `libjpeg` and not `jpeg`.

**Comment by bsgbryan** [comment]
`libjpeg` and `jpeg` are the same thing:

```
MacBook-Pro :: ~/Code/Skyll ‹master*› » brew install libjpeg
Warning: jpeg 8d is already installed
MacBook-Pro :: ~/Code/Skyll ‹master*› » brew install jpeg
Warning: jpeg 8d is already installed
```

**Comment by chearon** [comment]
Did you try linking it again maybe? I could see the upgrade partially replacing it with the system version. It'll try to use the homebrew one unless you change `binding.gyp`, I think.

```
> brew link libjpeg
Warning: Already linked: /usr/local/Cellar/jpeg/8d
To relink: brew unlink jpeg && brew link jpeg

> ls -l /usr/local/include | grep jpeg
lrwxr-xr-x  1 caleb  admin  35 Apr  1 11:51 jconfig.h -> ../Cellar/jpeg/8d/include/jconfig.h
lrwxr-xr-x  1 caleb  admin  34 Apr  1 11:51 jerror.h -> ../Cellar/jpeg/8d/include/jerror.h
lrwxr-xr-x  1 caleb  admin  36 Apr  1 11:51 jmorecfg.h -> ../Cellar/jpeg/8d/include/jmorecfg.h
lrwxr-xr-x  1 caleb  admin  35 Apr  1 11:51 jpeglib.h -> ../Cellar/jpeg/8d/include/jpeglib.h
```

**Comment by bsgbryan** [comment]
I unlinked and linked:
```
> brew link libjpeg
Warning: Already linked: /usr/local/Cellar/jpeg/8d
To relink: brew unlink jpeg && brew link jpeg
> brew unlink jpeg && brew link jpeg
Unlinking /usr/local/Cellar/jpeg/8d... 17 symlinks removed
Linking /usr/local/Cellar/jpeg/8d... 17 symlinks created
```

Still got this error:
```
In file included from ../src/Canvas.cc:20:
../src/JPEGStream.h:10:10: fatal error: 'jpeglib.h' file not found
#include <jpeglib.h>
         ^~~~~~~~~~~
1 error generated.
```

This is what I have for `/user/local/include`:
```
> ls -l /usr/local/include | grep jpeg
lrwxr-xr-x   1 fo  staff    35 Jun 21 13:01 jconfig.h -> ../Cellar/jpeg/8d/include/jconfig.h
lrwxr-xr-x   1 fo  staff    34 Jun 21 13:01 jerror.h -> ../Cellar/jpeg/8d/include/jerror.h
lrwxr-xr-x   1 fo  staff    36 Jun 21 13:01 jmorecfg.h -> ../Cellar/jpeg/8d/include/jmorecfg.h
lrwxr-xr-x   1 fo  staff    35 Jun 21 13:01 jpeglib.h -> ../Cellar/jpeg/8d/include/jpeglib.h
```

**Comment by chearon** [comment]
I think it's [this answer](https://stackoverflow.com/a/32929012/487014) all over again, only `xcode-select` didn't seem to work for High Sierra... Maybe it's something they'll fix.

Run `clang++ -E -x c++ - -v < /dev/null` to verify that `/usr/local/include` is not in your path.

**Comment by bsgbryan** [comment]
If I'm reading this correctly (_which is 50/50_) it looks like `/usr/local/include` is not in my path:
```
ignoring nonexistent directory "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/local/include"
```
Also; `#include <...> search starts here:` does not include `/usr/local/include`.

Full output:

```
clang++ -E -x c++ - -v < /dev/null
Apple LLVM version 9.0.0 (clang-900.0.22.8)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.13.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 301.1 -v -dwarf-column-info -debugger-tuning=lldb -resource-dir /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -stdlib=libc++ -fdeprecated-macro -fdebug-compilation-dir /Users/fo/Code/Skyll -ferror-limit 19 -fmessage-length 204 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.13.0 -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o - -x c++ -
clang -cc1 version 9.0.0 (clang-900.0.22.8) default target x86_64-apple-darwin17.0.0
ignoring nonexistent directory "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/v1"
ignoring nonexistent directory "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
 /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include
 /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include
 /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks (framework directory)
End of search list.
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 342 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2
```

**Comment by chearon** [comment]
Correct, it's not... so you need `/usr/local/include` in Clang's search path and you might also need `/usr/local/lib` in the search path for the linker. You could try editing the `binding.gyp` directly in node_modules/canvas and then running `node-gyp rebuild` in that directory. Or you can try to add it to clang's global list, not sure how you do that.

**Comment by bsgbryan** [comment]
I'll try the first option and report back.

Thanks! :metal:

**Comment by bsgbryan** [comment]
Oh wait! `canvas` isn't installed, so I can't edit `binding.gyp` ...

I'll try updating clang's include list.

**Comment by bsgbryan** [comment]
Ok, so I executed:
```
CPLUS_INCLUDE_PATH=/usr/local/include:/usr/local/lib
export CPLUS_INCLUDE_PATH
```

Then `clang++ -E -x c++ - -v < /dev/null` showed:
```
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /usr/local/lib
 .../Applications/Xcode-beta.app entries...
```

I'm not sure what the difference between `#include <...>` and `#include "..."` is, so I'm not sure if I did that correctly.

Then I executed `npm install canvas`.

**The good news:** The `jpeglib.h` error is gone!

**The bad news:** I'm now getting this: `ld: library not found for -ljpeg`

Full output of `npm install canvas`:
```
> npm install canvas

> canvas@1.6.5 install /Users/fo/Code/Skyll/node_modules/canvas
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
2017-06-21 13:46:54.344 xcodebuild[7585:420109] [MT] PluginLoading: Required plug-in compatibility UUID CA351AD8-3176-41CB-875C-42A05C7CDEC7 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
  CXX(target) Release/obj.target/canvas/src/color.o
  CXX(target) Release/obj.target/canvas/src/Image.o
  CXX(target) Release/obj.target/canvas/src/ImageData.o
  CXX(target) Release/obj.target/canvas/src/init.o
  CXX(target) Release/obj.target/canvas/src/FontFace.o
  SOLINK_MODULE(target) Release/canvas.node
ld: library not found for -ljpeg
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/canvas.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/fo/.nvm/versions/node/v7.7.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 17.0.0
gyp ERR! command "/Users/fo/.nvm/versions/node/v7.7.2/bin/node" "/Users/fo/.nvm/versions/node/v7.7.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/fo/Code/Skyll/node_modules/canvas
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fo/.npm/_logs/2017-06-21T18_47_05_838Z-debug.log
```

**Comment by chearon** [comment]
Yeah so you need to add `/usr/local/lib` to the linker path, not to Clang. Looks like maybe `export DYLD_LIBRARY_PATH="/usr/local/lib"` would work? You can still edit the `binding.gyp` file, it's in `<directory where you did npm install canvas>/node_modules/canvas`. To rebuild you run `node-gyp rebuild` in that directory (after you `npm install -g node-gyp`)

**Comment by bsgbryan** [comment]
**Great news:** Got this working!

Ok, so the env variable I needed to update was `LIBRARY_PATH`:
```
> export LIBRARY_PATH=/usr/local/lib
> node install canvas
```

_Worked:_
```
+ canvas@1.6.5
added 14 packages in 19.273s
```

**Comment by bsgbryan** [comment]
**To summarize**

The issue is that, as of now, the beta version of `xcode-select --install` does not properly update clangs include path or the linker path.

To correct this, the following needs to be done:

1. `export CPLUS_INCLUDE_PATH=/usr/local/include` (_this updates clangs include path_)
2. `export LIBRARY_PATH=/usr/local/lib` (_this updates the linker path so `-ljpeg` can be found_)

Once these two steps have been executed, _after installing all external dependencies listed in the [docs](https://github.com/Automattic/node-canvas#installation) and executing `xcode-select --install`_, `npm install canvas` should execute successfully.
