### ISSUE TITLE
Symbol not found _OBJC_CLASS_$_NSFont when requiring canvas

### ISSUE THREAD

**Issue by jmeyers91** [Automattic/node-canvas#928]
## Issue or Feature
I'm receiving this error while trying `require` node-canvas:

```
Error: Error: dlopen(/Users/james/projects/audiogram/node_modules/canvas/build/Release/canvas.node, 1): Symbol not found: _OBJC_CLASS_$_NSFont
  Referenced from: /Library/Frameworks/Mono.framework/Versions/4.8.1/lib/libpangocairo-1.0.0.dylib
  Expected in: flat namespace
 in /Library/Frameworks/Mono.framework/Versions/4.8.1/lib/libpangocairo-1.0.0.dylib
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/james/projects/audiogram/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

## Steps to Reproduce

```js
require('canvas');
```

## Your Environment
* Version of node-canvas (e.g. 1.4.0): ^1.6.5
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Node 7.8.0, npm 4.2.0, OSX 10.12.5

**Comment by lucyhao** [comment]
I aslo met this issue..
Node v8.9.4
Npm: 5.7.1

Referenced from: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/libpangocairo-1.0.0.dylib
Expected in: flat namespace

**Comment by chearon** [comment]
The recommended way to install `node-canvas` dependencies on macOS is via Homebrew, I haven't heard of anyone successfully linking against Mono.

**Comment by majid701** [comment]
I am facing the same issue. Tried `npm rebuild` but no luck.
Any workarounds or fixes?
Help would be much appreciated!

**Comment by jmeyers91** [comment]
I think I ended up using [canvas-prebuilt](https://www.npmjs.com/package/canvas-prebuilt) because I couldn't find a fix for this.

**Comment by Spoonin** [comment]
Solved with complete uninstallation of  Mono framework, then `npm install --build-from-source canvas`
