### ISSUE TITLE
[Release/obj.target/canvas/src/Canvas.o] Error 1

### ISSUE THREAD

**Issue by t2krew** [Automattic/node-canvas#940]
```
## Issue or Feature
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
make: Leaving directory `/opt/www/snh-api/node_modules/canvas/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-431.el6.x86_64
gyp ERR! command "/usr/local/node/bin/node" "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/www/snh-api/node_modules/canvas
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/opt/www/snh-api/node_modules/_@ava_babel-plugin-throws-helper@2.0.0@@ava/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/www/snh-api/node_modules/_@ava_babel-preset-stage-4@1.0.0@@ava/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/www/snh-api/node_modules/_@ava_babel-preset-stage-4@1.1.0@@ava/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/www/snh-api/node_modules/_@ava_babel-preset-transform-test-files@3.0.0@@ava/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/www/snh-api/node_modules/_@ava_pretty-format@1.1.0@@ava/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/www/snh-api/node_modules/_@types_geojson@1.0.2@@types/package.json'
npm WARN koa2-kickstarter@1.0.0 No repository field.
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "i" "canvas" "--unsafe-perm"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! canvas@1.6.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.6.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/root1/.npm/_logs/2017-07-10T03_51_12_922Z-debug.log
```

## MY Environment
* Version of node-canvas (e.g. 1.6.5):
* Environment (e.g. node 7.10.0 on Centos 6.9):

**Comment by raviksha** [comment]
@t2krew  - Were u able to get around this ?  My npm installation fails with a similar issue -
Interestingly if I downgrade it to node -v v-0.10xx, it works fine.

_make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
make: Leaving directory `/home/raviksha/node_modules/canvas/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/y/share/node/ynpm/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-642.6.2.el6.20161025.8.x86_64
gyp ERR! command "/home/y/libexec64/node" "/home/y/share/node/ynpm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/raviksha/node_modules/canvas
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
ynpm ERR! Linux 2.6.32-642.6.2.el6.20161025.8.x86_64
ynpm ERR! argv "/home/y/libexec64/node" "/home/y/share/node/ynpm/bin/ynpm-cli.js" "i" "canvas@1.6.5"
ynpm ERR! node v6.11.1
ynpm ERR! npm -v 2.15.11
ynpm ERR! ynpm -v 3.2.50
ynpm ERR! code ELIFECYCLE

ynpm ERR! canvas@1.6.5 install: `node-gyp rebuild`
ynpm ERR! Exit status 1
ynpm ERR! 
ynpm ERR! Failed at the canvas@1.6.5 install script._

**Comment by t2krew** [comment]
@raviksha my gcc version was lower, solved after update gcc

**Comment by LinusU** [comment]
@t2krew Awesome 👍
