### ISSUE TITLE
Package fontconfig was not found in the pkg-config search path.

### ISSUE THREAD

**Issue by marcoangelo** [Automattic/node-canvas#952]
I have followed the installation instructions on the main page and have tried everything I can think of, but still get the following error when running 'npm install canvas':

```
Package fontconfig was not found in the pkg-config search path.
Perhaps you should add the directory containing `fontconfig.pc'
to the PKG_CONFIG_PATH environment variable
Package 'fontconfig', required by 'cairo', not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/marcoangelo/Sites/verify/ui_source/node_modules/canvas
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN Verify@0.0.1 No description
npm WARN Verify@0.0.1 No repository field.
npm WARN Verify@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.6.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marcoangelo/.npm/_logs/2017-08-04T14_40_35_810Z-debug.log
```
I've tried the solutions as recommended here:  #260 
but no luck.

I have the latest version of X-code, Homebrew is updated. and NPM -v is 5.1.0

System is Mac OS Sierra 10.12.6

I am a bit of a n00b with NPM but hopefully someone can help.

Thanks in advance.

**Comment by marcoangelo** [comment]
managed to fix by adding:

`"qrcode": "^0.9.0"`

to my dependencies in package.json and running sudo npm update
