### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by kyranet** [Automattic/node-canvas#972]
```bash
kyra@MSI:/mnt/c/Users/antor/Documents/Repositories/canvasConstructor$ npm install Automattic/node-canvas

> canvas@2.0.0-alpha.3 install /mnt/c/Users/antor/Documents/Repositories/canvasConstructor/node_modules/canvas
> node-gyp rebuild

/bin/sh: 1: pkg-config: not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.4.0+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt/c/Users/antor/Documents/Repositories/canvasConstructor/node_modules/canvas
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.0.0-alpha.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.0.0-alpha.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kyra/.npm/_logs/2017-08-28T10_48_33_876Z-debug.log
```

A [Gist](https://gist.github.com/kyranet/94516c1761a7bb5b96cb422b3b982db4) with the debug logs.

## Issue or Feature
I cannot install the latest commit in the master branch.

## Steps to Reproduce
```bash
$ npm install Automattic/node-canvas
```

## Your Environment
* Version of node-canvas (e.g. 1.4.0): None, fails to install.
* Environment: Node.js 8.4.0 & NPM 5.3.0 on *Linux subsystem for Windows (Ubuntu)*

**Comment by kyranet** [comment]
Probably I forgot to install the binaries, I changed the computer and I didn't install the binaries yet.
