### ISSUE TITLE
Error on latest upgrade 0.6.0

### ISSUE THREAD

**Issue by wavded** [Automattic/node-canvas#98]
Got this on upgrade to latest release, any ideas?  New dependency?

```sh
> canvas@0.6.0 preinstall /var/www/harlem/node_modules/canvas
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
Checking for library jpeg                : yes 
Checking for cairo                       : yes 
'configure' finished successfully (0.324s)
Waf: Entering directory `/var/www/harlem/node_modules/canvas/build'
[1/9] cxx: src/CanvasRenderingContext2d.cc -> build/default/src/CanvasRenderingContext2d_1.o
[2/9] cxx: src/CanvasGradient.cc -> build/default/src/CanvasGradient_1.o
[3/9] cxx: src/init.cc -> build/default/src/init_1.o
[4/9] cxx: src/Image.cc -> build/default/src/Image_1.o
../src/Image.cc: In member function ‘cairo_status_t Image::loadJPEGFromBuffer(uint8_t*, unsigned int)’:
../src/Image.cc:349: error: ‘jpeg_mem_src’ was not declared in this scope
Waf: Leaving directory `/var/www/harlem/node_modules/canvas/build'
Build failed:  -> task failed (err #1): 
	{task: cxx Image.cc -> Image_1.o}
npm ERR! error installing canvas@0.6.0 Error: canvas@0.6.0 preinstall: `node-waf configure build`
npm ERR! error installing canvas@0.6.0 `sh "-c" "node-waf configure build"` failed with 1
npm ERR! error installing canvas@0.6.0     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing canvas@0.6.0     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing canvas@0.6.0     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! canvas@0.6.0 preinstall: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the canvas@0.6.0 preinstall script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 2.6.32-32-generic-pae
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/harlem/npm-debug.log
npm not ok
```

**Comment by LinusU** [comment]
Closing this since it's an old thread, please see our new installation instructions and report back if you still have problems...
