### ISSUE TITLE
Error npm install after upgrade npm to version 5.4.0

### ISSUE THREAD

**Issue by yanlyan** [Automattic/node-canvas#993]
Hi, after i'm upgrade npm to 5.4.0 and removed all node_modules. and got this error 

```
/bin/sh: ./util/has_lib.sh: Permission denied
gyp: Call to './util/has_lib.sh freetype' returned exit status 126 while in binding.gyp. while trying to load binding.gyp
```

```
> canvas@1.6.6 install /Users/yanlyan/Projects/store-idphotobook-api/node_modules/canvas
> node-gyp rebuild

/bin/sh: ./util/has_lib.sh: Permission denied
gyp: Call to './util/has_lib.sh freetype' returned exit status 126 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/yanlyan/Projects/store-idphotobook-api/node_modules/canvas
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

* Version of node-canvas ( 1.6.6)
* Version npm 5.4.0
* Environment (node 8.4.0 on Mac OS X 10.12.6 SIERRA)

**Comment by jnordberg** [comment]
Fixed in npm 5.4.1

**Comment by aadilh** [comment]
Still seeing the same error on Ubuntu 16.04 and npm 5.4.2 

```
error /media/cerebro/code/gmantra/maya/node_modules/canvas: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /media/cerebro/code/gmantra/maya/node_modules/canvas
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.8.1 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/aadilh/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/media/cerebro/code/gmantra/maya/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/aadilh/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/aadilh/.node-gyp/8.8.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/aadilh/.node-gyp/8.8.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/aadilh/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/aadilh/.node-gyp/8.8.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/media/cerebro/code/gmantra/maya/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
/bin/sh: 1: ./util/has_lib.sh: Permission denied
gyp: Call to './util/has_lib.sh freetype' returned exit status 126 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/aadilh/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.8.0-54-generic
gyp ERR! command "/home/aadilh/.nvm/versions/node/v8.8.1/bin/node" "/home/aadilh/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/cerebro/code/gmantra/maya/node_modules/canvas
```

**Comment by zbjornson** [comment]
@aadilh you might need to delete your `node_modules` folder if you tried previously with npm <5.4.2 and it created a folder with the wrong permissions.
